/** Video titles from The International Archive for Sinti & Gypsy Music (YouTube). No invented names. */

export type ArchiveVideo = { id: string; title: string; countries: string[] };

export const ARCHIVE_VIDEOS: ArchiveVideo[] = [
  { id: "alflJGC4Lww", title: "BIJ ONS OP HET KAMP-MET KOKALO ALIAS TATA MIRANDO.", countries: ["Netherlands"] },
  { id: "6mkqKhNGTS8", title: "THE ROYAL TATA MIRANDO GIPSEY ORHESTRA REHARSEL-BERLIN-1995.", countries: ["Netherlands", "Germany"] },
  { id: "HTs_5Vth8TA", title: "MORO & LUPA HEINA MIRANDO.", countries: ["Netherlands"] },
  { id: "EUShPIhNVd4", title: "BIJ ONS OP HET KAMP-PART ONE.", countries: ["Netherlands"] },
  { id: "Upg1vEklXyM", title: "Tata Mirando in gesprek met Jos Brink.", countries: ["Netherlands"] },
  { id: "GLgfwqrrZlk", title: "Violist zonder Viool .", countries: ["Netherlands"] },
  { id: "1aPVACDHK-c", title: "Tata Mirando Orkest- Een Jarig  Bestaan Csardas Taverne-1985.", countries: ["Netherlands"] },
  { id: "4jBlN7ylR4Q", title: "ERNO KALLAI KISS ES ZENEKARA", countries: ["Hungary"] },
  { id: "Sgopiuk8rnY", title: "ERNO KALLAI KISS AND FRIDO DIEPEVEEN Gipsy Orchestra", countries: ["Hungary", "Netherlands"] },
  { id: "_0ocB5_cXTM", title: "OLAH RINALDO THE PRIMAS AND HIS VIOLIN.", countries: ["Hungary", "Slovakia"] },
  { id: "4reD8UhQ1AI", title: "YOURI FARKAS EN ZENEKARA -HOTEL PALACE- GSTAAD SWISS- 2013.", countries: ["Hungary"] },
  { id: "iBNTpLcyEiI", title: "GABORA LAJOS ES ZENEKARA PART 3.", countries: ["Hungary"] },
  { id: "UXJ5DLo0dsU", title: "GABORA LAJOS ES ZENEKARA PART 2.", countries: ["Hungary"] },
  { id: "eQhlA83Q6rs", title: "GABORA LAJOS AND HIS GIPSY ORCHESTRA PART 1.", countries: ["Hungary"] },
  { id: "E8aGiRNwosw", title: "FODOR SANDOR ES ZENEKARA.", countries: ["Hungary", "Romania"] },
  { id: "BWWOUSZ32VY", title: "PADAR LAJOS ES ZENEKARA.", countries: ["Hungary"] },
  { id: "rcjRk7qstdg", title: "LAKATOS PITYU ES ZENEKARA", countries: ["Hungary"] },
  { id: "eY-RiGhCdt4", title: "VIRGIL RADELESCU AND HIS GIPSY ORCHESTRA 1995.", countries: ["Hungary", "Romania"] },
  { id: "ly_M8Y6feFU", title: "JAROKA SANYI & MAGRIT BANGO FINAL CLIP & AND THE MAKING OF.", countries: ["Hungary"] },
  { id: "CQA5Obk0G1s", title: "LUDWIG LOEILA WEISS MIRANDO 5-3-2000", countries: ["Netherlands"] },
  { id: "HLtig30fFss", title: "MARTIN WEISS & THE BRADY WINTERSTEIN  ORCHESTRA.", countries: ["Germany"] },
  { id: "vuWChXKysPs", title: "OPENING SINTI MUSIC SCHOOL ARNHEM HOLLAND 2008.", countries: ["Netherlands"] },
  { id: "vCHbMihfnlE", title: "LAKATOS MIKLOS AND HIS GYPSY ORCHESTRA   BUDAPEST IN A HUNGARIAN RESTAURANT", countries: ["Hungary"] },
  { id: "fS2aK2PqPAg", title: "TONTE ANDRAS ES ZENEKARA.", countries: ["Hungary"] },
  { id: "OogJUffi8us", title: "SARKOZI LAJOS JR ES ZENEKARA-IN CONCERT CIGANZY PLESS 2017.", countries: ["Hungary"] },
  { id: "2HHRRY1BOKc", title: "BALOGH JANOS ES ZENEKARA.", countries: ["Hungary"] },
  { id: "PVrvY5naDwM", title: "KIS TYUTYU ZENEKARA-HUNGARIA.", countries: ["Hungary"] },
  { id: "F5PHl7aKYhM", title: "VARGA JENO ES ZENEKARA.", countries: ["Hungary"] },
  { id: "4I54xSypiNk", title: "SANTA FERENC ES ZENEKARA.", countries: ["Hungary"] },
  { id: "ZtRgFZ1j4ng", title: "MAGYAR ZENEKARA.", countries: ["Hungary"] },
  { id: "m-udMtde9o4", title: "TCHA LIMBERGER A PRIMAS STORY.", countries: ["Hungary"] },
  { id: "DxdnaCBB4wQ", title: "GAGYI OSZCAR ES ZENEKARA.", countries: ["Hungary"] },
  { id: "MrFcd2m8gNE", title: "PUPORKA GEZA ES ZENEKARA HUNGARIA 1994.", countries: ["Hungary"] },
  { id: "hna-Q_2nYDc", title: "FRIDO VAN DIEPEVEEN ANNOUNCES THE DULA HORVATH GIPSY ORCHESTRA .", countries: ["Hungary", "Netherlands"] },
  { id: "HXTuEsrLpmk", title: "TATA MIRANDO SR - NELLO JAROKA MIRANDO AND BOKKIE VINK ARE PLAYING IN MALDEN -HOLLAND 2008.", countries: ["Hungary", "Netherlands"] },
  { id: "airQkF0CKjU", title: "THE MAKING OF A HUNGARIAN GYPSY ORCHESTRA RECORDING IN A SOUND STUDIO IN BUDAPEST.", countries: ["Hungary"] },
  { id: "tB6kPBKc7-0", title: "ROMA WEISS MIRANDO S.R &LA SONRISA ALIVE AT THE CAMP.", countries: ["Netherlands"] },
  { id: "H8S7hkzXekg", title: "IFJ JAROKA SANYI ES ZENEKARA-IN CONCERT -JHONNY IS THE BOY FOR ME", countries: ["Hungary"] },
  { id: "3NDMH6lwW18", title: "RENE BIKAR AND HIS GYPSY ORCHESTRA ARE PLAYING IN OOSTENDE BELGIUM.", countries: ["Hungary", "Belgium"] },
  { id: "RC7XvSrwpCw", title: "BUFFO RIGO SANDOR & JAROKA SANYI - PUSTARIKA PARTY-DEN HAAG HOLLAND-11-6-2000.", countries: ["Hungary", "Netherlands"] },
  { id: "uwsWJ95HnKY", title: "Lajos S\u00e1rk\u00f6zi jr Concert Splendor Amsterdam -04-11 -2014.", countries: ["Hungary", "Netherlands"] },
  { id: "Mx37tVAqh1E", title: "KALLAI KISS ERNO ID& IFJ FARM CAMPS IN ROLDE-HOLLAND-2015.", countries: ["Netherlands"] },
  { id: "iCGH_UhAQXk", title: "FRIDO VAN DIEPEVEEN AND HIS GYPSY ORCHESTRA ARE PLAYING A MEDLEY OF RUSSIAN AND ISRAELIAN MUSIC.", countries: ["Hungary", "Netherlands"] },
  { id: "ShKr_-oaGbw", title: "FRIDO DIEPEVEEN-KALLAI KISS ERNO AND DULA HORVATH VISIT RACZ PAL VIOLIN MAKER IN-BUDAPEST HUNGARIA.", countries: ["Hungary", "Netherlands"] },
  { id: "Jdy4nAg7rKo", title: "ROBY LAKATOS  PLAYING LIVE IN SHANGHAI CHINA", countries: ["Hungary"] },
  { id: "dMpoomj8X9Y", title: "NELLO MIRANDO JR JAROKA SANYI BUFFO RIGO SANDOR BOKKIE VINK BUDAPEST HUNGARIA.", countries: ["Hungary", "Netherlands"] },
  { id: "FJ0bUTvr27k", title: "TATA LUPA WEISS MIRANDO PLAYS A DOUBLE BASS SOLO-BERLIN GERMANY.", countries: ["Netherlands", "Germany"] },
  { id: "FpWNQM4eu40", title: "MORO MIRANDO SR-THE GOLDEN VIOLIN OFF FABRE MISCHKAA- IN THE NIGHT OFF THE BALKANS- 1980.", countries: ["Netherlands"] },
  { id: "VU4GlSGlXEM", title: "MORO MIRANDO -DOBRA DOBRA- IN THE NIGHT OFF THE BALKANS- 1980.", countries: ["Netherlands"] },
  { id: "Kp-aWBIEvqU", title: "NELO MIRANDO JR - HIS TELEVISION DEBUT IN THE NIGHT OFF THE BALKANS-1980.", countries: ["Netherlands"] },
  { id: "LdV8irtL7RY", title: "Paulus Sch\u00e4fer and his mother Pupa Sch\u00e4fer the documentary about life, religion and about the music.", countries: ["Netherlands"] },
  { id: "QQoAvoa2-30", title: "BAKKERO ROSENBERG A SINTI VIOLINIST WITH HEART AND SOUL TOGETHER WITH THE PAULUS SHAFFER BAND", countries: ["Netherlands"] },
  { id: "gRX5DIF0HG4", title: "SANDOR BUFFO RICO AND HIS LEGACY - PART 1.", countries: ["Hungary"] },
  { id: "0UUaKGWVX3M", title: "BOROS LAJOS HIS LIFE AND MUSIC - PART 1.", countries: ["Hungary"] },
  { id: "VXvhc1zWtOQ", title: "Racz Pal The Story About Building And Playing The Violin.", countries: ["Hungary"] },
  { id: "yve3hfD1VC8", title: "BUDAI SANDOR VIOLINIST AND VIOLIN BUILDER.", countries: ["Hungary"] },
  { id: "c5cOTiyzPjc", title: "LAJOS S\u00c1RK\u00d6ZYJR  LAJOS S\u00c1RK\u00d6ZY SR  MIKLOS LAKATOS  uOCHESTRA LIVE 2 SEPT 2022  AMSTERDAM-HOLLAND,", countries: ["Hungary", "Netherlands"] },
  { id: "0ZOWIECdqc4", title: "Jimmy Rosenberg - de vader, de zoon & het talent.", countries: ["Netherlands"] },
  { id: "6nPdx4x9x0E", title: "Tata Mirando Orkest Mei 1962.", countries: ["Netherlands"] },
  { id: "SpK9cMg_LdQ", title: "DOCUMANTAIRE EEN ZWAAR HART,TATA MIRANDO fAMILIE", countries: ["Netherlands"] },
  { id: "ow06SN4-DHk", title: "TATA MIRANDO SPEELT  PRIMAS NELLO MIRANDO. MUSIS SACRUM", countries: ["Hungary", "Netherlands"] },
  { id: "B_u8mjwHrXg", title: "MARIUS PREDA & GIANI LINCAN ARE IN THE POESTARIKA  THE HAGUE HOLLAND 2000.", countries: ["Netherlands"] },
  { id: "t1BEwh0PmYo", title: "NOOIT UITGEBRACHTE OPNAMES TATA MIRANDO ORCHESTRA 1996-1997.", countries: ["Netherlands"] },
  { id: "c9UHCAmaszs", title: "MOLNAR LACI PATAI OCSI BOXOLO CSORO CSAVO HUNGARIA.", countries: ["Hungary"] },
  { id: "OzfUbNRry2M", title: "Recently Found Materials From BOROSS LAJOS-FRIEDO DEEPEVEEN-2 THE VIOLIN-Margitkert-Hungary-2005", countries: ["Hungary"] },
  { id: "YlBDBzuhqQc", title: "MEIZEL WEISS MIRANDO S.R EN ZIJN ORKEST-TONI BOLTINI-PART 2", countries: ["Netherlands"] },
  { id: "gENpfWOGo_k", title: "NACHT VAN DE BALKAN 1980", countries: ["Netherlands"] },
  { id: "hf1hb0XaHjg", title: "TATA MIRANDO THE FIGHT COMPLEET.", countries: ["Netherlands"] },
  { id: "gVGQXlfFD4k", title: "THE ROYAL TATA MIRANDO ORCHESTRA -THEATER TOER-PART 1.", countries: ["Netherlands"] },
  { id: "wZhAA4GYYy0", title: "DODEN HERDENKING KONINGKLIJK TATA MIRANDO AMSTERDAM-1996.", countries: ["Netherlands"] },
  { id: "iVAKHzi5oy0", title: "BIJ ONS OP HET KAMP-2020-Part-1", countries: ["Netherlands"] },
  { id: "opbwvvZOPVs", title: "Ursel De geer En Tata Mirando Kokalo", countries: ["Netherlands"] },
  { id: "iBGyGCfC8dg", title: "ZIGEUNER MUZIEK DOET PIJN-NELLO WEIS MIRANDO-2", countries: ["Netherlands"] },
  { id: "7jvxwtmXEH8", title: "tata mirando Mpgun com", countries: ["Netherlands"] },
  { id: "tgZOizzZiKs", title: "ROMA WEIS MIRANDO-BLOED ZWEET EN TRANEN-AUDITIE 2014.", countries: ["Netherlands"] },
  { id: "QpEs0a91210", title: "mirandoFilm", countries: ["Netherlands"] },
  { id: "jRV8iB4kVIc", title: "moro mirando", countries: ["Netherlands"] },
  { id: "xX0sTlgSBYM", title: "Het Koninklijk Orkest Tata Mirando,Te Gast Bij Sonja Barends,18-3-1990.", countries: ["Netherlands"] },
  { id: "AGWOaAKpdfE", title: "Roma Weis Mirando Sr, Studeren 2015", countries: ["Netherlands"] },
  { id: "BKeFB9ng83U", title: "Klokhuis- 1996", countries: ["Netherlands"] },
  { id: "0MQQAQpOeww", title: "Tata Mirando S.r", countries: ["Netherlands"] },
  { id: "fbR6WGhrGeA", title: "Sinti Muziek Festival.", countries: ["Netherlands"] },
  { id: "bC1NS2hV-Qk", title: "Nello Jaroka Mirando Speelt.", countries: ["Hungary", "Netherlands"] },
  { id: "2KAC3jh0Kmw", title: "Maak Kennis Met Roma Weis Mirando S.r", countries: ["Netherlands"] },
  { id: "b2zvvlJJuZU", title: "Jouw Stad, Ons Dorp 2018.", countries: ["Netherlands"] },
  { id: "rEHERsNjw-s", title: "Tata Mirando orkest,speelt in het televisie progamma,Han Reizeger in muziek.", countries: ["Netherlands"] },
  { id: "bk_w87q_GTM", title: "Tata Mirando Orkest,optreden Bedevaart in Roermond.Hannes weis Tata Mirando Orkest en Rein Merscha", countries: ["Netherlands"] },
  { id: "15WMY8AHJFk", title: "Dark Eyes Mpgun com", countries: ["Netherlands"] },
  { id: "C6Y-svDQwyg", title: "Koningklijk Orkest Tata Mirando- Hor Die Cymbaal Klingen,Gast Violist Armando", countries: ["Netherlands"] },
  { id: "iAXGvu4z5gY", title: "Doden herdenking Den-Haag", countries: ["Netherlands"] },
  { id: "tYChY572TWU", title: "Herdenkings Fimpje Nello Jaroka Mirando", countries: ["Hungary", "Netherlands"] },
  { id: "Fy2W9nH3jqw", title: "Daantje  roma  Ik ga door  6 Juni 2018.", countries: ["Netherlands"] },
  { id: "CsBqQ3_TrUE", title: "Koningklijk Onderscheiden Tata Mirando S.r.", countries: ["Netherlands"] },
  { id: "51Ev3Jr6IU8", title: "Tata Mirando S.r Mag Een Krans Op De Dam Gaan  Leggen", countries: ["Netherlands"] },
  { id: "wM3lJK60g-M", title: "video clip tata mirando", countries: ["Netherlands"] },
  { id: "syLO0RzWxFI", title: "Interview met Nello Mirando", countries: ["Netherlands"] },
  { id: "8fEzl_orOxk", title: "Eliana onie Ilona", countries: ["Netherlands"] },
  { id: "8Gd0JPUlBd4", title: "PADAR LAJOS AND HIS GYPSY ORCHESTRA PLAYED IN A FARM NAMED FAMILY KAMP IN ROLDE IN DRENTE 2015.", countries: ["Hungary"] },
  { id: "CxW7XFU80KY", title: "Roby Lakatos and Dimiter Thernookov Csardas Van Monti-Gelders Orchestra.", countries: ["Hungary"] },
  { id: "f_JfF5WXDdg", title: "Requiem f\u00fcr Auschwitz: The making of by Roger Moreno-Rathgeb.", countries: ["Netherlands"] },
  { id: "hyqS5b44giU", title: "Budai S\u00e1ndor Piroska Are Playing Budai S\u00e1ndor Piroska at a street concert in Budapest-Hungaria-2022.", countries: ["Hungary"] },
  { id: "6_KU4Jms07A", title: "TOMORROW EVERYTHING WILL BE BETTER PLAYED BY THE CHILDREN AND GRAND CHILDREN OF TATA MIRANDO.", countries: ["Netherlands"] },
  { id: "fwKNU1mBhjQ", title: "TARIF THE HAIDOUKS-DOCUMANTAIRE-A RECOMMENDED FOR THE LOVERS OF ROMANIAN ROMA GYPSY MUSIC-NOV-1-2022", countries: ["Romania"] },
  { id: "vg6OZhoPuAk", title: "THE ROSENBERG TRIO  THE GUITAR - THREE PART DOCUMENTARY.", countries: ["Netherlands"] },
  { id: "zHYEVIAkxJA", title: "PUPORKA G\u00c9ZA PUPORKA BANDI NY\u00c1RI GABI LEFF\u0150 K\u00d3NYAI TIBOR S\u00dcNI- SZENTB\u00c9K\u00c1LLA-HUNGARIA-1994.", countries: ["Hungary"] },
  { id: "3quvrHw-0Pg", title: "LA SONRISA JUMPS DOWN AND MAKES HER FIRST TELEVISION DEBUT JUNI 2022.", countries: ["Netherlands"] },
  { id: "8HjDSvAFJq8", title: "THE KING OF THE VIOLINIST LAJOS BOROS DIED THIS PRIMAS HE WAS BORN IN 1925 AND BURIED IN 2014,", countries: ["Hungary"] },
  { id: "TvRtoXaAvoU", title: "ROBY LAKATOS & HIS GYPSY ORCHESTRA-JAAP OF SWEDEN-THE CHANAL CONCERT-AMSTERDAM-HOLLAND- 2000 -PART 2", countries: ["Hungary", "Netherlands"] },
  { id: "yXuI4eKnpHc", title: "HORVATH GYULA AND HIS GYPSY ORCHESTRA HUNGARIA-2000.", countries: ["Hungary"] },
  { id: "K-tctlUEdfk", title: "HORVATH GYULA VIGADO BUDAPEST HUNGARIA 2000.", countries: ["Hungary"] },
  { id: "9ODFJUOOk9Y", title: "OLAH VILMOS AND HIS GYPSY ORCHESTRA GIERO PUP BUDAPEST HUNGARIA 2005.", countries: ["Hungary"] },
  { id: "tZeWw1p8NUM", title: "PADAR LAJOS BUDAPEST HUNGARIA 2005.", countries: ["Hungary"] },
  { id: "-UNDreEiRpM", title: "MEZEI JOZSEF GOGO DUNA CORSO HUNGARIA 1995.", countries: ["Hungary"] },
  { id: "iB95ulZVVgg", title: "LAKATOS VILMOS  AND HIS GYPSY ORCHESTRA CHRISTMAS 1995- DANUBIUS GRAND HOTEL MARGITSZIGET-HUNGARIA.", countries: ["Hungary"] },
  { id: "rkUIhVDH6N0", title: "FRIDO DIEPEVEEN  AND PUKA KAROLY ARE PLAYING IN A HUGARIAN TELEVISION SHOW DUNA", countries: ["Hungary", "Netherlands"] },
  { id: "7NkYlo6zVjQ", title: "Buff\u00f3 Rig\u00f3 S\u00e1ndor \u00e9s Zenekara-Bang\u00f3 Margit \u00c9nekel - In Wageningen -Holland-1994.", countries: ["Hungary", "Netherlands"] },
  { id: "ydI_tftCsRQ", title: "BOROS LAJOS & HIS GYPSY ORCHESTRA -ARE SOMEWHERE PLAYING HUNGARIAN RESTAURANT", countries: ["Hungary"] },
  { id: "LnULLAKeSZw", title: "ROBY LAKATOS & HIS GYPSY ORCHESTRA-JAAP OF SWEDEN-THE CHANAL CONCERT-AMSTERDAM-HOLLAND- 2000 -PART 1", countries: ["Hungary", "Netherlands"] },
  { id: "f2Ckb1KfiMM", title: "JAROKA SANYI-BUFFO RIGO SANDOR-ROBY LAKATOS PLAYING AT THE POESTARIKA FESTIFAL-THE HAGUE-HOLLAND.", countries: ["Hungary", "Netherlands"] },
  { id: "fodW-MxGJa4", title: "FRIDO DIEPEVEEN & BUFFO RIGO SANDOR & HIS GYPSY ORCHESTRA PLAYING AT A WEDDING SOMEWHERE IN HUNGARY.", countries: ["Hungary", "Netherlands"] },
  { id: "mfrhKOpiDTQ", title: "FRIDO DEEPVEEN & TCHA LIMBERGER GYPSY ORCHESTRA-PLAYING IN ARNHEM.", countries: ["Hungary", "Netherlands"] },
  { id: "psMbkmh7YmU", title: "FRIDO DIEPEVEEN -JAROKA SANYI AND HIS GYPSY ORCHESTRA-BUDAPEST-HUNGARIA.-PART 2.", countries: ["Hungary", "Netherlands"] },
  { id: "jBLyFOUPWrI", title: "FRIDO DIEPEVEEN -JAROKA SANYI AND HIS GYPSY ORCHESTRA-BUDAPEST-HUNGARIA.-PART 1.", countries: ["Hungary", "Netherlands"] },
  { id: "EKNMxZtoyb8", title: "HAN REIZIGER VPRO-ROBY LAKATOS AND HIS GYPSY ORCHESTRA- 1999.", countries: ["Hungary", "Netherlands"] },
  { id: "IM_gqJ_ZWZ4", title: "TATA MIRANDO ORKEST-BUSSUM-12 AUGUSTUS-2022.", countries: ["Netherlands"] },
  { id: "fJn8JE3XH9E", title: "HAN REIZIGER IN MUZIEK,BEGRAVENIS VAN MORCHY-JANUARIE-1992.", countries: ["Netherlands"] },
  { id: "Es0ppBvKkLY", title: "DODEN HERDENKING MORO AND THE PAULUS SCHAFER BAND.", countries: ["Netherlands"] },
  { id: "DfkoZwiEnh4", title: "Schnuckenack\" Reinhardt .", countries: ["Germany"] },
  { id: "N7yQ6xG4dlQ", title: "TATA MIRANDO REIS NAAR AUSCHWITZ", countries: ["Netherlands"] },
  { id: "MF7kZfLl6IU", title: "TATA MIRANDO SPEELT VOOR VERA BETHS.", countries: ["Netherlands"] },
  { id: "2RLw7lwNvvQ", title: "MORCHY&LUPA WEISS MIRANDO BIJ VERMOLEN IN GOES 1983.PART-1", countries: ["Netherlands"] },
  { id: "KbTIHMA6A-0", title: "OEDOER DROM MET LALA WEISS", countries: ["Netherlands"] },
  { id: "bWaKZnBRroc", title: "MORSCHY EN ORKEST CSARDAS TAVERNE ROTTERDAM 1985", countries: ["Netherlands"] },
  { id: "wDyJGHnL7Gk", title: "TATA MIRANDO-KLOKHUIS-1996.", countries: ["Netherlands"] },
  { id: "irMWipQOh2U", title: "HET KONINGKLIJK SINTI-ORKEST TATA MIRANDO BERLIJN 90 ER JAREN", countries: ["Netherlands"] },
  { id: "9Xi8gpBNMDk", title: "HAN REIZIGER IN MUZIEK ORKEST TATA MIRANDO EN ARMANDO.PART 2,", countries: ["Netherlands"] },
  { id: "VP4gJ99jV7c", title: "Roma Mirando SR   Kom Bij Me Terug", countries: ["Netherlands"] },
  { id: "snzk5PDAtlk", title: "Roma Weis Mirando S.r En La Sonrisa   komm Doch Zu Mir", countries: ["Netherlands"] },
  { id: "X3-yJ-89xuA", title: "Tata Mirando koopt viool van ton op rommelmarkt", countries: ["Netherlands"] },
  { id: "o9LlKKgyiHo", title: "JOUW STAD MIJN DORP NOVEMBER 2018", countries: ["Netherlands"] },
  { id: "5qkiX-QrObU", title: "Gen 5   Item 4   La Sonrisa", countries: ["Netherlands"] },
  { id: "BP8DxoVHz8U", title: "Irene's GJ Adventures 404 Meet Carmen Weis   Sinti Women 3 SUBTITLED", countries: ["Netherlands"] },
  { id: "ImX_cMWqzFw", title: "BIJ ONS OP HET KAMP-2020-PART-2", countries: ["Netherlands"] },
  { id: "M99QaHxlx48", title: "BIJ ONS OP HET KAMP-2020-PART-3.", countries: ["Netherlands"] },
  { id: "Ec22jT-GD4g", title: "BIJ ONS OP HET KAMP-2020-PART5.", countries: ["Netherlands"] },
  { id: "xvG5PLxLFgw", title: "BIJ ONS OP HET KAMP-2020-PART-6.", countries: ["Netherlands"] },
  { id: "Eh74KZBb6wo", title: "BIJ ONS OP HET KAMP-2020-PART-7", countries: ["Netherlands"] },
  { id: "uklQo_yIFUA", title: "BIJ ONS OP HET KAMP-2020-PART-8.", countries: ["Netherlands"] },
  { id: "2VrJqntTIXs", title: "BIJ ONS OP HET KAMP-2020-PART-9.", countries: ["Netherlands"] },
  { id: "-dVi2KrcVkA", title: "LA-SONRISA EN MAMA DIDI KOENRAADS-VINK.2015.", countries: ["Netherlands"] },
  { id: "qZoLRK-8xu0", title: "ROMANO ZINGT.", countries: ["Netherlands"] },
  { id: "FsHnb_FK8RE", title: "NELLO-MIRANDO -2-SPEELT VOOR U.", countries: ["Netherlands"] },
  { id: "gyMbmtBwxus", title: "THE ROYAL TATA MIRANDO ORCHESTRA.", countries: ["Netherlands"] },
  { id: "OphDKCfC2J4", title: "DOCUMANTAIRE TATA MIRANDO-BOB ENTROP.", countries: ["Netherlands"] },
  { id: "nDHwMA7zJkM", title: "TATA MIRANDO KOOPT VIOOL-PART-2.", countries: ["Netherlands"] },
  { id: "HV3j_yBwMow", title: "ROMANO WEIS MIRANDO S.R-HENK BRES.", countries: ["Netherlands"] },
  { id: "lVmI9D857gY", title: "ORKEST MORO MIRANDO,1980", countries: ["Netherlands"] },
  { id: "IaB-APT_6as", title: "NELLO MIRANDO 2.", countries: ["Netherlands"] },
  { id: "aNkMz_ys6IQ", title: "TATA MIRANDO ORKEST-2015.", countries: ["Netherlands"] },
  { id: "2dk4RJBU6GQ", title: "THE ROYAL TATA MIRANDO ORCHESTRA MET JOEDO MIRANDO J R THEATHER TOER-PART 2.", countries: ["Netherlands"] },
  { id: "l0tcOFKTquw", title: "VIOLA HOLT EN TATA  MEIZEL MIRANDO EN DE GEBROEDERS BRANT", countries: ["Netherlands"] },
  { id: "zCgnW3JFYEQ", title: "MEIZEL WEISS  MIRANDO S.R EN ZIJN ORKEST EN TONI BOLTINI.", countries: ["Netherlands"] },
  { id: "kKoQw_JZyh0", title: "PAULI WEISS MIRANDO JHONNY KOKALJOO ALEX VAN WAYENBURG 1955.", countries: ["Netherlands"] },
  { id: "C5rUSt1Js7k", title: "EFTA BOTOCA \u2013 PEOTUL VIORII DIN  BANNAT VIOLIST UIT ROEMENIE", countries: ["Romania"] },
  { id: "Mnh0j3aSrLU", title: "TATA WEISS MIRANDO PIANO, PRIMAS NELLO WEISS MIRANDO", countries: ["Hungary", "Netherlands"] },
  { id: "bXWTTQoIAnI", title: "TATA MIRANDO VERTELD OVER DE OORLOGS JAREN.", countries: ["Netherlands"] },
  { id: "1jzAm--sbgM", title: "REIS NAAR AUSWITSCH MET TATA MIRANDO ORKEST.", countries: ["Netherlands"] },
  { id: "yWGDPOtjyxU", title: "TATA WEISS MIRANDO GAA MOE JAARE RADO ZONNEBLOEM 1955", countries: ["Netherlands"] },
  { id: "LawXRN1CBFs", title: "TATA LUPA WEISS MIRANDO CONTABAS SOLO", countries: ["Netherlands"] },
  { id: "YYdOP3Qgrts", title: "LOEILA MAGYARI WEISS MIRANDO ROMEENSE HORA.", countries: ["Netherlands"] },
  { id: "MuXzURlAA8I", title: "TATA EN NELLO WEISS MIRANDO ONDERSCHEIDEN MAGYAR NOT\u00c1", countries: ["Netherlands"] },
  { id: "l-zzFJi23DA", title: "MORCHY EN LUPA WEISS MIRANDO, CSARDAS TAVERNE ROTTERDAM  1985.", countries: ["Netherlands"] },
  { id: "jJ3ThCf9stM", title: "NELLO (BATO)& PRALA BRANDT DOMBURG.", countries: ["Netherlands"] },
  { id: "97SJgXbZoug", title: "POEROKATCHOO, HEINA,EN DE BROERS BRAND.", countries: ["Netherlands"] },
  { id: "HStF0xsC3L8", title: "MORO MIRANDO THE LOST TAPES-PART 2.", countries: ["Netherlands"] },
  { id: "jcRHnl3dWjQ", title: "TINEKE DE NOOI EN TATA MEIZEL MIRANDO EN HEINA EN CHAYA.", countries: ["Netherlands"] },
  { id: "6ONgLxh3kYs", title: "Armando De Kunstenaar En Schrijver,Neemt Afscheid Van Zijn muzikale Loopbaan,", countries: ["Netherlands"] },
  { id: "NIHvougzFQI", title: "Django Legacy Full Documentary", countries: ["France"] },
  { id: "HHEM3HGj3Yg", title: "THE ORIGINAL ROYAL TATA MIRANDO GYPSY ORCHESTRA-POKE BONZI.", countries: ["Hungary", "Netherlands"] },
  { id: "GFqRvTwJUWo", title: "MORO MIRANDO S.R IN ZIJN ELEMENT.", countries: ["Netherlands"] },
  { id: "uRSWPm4bPKA", title: "ROMANO WEIS MIRANDO SR VIOOL RESTAURATIE-JULI-2019.", countries: ["Netherlands"] },
  { id: "-o2vKMyBt1k", title: "ROMANO LA SONRISA EN JOHANNETJE.", countries: ["Netherlands"] },
  { id: "dnyKFqM2iB8", title: "ROMANO WEIS MIRANDO ZINGT.", countries: ["Netherlands"] },
  { id: "mmxVH-_mDbk", title: "MAMA DIDI KOENRAADS VINK-2020.", countries: ["Netherlands"] },
  { id: "H34FD2DOTDo", title: "PAPPOO VIOOL SPELEN VOOR FAYTJE-ZOMER 2020.", countries: ["Netherlands"] },
  { id: "Oa34aQpmuBs", title: "Czardas Van MONTI-Etienne  Patotte  Bousquet-Part-1.", countries: ["France"] },
  { id: "0yMFALbfxeE", title: "Quintett du Hot Club de France  -Part-1 Django  Reinhard.", countries: ["France"] },
  { id: "BysE0dqoT88", title: "Dekolja Ode Rieka Tu Moei  Schreeuwen Of Zwijgen", countries: ["Netherlands"] },
  { id: "sSM627nVSdI", title: "ZANGERES LA SONRISA WAT DAN ODE AAN HANS VERMEULEN", countries: ["Netherlands"] },
  { id: "bo0PxWG0F9o", title: "TATA MIRANDO ORCHESTRA DARK EYES WHIT MONICA WITKIEWICZOWNA.", countries: ["Netherlands"] },
  { id: "qK_7p34xrKE", title: "PROF SIPERKOV AN THE ROYAL TATA MIRANDO ORCHESTRA.", countries: ["Netherlands"] },
  { id: "TIjKzyfnfuI", title: "TATA MIRANDO SR MAG KRANS LEGGEN OP DE DAM.", countries: ["Netherlands"] },
  { id: "fX1GOmGnzlM", title: "JAROKA SANYI A KIRALY FELMENT AZ UR ISTENHEZ", countries: ["Hungary"] },
  { id: "KdObqqZH6Vs", title: "TATA MIRANDO PRAAT OVER DE OORLOGS JAREN.", countries: ["Netherlands"] },
  { id: "xVOgtOFiuX4", title: "Tchavolo & Dorado Schmitt \"Kali Sara\" & \"Tchavolo swing\" - Latcho drom", countries: ["France"] },
  { id: "KqoJVpmr80s", title: "George Boulanger   romanian violin virtuoso .", countries: ["Romania"] },
  { id: "C3JnDa-ezP0", title: "Kings of the World The Gypsy Kings Story.", countries: ["France"] },
  { id: "ReD-v4iRp4k", title: "TATA MIRANDO AUSCHWITZ DOCU KORT", countries: ["Netherlands"] },
  { id: "06jLF93_Pgg", title: "RAIKO OUDE OPNAMES.", countries: ["Netherlands"] },
  { id: "5PnVr55vmGU", title: "Rein Mercha en La Sonrisa   Maria 2010 en Orkest GItano Kings", countries: ["Netherlands"] },
  { id: "bmSi_Way1bc", title: "Rein Mercha & Gitano Kings & La Sonrisa     Brabant Party 16 mei 2010", countries: ["Netherlands"] },
  { id: "zbB3s75TG-M", title: "BRUILOFT PARTY ORKEST TATA MIRANDO.", countries: ["Netherlands"] },
  { id: "Tz0bpEKCS4s", title: "IMRI MAGYARI AND HIS ORCHESTRA BUDAPEST HONGARIJE-1931", countries: ["Hungary"] },
];

export function archiveVideosForCountry(country: string): ArchiveVideo[] {
  return ARCHIVE_VIDEOS.filter((row) => row.countries.includes(country));
}

export function archiveVideosMatching(terms: string[]): ArchiveVideo[] {
  const needles = terms.map((t) => t.toLowerCase()).filter(Boolean);
  if (!needles.length) return [];
  return ARCHIVE_VIDEOS.filter((row) => {
    const hay = row.title.toLowerCase();
    return needles.some((n) => hay.includes(n));
  });
}
