/** Localized festival when-labels and bios. Facts only; missing locale falls back to English. */

const WHEN: Record<string, Record<string, string>> = {
  fr: {
    January: "Janvier",
    "Late January": "Fin janvier",
    May: "Mai",
    "Mid May": "Mi-mai",
    "Late May": "Fin mai",
    "May — dates not posted": "Mai — dates non affichées",
    "May — next dates not posted": "Mai — prochaines dates non affichées",
    June: "Juin",
    "Late June": "Fin juin",
    July: "Juillet",
    August: "Août",
    "Late August": "Fin août",
    September: "Septembre",
    October: "Octobre",
    November: "Novembre",
    "Late November": "Fin novembre",
    "November, dates to be posted": "Novembre, dates à paraître",
    Autumn: "Automne",
    Spring: "Printemps",
    Summer: "Été",
    Whitsun: "Pentecôte",
    "June / November": "Juin / novembre",
    "Ongoing jams": "Jams réguliers",
    "New Year holidays — typically early January":
      "Vacances de Nouvel An — en général début janvier",
    "Late April — next 23–25 April 2027": "Fin avril — prochaine édition 23–25 avril 2027",
    "Late December — dates to be posted": "Fin décembre — dates à paraître",
  },
  de: {
    January: "Januar",
    "Late January": "Ende Januar",
    May: "Mai",
    "Mid May": "Mitte Mai",
    "Late May": "Ende Mai",
    "May — dates not posted": "Mai — Termine nicht veröffentlicht",
    "May — next dates not posted": "Mai — nächste Termine nicht veröffentlicht",
    June: "Juni",
    "Late June": "Ende Juni",
    July: "Juli",
    August: "August",
    "Late August": "Ende August",
    September: "September",
    October: "Oktober",
    November: "November",
    "Late November": "Ende November",
    "November, dates to be posted": "November, Termine folgen",
    Autumn: "Herbst",
    Spring: "Frühling",
    Summer: "Sommer",
    Whitsun: "Pfingsten",
    "June / November": "Juni / November",
    "Ongoing jams": "Regelmäßige Jams",
    "New Year holidays — typically early January":
      "Neujahrsferien — meist Anfang Januar",
    "Late April — next 23–25 April 2027": "Ende April — nächste Ausgabe 23.–25. April 2027",
    "Late December — dates to be posted": "Ende Dezember — Termine folgen",
  },
  nl: {
    January: "Januari",
    "Late January": "Eind januari",
    May: "Mei",
    "Mid May": "Half mei",
    "Late May": "Eind mei",
    "May — dates not posted": "Mei — data niet gezet",
    "May — next dates not posted": "Mei — volgende data niet gezet",
    June: "Juni",
    "Late June": "Eind juni",
    July: "Juli",
    August: "Augustus",
    "Late August": "Eind augustus",
    September: "September",
    October: "Oktober",
    November: "November",
    "Late November": "Eind november",
    "November, dates to be posted": "November, data volgen",
    Autumn: "Herfst",
    Spring: "Lente",
    Summer: "Zomer",
    Whitsun: "Pinksteren",
    "June / November": "Juni / november",
    "Ongoing jams": "Vaste jams",
    "New Year holidays — typically early January":
      "Nieuwjaarsdagen — meestal begin januari",
    "Late April — next 23–25 April 2027": "Eind april — volgende 23–25 april 2027",
    "Late December — dates to be posted": "Eind december — data volgen",
  },
  it: {
    January: "Gennaio",
    "Late January": "Fine gennaio",
    May: "Maggio",
    "Mid May": "Metà maggio",
    "Late May": "Fine maggio",
    "May — dates not posted": "Maggio — date non pubblicate",
    "May — next dates not posted": "Maggio — prossime date non pubblicate",
    June: "Giugno",
    "Late June": "Fine giugno",
    July: "Luglio",
    August: "Agosto",
    "Late August": "Fine agosto",
    September: "Settembre",
    October: "Ottobre",
    November: "Novembre",
    "Late November": "Fine novembre",
    "November, dates to be posted": "Novembre, date da pubblicare",
    Autumn: "Autunno",
    Spring: "Primavera",
    Summer: "Estate",
    Whitsun: "Pentecoste",
    "June / November": "Giugno / novembre",
    "Ongoing jams": "Jam regolari",
    "New Year holidays — typically early January":
      "Vacanze di Capodanno — di solito inizio gennaio",
    "Late April — next 23–25 April 2027": "Fine aprile — prossima 23–25 aprile 2027",
    "Late December — dates to be posted": "Fine dicembre — date da pubblicare",
  },
  es: {
    January: "Enero",
    "Late January": "Finales de enero",
    May: "Mayo",
    "Mid May": "Mediados de mayo",
    "Late May": "Finales de mayo",
    "May — dates not posted": "Mayo — fechas no publicadas",
    "May — next dates not posted": "Mayo — próximas fechas no publicadas",
    June: "Junio",
    "Late June": "Finales de junio",
    July: "Julio",
    August: "Agosto",
    "Late August": "Finales de agosto",
    September: "Septiembre",
    October: "Octubre",
    November: "Noviembre",
    "Late November": "Finales de noviembre",
    "November, dates to be posted": "Noviembre, fechas por publicar",
    Autumn: "Otoño",
    Spring: "Primavera",
    Summer: "Verano",
    Whitsun: "Pentecostés",
    "June / November": "Junio / noviembre",
    "Ongoing jams": "Jams regulares",
    "New Year holidays — typically early January":
      "Vacaciones de Año Nuevo — normalmente principios de enero",
    "Late April — next 23–25 April 2027": "Finales de abril — próxima 23–25 abril 2027",
    "Late December — dates to be posted": "Finales de diciembre — fechas por publicar",
  },
  pt: {
    January: "Janeiro",
    "Late January": "Final de janeiro",
    May: "Maio",
    "Mid May": "Meados de maio",
    "Late May": "Final de maio",
    "May — dates not posted": "Maio — datas não publicadas",
    "May — next dates not posted": "Maio — próximas datas não publicadas",
    June: "Junho",
    "Late June": "Final de junho",
    July: "Julho",
    August: "Agosto",
    "Late August": "Final de agosto",
    September: "Setembro",
    October: "Outubro",
    November: "Novembro",
    "Late November": "Final de novembro",
    "November, dates to be posted": "Novembro, datas a publicar",
    Autumn: "Outono",
    Spring: "Primavera",
    Summer: "Verão",
    Whitsun: "Pentecostes",
    "June / November": "Junho / novembro",
    "Ongoing jams": "Jams regulares",
    "New Year holidays — typically early January":
      "Férias de Ano Novo — em geral início de janeiro",
    "Late April — next 23–25 April 2027": "Final de abril — próxima 23–25 abril 2027",
    "Late December — dates to be posted": "Final de dezembro — datas a publicar",
  },
};

const BIOS: Record<string, Record<string, string>> = {
  "festival-django-reinhardt": {
    fr: "Le pèlerinage. Ce qui commença comme une soirée à Samois-sur-Seine en 1968 est devenu le rassemblement annuel dès 1983. Les scènes officielles sont désormais dans le parc du château de Fontainebleau ; l’Île du Berceau et les campings tiennent encore les sessions pour lesquelles les musiciens viennent. Fin juin, chaque année.",
    de: "Die Wallfahrt. Was 1968 als ein Abend in Samois-sur-Seine begann, ist seit 1983 das jährliche Treffen. Die offiziellen Bühnen stehen im Park des Schlosses Fontainebleau; die Île du Berceau und die Campingplätze halten weiter die Sessions, derentwegen die Spieler kommen. Ende Juni, jedes Jahr.",
    nl: "De bedevaart. Wat in 1968 als één avond in Samois-sur-Seine begon, is sinds 1983 de jaarlijkse bijeenkomst. De officiële podia staan in het park van het kasteel van Fontainebleau; het Île du Berceau en de campings houden nog de sessies waar spelers voor komen. Eind juni, elk jaar.",
    it: "Il pellegrinaggio. Quello che nel 1968 era una serata a Samois-sur-Seine è dal 1983 il raduno annuale. I palchi ufficiali sono nel parco del castello di Fontainebleau; l’Île du Berceau e i campeggi tengono ancora le sessioni per cui i musicisti vengono. Fine giugno, ogni anno.",
    es: "La peregrinación. Lo que empezó como una noche en Samois-sur-Seine en 1968 es el encuentro anual desde 1983. Los escenarios oficiales están en el parque del castillo de Fontainebleau; la Île du Berceau y los campings siguen con las sesiones por las que vienen los músicos. Finales de junio, cada año.",
    pt: "A peregrinação. O que começou como uma noite em Samois-sur-Seine em 1968 é o encontro anual desde 1983. Os palcos oficiais ficam no parque do castelo de Fontainebleau; a Île du Berceau e os campings ainda têm as sessões pelos quais os músicos vêm. Final de junho, todos os anos.",
    ru: "Паломничество. Вечер в Самуа-сюр-Сен в 1968 стал ежегодным сбором с 1983. Официальные сцены — в парке замка Фонтенбло; Île du Berceau и кемпинги по-прежнему держат сессии, ради которых приезжают. Конец июня, каждый год.",
  },
  "django-liberchies": {
    fr: "Le festival au village natal de Django. Liberchies, en Belgique, pose un week-end de gypsy jazz là où Jean Reinhardt est né en 1910 — un rassemblement plus petit, familial, qui attire encore les noms pour qui le village est terrain connu.",
    de: "Das Festival in Djangos Geburtsort. Liberchies in Belgien stellt ein Gypsy-Jazz-Wochenende auf den Boden, wo Jean Reinhardt 1910 geboren wurde — ein kleineres Familientreffen, das weiter die Namen zieht, die das Dorf als Heimatterrain behandeln.",
    nl: "Het festival in Django’s geboortedorp. Liberchies, België, zet een weekend gypsy jazz op de grond waar Jean Reinhardt in 1910 geboren werd — een kleinere, familiale bijeenkomst die nog de namen trekt die het dorp als thuis behandelen.",
    it: "Il festival nel paese natale di Django. Liberchies, in Belgio, mette un weekend di gypsy jazz sul suolo dove Jean Reinhardt nacque nel 1910 — un raduno più piccolo, di famiglia, che attira ancora i nomi per cui il paese è casa.",
    es: "El festival en el pueblo natal de Django. Liberchies, Bélgica, pone un fin de semana de gypsy jazz en el suelo donde nació Jean Reinhardt en 1910 — un encuentro más pequeño, de familia, que sigue atrayendo a quienes tratan el pueblo como casa.",
  },
  djangofollies: {
    fr: "Le festival d’hiver belge. Djangofollies a accueilli la famille Rosenberg, Fapy Lafertin et la lignée Waso pendant des années — une date de janvier, quand le reste du circuit est calme.",
    de: "Belgiens Winterfestival. Djangofollies hat die Familie Rosenberg, Fapy Lafertin und die belgische Waso-Linie jahrelang gehabt — ein Januartermin, wenn der Rest des Circuits ruhig ist.",
    nl: "Het Belgische winterfestival. Djangofollies had jaren de familie Rosenberg, Fapy Lafertin en de Waso-lijn — een januaridatum als de rest van het circuit stil is.",
    it: "Il festival invernale belga. Djangofollies ha ospitato per anni la famiglia Rosenberg, Fapy Lafertin e la linea Waso — una data di gennaio, quando il resto del circuito è fermo.",
    es: "El festival de invierno belga. Djangofollies ha tenido a la familia Rosenberg, Fapy Lafertin y la línea Waso durante años — una fecha de enero, cuando el resto del circuito está quieto.",
  },
  "django-reinhardt-festival-augsburg": {
    fr: "Week-end international de gypsy jazz au Parktheater im Kurhaus Göggingen. 5–7 juin 2026. Vendredi dès 19h30 : Diknu Schneeberger & Eva Scholten Quartet ; Mozes Rosenberg & Sandro Roy Group ; Adrien Moignard & Jermaine Landsberger Trio. Samedi : Django Deluxe invite Hugo Richter (Giovanni Weiss). Billets via le Parktheater. django-reinhardt-festival.de",
    de: "Internationales Gypsy-Jazz-Wochenende im Parktheater im Kurhaus Göggingen. 5.–7. Juni 2026. Freitag ab 19:30: Diknu Schneeberger & Eva Scholten Quartet; Mozes Rosenberg & Sandro Roy Group; Adrien Moignard & Jermaine Landsberger Trio. Samstag: Django Deluxe lädt Hugo Richter (Giovanni Weiss). Karten über das Parktheater. django-reinhardt-festival.de",
    nl: "Internationaal gypsy-jazzweekend in het Parktheater im Kurhaus Göggingen. 5–7 juni 2026. Vrijdag vanaf 19:30: Diknu Schneeberger & Eva Scholten Quartet; Mozes Rosenberg & Sandro Roy Group; Adrien Moignard & Jermaine Landsberger Trio. Zaterdag: Django Deluxe nodigt Hugo Richter (Giovanni Weiss). Kaarten via het Parktheater.",
    it: "Weekend internazionale di gypsy jazz al Parktheater im Kurhaus Göggingen. 5–7 giugno 2026. Venerdì dalle 19:30: Diknu Schneeberger & Eva Scholten Quartet; Mozes Rosenberg & Sandro Roy Group; Adrien Moignard & Jermaine Landsberger Trio. Sabato: Django Deluxe invita Hugo Richter (Giovanni Weiss).",
    es: "Fin de semana internacional de gypsy jazz en el Parktheater im Kurhaus Göggingen. 5–7 junio 2026. Viernes desde las 19:30: Diknu Schneeberger & Eva Scholten Quartet; Mozes Rosenberg & Sandro Roy Group; Adrien Moignard & Jermaine Landsberger Trio. Sábado: Django Deluxe invita a Hugo Richter (Giovanni Weiss).",
  },
  jazzabar: {
    fr: "17e Festival Jazzabar. Vendredi 11 septembre 2026, salle des fêtes, Bar-sur-Aube (10200). Quintette du Hot Club de France à 22h00.",
    de: "17. Festival Jazzabar. Freitag 11. September 2026, Salle des fêtes, Bar-sur-Aube (10200). Quintette du Hot Club de France um 22:00.",
    nl: "17e Festival Jazzabar. Vrijdag 11 september 2026, Salle des fêtes, Bar-sur-Aube (10200). Quintette du Hot Club de France om 22:00.",
    it: "17° Festival Jazzabar. Venerdì 11 settembre 2026, Salle des fêtes, Bar-sur-Aube (10200). Quintette du Hot Club de France alle 22:00.",
    es: "17.º Festival Jazzabar. Viernes 11 septiembre 2026, Salle des fêtes, Bar-sur-Aube (10200). Quintette du Hot Club de France a las 22:00.",
  },
  "montisola-manouche-off-road": {
    fr: "Raduno manouche à Monte Isola et Iseo. 16–19 juillet 2026 — concerts, masterclass, nuits itinérantes.",
    de: "Manouche-Treffen auf Monte Isola und in Iseo. 16.–19. Juli 2026 — Konzerte, Meisterklasse, wandernde Nächte.",
    nl: "Manouche-raduno op Monte Isola en Iseo. 16–19 juli 2026 — concerten, masterclass, rondtrekkende avonden.",
    it: "Raduno manouche a Monte Isola e Iseo. 16–19 luglio 2026 — concerti, masterclass, notti itineranti.",
    es: "Encuentro manouche en Monte Isola e Iseo. 16–19 julio 2026 — conciertos, masterclass, noches itinerantes.",
  },
  "raduno-jazz-manouche-procida": {
    fr: "IXe raduno jazz manouche sur l’île de Procida. 11–14 juin 2026 : Daniele Corvasce, Chiaré, Filippo Dall’Asta, jam et masterclass.",
    de: "IX. Jazz-Manouche-Treffen auf Procida. 11.–14. Juni 2026: Daniele Corvasce, Chiaré, Filippo Dall’Asta, Jam und Meisterklasse.",
    nl: "IXe jazz-manoucheraduno op Procida. 11–14 juni 2026: Daniele Corvasce, Chiaré, Filippo Dall’Asta, jam en masterclass.",
    it: "IX raduno jazz manouche a Procida. 11–14 giugno 2026: Daniele Corvasce, Chiaré, Filippo Dall’Asta, jam e masterclass.",
    es: "IX encuentro jazz manouche en Procida. 11–14 junio 2026: Daniele Corvasce, Chiaré, Filippo Dall’Asta, jam y masterclass.",
  },
  "toscana-django-festival": {
    fr: "Festival Django à Pontepetri / San Marcello Piteglio. 12–16 août 2026. Amati Schmitt parmi les invités. Soirée 15 € / 3 soirs 35 €.",
    de: "Django-Festival in Pontepetri / San Marcello Piteglio. 12.–16. August 2026. Amati Schmitt unter den Gästen. Abend 15 € / 3 Abende 35 €.",
    nl: "Djangofestival in Pontepetri / San Marcello Piteglio. 12–16 augustus 2026. Amati Schmitt onder de gasten. Avond €15 / 3 avonden €35.",
    it: "Festival Django a Pontepetri / San Marcello Piteglio. 12–16 agosto 2026. Tra gli ospiti Amati Schmitt. Sera 15 € / 3 sere 35 €.",
    es: "Festival Django en Pontepetri / San Marcello Piteglio. 12–16 agosto 2026. Amati Schmitt entre los invitados. Noche 15 € / 3 noches 35 €.",
  },
  "roma-django-festival": {
    fr: "Première édition. Soirées Django à Villa Celimontana, Rome — 26–28 août et 2 septembre 2026. Tchavolo Schmitt, Duved Dunayevsky, Accordi Disaccordi, Django Jazz (Renato Gattone). Gratuit.",
    de: "Erste Ausgabe. Django-Abende in der Villa Celimontana, Rom — 26.–28. August und 2. September 2026. Tchavolo Schmitt, Duved Dunayevsky, Accordi Disaccordi, Django Jazz (Renato Gattone). Frei.",
    nl: "Eerste editie. Django-avonden in Villa Celimontana, Rome — 26–28 augustus en 2 september 2026. Tchavolo Schmitt, Duved Dunayevsky, Accordi Disaccordi, Django Jazz (Renato Gattone). Gratis.",
    it: "Prima edizione. Serate Django a Villa Celimontana, Roma — 26–28 agosto e 2 settembre 2026. Tchavolo Schmitt, Duved Dunayevsky, Accordi Disaccordi, Django Jazz (Renato Gattone). Ingresso libero.",
    es: "Primera edición. Noches Django en Villa Celimontana, Roma — 26–28 agosto y 2 septiembre 2026. Tchavolo Schmitt, Duved Dunayevsky, Accordi Disaccordi, Django Jazz (Renato Gattone). Gratis.",
  },
  "bolzano-gipsy-jazz-festival": {
    fr: "Festival gipsy et gypsy jazz à Bolzano. 27–30 août 2026.",
    de: "Gipsy- und Gypsy-Jazz-Festival in Bozen. 27.–30. August 2026.",
    nl: "Gipsy- en gypsy-jazzfestival in Bolzano. 27–30 augustus 2026.",
    it: "Festival gipsy e gypsy jazz a Bolzano. 27–30 agosto 2026.",
    es: "Festival gipsy y gypsy jazz en Bolzano. 27–30 agosto 2026.",
  },
  "cremona-gypsy-jazz-meeting": {
    fr: "Rencontre gypsy jazz au Cremona Exhibition Centre. 2–4 octobre 2026.",
    de: "Gypsy-Jazz-Treffen im Cremona Exhibition Centre. 2.–4. Oktober 2026.",
    nl: "Gypsy-jazzmeeting in het Cremona Exhibition Centre. 2–4 oktober 2026.",
    it: "Meeting gypsy jazz al Cremona Exhibition Centre. 2–4 ottobre 2026.",
    es: "Encuentro gypsy jazz en el Cremona Exhibition Centre. 2–4 octubre 2026.",
  },
  "raduno-mediterraneo": {
    fr: "Le raduno gypsy jazz de Sicile — pas Santa Cecilia à Palerme. Petralia Sottana et Piano Battaglia (Madonie), 28–30 août 2026. Invité Mozes Rosenberg. radunomanouche.it",
    de: "Siziliens Gypsy-Jazz-Raduno — nicht Santa Cecilia in Palermo. Petralia Sottana und Piano Battaglia (Madonie), 28.–30. August 2026. Gast Mozes Rosenberg. radunomanouche.it",
    nl: "Sicilië’s gypsy-jazzraduno — niet Santa Cecilia in Palermo. Petralia Sottana en Piano Battaglia (Madonie), 28–30 augustus 2026. Gast Mozes Rosenberg. radunomanouche.it",
    it: "Il raduno gypsy jazz della Sicilia — non Santa Cecilia a Palermo. Petralia Sottana e Piano Battaglia (Madonie), 28–30 agosto 2026. Ospite Mozes Rosenberg. radunomanouche.it",
    es: "El raduno gypsy jazz de Sicilia — no Santa Cecilia en Palermo. Petralia Sottana y Piano Battaglia (Madonie), 28–30 agosto 2026. Invitado Mozes Rosenberg. radunomanouche.it",
  },
  "pennabilli-django-festival": {
    fr: "Jazz manouche dans la vallée du Marecchia. Teatro Vittoria, Pennabilli. Fin décembre, récurrent. Dates 2026 pas encore affichées.",
    de: "Jazz Manouche im Marecchia-Tal. Teatro Vittoria, Pennabilli. Wiederkehrend Ende Dezember. 2026-Termine noch nicht veröffentlicht.",
    nl: "Jazz manouche in de Marecchia-vallei. Teatro Vittoria, Pennabilli. Terugkerend eind december. 2026-data nog niet gezet.",
    it: "Jazz manouche in val Marecchia. Teatro Vittoria, Pennabilli. Fine dicembre, ricorrente. Date 2026 non ancora pubblicate.",
    es: "Jazz manouche en el valle del Marecchia. Teatro Vittoria, Pennabilli. Finales de diciembre, recurrente. Fechas 2026 aún no publicadas.",
  },
  "festival-jazz-manouche-forbach": {
    fr: "Forbach (Moselle), Centre de Congrès du Burghof, 15 rue du Parc. Depuis 2018. Récurrent en mai. Dernière édition au fichier : 8–10 mai 2026 (8e) — passée. Prochaines dates non affichées.",
    de: "Forbach (Moselle), Centre de Congrès du Burghof, 15 rue du Parc. Seit 2018. Wiederkehrend im Mai. Letzte Ausgabe: 8.–10. Mai 2026 (8.) — vorbei. Nächste Termine nicht veröffentlicht.",
    nl: "Forbach (Moezel), Centre de Congrès du Burghof. Sinds 2018. Terugkerend in mei. Laatste op bestand: 8–10 mei 2026 (8e) — voorbij. Volgende data niet gezet.",
    it: "Forbach (Moselle), Centre de Congrès du Burghof. Dal 2018. Di solito a maggio. Ultima edizione in archivio: 8–10 maggio 2026 (8ª) — passata. Prossime date non pubblicate.",
    es: "Forbach (Mosela), Centre de Congrès du Burghof. Desde 2018. Recurrente en mayo. Última edición: 8–10 mayo 2026 (8.ª) — pasada. Próximas fechas no publicadas.",
  },
  "festival-jazz-musette-des-puces": {
    fr: "Didier Lockwood / Jazz Musette des Puces — gypsy jazz, musette et swing dans les allées des Puces de Saint-Ouen. 18–21 juin 2026. Les sets en plein air sont gratuits ; dîners-concerts dans les salles du marché. Ce n’est pas Samois — le week-end du marché aux puces.",
    de: "Didier Lockwood / Jazz Musette des Puces — Gypsy Jazz, Musette und Swing in den Gängen der Puces de Saint-Ouen. 18.–21. Juni 2026. Open-Air-Sets sind frei; Dinner-Shows in den Markthallen. Nicht Samois — das Flohmarkt-Wochenende.",
    nl: "Didier Lockwood / Jazz Musette des Puces — gypsy jazz, musette en swing in de gangen van de Puces de Saint-Ouen. 18–21 juni 2026. Openluchtsets zijn gratis. Niet Samois — het vlooienmarktweekend.",
    it: "Didier Lockwood / Jazz Musette des Puces — gypsy jazz, musette e swing nei viali delle Puces de Saint-Ouen. 18–21 giugno 2026. I set all’aperto sono gratuiti. Non è Samois — il weekend del mercato delle pulci.",
    es: "Didier Lockwood / Jazz Musette des Puces — gypsy jazz, musette y swing en los pasillos de las Puces de Saint-Ouen. 18–21 junio 2026. Los sets al aire libre son gratis. No es Samois — el fin de semana del rastro.",
  },
  "welcome-in-tziganie": {
    fr: "Festival gersois de musiques tziganes, balkaniques et manouche au Théâtre de verdure, Seissan. 19e édition 24–26 avril 2026 passée. 20e anniversaire : 23–25 avril 2027. Organisateur L’Air des Balkans / Florian Calvez. welcome-in-tziganie.com.",
    de: "Gers-Festival für Tzigane-, Balkan- und Manouche-Musik im Théâtre de verdure, Seissan. 19. Ausgabe 24.–26. April 2026 ist vorbei. 20. Jubiläum: 23.–25. April 2027. Veranstalter L’Air des Balkans / Florian Calvez.",
    nl: "Gers-festival van Tzigane-, Balkan- en manouchemuziek in het Théâtre de verdure, Seissan. 19e editie 24–26 april 2026 is voorbij. 20e: 23–25 april 2027.",
    it: "Festival del Gers di musiche tzigane, balcaniche e manouche al Théâtre de verdure, Seissan. 19ª edizione 24–26 aprile 2026 passata. 20°: 23–25 aprile 2027.",
    es: "Festival del Gers de músicas tzigane, balcánicas y manouche en el Théâtre de verdure, Seissan. 19.ª edición 24–26 abril 2026 pasada. 20.º: 23–25 abril 2027.",
  },
  "gipsy-festival-angers": {
    fr: "Festival de musiques gitanes à Angers, qui programme régulièrement la guitare manouche à côté des programmes gitans et balkaniques — une date à l’ouest de Paris sur le circuit d’été.",
    de: "Ein französisches Gipsy-Musikfestival in Angers, das regelmäßig Manouche-Gitarre neben Gitan- und Balkan-Programmen setzt — ein Termin westlich von Paris auf dem Sommercircuit.",
    nl: "Frans zigeunermuziekfestival in Angers dat regelmatig manouchegitaar zet naast Gitan- en Balkanprogramma’s — een datum ten westen van Parijs op het zomercircuit.",
    it: "Festival francese di musiche gitane ad Angers, che mette spesso la chitarra manouche accanto a programmi gitani e balcanici — una data a ovest di Parigi sul circuito estivo.",
    es: "Festival francés de músicas gitanas en Angers, que suele poner guitarra manouche junto a programas gitanos y balcánicos — una fecha al oeste de París en el circuito de verano.",
  },
  "django-in-june": {
    fr: "La semaine de gypsy jazz de la Nouvelle-Angleterre : ateliers le jour, concerts et jams le soir. Django in June est l’école américaine du style depuis 2000, avec des invités européens à côté de la scène Hot Club US.",
    de: "New Englands Gypsy-Jazz-Woche: Workshops am Tag, Konzerte und Jams nachts. Django in June ist seit 2000 die amerikanische Schule des Stils, mit europäischen Gästen neben der US-Hot-Club-Szene.",
    nl: "New Englands gypsy-jazzweek: workshops overdag, concerten en jams ’s avonds. Django in June is sinds 2000 de Amerikaanse school van de stijl.",
    it: "La settimana di gypsy jazz del New England: workshop di giorno, concerti e jam di notte. Django in June è dal 2000 la scuola americana dello stile.",
    es: "La semana de gypsy jazz de Nueva Inglaterra: talleres de día, conciertos y jams de noche. Django in June es desde 2000 la escuela estadounidense del estilo.",
  },
  "djangofest-northwest": {
    fr: "Fondé en 2000 pour amener le gypsy jazz au nord-ouest du Pacifique. DjangoFest NW, c’est concerts, ateliers et jams tardives sur Whidbey Island — le pendant ouest de Django in June. 15–20 septembre 2026 au Whidbey Island Center for the Arts, Langley.",
    de: "2000 gegründet, um Gypsy Jazz in den Pazifischen Nordwesten zu bringen. DjangoFest NW sind Konzerte, Workshops und späte Jams auf Whidbey Island — das Westküsten-Gegenstück zu Django in June. 15.–20. September 2026 am Whidbey Island Center for the Arts, Langley.",
    nl: "Opgericht in 2000 om gypsy jazz naar de Pacific Northwest te brengen. DjangoFest NW is concerten, workshops en late jams op Whidbey Island. 15–20 september 2026 in Langley.",
    it: "Fondato nel 2000 per portare il gypsy jazz nel Pacific Northwest. DjangoFest NW è concerti, workshop e jam tarde a Whidbey Island. 15–20 settembre 2026 a Langley.",
    es: "Fundado en 2000 para llevar el gypsy jazz al Noroeste del Pacífico. DjangoFest NW son conciertos, talleres y jams tardíos en Whidbey Island. 15–20 septiembre 2026 en Langley.",
  },
  "djangofestivalen-oslo": {
    fr: "Depuis 1980, la semaine de Django en janvier à Oslo — le festival de Hot Club de Norvège au Cosmopolite, Torshov. Jon Larsen accueille encore. Dernière édition au fichier : 22–24 janvier 2026. Prochaine : 21–23 janvier 2027. Programmation pas encore affichée.",
    de: "Seit 1980 Djangos Januarwoche in Oslo — das Festival von Hot Club de Norvège im Cosmopolite, Torshov. Jon Larsen lädt noch. Letzte Ausgabe: 22.–24. Januar 2026. Nächste: 21.–23. Januar 2027. Line-up noch nicht veröffentlicht.",
    nl: "Sinds 1980 Django’s januariweek in Oslo — het festival van Hot Club de Norvège in Cosmopolite, Torshov. Volgende: 21–23 januari 2027. Line-up nog niet gezet.",
    it: "Dal 1980 la settimana di Django a gennaio a Oslo — il festival di Hot Club de Norvège al Cosmopolite, Torshov. Prossima: 21–23 gennaio 2027.",
    es: "Desde 1980, la semana de Django en enero en Oslo — el festival de Hot Club de Norvège en Cosmopolite, Torshov. Próxima: 21–23 enero 2027.",
  },
  "jazz-by-the-sea": {
    fr: "Week-end de jazz gratuit à Domburg, Zélande — 34e édition, 17–20 septembre 2026. Rues, restaurants et trois scènes. Gypsy jazz sur la Classic Stage : Mozes Rosenberg Trio, samedi 19 septembre 15h. Marcia Bamberg Swing Quartet, dimanche 20 septembre, 13h–15h.",
    de: "Kostenloses Jazzwochenende in Domburg, Zeeland — 34. Ausgabe, 17.–20. September 2026. Gypsy Jazz auf der Classic Stage: Mozes Rosenberg Trio, Samstag 19. September 15:00. Marcia Bamberg Swing Quartet, Sonntag 20. September, 13:00–15:00.",
    nl: "Gratis jazzweekend in Domburg, Zeeland — 34e editie, 17–20 september 2026. Gypsy jazz op het Classic Stage: Mozes Rosenberg Trio, zaterdag 19 september 15:00. Marcia Bamberg Swing Quartet, zondag 20 september, 13:00–15:00.",
    it: "Weekend jazz gratuito a Domburg, Zelanda — 34ª edizione, 17–20 settembre 2026. Gypsy jazz sul Classic Stage: Mozes Rosenberg Trio, sabato 19 settembre 15:00. Marcia Bamberg Swing Quartet, domenica 20 settembre, 13:00–15:00.",
    es: "Fin de semana de jazz gratis en Domburg, Zelanda — 34.ª edición, 17–20 septiembre 2026. Gypsy jazz en el Classic Stage: Mozes Rosenberg Trio, sábado 19 septiembre 15:00. Marcia Bamberg Swing Quartet, domingo 20 septiembre, 13:00–15:00.",
  },
  "django-in-london": {
    fr: "Trois jours à St Mary’s, Upper Street, Islington. Jeudi 17 : Harry Diplock Trio (19h30) et Hugo Guezbar Trio (21h). Vendredi 18 : Elias Prinz & Sunny Franz Quartet (19h30) et Angelo Debarre Trio (21h). Samedi 19 : matinée Giacomo Smith (15h) et London Django Collective avec Kourosh Kanani (21h).",
    de: "Drei Tage in St Mary’s, Upper Street, Islington. Donnerstag 17.: Harry Diplock Trio (19:30) und Hugo Guezbar Trio (21:00). Freitag 18.: Elias Prinz & Sunny Franz Quartet (19:30) und Angelo Debarre Trio (21:00). Samstag 19.: Giacomo Smith nachmittags (15:00) und London Django Collective mit Kourosh Kanani (21:00).",
    nl: "Drie dagen in St Mary’s, Upper Street, Islington. Donderdag 17e: Harry Diplock Trio (19:30) en Hugo Guezbar Trio (21:00). Vrijdag 18e: Elias Prinz & Sunny Franz Quartet en Angelo Debarre Trio. Zaterdag 19e: Giacomo Smith (15:00) en London Django Collective met Kourosh Kanani (21:00).",
    it: "Tre giorni a St Mary’s, Upper Street, Islington. Giovedì 17: Harry Diplock Trio (19:30) e Hugo Guezbar Trio (21:00). Venerdì 18: Elias Prinz & Sunny Franz Quartet e Angelo Debarre Trio. Sabato 19: Giacomo Smith (15:00) e London Django Collective con Kourosh Kanani (21:00).",
    es: "Tres días en St Mary’s, Upper Street, Islington. Jueves 17: Harry Diplock Trio (19:30) y Hugo Guezbar Trio (21:00). Viernes 18: Elias Prinz & Sunny Franz Quartet y Angelo Debarre Trio. Sábado 19: Giacomo Smith (15:00) y London Django Collective con Kourosh Kanani (21:00).",
  },
};

const MONTHS: Record<string, Record<string, string>> = {
  fr: {
    January: "janvier",
    February: "février",
    March: "mars",
    April: "avril",
    May: "mai",
    June: "juin",
    July: "juillet",
    August: "août",
    September: "septembre",
    October: "octobre",
    November: "novembre",
    December: "décembre",
  },
  de: {
    January: "Januar",
    February: "Februar",
    March: "März",
    April: "April",
    May: "Mai",
    June: "Juni",
    July: "Juli",
    August: "August",
    September: "September",
    October: "Oktober",
    November: "November",
    December: "Dezember",
  },
  nl: {
    January: "januari",
    February: "februari",
    March: "maart",
    April: "april",
    May: "mei",
    June: "juni",
    July: "juli",
    August: "augustus",
    September: "september",
    October: "oktober",
    November: "november",
    December: "december",
  },
  it: {
    January: "gennaio",
    February: "febbraio",
    March: "marzo",
    April: "aprile",
    May: "maggio",
    June: "giugno",
    July: "luglio",
    August: "agosto",
    September: "settembre",
    October: "ottobre",
    November: "novembre",
    December: "dicembre",
  },
  es: {
    January: "enero",
    February: "febrero",
    March: "marzo",
    April: "abril",
    May: "mayo",
    June: "junio",
    July: "julio",
    August: "agosto",
    September: "septiembre",
    October: "octubre",
    November: "noviembre",
    December: "diciembre",
  },
  pt: {
    January: "janeiro",
    February: "fevereiro",
    March: "março",
    April: "abril",
    May: "maio",
    June: "junho",
    July: "julho",
    August: "agosto",
    September: "setembro",
    October: "outubro",
    November: "novembro",
    December: "dezembro",
  },
  ru: {
    January: "января",
    February: "февраля",
    March: "марта",
    April: "апреля",
    May: "мая",
    June: "июня",
    July: "июля",
    August: "августа",
    September: "сентября",
    October: "октября",
    November: "ноября",
    December: "декабря",
  },
  ja: {
    January: "1月",
    February: "2月",
    March: "3月",
    April: "4月",
    May: "5月",
    June: "6月",
    July: "7月",
    August: "8月",
    September: "9月",
    October: "10月",
    November: "11月",
    December: "12月",
  },
  ko: {
    January: "1월",
    February: "2월",
    March: "3월",
    April: "4월",
    May: "5월",
    June: "6월",
    July: "7월",
    August: "8월",
    September: "9월",
    October: "10월",
    November: "11월",
    December: "12월",
  },
  zh: {
    January: "1月",
    February: "2月",
    March: "3月",
    April: "4月",
    May: "5月",
    June: "6月",
    July: "7月",
    August: "8月",
    September: "9月",
    October: "10月",
    November: "11月",
    December: "12月",
  },
  "zh-tw": {
    January: "1月",
    February: "2月",
    March: "3月",
    April: "4月",
    May: "5月",
    June: "6月",
    July: "7月",
    August: "8月",
    September: "9月",
    October: "10月",
    November: "11月",
    December: "12月",
  },
  hu: {
    January: "január",
    February: "február",
    March: "március",
    April: "április",
    May: "május",
    June: "június",
    July: "július",
    August: "augusztus",
    September: "szeptember",
    October: "október",
    November: "november",
    December: "december",
  },
  pl: {
    January: "stycznia",
    February: "lutego",
    March: "marca",
    April: "kwietnia",
    May: "maja",
    June: "czerwca",
    July: "lipca",
    August: "sierpnia",
    September: "września",
    October: "października",
    November: "listopada",
    December: "grudnia",
  },
  cs: {
    January: "ledna",
    February: "února",
    March: "března",
    April: "dubna",
    May: "května",
    June: "června",
    July: "července",
    August: "srpna",
    September: "září",
    October: "října",
    November: "listopadu",
    December: "prosince",
  },
  hr: {
    January: "siječnja",
    February: "veljače",
    March: "ožujka",
    April: "travnja",
    May: "svibnja",
    June: "lipnja",
    July: "srpnja",
    August: "kolovoza",
    September: "rujna",
    October: "listopada",
    November: "studenoga",
    December: "prosinca",
  },
  sr: {
    January: "јануара",
    February: "фебруара",
    March: "марта",
    April: "априла",
    May: "маја",
    June: "јуна",
    July: "јула",
    August: "августа",
    September: "септембра",
    October: "октобра",
    November: "новембра",
    December: "децембра",
  },
  ro: {
    January: "ianuarie",
    February: "februarie",
    March: "martie",
    April: "aprilie",
    May: "mai",
    June: "iunie",
    July: "iulie",
    August: "august",
    September: "septembrie",
    October: "octombrie",
    November: "noiembrie",
    December: "decembrie",
  },
  id: {
    January: "Januari",
    February: "Februari",
    March: "Maret",
    April: "April",
    May: "Mei",
    June: "Juni",
    July: "Juli",
    August: "Agustus",
    September: "September",
    October: "Oktober",
    November: "November",
    December: "Desember",
  },
  th: {
    January: "มกราคม",
    February: "กุมภาพันธ์",
    March: "มีนาคม",
    April: "เมษายน",
    May: "พฤษภาคม",
    June: "มิถุนายน",
    July: "กรกฎาคม",
    August: "สิงหาคม",
    September: "กันยายน",
    October: "ตุลาคม",
    November: "พฤศจิกายน",
    December: "ธันวาคม",
  },
};

const SEASONS: Record<string, Record<string, string>> = {
  fr: { Summer: "Été", Winter: "Hiver", Spring: "Printemps", Autumn: "Automne", Fall: "Automne", Whitsun: "Pentecôte" },
  de: { Summer: "Sommer", Winter: "Winter", Spring: "Frühling", Autumn: "Herbst", Fall: "Herbst", Whitsun: "Pfingsten" },
  nl: { Summer: "Zomer", Winter: "Winter", Spring: "Lente", Autumn: "Herfst", Fall: "Herfst", Whitsun: "Pinksteren" },
  it: { Summer: "Estate", Winter: "Inverno", Spring: "Primavera", Autumn: "Autunno", Fall: "Autunno", Whitsun: "Pentecoste" },
  es: { Summer: "Verano", Winter: "Invierno", Spring: "Primavera", Autumn: "Otoño", Fall: "Otoño", Whitsun: "Pentecostés" },
  pt: { Summer: "Verão", Winter: "Inverno", Spring: "Primavera", Autumn: "Outono", Fall: "Outono", Whitsun: "Pentecostes" },
  ru: { Summer: "Летом", Winter: "Зимой", Spring: "Весной", Autumn: "Осенью", Fall: "Осенью", Whitsun: "Троица" },
  ja: { Summer: "夏", Winter: "冬", Spring: "春", Autumn: "秋", Fall: "秋", Whitsun: "聖霊降臨祭" },
  ko: { Summer: "여름", Winter: "겨울", Spring: "봄", Autumn: "가을", Fall: "가을", Whitsun: "성령강림절" },
  zh: { Summer: "夏季", Winter: "冬季", Spring: "春季", Autumn: "秋季", Fall: "秋季", Whitsun: "圣灵降临节" },
  "zh-tw": { Summer: "夏季", Winter: "冬季", Spring: "春季", Autumn: "秋季", Fall: "秋季", Whitsun: "聖靈降臨節" },
  hu: { Summer: "Nyár", Winter: "Tél", Spring: "Tavasz", Autumn: "Ősz", Fall: "Ősz", Whitsun: "Pünkösd" },
  pl: { Summer: "Lato", Winter: "Zima", Spring: "Wiosna", Autumn: "Jesień", Fall: "Jesień", Whitsun: "Zielone Świątki" },
  cs: { Summer: "Léto", Winter: "Zima", Spring: "Jaro", Autumn: "Podzim", Fall: "Podzim", Whitsun: "Svatodušní svátky" },
  hr: { Summer: "Ljeto", Winter: "Zima", Spring: "Proljeće", Autumn: "Jesen", Fall: "Jesen", Whitsun: "Duhovi" },
  sr: { Summer: "Лето", Winter: "Зима", Spring: "Пролеће", Autumn: "Јесен", Fall: "Јесен", Whitsun: "Духови" },
  ro: { Summer: "Vară", Winter: "Iarnă", Spring: "Primăvară", Autumn: "Toamnă", Fall: "Toamnă", Whitsun: "Rusalii" },
  id: { Summer: "Musim panas", Winter: "Musim dingin", Spring: "Musim semi", Autumn: "Musim gugur", Fall: "Musim gugur", Whitsun: "Pentakosta" },
  th: { Summer: "ฤดูร้อน", Winter: "ฤดูหนาว", Spring: "ฤดูใบไม้ผลิ", Autumn: "ฤดูใบไม้ร่วง", Fall: "ฤดูใบไม้ร่วง", Whitsun: "วันเพ็นเทคอสต์" },
};

const AFFIX: Record<string, { Late: string; Mid: string; Early: string }> = {
  fr: { Late: "Fin", Mid: "Mi-", Early: "Début" },
  de: { Late: "Ende", Mid: "Mitte", Early: "Anfang" },
  nl: { Late: "Eind", Mid: "Half", Early: "Begin" },
  it: { Late: "Fine", Mid: "Metà", Early: "Inizio" },
  es: { Late: "Finales de", Mid: "Mediados de", Early: "Principios de" },
  pt: { Late: "Final de", Mid: "Meados de", Early: "Início de" },
  ru: { Late: "Конец", Mid: "Середина", Early: "Начало" },
  ja: { Late: "下旬", Mid: "中旬", Early: "上旬" },
  ko: { Late: "말", Mid: "중순", Early: "초" },
  zh: { Late: "下旬", Mid: "中旬", Early: "上旬" },
  "zh-tw": { Late: "下旬", Mid: "中旬", Early: "上旬" },
  hu: { Late: "vége", Mid: "közepe", Early: "eleje" },
  pl: { Late: "koniec", Mid: "połowa", Early: "początek" },
  cs: { Late: "konec", Mid: "polovina", Early: "začátek" },
  hr: { Late: "kraj", Mid: "sredina", Early: "početak" },
  sr: { Late: "крај", Mid: "средина", Early: "почетак" },
  ro: { Late: "Sfârșit de", Mid: "Mijloc de", Early: "Început de" },
  id: { Late: "Akhir", Mid: "Pertengahan", Early: "Awal" },
  th: { Late: "ปลาย", Mid: "กลาง", Early: "ต้น" },
};

const TAILS: Record<string, [string, string][]> = {
  fr: [
    ["dates not posted", "dates non affichées"],
    ["next dates not posted", "prochaines dates non affichées"],
    ["dates to be posted", "dates à paraître"],
    ["Ongoing jams", "Jams réguliers"],
  ],
  de: [
    ["dates not posted", "Termine nicht veröffentlicht"],
    ["next dates not posted", "nächste Termine nicht veröffentlicht"],
    ["dates to be posted", "Termine folgen"],
    ["Ongoing jams", "Regelmäßige Jams"],
  ],
  nl: [
    ["dates not posted", "data niet gezet"],
    ["next dates not posted", "volgende data niet gezet"],
    ["dates to be posted", "data volgen"],
    ["Ongoing jams", "Vaste jams"],
  ],
  it: [
    ["dates not posted", "date non pubblicate"],
    ["next dates not posted", "prossime date non pubblicate"],
    ["dates to be posted", "date da pubblicare"],
    ["Ongoing jams", "Jam regolari"],
  ],
  es: [
    ["dates not posted", "fechas no publicadas"],
    ["next dates not posted", "próximas fechas no publicadas"],
    ["dates to be posted", "fechas por publicar"],
    ["Ongoing jams", "Jams regulares"],
  ],
  pt: [
    ["dates not posted", "datas não publicadas"],
    ["next dates not posted", "próximas datas não publicadas"],
    ["dates to be posted", "datas a publicar"],
    ["Ongoing jams", "Jams regulares"],
  ],
};

export function festivalWhen(when: string, locale: string) {
  if (!when || locale === "en") return when;
  const exact = WHEN[locale]?.[when];
  if (exact) return exact;
  let out = when;
  const months = MONTHS[locale];
  const affix = AFFIX[locale];
  if (months && affix) {
    for (const [enM, trM] of Object.entries(months)) {
      out = out.replaceAll(`Late ${enM}`, locale === "ja" || locale === "ko" || locale === "zh" || locale === "zh-tw" ? `${trM}${affix.Late}` : `${affix.Late} ${trM}`);
      out = out.replaceAll(`Mid ${enM}`, locale === "fr" ? `Mi-${trM}` : `${affix.Mid} ${trM}`);
      out = out.replaceAll(`Early ${enM}`, `${affix.Early} ${trM}`);
    }
  }
  if (months) {
    const names = Object.keys(months).sort((a, b) => b.length - a.length);
    for (const enM of names) out = out.replaceAll(enM, months[enM]);
  }
  const seasons = SEASONS[locale];
  if (seasons) {
    for (const [en, tr] of Object.entries(seasons)) out = out.replaceAll(en, tr);
  }
  for (const [en, tr] of TAILS[locale] ?? []) out = out.replaceAll(en, tr);
  return out;
}

export const whenLabel = festivalWhen;

export function festivalBio(slug: string, locale: string, fallback: string) {
  if (!locale || locale === "en" || locale === "he") return fallback;
  return BIOS[slug]?.[locale] || fallback;
}

export function localizeFestival<T extends { slug: string; bio: string; when: string }>(
  festival: T,
  locale: string,
): T {
  return {
    ...festival,
    when: festivalWhen(festival.when, locale),
    bio: festivalBio(festival.slug, locale, festival.bio),
  };
}
