export type Festival = {
  slug: string;
  name: string;
  city: string;
  country: string;
  when: string;
  founded: string;
  site: string;
  tickets?: string;
  bio: string;
  nextStartsAt: string;
  tba?: boolean;
  relatedSlugs: string[];
};

export const FESTIVALS: Festival[] = [
  {
    slug: "festival-django-reinhardt",
    name: "Festival Django Reinhardt",
    city: "Fontainebleau",
    country: "France",
    when: "Late June",
    founded: "1968",
    site: "https://www.festivaldjangoreinhardt.com/",
    bio: "The pilgrimage. What began as a single evening in Samois-sur-Seine in 1968 became the annual gathering from 1983. Official stages now sit in the park of the Château de Fontainebleau; the Île du Berceau and the campsites still hold the sessions that players come for. Late June, every year.",
    nextStartsAt: "2027-06-24T18:00:00.000Z",
    relatedSlugs: [
      "django-reinhardt",
      "bireli-lagrene",
      "stochelo-rosenberg",
      "angelo-debarre",
      "yorgui-loeffler",
      "marcia-bamberg",
      "daniel-gueli",
    ],
  },
  {
    slug: "django-liberchies",
    name: "Django Liberchies",
    city: "Liberchies",
    country: "Belgium",
    when: "Mid May",
    founded: "1995",
    site: "https://www.djangoliberchies.be/",
    bio: "The festival in Django's birthplace. Liberchies, Belgium, puts a weekend of gypsy jazz on the ground where Jean Reinhardt was born in 1910 — a smaller, family gathering that still draws the names who treat the village as home turf.",
    nextStartsAt: "2027-05-14T18:00:00.000Z",
    relatedSlugs: ["django-reinhardt", "fapy-lafertin", "tcha-limberger"],
  },
  {
    slug: "djangofollies",
    name: "Djangofollies",
    city: "Lessines / Wallonia",
    country: "Belgium",
    when: "January",
    founded: "2000",
    site: "https://www.djangofollies.be/",
    bio: "Belgium's winter gypsy jazz festival. Djangofollies has hosted the Rosenberg family, Fapy Lafertin, and the Belgian Waso line for years — a January date when the rest of the circuit is quiet.",
    nextStartsAt: "2027-01-16T19:00:00.000Z",
    relatedSlugs: ["fapy-lafertin", "stochelo-rosenberg", "koen-de-cauter"],
  },
  {
    slug: "gypsy-festival-tilburg",
    name: "Gypsy Festival Tilburg",
    city: "Tilburg",
    country: "Netherlands",
    when: "22 August 2026",
    founded: "",
    site: "https://tilburg.com/agenda/gypsy-festival-tilburg-2026/",
    bio: "This Saturday — 22 August 2026 — at Cultuurbos Bosvreugd, Reeshofdijk 12, Tilburg. A Sinti gypsy jazz day in the woods: gates at 13:00, tickets about €16. Line-up: Lalla Weiss opens; Petit Barbeau Gadjo Orchestre; Django Rosenberg Trio with Noekie Basily and Daniel Gueli (15:30); Jaroka Mirando Band (17:00); young talent Jayson Lenting; then Stochelo & Mozes Rosenberg Trio (19:30). From 21:00 the afterparty and jams move inside the café.",
    nextStartsAt: "2026-08-22T11:00:00.000Z",
    relatedSlugs: [
      "stochelo-rosenberg",
      "mozes-rosenberg",
      "django-rosenberg",
      "noekie-basily",
      "daniel-gueli",
    ],
  },
  {
    slug: "jazz-by-the-sea",
    name: "Jazz by the Sea",
    city: "Domburg",
    country: "Netherlands",
    when: "17–20 September 2026",
    founded: "1993",
    site: "https://jazzbythesea.nl/",
    bio: "Free jazz weekend in Domburg, Zeeland — 34th edition, 17–20 September 2026. Streets, restaurants and three stages (Classic at the Badhotel, Fusion on the Markt, New Wave). Gypsy jazz on the Classic Stage: Mozes Rosenberg Trio, Saturday 19 September 15:00. Marcia Bamberg Swing Quartet, Sunday 20 September, 13:00–15:00.",
    nextStartsAt: "2026-09-17T12:00:00.000Z",
    relatedSlugs: [
      "mozes-rosenberg",
      "marcia-bamberg",
      "john-ligthart",
      "ronald-weel",
      "daniel-gueli",
    ],
  },
  {
    slug: "django-amsterdam",
    name: "Django Amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    when: "Late January",
    founded: "2000s",
    site: "https://www.bimhuis.nl/en/django-amsterdam-2",
    bio: "Django’s birthday week at the Bimhuis — Hot Club jazz, Dutch and visiting chairs. Last ran 22–25 January 2026. Stichting Hot Club de France Nederland covers the reports on hcdf.nl.",
    nextStartsAt: "2027-01-22T19:00:00.000Z",
    relatedSlugs: [
      "stochelo-rosenberg",
      "daniel-gueli",
      "dario-napoli",
      "marcia-bamberg",
    ],
  },
  {
    slug: "django-in-june",
    name: "Django in June",
    city: "Northampton, Massachusetts",
    country: "United States of America",
    when: "June",
    founded: "2000",
    site: "https://djangoinjune.com/",
    bio: "New England's gypsy jazz week: workshops by day, concerts and jams by night. Django in June has been the American school for the style since 2000, with European guests teaching beside the US Hot Club scene.",
    nextStartsAt: "2027-06-07T16:00:00.000Z",
    relatedSlugs: ["dario-napoli", "paulus-schafer", "stephane-wrembel"],
  },
  {
    slug: "djangofest-northwest",
    name: "DjangoFest Northwest",
    city: "Whidbey Island, Washington",
    country: "United States of America",
    when: "September",
    founded: "2000",
    site: "https://www.djangofest.com/",
    bio: "Founded in 2000 to bring gypsy jazz to the Pacific Northwest. DjangoFest NW is concerts, workshops and late jams on Whidbey Island — a West Coast counterpart to Django in June. 15–20 September 2026 at Whidbey Island Center for the Arts, Langley: 15 Sep 3 Parts Bourbon and Café Impromptu; 17 Sep Eric Vanderbilt-Mathews All-Stars and Leah and I; 18 Sep John Jorgenson Trio (matinee) and Gonzalo Bergara Quintet (evening); 19 Sep Pino Noir and Grappelli’s Django (matinee) and Gismo Graf Quintet (evening); 20 Sep Stella Heath and the Nick Lehr Memorial Djam. Free second stage: Ranger and the Re-Arrangers, Lone Fir Hot Club.",
    nextStartsAt: "2026-09-16T02:00:00.000Z",
    relatedSlugs: [
      "gismo-graf",
      "gonzalo-bergara",
      "tim-kliphuis",
      "john-jorgenson",
      "jimmy-grant",
      "greg-ruby",
      "stephane-wrembel",
    ],
  },
  {
    slug: "birdland-django-festival",
    name: "Django Reinhardt Festival at Birdland",
    city: "New York",
    country: "United States of America",
    when: "June / November",
    founded: "2001",
    site: "https://birdlandjazz.com/",
    bio: "New York's club festival. For years Birdland has given a week to Django's music — Dorado and Samson Schmitt, Ludovic Beier, Pierre Blanchard and the American Hot Club players in the room where the city still goes for jazz.",
    nextStartsAt: "2026-11-18T19:30:00.000Z",
    relatedSlugs: ["dorado-schmitt", "samson-schmitt", "ludovic-beier", "frank-vignola"],
  },
  {
    slug: "iggf-gossington",
    name: "International Gypsy Guitar Festival",
    city: "Gossington",
    country: "United Kingdom",
    when: "Summer",
    founded: "2000s",
    site: "",
    bio: "England's gypsy guitar meeting. IGGF Gossington has hosted Paulus Schäfer, the Rosenberg orbit and British Hot Club groups — a field and a stage for the UK scene.",
    nextStartsAt: "2027-07-10T17:00:00.000Z",
    relatedSlugs: ["paulus-schafer", "dave-kelbie", "robin-nolan"],
  },
  {
    slug: "djangofestivalen-oslo",
    name: "Djangofestivalen Oslo",
    city: "Oslo",
    country: "Norway",
    when: "January",
    founded: "1980s",
    site: "https://cosmopolite.no/en/news/2025/djangofestivalen-2026",
    bio: "Since 1980, Django’s January week in Oslo — Hot Club de Norvège’s festival at Cosmopolite, Torshov. Jon Larsen still hosts. Last on file: 22–24 January 2026 (Hot Club de Norvège with Lars Frank; Graf–Winterstein–Kliphuis; Gustav Skaaret Trio; StradiMarius; Fanou Torracinta). Next: 21–23 January 2027. Line-up not posted yet.",
    nextStartsAt: "2027-01-21T19:00:00.000Z",
    relatedSlugs: ["jon-larsen", "ola-erlien", "gildas-le-pape", "gustav-skaaret", "gismo-graf", "tim-kliphuis"],
  },
  {
    slug: "eddie-lang-jazzfest",
    name: "Eddie Lang Jazz Festival",
    city: "Monteroduni",
    country: "Italy",
    when: "July",
    founded: "1990s",
    site: "",
    bio: "The Italian jazz-guitar festival named for Eddie Lang, a regular stop for gypsy jazz players on the summer circuit — Dario Napoli and visiting European guitarists among them.",
    nextStartsAt: "2027-07-16T20:00:00.000Z",
    relatedSlugs: ["dario-napoli", "benji-winterstein"],
  },
  {
    slug: "montisola-manouche-off-road",
    name: "Montisola Manouche Off Road",
    city: "Monte Isola",
    country: "Italy",
    when: "16–19 July 2026",
    founded: "",
    site: "",
    bio: "Manouche raduno on Monte Isola and Iseo. 16–19 July 2026.",
    nextStartsAt: "2027-07-16T18:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "raduno-jazz-manouche-procida",
    name: "Raduno Jazz Manouche di Procida",
    city: "Procida",
    country: "Italy",
    when: "11–14 June 2026",
    founded: "",
    site: "",
    bio: "Jazz manouche gathering on Procida island. 11–14 June 2026.",
    nextStartsAt: "2027-06-11T18:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "toscana-django-festival",
    name: "Toscana Django Festival",
    city: "Pontepetri",
    country: "Italy",
    when: "12–16 August 2026",
    founded: "",
    site: "",
    bio: "Django festival in the Pistoia hills — Pontepetri. 12–16 August 2026.",
    nextStartsAt: "2027-08-12T18:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "roma-django-festival",
    name: "Roma Django Festival",
    city: "Rome",
    country: "Italy",
    when: "26–28 August and 2 September 2026",
    founded: "",
    site: "",
    bio: "Django nights at Villa Celimontana, Rome. 26–28 August and 2 September 2026.",
    nextStartsAt: "2027-08-26T18:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "bolzano-gipsy-jazz-festival",
    name: "Bolzano Gipsy and Gypsy Jazz Festival",
    city: "Bolzano",
    country: "Italy",
    when: "27–30 August 2026",
    founded: "",
    site: "",
    bio: "Gipsy and gypsy jazz festival in Bolzano. 27–30 August 2026.",
    nextStartsAt: "2027-08-27T18:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "cremona-gypsy-jazz-meeting",
    name: "Cremona Gypsy Jazz Meeting",
    city: "Cremona",
    country: "Italy",
    when: "2–4 October 2026",
    founded: "",
    site: "",
    bio: "Gypsy jazz meeting at the Cremona Exhibition Centre. 2–4 October 2026.",
    nextStartsAt: "2026-10-02T17:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "raduno-mediterraneo",
    name: "XV Raduno Mediterraneo Jazz Manouche",
    city: "Petralia Sottana",
    country: "Italy",
    when: "28–30 August 2026",
    founded: "2000s",
    site: "https://www.radunomanouche.it/",
    bio: "Mediterranean manouche meeting in Petralia Sottana and Piano Battaglia, Sicily. 28–30 August 2026.",
    nextStartsAt: "2027-08-28T18:00:00.000Z",
    relatedSlugs: ["dario-napoli", "benji-winterstein"],
  },
  {
    slug: "khamoro",
    name: "Khamoro",
    city: "Prague",
    country: "Czechia",
    when: "May",
    founded: "1999",
    site: "https://www.khamoro.cz/",
    bio: "Prague's world Roma festival. Khamoro is broader than gypsy jazz, but the manouche nights have hosted Paulus Schäfer and other Sinti guitarists as part of Europe's largest Roma cultural week. 2026 ran 24–30 May; next edition late May 2027.",
    nextStartsAt: "2027-05-26T18:00:00.000Z",
    relatedSlugs: ["paulus-schafer"],
  },
  {
    slug: "django-feszt-budapest",
    name: "Django Feszt Budapest",
    city: "Budapest",
    country: "Hungary",
    when: "Late August",
    founded: "2021",
    site: "https://www.facebook.com/groups/628542240660254/",
    bio: "Budapest’s jazz-manouche day — historically Margaret Island / Pavilon Kert, with Manuska Jam Club holding the jam. The 2026 date has not been posted yet; watch Gypsy Jazz Jams Budapest and Jazz Manouche Hungary. Until organisers publish, the next week is late August 2027.",
    nextStartsAt: "2027-08-27T11:00:00.000Z",
    relatedSlugs: ["roby-lakatos", "robert-karpati", "vilmos-lakatos", "tamas-szakal"],
  },
  {
    slug: "victoria-django",
    name: "Victoria Django Festival",
    city: "Victoria",
    country: "Canada",
    when: "3 October 2026",
    founded: "2012",
    site: "https://marywinspear.ca/events-and-programs/the-bc-django-festival/",
    tickets: "https://purchase.marywinspear.ca/EventAvailability?WebEventId=159",
    bio: "Gypsy jazz on Vancouver Island — now billed as The BC Django Festival, presented by The Victoria Django Society. Saturday 3 October 2026, 19:30, Charlie White Theatre at the Mary Winspear Centre, Sidney. Marc Atkinson Trio and Club Voltaire. Tickets $46.",
    nextStartsAt: "2026-10-04T02:30:00.000Z",
    relatedSlugs: ["marc-atkinson", "oliver-swain"],
  },
  {
    slug: "hita-django",
    name: "Hita Django Festival",
    city: "Hita",
    country: "Japan",
    when: "Autumn",
    founded: "1999",
    site: "",
    bio: "Japan's Django festival, in the town of Hita. One of the longest-running gypsy jazz gatherings in Asia, with European guests and a devoted Japanese Hot Club scene.",
    nextStartsAt: "2026-10-10T10:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "setouchi-django-street",
    name: "Setouchi Django Street",
    city: "Yashima",
    country: "Japan",
    when: "October",
    founded: "2019",
    site: "https://stu-django.net/english.html",
    bio: "Japan’s big gypsy jazz weekend in Yashima, Kagawa — 瀬戸内ジャンゴ・ストリート. Seventh edition 10–11 October 2026. Denis Chang’s first leader mini-tour lands here after Tokyo and Osaka, with Reilly Farrell, Alison Zhen and Hanaoka Toshio. django.tigalle@gmail.com",
    nextStartsAt: "2026-10-10T03:00:00.000Z",
    relatedSlugs: ["denis-chang", "reilly-farrell", "alison-zhen", "hanaoka-toshio"],
  },
  {
    slug: "gipsy-festival-angers",
    name: "Gipsy Festival Angers",
    city: "Angers",
    country: "France",
    when: "Summer",
    founded: "1990s",
    site: "",
    bio: "A French gypsy music festival in Angers that regularly bills manouche guitar beside the wider Gitan and Balkan programmes — a west-of-Paris date on the summer circuit.",
    nextStartsAt: "2027-07-03T18:00:00.000Z",
    relatedSlugs: ["angelo-debarre", "yorgui-loeffler"],
  },
  {
    slug: "festival-jazz-manouche-forbach",
    name: "Festival de jazz manouche de Forbach",
    city: "Forbach",
    country: "France",
    when: "May — next dates not posted",
    founded: "2018",
    site: "https://www.mairie-forbach.fr/agenda/festival-de-jazz-manouche-centre-de-congres-du-burghof",
    tba: true,
    bio: "Forbach (Moselle), at the Centre de Congrès du Burghof, 15 rue du Parc. Since 2018. Recurring May. Last on file: 8–10 May 2026 (8th edition) — past, not upcoming. Next dates not posted. 2026 archive bill: Mario Hoffman; David Girardi Project; Hot Sugar with Amati Schmitt, Sébastien Giniaux, Gismo Graf; Dario Napoli Trio with Baiju Bhatt; Sanseverino, Brady Winterstein, Hervé Poulikin; Pansch Weiss, Jimmy Hoffmann 4TET; Luis Salinas. Organisers: Jazz Festival Forbach, Popots / Benji Winterstein, town of Forbach, Département de la Moselle.",
    nextStartsAt: "2027-05-08T18:00:00.000Z",
    relatedSlugs: [
      "amati-schmitt",
      "sebastien-giniaux",
      "gismo-graf",
      "dario-napoli",
      "brady-winterstein",
      "benji-winterstein",
      "hono-winterstein",
      "popots-winterstein",
    ],
  },
  {
    slug: "jazz-in-duketown",
    name: "Jazz in Duketown",
    city: "'s-Hertogenbosch",
    country: "Netherlands",
    when: "Whitsun",
    founded: "1981",
    site: "https://www.jazzinduketown.nl/",
    bio: "Den Bosch's city jazz festival. Not only gypsy jazz, but the Dutch Sinti groups — Rosenberg, Schäfer — are a fixture of the squares every spring.",
    nextStartsAt: "2027-05-16T14:00:00.000Z",
    relatedSlugs: ["paulus-schafer", "stochelo-rosenberg", "daniel-gueli"],
  },
  {
    slug: "django-sur-lennon",
    name: "Django sur Lennon / Django Donegal",
    city: "Letterkenny",
    country: "Ireland",
    when: "5–7 December 2026",
    founded: "2010s",
    site: "https://djangosurlennon.com/",
    tickets: "https://regionalculturalcentre.com/",
    bio: "Ireland’s gypsy jazz gathering — Django sur Lennon, now billed as Django Donegal at the Regional Cultural Centre, Letterkenny. Next festival 5–7 December 2026. Before that: Hugo Guezbar Trio with Giacomo Smith, Friday 2 October 2026, 20:00. Late sessions at Blake’s Bar.",
    nextStartsAt: "2026-12-05T19:00:00.000Z",
    relatedSlugs: ["hugo-guezbar", "giacomo-smith", "adrien-moignard", "paulus-schafer"],
  },
  {
    slug: "charm-city-django",
    name: "Charm City Django Jazz Fest",
    city: "Baltimore",
    country: "United States of America",
    when: "Autumn",
    founded: "2010s",
    site: "",
    bio: "Baltimore's gypsy jazz weekend. Charm City Django is part of the East Coast string of US Django dates — concerts and workshops in the same spirit as Django in June.",
    nextStartsAt: "2026-10-24T19:00:00.000Z",
    relatedSlugs: ["stephane-wrembel"],
  },
  {
    slug: "camp-django",
    name: "Camp Django",
    city: "Ashland / Portland, Oregon",
    country: "United States of America",
    when: "Summer",
    founded: "2010s",
    site: "",
    bio: "Pacific Northwest gypsy jazz camp and concerts. Camp Django is workshops by day and a legends concert by night — a working school for the American scene.",
    nextStartsAt: "2027-07-08T18:00:00.000Z",
    relatedSlugs: ["paulus-schafer"],
  },
  {
    slug: "grappelli-django-camp",
    name: "Grappelli-Django Camp",
    city: "Netherlands",
    country: "Netherlands",
    when: "Summer",
    founded: "2000s",
    site: "",
    bio: "The Dutch teaching camp named for both chairs of the Quintette. Violin and guitar students work the repertoire with European guests, then sit in at night.",
    nextStartsAt: "2027-08-12T16:00:00.000Z",
    relatedSlugs: ["tim-kliphuis", "christiaan-van-hemert"],
  },
  {
    slug: "copenhagen-django",
    name: "Copenhagen Django / Jazz Festival",
    city: "Copenhagen",
    country: "Denmark",
    when: "July",
    founded: "1979",
    site: "",
    bio: "Copenhagen Jazz Festival always holds a gypsy jazz strand. Hot Club players from the Netherlands and France treat the July city festival as a Scandinavian date on the circuit.",
    nextStartsAt: "2027-07-02T18:00:00.000Z",
    relatedSlugs: ["paulus-schafer"],
  },
  {
    slug: "django-a-gogo",
    name: "Django à Gogo",
    city: "New York",
    country: "United States of America",
    when: "Spring",
    founded: "2010s",
    site: "http://www.djangoagogo.com/",
    bio: "Stéphane Wrembel's music festival and guitar camp. Django à Gogo is a world-class evening of gypsy jazz plus a week of workshops — New York at the core, with Canadian editions. Professionals on stage, amateurs in the classrooms and late jams.",
    nextStartsAt: "2027-03-12T19:00:00.000Z",
    relatedSlugs: ["stephane-wrembel"],
  },
  {
    slug: "london-gypsy-jazz-festival",
    name: "London Gypsy Jazz Festival",
    city: "London",
    country: "United Kingdom",
    when: "Autumn",
    founded: "2010s",
    site: "",
    bio: "The capital's gypsy jazz week: concerts, workshops and jams that pull in the British Hot Club bands and visiting European players. Amateurs sit in; professionals take the bigger rooms.",
    nextStartsAt: "2026-10-15T19:00:00.000Z",
    relatedSlugs: ["dave-kelbie", "robin-nolan", "paulus-schafer"],
  },
  {
    slug: "django-in-london",
    name: "Django In London",
    city: "London",
    country: "United Kingdom",
    when: "17–19 September 2026",
    founded: "2020s",
    site: "https://www.eventbrite.com/e/django-in-london-tickets-1995698734638",
    bio: "Three days at St Mary's, Upper Street, Islington. Thursday 17th: Harry Diplock Trio (19:30) and Hugo Guezbar Trio (21:00). Friday 18th: Elias Prinz & Sunny Franz Quartet (19:30) and Angelo Debarre Trio (21:00). Saturday 19th: Giacomo Smith matinee (15:00) and London Django Collective with Kourosh Kanani (21:00). Tickets on Eventbrite.",
    nextStartsAt: "2026-09-17T18:30:00.000Z",
    relatedSlugs: [
      "harry-diplock",
      "hugo-guezbar",
      "angelo-debarre",
      "elias-prinz",
      "sunny-franz",
      "giacomo-smith",
      "kourosh-kanani",
    ],
  },
  {
    slug: "django-in-the-bay",
    name: "Django In The Bay",
    city: "Rutland",
    country: "United Kingdom",
    when: "Late May",
    founded: "2023",
    site: "https://djangointhebay.co.uk/",
    tickets: "https://djangointhebay.co.uk/tickets/",
    bio: "A Django Reinhardt festival on the shores of Rutland Water, at The Hide at Manton Bay. Small — about 400 people — with evening concerts, workshops, jam sessions all over the grounds, camping and a luthier tent. Players from the Gypsy jazz uk Facebook group treat it as the UK gathering. Luthiers who have shown there include Jerome Duffell, Killy Nonis, Robert Ford, Alex Bishop and John Le Voi. Run by Natalia Douglas and Matt Kerry. Next edition after the 22–24 May 2026 gathering.",
    nextStartsAt: "2027-05-21T17:00:00.000Z",
    relatedSlugs: [
      "fapy-lafertin",
      "tcha-limberger",
      "wawau-adler",
      "sebastien-giniaux",
      "simba-baumgartner",
      "angelo-debarre",
      "amati-schmitt",
    ],
  },
  {
    slug: "shrewsbury-django-fest",
    name: "Shrewsbury Django Fest",
    city: "Shrewsbury",
    country: "United Kingdom",
    when: "23–25 October 2026",
    founded: "2020s",
    site: "https://www.shrewsburydjangofest.co.uk/",
    bio: "The Shropshire gypsy jazz weekend. Friday 23 October: John Wheatcroft Trio featuring Olivia Frances Brown, then Mozes Rosenberg Trio with Christiaan van Hemert (Chris Quinn, Mike Green). Saturday 24 October: Marion & Sobo Band, then Paulus Schäfer and Olli Soikkeli with Matheus Nicolaiewsky. Sunday 25 October: Gypsy Jazz Retreat concert, Marion & Sobo, all-star jam. Free daytime DJams Saturday and Sunday — Glou Glou Wine Bar, The Bull Inn, The Nags Head. Workshops sit on the same weekend (Gypsy Jazz Retreats).",
    nextStartsAt: "2026-10-23T18:00:00.000Z",
    relatedSlugs: [
      "mozes-rosenberg",
      "paulus-schafer",
      "olli-soikkeli",
      "christiaan-van-hemert",
      "chris-quinn",
      "john-wheatcroft",
    ],
  },
  {
    slug: "biggar-django-festival",
    name: "Biggar Django Festival",
    city: "Biggar",
    country: "United Kingdom",
    when: "16–18 April 2027",
    founded: "2026",
    site: "https://biggardjangofestival.org.uk/",
    bio: "Three days in the Scottish town of Biggar: concerts, open workshops, film and jam sessions across Arcadia Music Cafe, the Corn Exchange, The Crown Inn, The Gillespie Centre and The Elphinstone. 2026 was 19–21 June (Robin Nolan Trio, Manouchetones, Seonaid Aitken’s Manouche Nouveau). Next dates 16–18 April 2027.",
    nextStartsAt: "2027-04-16T18:00:00.000Z",
    relatedSlugs: ["robin-nolan"],
  },
  {
    slug: "chicago-gypsy-jazz-fest",
    name: "Chicago Gypsy Jazz Fest",
    city: "Chicago",
    country: "United States of America",
    when: "15–19 September 2026",
    founded: "2000s",
    site: "https://gypsyjazzfest.com/",
    bio: "24th annual. SPACE in Evanston (15 Sep), Gale Street Inn (17 Sep), Green Mill (16–19 Sep) — Hot Club of Baltimore Trio, Alfonso Ponticelli, Dario Napoli (18–19). gypsyjazzfest.com / gypsyjazz.us.",
    nextStartsAt: "2026-09-16T00:30:00.000Z",
    relatedSlugs: ["alfonso-ponticelli", "dario-napoli"],
  },
  {
    slug: "taipei-gypsy-jazz-festival",
    name: "Taipei Gypsy Jazz Festival",
    city: "Taipei",
    country: "Taiwan",
    when: "November",
    founded: "2015",
    site: "https://www.gypsyjazztaipei.com/",
    bio: "Taipei Gypsy Jazz Festival — 台北吉普賽爵士音樂節. Since 2015, Vincent Tsai’s room: European guests, workshops at his accordion studio, night jams at Sappho Live, the November concert at Songshan Eslite. 2025 brought Paulus Schäfer and Christiaan van Hemert; the local chairs — Tsai, bassist Larry Chen, harmonica Yen-Hua Wang, piano Ming-Hsuan Mao — hold the circle with Denis Chang, who returns each year. 2026 dates on the festival page.",
    nextStartsAt: "2026-11-19T12:00:00.000Z",
    relatedSlugs: [
      "vincent-tsai",
      "larry-chen",
      "yen-hua-wang",
      "ming-hsuan-mao",
      "paulus-schafer",
      "christiaan-van-hemert",
      "denis-chang",
      "jose-fernando-seifarth",
    ],
  },
  {
    slug: "taipei-jazz-festival",
    name: "Taipei Jazz Festival",
    city: "Taipei",
    country: "Taiwan",
    when: "4 September – 11 October 2026",
    founded: "2007",
    site: "https://www.travel.taipei/en/event-calendar/details/66797",
    bio: "臺北爵士音樂節 — the city’s jazz month, 20th year. Indoor nights in Taipei rooms, outdoor sets, and a main stage at Taipei Music Center. Not a gypsy-jazz-only bill, but the room where the Taipei scene meets the rest of jazz. Bassist Larry Chen sat the 2018–2021 editions.",
    nextStartsAt: "2026-09-04T12:00:00.000Z",
    relatedSlugs: ["larry-chen"],
  },
  {
    slug: "ozmanouche",
    name: "OzManouche",
    city: "Brisbane",
    country: "Australia",
    when: "23–27 September 2026",
    founded: "2000s",
    site: "https://www.ozmanouche.com/",
    bio: "Australia’s jazz manouche festival, 23–27 September 2026 at Brisbane Jazz Club. John Jorgenson guest; The Date Brothers, Daniel Weltlinger, Tea For Two, Sydney Gypsies, Hot Club Caravane, Hot Club of Wollongong. River-deck jams including Tazzmania Jam with Charlie McCarthy. ozmanouche.com.",
    nextStartsAt: "2026-09-23T09:00:00.000Z",
    relatedSlugs: ["john-jorgenson", "daniel-weltlinger", "nigel-date", "ian-date", "charlie-mccarthy"],
  },
  {
    slug: "midwest-gypsy-swing-fest",
    name: "Midwest Gypsy Swing Fest",
    city: "Madison, Wisconsin",
    country: "United States of America",
    when: "11–12 September 2026",
    founded: "2010s",
    site: "https://midwestdjangofestival.com/",
    bio: "The Midwest's Django weekend, this year at William G. Lunney Lake Farm County Park, 4330 Libby Road. Friday 11 Sep from 18:00, Saturday 12 Sep from 15:00. Harmonious Wail host; Gonzalo Bergara Trio, Dario Napoli Trio, Alfonso Ponticelli, Hot Club of Baltimore, Shauncey Ali Quartet. Super Djam and campfire after the billed sets.",
    nextStartsAt: "2026-09-11T23:00:00.000Z",
    relatedSlugs: ["dario-napoli", "gonzalo-bergara", "alfonso-ponticelli"],
  },
  {
    slug: "festival-django-portugal",
    name: "Festival Django Portugal",
    city: "Lisbon",
    country: "Portugal",
    when: "May — dates not posted",
    founded: "2020",
    site: "https://festivaldjangoportugal.pt/",
    tba: true,
    bio: "Nuno Marinho’s festival — a year-round series, main week usually May (festivaldjangoportugal.pt). 2026 week already happened: 8–22 May, Lisbon (Fábrica Braço de Prata) and Coimbra. Adrien Moignard 8 May, Lollo Meier Quartet 15 May, Hugo Guezbar Trio 22 May. Next edition: dates not posted. The Tim Kliphuis Trio with Nuno Marinho nights at Fábrica Braço de Prata (30 Oct 2026) and Salão Brazil, Coimbra (31 Oct 2026) are separate concerts, not the festival week.",
    nextStartsAt: "2027-05-08T20:00:00.000Z",
    relatedSlugs: [
      "nuno-marinho",
      "marian-yanchyk",
      "adrien-moignard",
      "frank-meester",
      "hugo-guezbar",
      "lollo-meier",
    ],
  },
  {
    slug: "festival-jazz-manouche-almada",
    name: "Festival Jazz Manouche de Almada",
    city: "Almada",
    country: "Portugal",
    when: "May — next dates not posted",
    founded: "",
    site: "https://www.instagram.com/festivaljazzmanouchealmada/",
    tba: true,
    bio: "Not Nuno Marinho’s festival. Organised by Alma Danada at Cine Incrível, Almada. Last edition: 8–10 May 2026 (5th). Friday David Regueiro Trio ft. Thomas Kretzschmar; Saturday Nouveau Quintette du Hot Club de France (Duved Dunayevsky, Daniel Garlitsky); Sunday dance class + Stomping at Six. Recurring May. Next dates not posted. festivaljazzmanouchealmada@gmail.com.",
    nextStartsAt: "2027-05-08T18:00:00.000Z",
    relatedSlugs: ["duved-dunayevsky"],
  },
  {
    slug: "festival-django-lh",
    name: "Festival Django L'H",
    city: "L'Hospitalet de Llobregat",
    country: "Spain",
    when: "November, dates to be posted",
    founded: "2010",
    site: "https://www.festivaldjangolh.com/",
    tba: true,
    bio: "Spain’s dedicated Django / jazz manouche festival, in L'Hospitalet de Llobregat on the Barcelona metro since 2010. Typical window: November. Last edition on file: 7–9 November 2025. Run with EMMCA (Escola Municipal de Música – Centre de les Arts de L’Hospitalet), the public school in Gornal that teaches jazz manouche. Albert Bello directs the festival. Do not treat a missing 2026 poster as a cancelled year — dates to be posted.",
    nextStartsAt: "2026-11-01T18:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "villamajazz",
    name: "Villamajazz",
    city: "Villamañán",
    country: "Spain",
    when: "4–6 September 2026",
    founded: "2006",
    site: "https://www.facebook.com/p/VillamaJazz-100054528457475/",
    bio: "Outdoor manouche/swing in Villamañán, León, since 2006. Free, usually September with the village fiestas. 19th edition 4–6 September 2026. Bill not posted — no invented names. Last 2025 names stay in the past, not as upcoming.",
    nextStartsAt: "2026-09-04T16:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "melbourne-hot-djams",
    name: "Melbourne Hot Djams",
    city: "Melbourne",
    country: "Australia",
    when: "Ongoing jams",
    founded: "2000s",
    site: "",
    bio: "First-Sunday Melbourne Hot Djams at the Caulfield Park rotunda — the long amateur jam between festivals. Melbourne Hot Club keeps the chairs filled.",
    nextStartsAt: "2026-09-06T03:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "festival-jazz-manouche-piracicaba",
    name: "Festival Jazz Manouche Piracicaba",
    city: "Piracicaba",
    country: "Brazil",
    when: "August",
    founded: "2013",
    site: "https://festivaljazzmanouche.com.br/",
    bio: "José Fernando Seifarth’s festival — 12th edition 6–9 August 2026, Engenho Central, Teatro Erotides de Campos, free. Thursday: Marcos Moraes and André Ribas, then Guinga. Friday 7 August, the European night: Tim Kliphuis with Brasília mandolin Victor Angeleas; then Sébastien Giniaux, Nuno Marinho, Arnoud van den Berg and Florian Cristea. Saturday outdoor: Hot Club de Piracicaba, Caipira Jazz Duo, Bina Coquet with Ming-Hsuan Mao, the Brasília–Curitiba–Piracicaba conexão, Denis Chang with Django Sessions (Argentina). Sunday jam for Eloy Porto Neto. House band since 2008.",
    nextStartsAt: "2027-08-05T23:00:00.000Z",
    relatedSlugs: [
      "jose-fernando-seifarth",
      "marcos-moraes",
      "bina-coquet",
      "estela-manfrinato",
      "victor-angeleas",
      "eduardo-souza",
      "tim-kliphuis",
      "nuno-marinho",
      "sebastien-giniaux",
      "arnoud-van-den-berg",
      "florian-cristea",
      "denis-chang",
      "ming-hsuan-mao",
    ],
  },
  {
    slug: "festival-django-argentina",
    name: "Festival Internacional de Jazz Django Argentina",
    city: "Buenos Aires",
    country: "Argentina",
    when: "May",
    founded: "2002",
    site: "https://www.instagram.com/argentinadjangofestival/",
    bio: "Buenos Aires Django week — 24th edition May 2026, several rooms (Bar de Fondo, Centro Cultural 25 de Mayo). Ricardo Pellican artistic director. Swing Medical held jam nights inside the festival. Next edition typically May. Instagram @argentinadjangofestival.",
    nextStartsAt: "2027-05-12T22:00:00.000Z",
    relatedSlugs: ["ricardo-pellican", "lucas-reydo", "roque-monsalve", "rafael-marrero", "lara-fichera"],
  },
  {
    slug: "festival-manouche-curitiba",
    name: "Festival Manouche Curitiba",
    city: "Curitiba",
    country: "Brazil",
    when: "October",
    founded: "2023",
    site: "https://www.instagram.com/festivalmanouchecuritiba/",
    bio: "4th edition 20–25 October 2026. Produced by Mateus Azevedo and Marcela Zanette. Jazz Cigano Quinteto house band; Londrina Hot Club, Hot Club de Piracicaba guests. Teatro Paiol and city rooms. Instagram @festivalmanouchecuritiba.",
    nextStartsAt: "2026-10-20T23:00:00.000Z",
    relatedSlugs: ["lucas-miranda", "vinicius-araujo", "mateus-azevedo", "john-theo", "jose-fernando-seifarth"],
  },
  {
    slug: "festival-django-cl",
    name: "Festival Django CL",
    city: "Santiago",
    country: "Chile",
    when: "October",
    founded: "2018",
    site: "https://gam.cl/es/que-hacer-en-gam/musica-popular/festival-django/",
    bio: "Chile’s manouche week. 8th edition October 2025 at GAM (Centro Gabriela Mistral) — Ricardo Pellican, Lara Fichera, Hermanouche, Santiago Royal. Workshops and clinics as well as concerts. 2026 date unpublished; usually October at GAM, Av. Libertador Bernardo O'Higgins 227.",
    nextStartsAt: "2026-10-11T21:00:00.000Z",
    relatedSlugs: ["ricardo-pellican", "lara-fichera"],
  },
  {
    slug: "asheville-djangofest",
    name: "Asheville Djangofest",
    city: "Swannanoa, North Carolina",
    country: "United States of America",
    when: "24 October 2026",
    founded: "2020s",
    site: "https://www.eventbrite.com/e/asheville-djangofest-tickets-1992387859722",
    bio: "Saturday 24 October at Kittredge Theatre, Warren Wilson College, 701 Warren Wilson Road. Stéphane Wrembel solo, with Gustav Viehmeyer, Fil Pate and Danny Iannucci. Concert from 19:00; the afternoon is a longer Django afternoon. Tickets on Eventbrite.",
    nextStartsAt: "2026-10-24T23:00:00.000Z",
    relatedSlugs: ["stephane-wrembel"],
  },
  {
    slug: "djangofest-mill-valley",
    name: "DjangoFest Mill Valley",
    city: "Mill Valley, California",
    country: "United States of America",
    when: "24–27 September 2026",
    founded: "2020s",
    site: "https://www.throckmortontheatre.org/djangofest-mill-valley",
    bio: "West Coast Django week at 142 Throckmorton Theatre. Official 2026 nights: Thursday 24 Sep 20:00 Gonzalo Bergara Quintet feat. Leah Zeger and Rob Hardt; Friday 25 Sep 20:00 Sam Farthing All Stars feat. Stella Heath; Saturday 26 Sep 20:00 Gismo Graf Quintet with Tim Kliphuis; Sunday 27 Sep Grappelli’s Django. Workshops in the same house. throckmortontheatre.org.",
    nextStartsAt: "2026-09-25T03:00:00.000Z",
    relatedSlugs: ["gonzalo-bergara", "gismo-graf", "tim-kliphuis", "jimmy-grant", "sam-farthing"],
  },
  {
    slug: "viljandi-guitar-festival",
    name: "Viljandi Guitar Festival",
    city: "Viljandi",
    country: "Estonia",
    when: "7–11 October 2026",
    founded: "2000s",
    site: "https://viljandiguitar.ee/",
    bio: "Estonia’s guitar week at Pärimusmuusika Ait. Not a gypsy-jazz-only bill, but 9 October 2026 the Stochelo & Mozes Rosenberg Trio play The Chaplin Project — Charlie Chaplin songs in the Dutch Sinti language. viljandiguitar.ee.",
    nextStartsAt: "2026-10-09T15:00:00.000Z",
    relatedSlugs: ["stochelo-rosenberg", "mozes-rosenberg"],
  },
  {
    slug: "tsaritsyno-gypsy-jazz",
    name: "Tsaritsyno Gypsy Jazz",
    city: "Moscow",
    country: "Russia",
    when: "New Year holidays — typically early January",
    founded: "2017",
    site: "https://tsaritsyno-museum.ru/",
    bio: "Царицыно. Gypsy Jazz — Moscow’s jazz-manouche festival at the Khlebny Dom, Tsaritsyno museum-reserve. New Year holiday concerts. Dmitry Kuptsov and the Moscow circle have sat it. Confirm the next edition on the museum page — not a weekly jam.",
    nextStartsAt: "2027-01-04T13:00:00.000Z",
    relatedSlugs: ["dmitry-kuptsov", "georgiy-yashagashvili"],
  },
  {
    slug: "dubai-jass-lounge-gypsy-jazz",
    name: "Gypsy Jazz at Jass Lounge",
    city: "Dubai",
    country: "United Arab Emirates",
    when: "16 September 2026, 21:00",
    founded: "2020s",
    site: "https://www.afdubai.org/",
    bio: "Alliance Française Dubai gypsy jazz night at Jass Lounge, Wednesday 16 September 2026, 21:00. Concert, not an open jam. Check AF Dubai for the billed names.",
    nextStartsAt: "2026-09-16T17:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "reykjavik-jazz-festival",
    name: "Reykjavík Jazz Festival",
    city: "Reykjavík",
    country: "Iceland",
    when: "Late August",
    founded: "1990s",
    site: "https://www.reykjavikjazz.is/",
    tickets: "https://tix.is/en/category/festival/jazzhatid-reykjavikur",
    bio: "City jazz week, 25–30 August 2026 — Icelandic and visiting chairs across Reykjavík rooms (Harpa / Múlinn, Iðnó and others). Straight-ahead and Nordic jazz, not a Gypsy Jazz festival. A week when a Hot Club set could sit if someone books it.",
    nextStartsAt: "2026-08-25T18:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "java-jazz-festival",
    name: "Jakarta International Java Jazz Festival",
    city: "Jakarta",
    country: "Indonesia",
    when: "Late May",
    founded: "2005",
    site: "https://www.javajazzfestival.com/",
    bio: "Southeast Asia’s big jazz week. 2026 sat 29–31 May at Nusantara International Convention Exhibition, PIK 2. Straight-ahead, soul and visiting chairs — not a Gypsy Jazz festival. A week when a Hot Club set could sit if someone books it.",
    nextStartsAt: "2027-05-28T10:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "ncpa-international-jazz-festival",
    name: "NCPA International Jazz Festival",
    city: "Mumbai",
    country: "India",
    when: "Late November",
    founded: "2010s",
    site: "https://www.ncpamumbai.com/event/ncpa-international-jazz-festival-2026/",
    bio: "Mumbai concert jazz at the National Centre for the Performing Arts — 20–22 November 2026, Jamshed Bhabha Theatre. Visiting chairs, not a Gypsy Jazz festival.",
    nextStartsAt: "2026-11-20T13:30:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "django-reinhardt-festival-augsburg",
    name: "Django Reinhardt Festival Augsburg",
    city: "Augsburg",
    country: "Germany",
    when: "5–7 June 2026",
    founded: "2010s",
    site: "https://django-reinhardt-festival.de/",
    tickets: "https://django-reinhardt-festival.de/",
    bio: "International gypsy-jazz weekend at the Parktheater im Kurhaus Göggingen. 5–7 June 2026. Friday from 19:30: Diknu Schneeberger & Eva Scholten Quartet; Mozes Rosenberg & Sandro Roy Group; Adrien Moignard & Jermaine Landsberger Trio. Saturday: Django Deluxe invite Hugo Richter (Giovanni Weiss). Tickets via the Parktheater. django-reinhardt-festival.de / django-reinhardt-festival.eu.",
    nextStartsAt: "2026-06-05T17:30:00.000Z",
    relatedSlugs: [
      "diknu-schneeberger",
      "eva-scholten",
      "mozes-rosenberg",
      "sandro-roy",
      "adrien-moignard",
      "jermaine-landsberger",
      "giovanni-weiss",
      "hugo-richter",
      "dorado-schmitt",
    ],
  },
  {
    slug: "welcome-in-tziganie",
    name: "Welcome in Tziganie",
    city: "Seissan",
    country: "France",
    when: "Late April — next 23–25 April 2027",
    founded: "2008",
    site: "https://www.welcome-in-tziganie.com/",
    bio: "Gers festival of Tzigane, Balkan and manouche music at the Théâtre de verdure, Seissan. 19th edition 24–26 April 2026 is past (record crowd, Aurore Voilqué’s Balkan Ladies Connexion). 20th anniversary: 23–25 April 2027. Organiser L’Air des Balkans / Florian Calvez. welcome-in-tziganie.com.",
    nextStartsAt: "2027-04-23T17:00:00.000Z",
    relatedSlugs: ["aurore-voilque"],
  },
  {
    slug: "festival-jazz-musette-des-puces",
    name: "Festival Jazz Musette des Puces",
    city: "Saint-Ouen",
    country: "France",
    when: "18–21 June 2026",
    founded: "2000s",
    site: "https://www.festivaldespuces.com/",
    bio: "Didier Lockwood / Jazz Musette des Puces — gypsy jazz, musette and swing in the aisles of the Puces de Saint-Ouen. 18–21 June 2026. Open-air sets are free; dinner shows in the market rooms. Saturday stroll through the market. Not Samois — the flea-market weekend.",
    nextStartsAt: "2026-06-18T16:00:00.000Z",
    relatedSlugs: [],
  },
  {
    slug: "pennabilli-django-festival",
    name: "Pennabilli Django Festival",
    city: "Pennabilli",
    country: "Italy",
    when: "27–29 December 2026",
    founded: "2013",
    site: "http://www.pennabillidjangofestival.com/",
    bio: "Jazz manouche in the Marecchia valley, Rimini Appennines. Pennabilli Django Festival, 27–29 December 2026. pennabillidjangofestival.com.",
    nextStartsAt: "2026-12-27T19:00:00.000Z",
    relatedSlugs: ["jimmy-rosenberg", "gismo-graf"],
  },
  {
    slug: "jazzabar",
    name: "Festival Jazzabar",
    city: "Bar-sur-Aube",
    country: "France",
    when: "11 September 2026",
    founded: "",
    site: "",
    bio: "17e Festival Jazzabar. Friday 11 September 2026, Salle des fêtes, Bar-sur-Aube (10200). Quintette du Hot Club de France at 22:00.",
    nextStartsAt: "2026-09-11T20:00:00.000Z",
    relatedSlugs: [
      "duved-dunayevsky",
      "daniel-garlitsky",
      "pierre-richeux",
      "andrea-soria",
      "scott-koehler",
    ],
  },
];

export function festivalsInCountry(atlasName: string): Festival[] {
  return FESTIVALS.filter((festival) => festival.country === atlasName);
}

export function getFestival(slug: string): Festival | undefined {
  return FESTIVALS.find((festival) => festival.slug === slug);
}

export function festivalNextLabel(festival: Festival) {
  if (festival.tba) return festival.when;
  return festival.nextStartsAt;
}

const TICKET_PAGES: Record<string, string> = {
  "victoria-django": "https://purchase.marywinspear.ca/EventAvailability?WebEventId=159",
  "djangofest-northwest": "https://www.djangofest.com/box-office",
  ozmanouche: "https://linktr.ee/OzManouche",
  "midwest-gypsy-swing-fest": "https://midwestdjangofestival.com/",
  "django-in-london": "https://www.eventbrite.com/e/django-in-london-tickets-1995698734638",
  "django-in-the-bay": "https://djangointhebay.co.uk/tickets/",
  "shrewsbury-django-fest": "https://www.gypsyjazzretreats.com/sign-up-earlybird2026",
  "biggar-django-festival": "https://biggardjangofestival.org.uk/",
  "asheville-djangofest": "https://www.eventbrite.com/e/asheville-djangofest-tickets-1992387859722",
  "djangofest-mill-valley": "https://www.throckmortontheatre.org/djangofest-mill-valley",
  "chicago-gypsy-jazz-fest": "https://gypsyjazzfest.com/",
  "viljandi-guitar-festival": "https://fienta.com/viljandiguitar-festivalipass26",
  "festival-django-portugal": "https://festivaldjangoportugal.pt/",
  "festival-django-lh": "https://www.festivaldjangolh.com/",
  "taipei-gypsy-jazz-festival": "https://www.gypsyjazztaipei.com/",
  "birdland-django-festival": "https://www.birdlandjazz.com/",
  "festival-django-cl": "https://gam.cl/es/que-hacer-en-gam/musica-popular/festival-django/",
  "setouchi-django-street": "https://stu-django.net/english.html",
  "django-sur-lennon": "https://regionalculturalcentre.ticketsolve.com/ticketbooth/shows/873666847",
};

export function festivalTicketUrl(festival: Festival): string {
  if (festival.tickets) return festival.tickets;
  if (TICKET_PAGES[festival.slug]) return TICKET_PAGES[festival.slug]!;
  if (/eventbrite|ticketsearch|purchase\.|fienta/.test(festival.site)) return festival.site;
  return "";
}

export function festivalForConcert(concert: { title: string; venue: string; city: string }) {
  const exact = FESTIVALS.find(
    (row) => row.name.toLowerCase() === concert.title.trim().toLowerCase(),
  );
  if (exact) return exact;
  return FESTIVALS.find((row) => concertBelongsToFestival(row, concert));
}

export function concertBelongsToFestival(
  festival: Festival,
  concert: { title: string; venue: string; city: string },
) {
  const hay = `${concert.title} ${concert.venue} ${concert.city}`.toLowerCase();
  const keys = [festival.name, festival.slug.replace(/-/g, " ")];
  if (festival.slug === "victoria-django") keys.push("bc django festival", "mary winspear");
  if (festival.slug === "django-sur-lennon") keys.push("django donegal", "letterkenny");
  return keys.some((key) => key.length > 3 && hay.includes(key.toLowerCase()));
}

export function festivalsForArtist(slug: string, samois = false): Festival[] {
  const hits = FESTIVALS.filter((festival) => festival.relatedSlugs.includes(slug));
  if (samois) {
    const fdr = getFestival("festival-django-reinhardt");
    if (fdr && !hits.some((festival) => festival.slug === fdr.slug)) {
      hits.unshift(fdr);
    }
  }
  return hits;
}
