/** Localized Hot Club bios. Facts only; missing locale falls back to English. */

const BIOS: Record<string, Record<string, string>> = {
  "hcdf-nederland": {
    fr: "Fondation gypsy jazz néerlandaise, créée en 1983. Premier concert : le WASO Quartet. Ils tiennent un magazine trimestriel, De Quintette, une lettre et une liste de donateurs. Ils signalaient les jams des grandes villes — environ 100 groupes Hot Club et plus de 100 jams par an aux Pays-Bas. Écrire, devenir donateur : hcdf.nl",
    de: "Niederländische Gypsy-Jazz-Stiftung, 1983 gegründet. Erstes Konzert: WASO Quartet. Vierteljahresheft De Quintette, Newsletter, Förderliste. Sie verweisen auf Jams in den großen Städten — etwa 100 Hot-Club-Bands und über 100 Jams im Jahr in den Niederlanden. Schreiben, Fördermitglied: hcdf.nl",
    nl: "Nederlandse gypsy-jazzstichting, opgericht in 1983. Eerste concert: het WASO Quartet. Kwartaalblad De Quintette, nieuwsbrief en donateurslijst. Ze wijzen naar jams in de grote steden — ongeveer 100 Hot Club-bands en meer dan 100 jams per jaar in Nederland. Schrijf, word donateur: hcdf.nl",
    it: "Fondazione gypsy jazz olandese, nata nel 1983. Primo concerto: WASO Quartet. Rivista trimestrale De Quintette. Indicano i jam delle città — circa 100 gruppi Hot Club e oltre 100 jam all’anno nei Paesi Bassi. Scrivi, diventa donatore: hcdf.nl",
    es: "Fundación holandesa de gypsy jazz, 1983. Primer concierto: WASO Quartet. Revista De Quintette. Señalan jams en las ciudades — unos 100 grupos Hot Club y más de 100 jams al año en los Países Bajos. Escribe, hazte donante: hcdf.nl",
    pt: "Fundação holandesa de gypsy jazz, 1983. Primeiro concerto: WASO Quartet. Revista De Quintette. Indicam jams nas cidades — cerca de 100 grupos Hot Club e mais de 100 jams por ano nos Países Baixos. Escreve, torna-te dador: hcdf.nl",
    ru: "Нидерландский фонд gypsy jazz, 1983. Первый концерт: WASO Quartet. Журнал De Quintette. Указывают джемы в городах — около 100 Hot Club групп и более 100 джемов в год. Пишите, становитесь донором: hcdf.nl",
  },
  "hot-club-de-france": {
    fr: "La société de jazz d’origine (1932). Le quintette de Django a pris ce nom. Aujourd’hui ils défendent le jazz authentique, des concerts et un bulletin — pas seulement le gypsy jazz, mais la maison d’où vient le nom Hot Club. hot-club.asso.fr",
    de: "Die ursprüngliche Jazzgesellschaft (1932). Djangos Quintett nahm diesen Namen. Heute fördern sie authentischen Jazz, Konzerte und ein Bulletin — nicht nur Gypsy Jazz, sondern das Haus, aus dem der Name Hot Club kommt. hot-club.asso.fr",
    nl: "De oorspronkelijke jazzvereniging (1932). Django’s kwintet nam deze naam. Vandaag steunen ze authentieke jazz, concerten en een bulletin — niet alleen gypsy jazz, maar het huis waar de naam Hot Club vandaan komt. hot-club.asso.fr",
    it: "La società jazz originale (1932). Il quintetto di Django prese questo nome. Oggi promuovono jazz autentico, concerti e un bollettino — non solo gypsy jazz, ma la casa da cui viene il nome Hot Club. hot-club.asso.fr",
    es: "La sociedad de jazz original (1932). El quinteto de Django tomó este nombre. Hoy promueven el jazz auténtico, conciertos y un boletín — no solo gypsy jazz, sino la casa de la que sale el nombre Hot Club. hot-club.asso.fr",
    pt: "A sociedade de jazz original (1932). O quinteto de Django tomou este nome. Hoje promovem jazz autêntico, concertos e um boletim — não só gypsy jazz, mas a casa de onde vem o nome Hot Club. hot-club.asso.fr",
    ru: "Первоначальное джазовое общество (1932). Квинтет Django взял это имя. Сегодня они поддерживают настоящий джаз, концерты и бюллетень — не только gypsy jazz, а дом, откуда имя Hot Club. hot-club.asso.fr",
    ja: "元のジャズ協会（1932）。ジャンゴの五重奏がこの名を取った。今も本格ジャズ、コンサート、会報。ジプシージャズだけでなく、Hot Club の名前の家。hot-club.asso.fr",
    ko: "원래의 재즈 협회(1932). 장고의 퀸텟이 이 이름을 썼다. 정통 재즈, 콘서트, 회보. 집시 재즈만이 아니라 Hot Club 이름의 집. hot-club.asso.fr",
    zh: "最初的爵士协会（1932）。Django 的五重奏用了这个名字。如今推广正宗爵士、音乐会和会刊——不只是吉普赛爵士，而是 Hot Club 这个名字的出处。hot-club.asso.fr",
    "zh-tw": "最初的爵士協會（1932）。Django 的五重奏用了這個名字。如今推廣正宗爵士、音樂會和會刊——不只是吉普賽爵士，而是 Hot Club 這個名字的出處。hot-club.asso.fr",
    hu: "Az eredeti jazz-társaság (1932). Django kvintettje vette fel a nevet. Ma az autentikus jazzt, koncerteket és egy közlönyt viszik — nemcsak gypsy jazz, hanem a Hot Club név háza. hot-club.asso.fr",
    pl: "Pierwotne towarzystwo jazzowe (1932). Kwintet Djangów wziął tę nazwę. Dziś wspierają autentyczny jazz, koncerty i biuletyn. hot-club.asso.fr",
    cs: "Původní jazzová společnost (1932). Djangovo kvinteto vzalo toto jméno. Dnes podporují autentický jazz, koncerty a bulletin. hot-club.asso.fr",
    hr: "Izvorno jazz društvo (1932). Djangov kvintet uzeo je ovo ime. Danas promiču autentični jazz, koncerte i bilten. hot-club.asso.fr",
    sr: "Изворно џез друштво (1932). Djangov квинтет узео је ово име. Данас промовишу аутентични џез, концерте и билтен. hot-club.asso.fr",
    ro: "Societatea de jazz de origine (1932). Quintetul lui Django a luat acest nume. Azi promovează jazz autentic, concerte și un buletin. hot-club.asso.fr",
    id: "Perkumpulan jazz asli (1932). Kuintet Django memakai nama ini. Kini mereka mendukung jazz otentik, konser, dan buletin. hot-club.asso.fr",
    th: "สมาคมแจ๊สดั้งเดิม (1932) ควินเท็ตของ Django ใช้ชื่อนี วันนี้สนับสนุนแจ๊สแท้ คอนเสิร์ต และจดหมายข่าว hot-club.asso.fr",
  },
  "hot-club-de-lyon": {
    fr: "Le plus ancien club de jazz d’Europe encore ouvert (1948), cave voûtée sur la Presqu’île. Tout le jazz, y compris des soirées manouche et des jams hebdomadaires. Une soirée Hot Club ici, c’est du jazz live — écrivez-leur pour une affiche manouche. hotclubjazzlyon.com",
    de: "Europas ältester noch laufender Jazzclub (1948), Gewölbekeller auf der Presqu’île. Aller Jazz, auch Manouche-Abende und wöchentliche Jams. Ein Hot-Club-Abend hier heißt Live-Jazz — schreib ihnen für eine Manouche-Nacht. hotclubjazzlyon.com",
    nl: "Europa’s oudste jazzclub die nog draait (1948), gewelfde kelder op de Presqu’île. Alle jazz, ook manouche-avonden en wekelijkse jams. Een Hot Club-avond hier is live jazz — schrijf hen voor een manouche-avond. hotclubjazzlyon.com",
    it: "Il jazz club più antico d’Europa ancora aperto (1948), cantina a volte sulla Presqu’île. Tutto il jazz, serate manouche e jam settimanali. Una sera Hot Club qui è jazz dal vivo — scrivi per una serata manouche. hotclubjazzlyon.com",
    es: "El club de jazz más antiguo de Europa aún abierto (1948), bodega abovedada en la Presqu’île. Todo el jazz, noches manouche y jams semanales. Una noche Hot Club aquí es jazz en vivo — escríbeles para un cartel manouche. hotclubjazzlyon.com",
    pt: "O clube de jazz mais antigo da Europa ainda aberto (1948), cave na Presqu’île. Todo o jazz, noites manouche e jams semanais. Uma noite Hot Club aqui é jazz ao vivo. hotclubjazzlyon.com",
    ru: "Старейший джаз-клуб Европы, всё ещё работает (1948), сводчатый подвал на Presqu’île. Весь джаз, мануш-вечера и еженедельные джемы. hotclubjazzlyon.com",
    ja: "現役で最も古いヨーロッパのジャズクラブ（1948）。プレキルのアーチ地下室。マヌーシュの夜と毎週のジャム。hotclubjazzlyon.com",
    ko: "유럽에서 아직 열리는 가장 오래된 재즈 클럽(1948). 마누슈 밤과 매주 잼. hotclubjazzlyon.com",
    zh: "欧洲仍在营业的最老爵士俱乐部（1948），半岛拱顶地窖。含马努什之夜和每周即兴。hotclubjazzlyon.com",
    "zh-tw": "歐洲仍在營業的最老爵士俱樂部（1948）。含馬努什之夜與每週即興。hotclubjazzlyon.com",
    hu: "Európa legrégebbi, még működő jazzklubja (1948). Manouche-estek és heti jamek. hotclubjazzlyon.com",
    pl: "Najstarszy wciąż działający klub jazzowy w Europie (1948). Wieczory manouche i cotygodniowe jamy. hotclubjazzlyon.com",
    cs: "Nejstarší stále otevřený jazzový klub v Evropě (1948). Manouche večery a týdenní jamy. hotclubjazzlyon.com",
    hr: "Najstariji još otvoreni europski jazz klub (1948). Manouche večeri i tjedni jamovi. hotclubjazzlyon.com",
    sr: "Најстарији још отворени европски џез клуб (1948). Мануш вечери и недељни џемови. hotclubjazzlyon.com",
    ro: "Cel mai vechi club de jazz din Europa încă deschis (1948). Seri manouche și jam-uri săptămânale. hotclubjazzlyon.com",
    id: "Klub jazz tertua di Eropa yang masih buka (1948). Malam manouche dan jam mingguan. hotclubjazzlyon.com",
    th: "คลับแจ๊สที่เก่าแก่ที่สุดในยุโรปที่ยังเปิด (1948) คืนมานูชและแจมรายสัปดาห์ hotclubjazzlyon.com",
  },
  "hot-club-de-norvege": {
    fr: "Le quatuor de Jon Larsen depuis 1979 — la maison string-swing de Norvège. Il a quitté la scène en 2019 ; Ola Erlien et Gildas Le Pape jouent la guitare, avec Finn Hauge et Svein Aarbostad. Ils ont bâti Djangofestivalen à Cosmopolite (prochaine : 21–23 janvier 2027). Concerts, pas de jam ouverte hebdo. hotclub.no",
    de: "Jon Larsens Quartett seit 1979 — Norwegens String-Swing-Haus. Er verließ die Bühne 2019; Ola Erlien und Gildas Le Pape spielen Gitarre, mit Finn Hauge und Svein Aarbostad. Sie bauten Djangofestivalen im Cosmopolite (nächste: 21.–23. Januar 2027). Konzerte, kein wöchentlicher Open Jam. hotclub.no",
    nl: "Jon Larsens kwartet sinds 1979 — Noorwegens string-swinghuis. Hij stopte in 2019; Ola Erlien en Gildas Le Pape spelen gitaar, met Finn Hauge en Svein Aarbostad. Zij bouwden Djangofestivalen in Cosmopolite (volgende: 21–23 januari 2027). Concerten, geen wekelijkse open jam. hotclub.no",
    it: "Il quartetto di Jon Larsen dal 1979. Ha lasciato il palco nel 2019; Ola Erlien e Gildas Le Pape alla chitarra, con Finn Hauge e Svein Aarbostad. Hanno costruito Djangofestivalen al Cosmopolite (prossima: 21–23 gennaio 2027). Concerti, non un jam aperto settimanale. hotclub.no",
    es: "El cuarteto de Jon Larsen desde 1979. Dejó el escenario en 2019; Ola Erlien y Gildas Le Pape a la guitarra, con Finn Hauge y Svein Aarbostad. Levantaron Djangofestivalen en Cosmopolite (próxima: 21–23 enero 2027). Conciertos, no jam abierta semanal. hotclub.no",
    pt: "O quarteto de Jon Larsen desde 1979. Saiu do palco em 2019; Ola Erlien e Gildas Le Pape na guitarra. Fizeram o Djangofestivalen no Cosmopolite (próxima: 21–23 janeiro 2027). Concertos, não jam aberta semanal. hotclub.no",
  },
  "hot-club-of-san-francisco": {
    fr: "Le Hot Club de la côte ouest de Paul Mehling. Concerts et tournées dans la langue de Django. hotclubsf.com",
    de: "Paul Mehlings Westküsten-Hot-Club. Konzerte und Touren in Djangos Sprache. hotclubsf.com",
    nl: "Paul Mehlings West Coast Hot Club. Concerten en tours in Django’s taal. hotclubsf.com",
    it: "L’Hot Club della West Coast di Paul Mehling. Concerti e tournée nella lingua di Django. hotclubsf.com",
    es: "El Hot Club de la costa oeste de Paul Mehling. Conciertos y giras en la lengua de Django. hotclubsf.com",
    pt: "O Hot Club da costa oeste de Paul Mehling. Concertos e tournées na língua de Django. hotclubsf.com",
  },
  "hot-club-of-los-angeles": {
    fr: "Quintette gypsy jazz de Los Angeles — swing des années 30 à la Django, chansons françaises et rom. Concerts et soirées hôtel/privées. hotclubofla.com",
    de: "LA-Gypsy-Jazz-Quintett — Django-Swing der 1930er, französische und Roma-Lieder. Konzerte und Hotel-/Privatabende. hotclubofla.com",
    nl: "LA gypsy-jazzkwintet — Django-swing uit de jaren 30, Franse en Roma-liederen. Concerten en hotel-/privéavonden. hotclubofla.com",
    it: "Quintetto gypsy jazz di Los Angeles — swing anni 30 alla Django, canti francesi e rom. Concerti e serate in hotel. hotclubofla.com",
    es: "Quinteto gypsy jazz de Los Ángeles — swing de los 30 a lo Django, canciones francesas y romaníes. Conciertos y noches de hotel. hotclubofla.com",
    pt: "Quinteto gypsy jazz de Los Angeles — swing dos anos 30 à Django. Concertos e noites de hotel. hotclubofla.com",
  },
  "hot-club-of-detroit": {
    fr: "Le Hot Club de Detroit d’Evan Perri. Concerts dans la langue de Django, accordéon et anches.",
    de: "Evan Perris Detroit-Hot-Club. Konzerte in Djangos Sprache, Akkordeon und Rohrblatt.",
    nl: "Evan Perri’s Detroit Hot Club. Concerten in Django’s taal, accordeon en rieten.",
    it: "L’Hot Club di Detroit di Evan Perri. Concerti nella lingua di Django, fisarmonica e ance.",
    es: "El Hot Club de Detroit de Evan Perri. Conciertos en la lengua de Django, acordeón y vientos.",
    pt: "O Hot Club de Detroit de Evan Perri. Concertos na língua de Django, acordeão e palhetas.",
  },
  "hot-club-srq": {
    fr: "Gypsy jazz de Sarasota — soirées hôtel et concerts dans la langue du Quintette. hotclubsrq.com",
    de: "Sarasota Gypsy Jazz — Hotel- und Konzertabende in der Quintette-Sprache. hotclubsrq.com",
    nl: "Sarasota gypsy jazz — hotel- en concertavonden in de taal van het Quintette. hotclubsrq.com",
    it: "Gypsy jazz di Sarasota — serate in hotel e concerti nella lingua del Quintette. hotclubsrq.com",
    es: "Gypsy jazz de Sarasota — noches de hotel y conciertos en la lengua del Quintette. hotclubsrq.com",
    pt: "Gypsy jazz de Sarasota — noites de hotel e concertos na língua do Quintette. hotclubsrq.com",
  },
  "hot-club-of-berlin": {
    fr: "Hot Club acoustique de Berlin — Francisco Batista et Thomas Dekas. Concerts dans la langue Django / Grappelli. thehotclubofberlin.com",
    de: "Berliner akustischer Hot Club — Francisco Batista und Thomas Dekas. Konzerte in der Sprache Django / Grappelli. thehotclubofberlin.com",
    nl: "Berlijns akoestisch Hot Club — Francisco Batista en Thomas Dekas. Concerten in de taal van Django / Grappelli. thehotclubofberlin.com",
    it: "Hot Club acustico di Berlino — Francisco Batista e Thomas Dekas. Concerti nella lingua Django / Grappelli. thehotclubofberlin.com",
    es: "Hot Club acústico de Berlín — Francisco Batista y Thomas Dekas. Conciertos en la lengua Django / Grappelli. thehotclubofberlin.com",
    pt: "Hot Club acústico de Berlim — Francisco Batista e Thomas Dekas. Concertos na língua Django / Grappelli. thehotclubofberlin.com",
  },
  "hot-club-of-valletta": {
    fr: "Le groupe Jazz Manouche de Malte — George Curmi (il-Pusè) violon et sax. Concerts dans les théâtres de La Valette et sets de midi en festival. Une soirée Hot Club dans la capitale.",
    de: "Maltas Jazz-Manouche-Gruppe — George Curmi (il-Pusè) Violine und Sax. Konzerte in Valletta und Festival-Mittagssets. Ein Hot-Club-Abend in der Hauptstadt.",
    nl: "Malta’s Jazz Manouche-groep — George Curmi (il-Pusè) viool en sax. Concerten in Valletta en festival-middagsets. Een Hot Club-avond in de hoofdstad.",
    it: "Il gruppo Jazz Manouche di Malta — George Curmi (il-Pusè) violino e sax. Concerti a La Valletta. Una sera Hot Club in capitale.",
    es: "El grupo Jazz Manouche de Malta — George Curmi (il-Pusè) violín y saxo. Conciertos en La Valeta. Una noche Hot Club en la capital.",
    pt: "O grupo Jazz Manouche de Malta — George Curmi (il-Pusè) violino e sax. Concertos em Valeta. Uma noite Hot Club na capital.",
  },
  "hot-club-de-finlande": {
    fr: "Ari-Jukka Luomaranta (AJL Guitars) et solistes finlandais. Concerts dans la langue de Django — la chaise Hot Club de Finlande.",
    de: "Ari-Jukka Luomaranta (AJL Guitars) und finnische Solisten. Konzerte in Djangos Sprache — Finnlands Hot-Club-Stuhl.",
    nl: "Ari-Jukka Luomaranta (AJL Guitars) en Finse solisten. Concerten in Django’s taal — Finlands Hot Club-stoel.",
    it: "Ari-Jukka Luomaranta (AJL Guitars) e solisti finlandesi. Concerti nella lingua di Django.",
    es: "Ari-Jukka Luomaranta (AJL Guitars) y solistas finlandeses. Conciertos en la lengua de Django.",
    pt: "Ari-Jukka Luomaranta (AJL Guitars) e solistas finlandeses. Concertos na língua de Django.",
  },
  "hot-club-of-manila": {
    fr: "Gypsy jazz de Manille — Franz Morales, Kakoy Legaspi, Jing Reyna-Jorge. Concerts quand ils sont affichés (19 East, Malate). Facebook @hotclubofmanila",
    de: "Manila Gypsy Jazz — Franz Morales, Kakoy Legaspi, Jing Reyna-Jorge. Konzerte wenn gepostet (19 East, Malate). Facebook @hotclubofmanila",
    nl: "Manilla gypsy jazz — Franz Morales, Kakoy Legaspi, Jing Reyna-Jorge. Concerten wanneer gezet (19 East, Malate). Facebook @hotclubofmanila",
    it: "Gypsy jazz di Manila — Franz Morales, Kakoy Legaspi, Jing Reyna-Jorge. Concerti quando pubblicati. Facebook @hotclubofmanila",
    es: "Gypsy jazz de Manila — Franz Morales, Kakoy Legaspi, Jing Reyna-Jorge. Conciertos cuando se anuncian. Facebook @hotclubofmanila",
    pt: "Gypsy jazz de Manila — Franz Morales, Kakoy Legaspi, Jing Reyna-Jorge. Concertos quando anunciados. Facebook @hotclubofmanila",
  },
  "hot-club-de-hong-kong": {
    fr: "Simon Choi et Neil Lau — le groupe gypsy jazz de la ville. Allure Music Salon, Tai Hang, Fringe Club, Make Music Hong Kong. Instagram @hotclubdehk",
    de: "Simon Choi und Neil Lau — die arbeitende Gypsy-Jazz-Band der Stadt. Allure Music Salon, Tai Hang, Fringe Club. Instagram @hotclubdehk",
    nl: "Simon Choi en Neil Lau — de werkende gypsy-jazzband van de stad. Allure Music Salon, Tai Hang, Fringe Club. Instagram @hotclubdehk",
    it: "Simon Choi e Neil Lau — la band gypsy jazz della città. Allure Music Salon, Tai Hang, Fringe Club. Instagram @hotclubdehk",
    es: "Simon Choi y Neil Lau — la banda gypsy jazz de la ciudad. Allure Music Salon, Tai Hang, Fringe Club. Instagram @hotclubdehk",
    pt: "Simon Choi e Neil Lau — a banda gypsy jazz da cidade. Allure Music Salon, Tai Hang, Fringe Club. Instagram @hotclubdehk",
  },
  "hot-club-de-piracicaba": {
    fr: "Le Hot Club brésilien de José Fernando Seifarth et le Festival Jazz Manouche de Piracicaba.",
    de: "José Fernando Seifarths brasilianischer Hot Club und das Festival Jazz Manouche de Piracicaba.",
    nl: "José Fernando Seifarths Braziliaanse Hot Club en het Festival Jazz Manouche de Piracicaba.",
    it: "L’Hot Club brasiliano di José Fernando Seifarth e il Festival Jazz Manouche de Piracicaba.",
    es: "El Hot Club brasileño de José Fernando Seifarth y el Festival Jazz Manouche de Piracicaba.",
    pt: "O Hot Club brasileiro de José Fernando Seifarth e o Festival Jazz Manouche de Piracicaba.",
  },
  "hot-club-de-frank": {
    fr: "Le quatuor gypsy-swing d’Amsterdam de Frank Meester — North Sea Jazz, Montreux, Kaptein Zeppos. Une soirée Hot Club néerlandaise, pas la fondation.",
    de: "Frank Meesters Amsterdamer Gypsy-Swing-Quartett — North Sea Jazz, Montreux, Kaptein Zeppos. Ein niederländischer Hot-Club-Abend, nicht die Stiftung.",
    nl: "Frank Meesters Amsterdamse gypsy-swingkwartet — North Sea Jazz, Montreux, Kaptein Zeppos. Een Nederlandse Hot Club-avond, niet de stichting.",
    it: "Il quartetto gypsy-swing di Amsterdam di Frank Meester — North Sea Jazz, Montreux. Una sera Hot Club olandese, non la fondazione.",
    es: "El cuarteto gypsy-swing de Ámsterdam de Frank Meester — North Sea Jazz, Montreux. Una noche Hot Club holandesa, no la fundación.",
    pt: "O quarteto gypsy-swing de Amesterdão de Frank Meester — North Sea Jazz, Montreux. Uma noite Hot Club holandesa, não a fundação.",
  },
  "hot-club-of-buffalo": {
    fr: "Quatuor gypsy jazz de Buffalo, NY. Concerts, hôtels et Pausa Art House. hotclubofbuffalo.com",
    de: "Vierköpfiger Gypsy Jazz aus Buffalo, NY. Konzerte, Hotels und Pausa Art House. hotclubofbuffalo.com",
    nl: "Vier mans gypsy jazz uit Buffalo, NY. Concerten, hotels en Pausa Art House. hotclubofbuffalo.com",
    it: "Quartetto gypsy jazz di Buffalo, NY. Concerti, hotel e Pausa Art House. hotclubofbuffalo.com",
    es: "Cuarteto gypsy jazz de Buffalo, NY. Conciertos, hoteles y Pausa Art House. hotclubofbuffalo.com",
    pt: "Quarteto gypsy jazz de Buffalo, NY. Concertos, hotéis e Pausa Art House. hotclubofbuffalo.com",
  },
  "hot-club-medellin": {
    fr: "Le Hot Club colombien de Dorkis et le Django Festival Colombia. Concerts quand ils sont affichés.",
    de: "Dorkis’ kolumbianischer Hot Club und Django Festival Colombia. Konzerte wenn gepostet.",
    nl: "Dorkis’ Colombiaanse Hot Club en Django Festival Colombia. Concerten wanneer gezet.",
    it: "L’Hot Club colombiano di Dorkis e Django Festival Colombia. Concerti quando pubblicati.",
    es: "El Hot Club colombiano de Dorkis y Django Festival Colombia. Conciertos cuando se anuncian.",
    pt: "O Hot Club colombiano de Dorkis e Django Festival Colombia. Concertos quando anunciados.",
  },
  "hot-club-of-belgrade": {
    fr: "Dejan Krsmanović et le groupe Django de Belgrade. Soirées au Gypsy Jazz Club, Kičevska 21.",
    de: "Dejan Krsmanović und die Belgrader Django-Gruppe. Abende im Gypsy Jazz Club, Kičevska 21.",
    nl: "Dejan Krsmanović en de Belgrado Django-groep. Avonden in Gypsy Jazz Club, Kičevska 21.",
    it: "Dejan Krsmanović e il gruppo Django di Belgrado. Sere al Gypsy Jazz Club, Kičevska 21.",
    es: "Dejan Krsmanović y el grupo Django de Belgrado. Noches en Gypsy Jazz Club, Kičevska 21.",
    pt: "Dejan Krsmanović e o grupo Django de Belgrado. Noites no Gypsy Jazz Club, Kičevska 21.",
    sr: "Дејан Крсмановић и београдска Django група. Вечери у Gypsy Jazz Club, Кичевска 21.",
    hr: "Dejan Krsmanović i beogradska Django grupa. Večeri u Gypsy Jazz Club, Kičevska 21.",
  },
  "hot-clube-de-portugal": {
    fr: "Le club de jazz historique de Lisbonne. Tout le jazz, y compris des affiches gypsy — une maison qui programme déjà la musique.",
    de: "Lissabons historischer Jazzclub. Aller Jazz, auch Gypsy-Abende — ein Haus, das die Musik schon bucht.",
    nl: "Lissabons historische jazzclub. Alle jazz, ook gypsy-avonden — een huis dat de muziek al boekt.",
    it: "Lo storico jazz club di Lisbona. Tutto il jazz, anche serate gypsy — una casa che già programma la musica.",
    es: "El histórico club de jazz de Lisboa. Todo el jazz, también noches gypsy — una casa que ya programa la música.",
    pt: "O histórico clube de jazz de Lisboa. Todo o jazz, também noites gypsy — uma casa que já programa a música.",
  },
};

export function hotClubBio(slug: string, locale: string, fallback: string) {
  if (!locale || locale === "en" || locale === "he") return fallback;
  return BIOS[slug]?.[locale] || fallback;
}
