import { festivalWhen } from "@/lib/festival-copy";

const PHRASES: Record<string, [string, string][]> = {
  fr: [
    ["No regular Gypsy Jazz jam posted", "Pas de jam gypsy jazz régulière affichée"],
    ["No regular open jam posted", "Pas de jam ouverte régulière affichée"],
    ["No regular jam posted", "Pas de jam régulière affichée"],
    ["First Saturday of the month", "Premier samedi du mois"],
    ["Second Wednesday of the month", "Deuxième mercredi du mois"],
    ["Last Wednesday of the month", "Dernier mercredi du mois"],
    ["Thursday series — dates as posted", "Série du jeudi — dates affichées"],
    ["Around the festival, plus monthly", "Autour du festival, plus mensuel"],
    ["Concerts; open jams when posted", "Concerts ; jams ouvertes quand c’est annoncé"],
    ["Monthly, Thursday — check the band", "Mensuel, jeudi — voir le groupe"],
    ["Monthly Sunday — check Facebook", "Dimanche mensuel — voir Facebook"],
    ["Regular — check Kozlov Club", "Régulier — voir Kozlov Club"],
    ["When posted — not weekly", "Quand c’est annoncé — pas chaque semaine"],
    ["2nd Friday of even months", "2e vendredi des mois pairs"],
    ["1st and 3rd Tuesdays", "1er et 3e mardis"],
    ["2nd and 4th Sundays", "2e et 4e dimanches"],
    ["2nd and 4th Thursday", "2e et 4e jeudis"],
    ["Every other Tuesday", "Un mardi sur deux"],
    ["Tuesdays when posted", "Les mardis quand c’est annoncé"],
    ["Thursday when posted", "Le jeudi quand c’est annoncé"],
    ["Session nights (posted)", "Soirées (annoncées)"],
    ["Monthly (date posted)", "Mensuel (date affichée)"],
    ["Posted per date", "Annoncé par date"],
    ["Selected Fridays", "Certains vendredis"],
    ["Festival week, late June", "Semaine du festival, fin juin"],
    ["Festival week", "Semaine du festival"],
    ["Spring camp", "Camp de printemps"],
    ["Camp weeks", "Semaines de camp"],
    ["Every Thursday", "Tous les jeudis"],
    ["Every Sunday", "Tous les dimanches"],
    ["Every Tuesday", "Tous les mardis"],
    ["Every Wednesday", "Tous les mercredis"],
    ["Every Monday", "Tous les lundis"],
    ["First Tuesday", "Premier mardi"],
    ["First Sunday", "Premier dimanche"],
    ["Last Tuesday", "Dernier mardi"],
    ["4th Wednesday", "4e mercredi"],
    ["2nd Wednesday", "2e mercredi"],
    ["3rd Saturday", "3e samedi"],
    ["3rd Sunday", "3e dimanche"],
    ["1st Sunday", "1er dimanche"],
    ["Most Mondays", "La plupart des lundis"],
    ["Weekly, Wednesday", "Hebdomadaire, mercredi"],
    ["Weekly, Monday", "Hebdomadaire, lundi"],
    ["Wednesday–Saturday", "Mercredi–samedi"],
    ["When posted", "Quand c’est annoncé"],
    ["Weekends", "Week-ends"],
    ["Weekly", "Hebdomadaire"],
    ["Monthly", "Mensuel"],
    ["Mondays", "Les lundis"],
    ["Thursday", "Jeudi"],
    ["Sunday", "Dimanche"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sam. & dim."],
    ["from ", "à partir de "],
  ],
  de: [
    ["No regular Gypsy Jazz jam posted", "Kein regelmäßiger Gypsy-Jazz-Jam angegeben"],
    ["No regular open jam posted", "Kein regelmäßiger offener Jam angegeben"],
    ["No regular jam posted", "Kein regelmäßiger Jam angegeben"],
    ["First Saturday of the month", "Erster Samstag im Monat"],
    ["Second Wednesday of the month", "Zweiter Mittwoch im Monat"],
    ["Last Wednesday of the month", "Letzter Mittwoch im Monat"],
    ["Thursday series — dates as posted", "Donnerstagsserie — Termine wie angegeben"],
    ["Around the festival, plus monthly", "Rund ums Festival, plus monatlich"],
    ["Concerts; open jams when posted", "Konzerte; offene Jams wenn angegeben"],
    ["Monthly, Thursday — check the band", "Monatlich, Donnerstag — Band prüfen"],
    ["Monthly Sunday — check Facebook", "Monatlicher Sonntag — Facebook prüfen"],
    ["Regular — check Kozlov Club", "Regelmäßig — Kozlov Club prüfen"],
    ["When posted — not weekly", "Wenn angegeben — nicht wöchentlich"],
    ["2nd Friday of even months", "2. Freitag in geraden Monaten"],
    ["1st and 3rd Tuesdays", "1. und 3. Dienstag"],
    ["2nd and 4th Sundays", "2. und 4. Sonntag"],
    ["2nd and 4th Thursday", "2. und 4. Donnerstag"],
    ["Every other Tuesday", "Jeden zweiten Dienstag"],
    ["Tuesdays when posted", "Dienstage wenn angegeben"],
    ["Thursday when posted", "Donnerstag wenn angegeben"],
    ["Session nights (posted)", "Session-Abende (angegeben)"],
    ["Monthly (date posted)", "Monatlich (Datum angegeben)"],
    ["Posted per date", "Pro Termin angegeben"],
    ["Selected Fridays", "Ausgewählte Freitage"],
    ["Festival week, late June", "Festivalwoche, Ende Juni"],
    ["Festival week", "Festivalwoche"],
    ["Spring camp", "Frühlingscamp"],
    ["Camp weeks", "Campwochen"],
    ["Every Thursday", "Jeden Donnerstag"],
    ["Every Sunday", "Jeden Sonntag"],
    ["Every Tuesday", "Jeden Dienstag"],
    ["Every Wednesday", "Jeden Mittwoch"],
    ["Every Monday", "Jeden Montag"],
    ["First Tuesday", "Erster Dienstag"],
    ["First Sunday", "Erster Sonntag"],
    ["Last Tuesday", "Letzter Dienstag"],
    ["4th Wednesday", "4. Mittwoch"],
    ["2nd Wednesday", "2. Mittwoch"],
    ["3rd Saturday", "3. Samstag"],
    ["3rd Sunday", "3. Sonntag"],
    ["1st Sunday", "1. Sonntag"],
    ["Most Mondays", "Die meisten Montage"],
    ["Weekly, Wednesday", "Wöchentlich, Mittwoch"],
    ["Weekly, Monday", "Wöchentlich, Montag"],
    ["Wednesday–Saturday", "Mittwoch–Samstag"],
    ["When posted", "Wenn angegeben"],
    ["Weekends", "Wochenenden"],
    ["Weekly", "Wöchentlich"],
    ["Monthly", "Monatlich"],
    ["Mondays", "Montags"],
    ["Thursday", "Donnerstag"],
    ["Sunday", "Sonntag"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sa. & So."],
    ["from ", "ab "],
  ],
  nl: [
    ["No regular Gypsy Jazz jam posted", "Geen vaste gypsy-jazzjam gezet"],
    ["No regular open jam posted", "Geen vaste open jam gezet"],
    ["No regular jam posted", "Geen vaste jam gezet"],
    ["First Saturday of the month", "Eerste zaterdag van de maand"],
    ["Second Wednesday of the month", "Tweede woensdag van de maand"],
    ["Last Wednesday of the month", "Laatste woensdag van de maand"],
    ["Thursday series — dates as posted", "Donderdagreeks — data zoals gezet"],
    ["Around the festival, plus monthly", "Rond het festival, plus maandelijks"],
    ["Concerts; open jams when posted", "Concerten; open jams wanneer gezet"],
    ["Monthly, Thursday — check the band", "Maandelijks, donderdag — check de band"],
    ["Monthly Sunday — check Facebook", "Maandelijkse zondag — check Facebook"],
    ["Regular — check Kozlov Club", "Vast — check Kozlov Club"],
    ["When posted — not weekly", "Wanneer gezet — niet wekelijks"],
    ["2nd Friday of even months", "2e vrijdag van even maanden"],
    ["1st and 3rd Tuesdays", "1e en 3e dinsdag"],
    ["2nd and 4th Sundays", "2e en 4e zondag"],
    ["2nd and 4th Thursday", "2e en 4e donderdag"],
    ["Every other Tuesday", "Om de dinsdag"],
    ["Tuesdays when posted", "Dinsdagen wanneer gezet"],
    ["Thursday when posted", "Donderdag wanneer gezet"],
    ["Session nights (posted)", "Sessieavonden (gezet)"],
    ["Monthly (date posted)", "Maandelijks (datum gezet)"],
    ["Posted per date", "Per datum gezet"],
    ["Selected Fridays", "Geselecteerde vrijdagen"],
    ["Festival week, late June", "Festivalweek, eind juni"],
    ["Festival week", "Festivalweek"],
    ["Spring camp", "Lentekamp"],
    ["Camp weeks", "Kampweken"],
    ["Every Thursday", "Elke donderdag"],
    ["Every Sunday", "Elke zondag"],
    ["Every Tuesday", "Elke dinsdag"],
    ["Every Wednesday", "Elke woensdag"],
    ["Every Monday", "Elke maandag"],
    ["First Tuesday", "Eerste dinsdag"],
    ["First Sunday", "Eerste zondag"],
    ["Last Tuesday", "Laatste dinsdag"],
    ["4th Wednesday", "4e woensdag"],
    ["2nd Wednesday", "2e woensdag"],
    ["3rd Saturday", "3e zaterdag"],
    ["3rd Sunday", "3e zondag"],
    ["1st Sunday", "1e zondag"],
    ["Most Mondays", "De meeste maandagen"],
    ["Weekly, Wednesday", "Wekelijks, woensdag"],
    ["Weekly, Monday", "Wekelijks, maandag"],
    ["Wednesday–Saturday", "Woensdag–zaterdag"],
    ["When posted", "Wanneer gezet"],
    ["Weekends", "Weekends"],
    ["Weekly", "Wekelijks"],
    ["Monthly", "Maandelijks"],
    ["Mondays", "Maandagen"],
    ["Thursday", "Donderdag"],
    ["Sunday", "Zondag"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Za. & zo."],
    ["from ", "vanaf "],
  ],
  es: [
    ["No regular Gypsy Jazz jam posted", "No hay jam regular de gypsy jazz anunciado"],
    ["No regular open jam posted", "No hay jam abierto regular anunciado"],
    ["No regular jam posted", "No hay jam regular anunciado"],
    ["First Saturday of the month", "Primer sábado del mes"],
    ["Second Wednesday of the month", "Segundo miércoles del mes"],
    ["Last Wednesday of the month", "Último miércoles del mes"],
    ["Thursday series — dates as posted", "Serie de jueves — fechas según anuncio"],
    ["Around the festival, plus monthly", "En torno al festival, más mensual"],
    ["Concerts; open jams when posted", "Conciertos; jams abiertos cuando se anuncian"],
    ["Monthly, Thursday — check the band", "Mensual, jueves — consultar el grupo"],
    ["Monthly Sunday — check Facebook", "Domingo mensual — consultar Facebook"],
    ["Regular — check Kozlov Club", "Regular — consultar Kozlov Club"],
    ["When posted — not weekly", "Cuando se anuncia — no semanal"],
    ["2nd Friday of even months", "2.º viernes de meses pares"],
    ["1st and 3rd Tuesdays", "1.er y 3.er martes"],
    ["2nd and 4th Sundays", "2.º y 4.º domingo"],
    ["2nd and 4th Thursday", "2.º y 4.º jueves"],
    ["Every other Tuesday", "Un martes sí y otro no"],
    ["Tuesdays when posted", "Martes cuando se anuncia"],
    ["Thursday when posted", "Jueves cuando se anuncia"],
    ["Session nights (posted)", "Noches de sesión (anunciadas)"],
    ["Monthly (date posted)", "Mensual (fecha anunciada)"],
    ["Posted per date", "Anunciado por fecha"],
    ["Selected Fridays", "Viernes concretos"],
    ["Festival week, late June", "Semana del festival, finales de junio"],
    ["Festival week", "Semana del festival"],
    ["Spring camp", "Campamento de primavera"],
    ["Camp weeks", "Semanas de campamento"],
    ["Every Thursday", "Todos los jueves"],
    ["Every Sunday", "Todos los domingos"],
    ["Every Tuesday", "Todos los martes"],
    ["Every Wednesday", "Todos los miércoles"],
    ["Every Monday", "Todos los lunes"],
    ["First Tuesday", "Primer martes"],
    ["First Sunday", "Primer domingo"],
    ["Last Tuesday", "Último martes"],
    ["4th Wednesday", "4.º miércoles"],
    ["2nd Wednesday", "2.º miércoles"],
    ["3rd Saturday", "3.er sábado"],
    ["3rd Sunday", "3.er domingo"],
    ["1st Sunday", "1.er domingo"],
    ["Most Mondays", "La mayoría de los lunes"],
    ["Weekly, Wednesday", "Semanal, miércoles"],
    ["Weekly, Monday", "Semanal, lunes"],
    ["Wednesday–Saturday", "Miércoles–sábado"],
    ["When posted", "Cuando se anuncia"],
    ["Weekends", "Fines de semana"],
    ["Weekly", "Semanal"],
    ["Monthly", "Mensual"],
    ["Mondays", "Los lunes"],
    ["Thursday", "Jueves"],
    ["Sunday", "Domingo"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sáb. y dom."],
    ["from ", "desde "],
  ],
  pt: [
    ["No regular Gypsy Jazz jam posted", "Não há jam regular de gypsy jazz anunciada"],
    ["No regular open jam posted", "Não há jam aberta regular anunciada"],
    ["No regular jam posted", "Não há jam regular anunciada"],
    ["First Saturday of the month", "Primeiro sábado do mês"],
    ["Second Wednesday of the month", "Segunda quarta-feira do mês"],
    ["Last Wednesday of the month", "Última quarta-feira do mês"],
    ["Thursday series — dates as posted", "Série de quintas — datas conforme anúncio"],
    ["Around the festival, plus monthly", "Em torno do festival, mais mensal"],
    ["Concerts; open jams when posted", "Concertos; jams abertas quando anunciadas"],
    ["Monthly, Thursday — check the band", "Mensal, quinta — ver a banda"],
    ["Monthly Sunday — check Facebook", "Domingo mensal — ver Facebook"],
    ["Regular — check Kozlov Club", "Regular — ver Kozlov Club"],
    ["When posted — not weekly", "Quando anunciado — não semanal"],
    ["2nd Friday of even months", "2.ª sexta dos meses pares"],
    ["1st and 3rd Tuesdays", "1.ª e 3.ª terças"],
    ["2nd and 4th Sundays", "2.º e 4.º domingo"],
    ["2nd and 4th Thursday", "2.ª e 4.ª quinta"],
    ["Every other Tuesday", "Uma terça sim, outra não"],
    ["Tuesdays when posted", "Terças quando anunciado"],
    ["Thursday when posted", "Quinta quando anunciado"],
    ["Session nights (posted)", "Noites de sessão (anunciadas)"],
    ["Monthly (date posted)", "Mensal (data anunciada)"],
    ["Posted per date", "Anunciado por data"],
    ["Selected Fridays", "Sextas escolhidas"],
    ["Festival week, late June", "Semana do festival, fim de junho"],
    ["Festival week", "Semana do festival"],
    ["Spring camp", "Campo de primavera"],
    ["Camp weeks", "Semanas de campo"],
    ["Every Thursday", "Todas as quintas"],
    ["Every Sunday", "Todos os domingos"],
    ["Every Tuesday", "Todas as terças"],
    ["Every Wednesday", "Todas as quartas"],
    ["Every Monday", "Todas as segundas"],
    ["First Tuesday", "Primeira terça"],
    ["First Sunday", "Primeiro domingo"],
    ["Last Tuesday", "Última terça"],
    ["4th Wednesday", "4.ª quarta"],
    ["2nd Wednesday", "2.ª quarta"],
    ["3rd Saturday", "3.º sábado"],
    ["3rd Sunday", "3.º domingo"],
    ["1st Sunday", "1.º domingo"],
    ["Most Mondays", "A maior parte das segundas"],
    ["Weekly, Wednesday", "Semanal, quarta"],
    ["Weekly, Monday", "Semanal, segunda"],
    ["Wednesday–Saturday", "Quarta–sábado"],
    ["When posted", "Quando anunciado"],
    ["Weekends", "Fins de semana"],
    ["Weekly", "Semanal"],
    ["Monthly", "Mensal"],
    ["Mondays", "As segundas"],
    ["Thursday", "Quinta"],
    ["Sunday", "Domingo"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sáb. e dom."],
    ["from ", "a partir de "],
  ],
  it: [
    ["No regular Gypsy Jazz jam posted", "Nessun jam gypsy jazz fisso indicato"],
    ["No regular open jam posted", "Nessun jam aperto fisso indicato"],
    ["No regular jam posted", "Nessun jam fisso indicato"],
    ["First Saturday of the month", "Primo sabato del mese"],
    ["Second Wednesday of the month", "Secondo mercoledì del mese"],
    ["Last Wednesday of the month", "Ultimo mercoledì del mese"],
    ["Thursday series — dates as posted", "Serie del giovedì — date come indicate"],
    ["Around the festival, plus monthly", "Intorno al festival, più mensile"],
    ["Concerts; open jams when posted", "Concerti; jam aperti quando indicati"],
    ["Monthly, Thursday — check the band", "Mensile, giovedì — vedi il gruppo"],
    ["Monthly Sunday — check Facebook", "Domenica mensile — vedi Facebook"],
    ["Regular — check Kozlov Club", "Fisso — vedi Kozlov Club"],
    ["When posted — not weekly", "Quando indicato — non settimanale"],
    ["2nd Friday of even months", "2° venerdì dei mesi pari"],
    ["1st and 3rd Tuesdays", "1° e 3° martedì"],
    ["2nd and 4th Sundays", "2° e 4° domenica"],
    ["2nd and 4th Thursday", "2° e 4° giovedì"],
    ["Every other Tuesday", "Un martedì sì e uno no"],
    ["Tuesdays when posted", "Martedì quando indicato"],
    ["Thursday when posted", "Giovedì quando indicato"],
    ["Session nights (posted)", "Sere di sessione (indicate)"],
    ["Monthly (date posted)", "Mensile (data indicata)"],
    ["Posted per date", "Indicato per data"],
    ["Selected Fridays", "Venerdì scelti"],
    ["Festival week, late June", "Settimana del festival, fine giugno"],
    ["Festival week", "Settimana del festival"],
    ["Spring camp", "Campo di primavera"],
    ["Camp weeks", "Settimane di campo"],
    ["Every Thursday", "Ogni giovedì"],
    ["Every Sunday", "Ogni domenica"],
    ["Every Tuesday", "Ogni martedì"],
    ["Every Wednesday", "Ogni mercoledì"],
    ["Every Monday", "Ogni lunedì"],
    ["First Tuesday", "Primo martedì"],
    ["First Sunday", "Prima domenica"],
    ["Last Tuesday", "Ultimo martedì"],
    ["4th Wednesday", "4° mercoledì"],
    ["2nd Wednesday", "2° mercoledì"],
    ["3rd Saturday", "3° sabato"],
    ["3rd Sunday", "3° domenica"],
    ["1st Sunday", "1° domenica"],
    ["Most Mondays", "La maggior parte dei lunedì"],
    ["Weekly, Wednesday", "Settimanale, mercoledì"],
    ["Weekly, Monday", "Settimanale, lunedì"],
    ["Wednesday–Saturday", "Mercoledì–sabato"],
    ["When posted", "Quando indicato"],
    ["Weekends", "Fine settimana"],
    ["Weekly", "Settimanale"],
    ["Monthly", "Mensile"],
    ["Mondays", "I lunedì"],
    ["Thursday", "Giovedì"],
    ["Sunday", "Domenica"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sab. e dom."],
    ["from ", "dalle "],
  ],
};

for (const rows of Object.values(PHRASES)) rows.sort((a, b) => b[0].length - a[0].length);

const GENERIC_DAYS: Record<string, Record<string, string>> = {
  ru: { Thursday: "четверг", Sunday: "воскресенье", Tuesday: "вторник", Wednesday: "среда", Monday: "понедельник", Friday: "пятница", Saturday: "суббота", Weekends: "выходные" },
  ja: { Thursday: "木曜日", Sunday: "日曜日", Tuesday: "火曜日", Wednesday: "水曜日", Monday: "月曜日", Friday: "金曜日", Saturday: "土曜日", Weekends: "週末" },
  ko: { Thursday: "목요일", Sunday: "일요일", Tuesday: "화요일", Wednesday: "수요일", Monday: "월요일", Friday: "금요일", Saturday: "토요일", Weekends: "주말" },
  zh: { Thursday: "周四", Sunday: "周日", Tuesday: "周二", Wednesday: "周三", Monday: "周一", Friday: "周五", Saturday: "周六", Weekends: "周末" },
  "zh-tw": { Thursday: "週四", Sunday: "週日", Tuesday: "週二", Wednesday: "週三", Monday: "週一", Friday: "週五", Saturday: "週六", Weekends: "週末" },
  hu: { Thursday: "csütörtök", Sunday: "vasárnap", Tuesday: "kedd", Wednesday: "szerda", Monday: "hétfő", Friday: "péntek", Saturday: "szombat", Weekends: "hétvégék" },
  pl: { Thursday: "czwartek", Sunday: "niedziela", Tuesday: "wtorek", Wednesday: "środa", Monday: "poniedziałek", Friday: "piątek", Saturday: "sobota", Weekends: "weekendy" },
  cs: { Thursday: "čtvrtek", Sunday: "neděle", Tuesday: "úterý", Wednesday: "středa", Monday: "pondělí", Friday: "pátek", Saturday: "sobota", Weekends: "víkendy" },
  hr: { Thursday: "četvrtak", Sunday: "nedjelja", Tuesday: "utorak", Wednesday: "srijeda", Monday: "ponedjeljak", Friday: "petak", Saturday: "subota", Weekends: "vikendi" },
  sr: { Thursday: "четвртак", Sunday: "недеља", Tuesday: "уторак", Wednesday: "среда", Monday: "понедељак", Friday: "петак", Saturday: "субота", Weekends: "викенди" },
  ro: { Thursday: "joi", Sunday: "duminică", Tuesday: "marți", Wednesday: "miercuri", Monday: "luni", Friday: "vineri", Saturday: "sâmbătă", Weekends: "weekenduri" },
  id: { Thursday: "Kamis", Sunday: "Minggu", Tuesday: "Selasa", Wednesday: "Rabu", Monday: "Senin", Friday: "Jumat", Saturday: "Sabtu", Weekends: "akhir pekan" },
  th: { Thursday: "พฤหัส", Sunday: "อาทิตย์", Tuesday: "อังคาร", Wednesday: "พุธ", Monday: "จันทร์", Friday: "ศุกร์", Saturday: "เสาร์", Weekends: "สุดสัปดาห์" },
};

const GENERIC_BITS: Record<string, [string, string][]> = {
  ru: [["Every ", "Каждый "], ["Weekly", "Еженедельно"], ["Monthly", "Ежемесячно"], ["When posted", "Когда объявлено"], ["Festival week", "Неделя фестиваля"], ["from ", "с "], ["Sat & Sun", "сб и вс"]],
  ja: [["Every ", "毎週"], ["Weekly", "毎週"], ["Monthly", "毎月"], ["When posted", "告知時"], ["Festival week", "フェスティバル週"], ["from ", ""], ["Sat & Sun", "土・日"]],
  ko: [["Every ", "매주 "], ["Weekly", "매주"], ["Monthly", "매월"], ["When posted", "공지 시"], ["Festival week", "페스티벌 주"], ["from ", ""], ["Sat & Sun", "토·일"]],
  zh: [["Every ", "每周"], ["Weekly", "每周"], ["Monthly", "每月"], ["When posted", "公布时"], ["Festival week", "音乐节周"], ["from ", ""], ["Sat & Sun", "周六周日"]],
  "zh-tw": [["Every ", "每週"], ["Weekly", "每週"], ["Monthly", "每月"], ["When posted", "公布時"], ["Festival week", "音樂節週"], ["from ", ""], ["Sat & Sun", "週六週日"]],
  hu: [["Every ", "Minden "], ["Weekly", "Hetente"], ["Monthly", "Havonta"], ["When posted", "Ha kiírják"], ["Festival week", "Fesztiválhét"], ["from ", ""], ["Sat & Sun", "szo és v"]],
  pl: [["Every ", "Każdy "], ["Weekly", "Co tydzień"], ["Monthly", "Co miesiąc"], ["When posted", "Gdy podane"], ["Festival week", "Tydzień festiwalu"], ["from ", "od "], ["Sat & Sun", "sob. i nd."]],
  cs: [["Every ", "Každý "], ["Weekly", "Týdně"], ["Monthly", "Měsíčně"], ["When posted", "Když je vypsáno"], ["Festival week", "Týden festivalu"], ["from ", "od "], ["Sat & Sun", "so a ne"]],
  hr: [["Every ", "Svaki "], ["Weekly", "Tjedno"], ["Monthly", "Mjesečno"], ["When posted", "Kad je objavljeno"], ["Festival week", "Tjedan festivala"], ["from ", "od "], ["Sat & Sun", "sub i ned"]],
  sr: [["Every ", "Сваки "], ["Weekly", "Недељно"], ["Monthly", "Месечно"], ["When posted", "Кад је објављено"], ["Festival week", "Недеља фестивала"], ["from ", "од "], ["Sat & Sun", "суб и нед"]],
  ro: [["Every ", "Fiecare "], ["Weekly", "Săptămânal"], ["Monthly", "Lunar"], ["When posted", "Când e anunțat"], ["Festival week", "Săptămâna festivalului"], ["from ", "de la "], ["Sat & Sun", "sâm. și dum."]],
  id: [["Every ", "Setiap "], ["Weekly", "Mingguan"], ["Monthly", "Bulanan"], ["When posted", "Saat diumumkan"], ["Festival week", "Minggu festival"], ["from ", "dari "], ["Sat & Sun", "Sab & Min"]],
  th: [["Every ", "ทุก"], ["Weekly", "รายสัปดาห์"], ["Monthly", "รายเดือน"], ["When posted", "เมื่อประกาศ"], ["Festival week", "สัปดาห์เทศกาล"], ["from ", "ตั้งแต่ "], ["Sat & Sun", "ส. และ อา."]],
};

export function jamWhen(when: string, locale: string) {
  if (!when || locale === "en" || locale === "he") return when;
  const rows = PHRASES[locale];
  let out = when;
  if (rows) {
    for (const [en, tr] of rows) out = out.replaceAll(en, tr);
  } else {
    const days = GENERIC_DAYS[locale];
    if (days) {
      for (const [en, tr] of Object.entries(days).sort((a, b) => b[0].length - a[0].length)) {
        out = out.replaceAll(en, tr);
      }
    }
    const bits = GENERIC_BITS[locale];
    if (bits) for (const [en, tr] of bits) out = out.replaceAll(en, tr);
  }
  return festivalWhen(out, locale);
}

export function jamHoursLabel(hours: string, locale: string) {
  if (!hours || locale === "en" || locale === "he") return hours;
  return jamWhen(hours, locale);
}

export const JAM_UI: Record<string, Record<string, string>> = {
  en: {
    "jam.fromDjangoBooks": "From DjangoBooks",
    "jam.save": "Save jam",
    "jam.notify": "Notify me",
    "jam.follow": "Follow / join",
    "jam.whatsapp": "WhatsApp community — updates and sessions",
    "jam.djangobooksThread": "DjangoBooks thread",
  },
  fr: {
    "jam.fromDjangoBooks": "Depuis DjangoBooks",
    "jam.save": "Enregistrer le jam",
    "jam.notify": "Me prévenir",
    "jam.follow": "Suivre / rejoindre",
    "jam.whatsapp": "Communauté WhatsApp — dates et sessions",
    "jam.djangobooksThread": "Fil DjangoBooks",
  },
  de: {
    "jam.fromDjangoBooks": "Von DjangoBooks",
    "jam.save": "Jam speichern",
    "jam.notify": "Benachrichtige mich",
    "jam.follow": "Folgen / beitreten",
    "jam.whatsapp": "WhatsApp-Community — Termine und Sessions",
    "jam.djangobooksThread": "DjangoBooks-Thread",
  },
  nl: {
    "jam.fromDjangoBooks": "Van DjangoBooks",
    "jam.save": "Jam bewaren",
    "jam.notify": "Houd me op de hoogte",
    "jam.follow": "Volgen / meedoen",
    "jam.whatsapp": "WhatsApp-groep — updates en sessies",
    "jam.djangobooksThread": "DjangoBooks-draad",
  },
  es: {
    "jam.fromDjangoBooks": "De DjangoBooks",
    "jam.save": "Guardar jam",
    "jam.notify": "Avísame",
    "jam.follow": "Seguir / unirse",
    "jam.whatsapp": "Comunidad WhatsApp — fechas y sesiones",
    "jam.djangobooksThread": "Hilo de DjangoBooks",
  },
  pt: {
    "jam.fromDjangoBooks": "Do DjangoBooks",
    "jam.save": "Guardar jam",
    "jam.notify": "Avisar-me",
    "jam.follow": "Seguir / juntar-me",
    "jam.whatsapp": "Comunidade WhatsApp — datas e sessões",
    "jam.djangobooksThread": "Tópico DjangoBooks",
  },
  it: {
    "jam.fromDjangoBooks": "Da DjangoBooks",
    "jam.save": "Salva jam",
    "jam.notify": "Avvisami",
    "jam.follow": "Segui / unisciti",
    "jam.whatsapp": "Community WhatsApp — date e sessioni",
    "jam.djangobooksThread": "Thread DjangoBooks",
  },
  ru: {
    "jam.fromDjangoBooks": "С DjangoBooks",
    "jam.save": "Сохранить джем",
    "jam.notify": "Напомнить",
    "jam.follow": "Следить / присоединиться",
    "jam.whatsapp": "Сообщество WhatsApp — даты и сессии",
    "jam.djangobooksThread": "Тема DjangoBooks",
  },
  ja: {
    "jam.fromDjangoBooks": "DjangoBooks より",
    "jam.save": "ジャムを保存",
    "jam.notify": "通知する",
    "jam.follow": "フォロー / 参加",
    "jam.whatsapp": "WhatsAppコミュニティ — 日程とセッション",
    "jam.djangobooksThread": "DjangoBooksスレッド",
  },
  ko: {
    "jam.fromDjangoBooks": "DjangoBooks에서",
    "jam.save": "잼 저장",
    "jam.notify": "알림 받기",
    "jam.follow": "팔로우 / 참여",
    "jam.whatsapp": "WhatsApp 커뮤니티 — 일정과 세션",
    "jam.djangobooksThread": "DjangoBooks 스레드",
  },
  zh: {
    "jam.fromDjangoBooks": "来自 DjangoBooks",
    "jam.save": "收藏即兴",
    "jam.notify": "提醒我",
    "jam.follow": "关注 / 加入",
    "jam.whatsapp": "WhatsApp 社群 — 日期与场次",
    "jam.djangobooksThread": "DjangoBooks 帖子",
  },
  "zh-tw": {
    "jam.fromDjangoBooks": "來自 DjangoBooks",
    "jam.save": "收藏即興",
    "jam.notify": "通知我",
    "jam.follow": "追蹤 / 加入",
    "jam.whatsapp": "WhatsApp 社群 — 日期與場次",
    "jam.djangobooksThread": "DjangoBooks 討論串",
  },
  id: {
    "jam.fromDjangoBooks": "Dari DjangoBooks",
    "jam.save": "Simpan jam",
    "jam.notify": "Kabari saya",
    "jam.follow": "Ikuti / gabung",
    "jam.whatsapp": "Komunitas WhatsApp — jadwal dan sesi",
    "jam.djangobooksThread": "Utas DjangoBooks",
  },
  th: {
    "jam.fromDjangoBooks": "จาก DjangoBooks",
    "jam.save": "บันทึกแจม",
    "jam.notify": "แจ้งเตือนฉัน",
    "jam.follow": "ติดตาม / เข้าร่วม",
    "jam.whatsapp": "ชุมชน WhatsApp — วันและเซสชัน",
    "jam.djangobooksThread": "กระทู้ DjangoBooks",
  },
  hu: {
    "jam.fromDjangoBooks": "DjangoBooks-ról",
    "jam.save": "Jam mentése",
    "jam.notify": "Értesíts",
    "jam.follow": "Követés / csatlakozás",
    "jam.whatsapp": "WhatsApp-közösség — dátumok és sessionök",
    "jam.djangobooksThread": "DjangoBooks-szál",
  },
  pl: {
    "jam.fromDjangoBooks": "Z DjangoBooks",
    "jam.save": "Zapisz jam",
    "jam.notify": "Powiadom mnie",
    "jam.follow": "Obserwuj / dołącz",
    "jam.whatsapp": "Społeczność WhatsApp — daty i sesje",
    "jam.djangobooksThread": "Wątek DjangoBooks",
  },
  cs: {
    "jam.fromDjangoBooks": "Z DjangoBooks",
    "jam.save": "Uložit jam",
    "jam.notify": "Upozornit mě",
    "jam.follow": "Sledovat / připojit se",
    "jam.whatsapp": "WhatsApp komunita — termíny a session",
    "jam.djangobooksThread": "Vlákno DjangoBooks",
  },
  hr: {
    "jam.fromDjangoBooks": "S DjangoBooksa",
    "jam.save": "Spremi jam",
    "jam.notify": "Obavijesti me",
    "jam.follow": "Prati / pridruži se",
    "jam.whatsapp": "WhatsApp zajednica — datumi i sessioni",
    "jam.djangobooksThread": "DjangoBooks nit",
  },
  sr: {
    "jam.fromDjangoBooks": "Са DjangoBooks-а",
    "jam.save": "Сачувај џем",
    "jam.notify": "Обавивести ме",
    "jam.follow": "Прати / придружи се",
    "jam.whatsapp": "WhatsApp заједница — датуми и сесије",
    "jam.djangobooksThread": "DjangoBooks тема",
  },
  ro: {
    "jam.fromDjangoBooks": "De pe DjangoBooks",
    "jam.save": "Salvează jam-ul",
    "jam.notify": "Anunță-mă",
    "jam.follow": "Urmărește / alătură-te",
    "jam.whatsapp": "Comunitate WhatsApp — date și sesiuni",
    "jam.djangobooksThread": "Fir DjangoBooks",
  },
};
