export const JAM_GOING_KEYS = [
  "jam.going",
  "jam.goingNot",
  "jam.goingKicker",
  "jam.goingEmpty",
  "jam.goingCount",
  "jam.goingSignin",
  "jam.goingLead",
  "jam.goingNoNight",
  "jam.remind",
  "jam.remindOn",
  "jam.remindLead",
  "jam.remindSignin",
] as const;

export const JAM_GOING_UI: Record<string, Record<string, string>> = {
  en: {
    "jam.going": "I'm going",
    "jam.goingNot": "Not going",
    "jam.goingKicker": "Next session",
    "jam.goingEmpty": "Be the first to say you're going.",
    "jam.goingCount": "{n} going",
    "jam.goingSignin": "Sign in to say you're going.",
    "jam.goingLead": "The list resets after this night.",
    "jam.goingNoNight": "Going opens when the next night is posted.",
    "jam.remind": "Email me 2 days before",
    "jam.remindOn": "Reminder on",
    "jam.remindLead": "A mail two days before the next session. You can leave the list anytime.",
    "jam.remindSignin": "Sign in to get the reminder mail.",
  },
  es: {
    "jam.going": "Voy",
    "jam.goingNot": "No voy",
    "jam.goingKicker": "Próxima sesión",
    "jam.goingEmpty": "Sé el primero en decir que vas.",
    "jam.goingCount": "{n} van",
    "jam.goingSignin": "Inicia sesión para decir que vas.",
    "jam.goingLead": "La lista se borra después de esta noche.",
    "jam.goingNoNight": "Podrás apuntarte cuando esté la próxima fecha.",
    "jam.remind": "Avísame 2 días antes",
    "jam.remindOn": "Recordatorio activo",
    "jam.remindLead": "Un correo dos días antes de la próxima sesión. Puedes salir de la lista cuando quieras.",
    "jam.remindSignin": "Inicia sesión para el recordatorio.",
  },
  pt: {
    "jam.going": "Vou",
    "jam.goingNot": "Não vou",
    "jam.goingKicker": "Próxima sessão",
    "jam.goingEmpty": "Sê o primeiro a dizer que vais.",
    "jam.goingCount": "{n} vão",
    "jam.goingSignin": "Entra para dizer que vais.",
    "jam.goingLead": "A lista apaga-se depois desta noite.",
    "jam.goingNoNight": "Podes marcar presença quando a próxima data estiver.",
    "jam.remind": "Email 2 dias antes",
    "jam.remindOn": "Lembrete ligado",
    "jam.remindLead": "Um email dois dias antes da próxima sessão. Podes sair da lista quando quiseres.",
    "jam.remindSignin": "Entra para receber o lembrete.",
  },
  fr: {
    "jam.going": "J’y vais",
    "jam.goingNot": "Je n’y vais pas",
    "jam.goingKicker": "Prochaine session",
    "jam.goingEmpty": "Sois le premier à dire que tu y vas.",
    "jam.goingCount": "{n} inscrits",
    "jam.goingSignin": "Connecte-toi pour dire que tu y vas.",
    "jam.goingLead": "La liste s’efface après cette soirée.",
    "jam.goingNoNight": "On pourra s’inscrire dès que la prochaine date est affichée.",
    "jam.remind": "Un mail 2 jours avant",
    "jam.remindOn": "Rappel activé",
    "jam.remindLead": "Un mail deux jours avant la prochaine session. Tu peux te retirer à tout moment.",
    "jam.remindSignin": "Connecte-toi pour recevoir le rappel.",
  },
  de: {
    "jam.going": "Ich gehe hin",
    "jam.goingNot": "Ich gehe nicht",
    "jam.goingKicker": "Nächste Session",
    "jam.goingEmpty": "Sei der Erste, der zusagt.",
    "jam.goingCount": "{n} kommen",
    "jam.goingSignin": "Melde dich an, um zuzusagen.",
    "jam.goingLead": "Die Liste wird nach diesem Abend gelöscht.",
    "jam.goingNoNight": "Zusagen geht, sobald der nächste Abend steht.",
    "jam.remind": "Mail 2 Tage vorher",
    "jam.remindOn": "Erinnerung an",
    "jam.remindLead": "Eine Mail zwei Tage vor der nächsten Session. Du kannst dich jederzeit austragen.",
    "jam.remindSignin": "Melde dich an für die Erinnerungsmail.",
  },
  nl: {
    "jam.going": "Ik ga",
    "jam.goingNot": "Ik ga niet",
    "jam.goingKicker": "Volgende sessie",
    "jam.goingEmpty": "Wees de eerste die zegt dat-ie komt.",
    "jam.goingCount": "{n} komen",
    "jam.goingSignin": "Log in om te zeggen dat je komt.",
    "jam.goingLead": "De lijst wordt na deze avond gewist.",
    "jam.goingNoNight": "Aanmelden kan zodra de volgende avond staat.",
    "jam.remind": "Mail me 2 dagen van tevoren",
    "jam.remindOn": "Herinnering aan",
    "jam.remindLead": "Een mail twee dagen voor de volgende sessie. Je kunt je altijd afmelden.",
    "jam.remindSignin": "Log in voor de herinneringsmail.",
  },
  it: {
    "jam.going": "Ci vado",
    "jam.goingNot": "Non ci vado",
    "jam.goingKicker": "Prossima sessione",
    "jam.goingEmpty": "Sii il primo a dire che ci vai.",
    "jam.goingCount": "{n} ci vanno",
    "jam.goingSignin": "Accedi per dire che ci vai.",
    "jam.goingLead": "La lista si cancella dopo questa serata.",
    "jam.goingNoNight": "Potrai iscriverti quando c’è la prossima data.",
    "jam.remind": "Email 2 giorni prima",
    "jam.remindOn": "Promemoria attivo",
    "jam.remindLead": "Una mail due giorni prima della prossima sessione. Puoi uscire quando vuoi.",
    "jam.remindSignin": "Accedi per la mail di promemoria.",
  },
  hu: {
    "jam.going": "Megyek",
    "jam.goingNot": "Nem megyek",
    "jam.goingKicker": "Következő session",
    "jam.goingEmpty": "Légy az első, aki jön.",
    "jam.goingCount": "{n} jön",
    "jam.goingSignin": "Jelentkezz be, hogy jelezd, jössz.",
    "jam.goingLead": "A lista törlődik ezután az este után.",
    "jam.goingNoNight": "Jelentkezni akkor lehet, ha ki van téve a következő este.",
    "jam.remind": "Mail 2 nappal előtte",
    "jam.remindOn": "Emlékeztető be",
    "jam.remindLead": "Levél két nappal a következő session előtt. Bármikor leiratkozhatsz.",
    "jam.remindSignin": "Jelentkezz be az emlékeztetőhöz.",
  },
  ro: {
    "jam.going": "Vin",
    "jam.goingNot": "Nu vin",
    "jam.goingKicker": "Următoarea sesiune",
    "jam.goingEmpty": "Fii primul care spune că vine.",
    "jam.goingCount": "{n} vin",
    "jam.goingSignin": "Autentifică-te ca să spui că vii.",
    "jam.goingLead": "Lista se șterge după această seară.",
    "jam.goingNoNight": "Te poți trece pe listă când e afișată următoarea dată.",
    "jam.remind": "Email cu 2 zile înainte",
    "jam.remindOn": "Memento activ",
    "jam.remindLead": "Un email cu două zile înainte de următoarea sesiune. Poți ieși oricând.",
    "jam.remindSignin": "Autentifică-te pentru memento.",
  },
  sr: {
    "jam.going": "Идем",
    "jam.goingNot": "Не идем",
    "jam.goingKicker": "Следећа сесија",
    "jam.goingEmpty": "Буди први који каже да долази.",
    "jam.goingCount": "{n} долазе",
    "jam.goingSignin": "Пријави се да кажеш да долазиш.",
    "jam.goingLead": "Листа се брише после ове вечери.",
    "jam.goingNoNight": "Можеш се уписати кад стоји следећи термин.",
    "jam.remind": "Мејл 2 дана раније",
    "jam.remindOn": "Подсетник укључен",
    "jam.remindLead": "Мејл два дана пре следеће сесије. Можеш се скинути кад год.",
    "jam.remindSignin": "Пријави се за подсетник.",
  },
  cs: {
    "jam.going": "Jdu",
    "jam.goingNot": "Nejdu",
    "jam.goingKicker": "Příští session",
    "jam.goingEmpty": "Buď první, kdo řekne, že jde.",
    "jam.goingCount": "{n} jdou",
    "jam.goingSignin": "Přihlas se, abys řekl, že jdeš.",
    "jam.goingLead": "Seznam se po tomto večeru smaže.",
    "jam.goingNoNight": "Zapsat se půjde, až bude příští termín.",
    "jam.remind": "E-mail 2 dny předem",
    "jam.remindOn": "Připomínka zapnutá",
    "jam.remindLead": "E-mail dva dny před příští session. Můžeš se kdykoli odhlásit.",
    "jam.remindSignin": "Přihlas se pro připomínku.",
  },
  pl: {
    "jam.going": "Idę",
    "jam.goingNot": "Nie idę",
    "jam.goingKicker": "Następna sesja",
    "jam.goingEmpty": "Bądź pierwszy, który powie, że idzie.",
    "jam.goingCount": "{n} idzie",
    "jam.goingSignin": "Zaloguj się, żeby powiedzieć, że idziesz.",
    "jam.goingLead": "Lista kasuje się po tej nocy.",
    "jam.goingNoNight": "Zapiszesz się, gdy będzie następna data.",
    "jam.remind": "Mail 2 dni wcześniej",
    "jam.remindOn": "Przypomnienie włączone",
    "jam.remindLead": "Mail dwa dni przed następną sesją. Możesz wypisać się w każdej chwili.",
    "jam.remindSignin": "Zaloguj się po przypomnienie.",
  },
  hr: {
    "jam.going": "Idem",
    "jam.goingNot": "Ne idem",
    "jam.goingKicker": "Sljedeća sesija",
    "jam.goingEmpty": "Budi prvi koji kaže da dolazi.",
    "jam.goingCount": "{n} dolaze",
    "jam.goingSignin": "Prijavi se da kažeš da dolaziš.",
    "jam.goingLead": "Lista se briše nakon ove večeri.",
    "jam.goingNoNight": "Možeš se upisati kad stoji sljedeći termin.",
    "jam.remind": "Mail 2 dana prije",
    "jam.remindOn": "Podsjetnik uključen",
    "jam.remindLead": "Mail dva dana prije sljedeće sesije. Možeš se skinuti kad god.",
    "jam.remindSignin": "Prijavi se za podsjetnik.",
  },
  ru: {
    "jam.going": "Я иду",
    "jam.goingNot": "Не иду",
    "jam.goingKicker": "Следующая сессия",
    "jam.goingEmpty": "Будь первым, кто напишет, что идёт.",
    "jam.goingCount": "{n} идут",
    "jam.goingSignin": "Войди, чтобы сказать, что идёшь.",
    "jam.goingLead": "Список стирается после этого вечера.",
    "jam.goingNoNight": "Записаться можно, когда появится ближайшая дата.",
    "jam.remind": "Письмо за 2 дня",
    "jam.remindOn": "Напоминание включено",
    "jam.remindLead": "Письмо за два дня до следующей сессии. Можно отписаться в любой момент.",
    "jam.remindSignin": "Войди, чтобы получить напоминание.",
  },
  ja: {
    "jam.going": "行きます",
    "jam.goingNot": "行きません",
    "jam.goingKicker": "次回セッション",
    "jam.goingEmpty": "最初に「行きます」と書いてください。",
    "jam.goingCount": "{n}人参加",
    "jam.goingSignin": "ログインして参加を伝える。",
    "jam.goingLead": "この夜が終わるとリストは消えます。",
    "jam.goingNoNight": "次回の日程が出たら参加表明できます。",
    "jam.remind": "2日前にメール",
    "jam.remindOn": "リマインダーオン",
    "jam.remindLead": "次回の2日前にメールします。いつでも外せます。",
    "jam.remindSignin": "ログインしてリマインダーを受け取る。",
  },
  ko: {
    "jam.going": "갈게요",
    "jam.goingNot": "안 가요",
    "jam.goingKicker": "다음 세션",
    "jam.goingEmpty": "먼저 간다고 말해 주세요.",
    "jam.goingCount": "{n}명 참석",
    "jam.goingSignin": "로그인하고 참석을 알려 주세요.",
    "jam.goingLead": "이 밤이 지나면 목록이 지워집니다.",
    "jam.goingNoNight": "다음 날짜가 올라오면 참석을 표시할 수 있습니다.",
    "jam.remind": "이틀 전 이메일",
    "jam.remindOn": "알림 켜짐",
    "jam.remindLead": "다음 세션 이틀 전에 메일이 갑니다. 언제든 끌 수 있습니다.",
    "jam.remindSignin": "로그인하고 알림 메일을 받으세요.",
  },
  zh: {
    "jam.going": "我去",
    "jam.goingNot": "不去",
    "jam.goingKicker": "下一场",
    "jam.goingEmpty": "做第一个说要去的人。",
    "jam.goingCount": "{n} 人要去",
    "jam.goingSignin": "登录后才能说你要去。",
    "jam.goingLead": "这场结束后名单会清空。",
    "jam.goingNoNight": "下一场日期公布后就可以报名。",
    "jam.remind": "两天前发邮件",
    "jam.remindOn": "提醒已开",
    "jam.remindLead": "下一场两天前会发邮件。随时可以关掉。",
    "jam.remindSignin": "登录后接收提醒邮件。",
  },
  "zh-tw": {
    "jam.going": "我去",
    "jam.goingNot": "不去",
    "jam.goingKicker": "下一場",
    "jam.goingEmpty": "做第一個說要去的人。",
    "jam.goingCount": "{n} 人要去",
    "jam.goingSignin": "登入後才能說你要去。",
    "jam.goingLead": "這場結束後名單會清空。",
    "jam.goingNoNight": "下一場日期公布後就可以報名。",
    "jam.remind": "兩天前寄信",
    "jam.remindOn": "提醒已開",
    "jam.remindLead": "下一場兩天前會寄信。隨時可以關掉。",
    "jam.remindSignin": "登入後接收提醒信。",
  },
  id: {
    "jam.going": "Saya datang",
    "jam.goingNot": "Tidak datang",
    "jam.goingKicker": "Sesi berikutnya",
    "jam.goingEmpty": "Jadilah yang pertama bilang datang.",
    "jam.goingCount": "{n} datang",
    "jam.goingSignin": "Masuk untuk bilang kamu datang.",
    "jam.goingLead": "Daftar dihapus setelah malam ini.",
    "jam.goingNoNight": "Bisa daftar begitu tanggal berikutnya terpasang.",
    "jam.remind": "Email 2 hari sebelumnya",
    "jam.remindOn": "Pengingat aktif",
    "jam.remindLead": "Email dua hari sebelum sesi berikutnya. Bisa berhenti kapan saja.",
    "jam.remindSignin": "Masuk untuk email pengingat.",
  },
  th: {
    "jam.going": "ไป",
    "jam.goingNot": "ไม่ไป",
    "jam.goingKicker": "เซสชันถัดไป",
    "jam.goingEmpty": "เป็นคนแรกที่บอกว่าจะไป",
    "jam.goingCount": "{n} คนไป",
    "jam.goingSignin": "เข้าสู่ระบบเพื่อบอกว่าจะไป",
    "jam.goingLead": "รายชื่อถูกลบหลังคืนนี้",
    "jam.goingNoNight": "ลงชื่อได้เมื่อมีวันถัดไป",
    "jam.remind": "อีเมลก่อน 2 วัน",
    "jam.remindOn": "เปิดเตือนแล้ว",
    "jam.remindLead": "อีเมลสองวันก่อนเซสชันถัดไป เอาออกได้ทุกเมื่อ",
    "jam.remindSignin": "เข้าสู่ระบบเพื่อรับอีเมลเตือน",
  },
};
