import { festivalWhen } from "@/lib/festival-copy";

const PHRASES: Record<string, [string, string][]> = {
  fr: [
    ["No regular Gypsy Jazz jam posted", "Pas de jam gypsy jazz régulière affichée"],
    ["No regular open jam posted", "Pas de jam ouverte régulière affichée"],
    ["No regular jam posted", "Pas de jam régulière affichée"],
    ["First Saturday of the month", "Premier samedi du mois"],
    ["First Tuesday of the month", "Premier mardi du mois"],
    ["Third Saturday of the month", "Troisième samedi du mois"],
    ["Second Wednesday of the month", "Deuxième mercredi du mois"],
    ["Last Wednesday of the month", "Dernier mercredi du mois"],
    ["Last Sunday of the month", "Dernier dimanche du mois"],
    ["Thursday series — dates as posted", "Série du jeudi — dates affichées"],
    ["Around the festival, plus monthly", "Autour du festival, plus mensuel"],
    ["Concerts; open jams when posted", "Concerts ; jams ouvertes quand c’est annoncé"],
    ["Monthly, Thursday — check the band", "Mensuel, jeudi — voir le groupe"],
    ["Monthly Sunday — check Facebook", "Dimanche mensuel — voir Facebook"],
    ["Regular — check Kozlov Club", "Régulier — voir Kozlov Club"],
    ["When posted — not weekly", "Quand c’est annoncé — pas chaque semaine"],
    ["2nd Friday of even months", "2e vendredi des mois pairs"],
    ["1st and 3rd Tuesdays", "1er et 3e mardis"],
    ["2nd and 4th Sundays", "2e et 4e dimanches"],
    ["2nd and 4th Thursday", "2e et 4e jeudis"],
    ["Every other Tuesday", "Un mardi sur deux"],
    ["Tuesdays when posted", "Les mardis quand c’est annoncé"],
    ["Thursday when posted", "Le jeudi quand c’est annoncé"],
    ["Session nights (posted)", "Soirées (annoncées)"],
    ["Monthly (date posted)", "Mensuel (date affichée)"],
    ["Posted per date", "Annoncé par date"],
    ["Selected Fridays", "Certains vendredis"],
    ["Festival week, late June", "Semaine du festival, fin juin"],
    ["Festival week", "Semaine du festival"],
    ["Spring camp", "Camp de printemps"],
    ["Camp weeks", "Semaines de camp"],
    ["Every Thursday", "Tous les jeudis"],
    ["Every Sunday", "Tous les dimanches"],
    ["Every Tuesday", "Tous les mardis"],
    ["Every Wednesday", "Tous les mercredis"],
    ["Every Monday", "Tous les lundis"],
    ["First Tuesday", "Premier mardi"],
    ["First Sunday", "Premier dimanche"],
    ["Last Tuesday", "Dernier mardi"],
    ["4th Wednesday", "4e mercredi"],
    ["2nd Wednesday", "2e mercredi"],
    ["3rd Saturday", "3e samedi"],
    ["3rd Sunday", "3e dimanche"],
    ["1st Sunday", "1er dimanche"],
    ["Most Mondays", "La plupart des lundis"],
    ["Weekly, Wednesday", "Hebdomadaire, mercredi"],
    ["Weekly, Monday", "Hebdomadaire, lundi"],
    ["Wednesday–Saturday", "Mercredi–samedi"],
    ["When posted", "Quand c’est annoncé"],
    ["Weekends", "Week-ends"],
    ["Weekly", "Hebdomadaire"],
    ["Monthly", "Mensuel"],
    ["Mondays", "Les lundis"],
    ["Thursday", "Jeudi"],
    ["Sunday", "Dimanche"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sam. & dim."],
    ["from ", "à partir de "],
  ],
  de: [
    ["No regular Gypsy Jazz jam posted", "Kein regelmäßiger Gypsy-Jazz-Jam angegeben"],
    ["No regular open jam posted", "Kein regelmäßiger offener Jam angegeben"],
    ["No regular jam posted", "Kein regelmäßiger Jam angegeben"],
    ["First Saturday of the month", "Erster Samstag im Monat"],
    ["First Tuesday of the month", "Erster Dienstag im Monat"],
    ["Third Saturday of the month", "Dritter Samstag im Monat"],
    ["Second Wednesday of the month", "Zweiter Mittwoch im Monat"],
    ["Last Wednesday of the month", "Letzter Mittwoch im Monat"],
    ["Last Sunday of the month", "Letzter Sonntag im Monat"],
    ["Thursday series — dates as posted", "Donnerstagsserie — Termine wie angegeben"],
    ["Around the festival, plus monthly", "Rund ums Festival, plus monatlich"],
    ["Concerts; open jams when posted", "Konzerte; offene Jams wenn angegeben"],
    ["Monthly, Thursday — check the band", "Monatlich, Donnerstag — Band prüfen"],
    ["Monthly Sunday — check Facebook", "Monatlicher Sonntag — Facebook prüfen"],
    ["Regular — check Kozlov Club", "Regelmäßig — Kozlov Club prüfen"],
    ["When posted — not weekly", "Wenn angegeben — nicht wöchentlich"],
    ["2nd Friday of even months", "2. Freitag in geraden Monaten"],
    ["1st and 3rd Tuesdays", "1. und 3. Dienstag"],
    ["2nd and 4th Sundays", "2. und 4. Sonntag"],
    ["2nd and 4th Thursday", "2. und 4. Donnerstag"],
    ["Every other Tuesday", "Jeden zweiten Dienstag"],
    ["Tuesdays when posted", "Dienstage wenn angegeben"],
    ["Thursday when posted", "Donnerstag wenn angegeben"],
    ["Session nights (posted)", "Session-Abende (angegeben)"],
    ["Monthly (date posted)", "Monatlich (Datum angegeben)"],
    ["Posted per date", "Pro Termin angegeben"],
    ["Selected Fridays", "Ausgewählte Freitage"],
    ["Festival week, late June", "Festivalwoche, Ende Juni"],
    ["Festival week", "Festivalwoche"],
    ["Spring camp", "Frühlingscamp"],
    ["Camp weeks", "Campwochen"],
    ["Every Thursday", "Jeden Donnerstag"],
    ["Every Sunday", "Jeden Sonntag"],
    ["Every Tuesday", "Jeden Dienstag"],
    ["Every Wednesday", "Jeden Mittwoch"],
    ["Every Monday", "Jeden Montag"],
    ["First Tuesday", "Erster Dienstag"],
    ["First Sunday", "Erster Sonntag"],
    ["Last Tuesday", "Letzter Dienstag"],
    ["4th Wednesday", "4. Mittwoch"],
    ["2nd Wednesday", "2. Mittwoch"],
    ["3rd Saturday", "3. Samstag"],
    ["3rd Sunday", "3. Sonntag"],
    ["1st Sunday", "1. Sonntag"],
    ["Most Mondays", "Die meisten Montage"],
    ["Weekly, Wednesday", "Wöchentlich, Mittwoch"],
    ["Weekly, Monday", "Wöchentlich, Montag"],
    ["Wednesday–Saturday", "Mittwoch–Samstag"],
    ["When posted", "Wenn angegeben"],
    ["Weekends", "Wochenenden"],
    ["Weekly", "Wöchentlich"],
    ["Monthly", "Monatlich"],
    ["Mondays", "Montags"],
    ["Thursday", "Donnerstag"],
    ["Sunday", "Sonntag"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sa. & So."],
    ["from ", "ab "],
  ],
  nl: [
    ["No regular Gypsy Jazz jam posted", "Geen vaste gypsy-jazzjam gezet"],
    ["No regular open jam posted", "Geen vaste open jam gezet"],
    ["No regular jam posted", "Geen vaste jam gezet"],
    ["First Saturday of the month", "Eerste zaterdag van de maand"],
    ["First Tuesday of the month", "Eerste dinsdag van de maand"],
    ["Third Saturday of the month", "Derde zaterdag van de maand"],
    ["Second Wednesday of the month", "Tweede woensdag van de maand"],
    ["Last Wednesday of the month", "Laatste woensdag van de maand"],
    ["Last Sunday of the month", "Laatste zondag van de maand"],
    ["Thursday series — dates as posted", "Donderdagreeks — data zoals gezet"],
    ["Around the festival, plus monthly", "Rond het festival, plus maandelijks"],
    ["Concerts; open jams when posted", "Concerten; open jams wanneer gezet"],
    ["Monthly, Thursday — check the band", "Maandelijks, donderdag — check de band"],
    ["Monthly Sunday — check Facebook", "Maandelijkse zondag — check Facebook"],
    ["Regular — check Kozlov Club", "Vast — check Kozlov Club"],
    ["When posted — not weekly", "Wanneer gezet — niet wekelijks"],
    ["2nd Friday of even months", "2e vrijdag van even maanden"],
    ["1st and 3rd Tuesdays", "1e en 3e dinsdag"],
    ["2nd and 4th Sundays", "2e en 4e zondag"],
    ["2nd and 4th Thursday", "2e en 4e donderdag"],
    ["Every other Tuesday", "Om de dinsdag"],
    ["Tuesdays when posted", "Dinsdagen wanneer gezet"],
    ["Thursday when posted", "Donderdag wanneer gezet"],
    ["Session nights (posted)", "Sessieavonden (gezet)"],
    ["Monthly (date posted)", "Maandelijks (datum gezet)"],
    ["Posted per date", "Per datum gezet"],
    ["Selected Fridays", "Geselecteerde vrijdagen"],
    ["Festival week, late June", "Festivalweek, eind juni"],
    ["Festival week", "Festivalweek"],
    ["Spring camp", "Lentekamp"],
    ["Camp weeks", "Kampweken"],
    ["Every Thursday", "Elke donderdag"],
    ["Every Sunday", "Elke zondag"],
    ["Every Tuesday", "Elke dinsdag"],
    ["Every Wednesday", "Elke woensdag"],
    ["Every Monday", "Elke maandag"],
    ["First Tuesday", "Eerste dinsdag"],
    ["First Sunday", "Eerste zondag"],
    ["Last Tuesday", "Laatste dinsdag"],
    ["4th Wednesday", "4e woensdag"],
    ["2nd Wednesday", "2e woensdag"],
    ["3rd Saturday", "3e zaterdag"],
    ["3rd Sunday", "3e zondag"],
    ["1st Sunday", "1e zondag"],
    ["Most Mondays", "De meeste maandagen"],
    ["Weekly, Wednesday", "Wekelijks, woensdag"],
    ["Weekly, Monday", "Wekelijks, maandag"],
    ["Wednesday–Saturday", "Woensdag–zaterdag"],
    ["When posted", "Wanneer gezet"],
    ["Weekends", "Weekends"],
    ["Weekly", "Wekelijks"],
    ["Monthly", "Maandelijks"],
    ["Mondays", "Maandagen"],
    ["Thursday", "Donderdag"],
    ["Sunday", "Zondag"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Za. & zo."],
    ["from ", "vanaf "],
  ],
  es: [
    ["No regular Gypsy Jazz jam posted", "No hay jam regular de gypsy jazz anunciado"],
    ["No regular open jam posted", "No hay jam abierto regular anunciado"],
    ["No regular jam posted", "No hay jam regular anunciado"],
    ["First Saturday of the month", "Primer sábado del mes"],
    ["First Tuesday of the month", "Primer martes del mes"],
    ["Third Saturday of the month", "Tercer sábado del mes"],
    ["Second Wednesday of the month", "Segundo miércoles del mes"],
    ["Last Wednesday of the month", "Último miércoles del mes"],
    ["Last Sunday of the month", "Último domingo del mes"],
    ["Thursday series — dates as posted", "Serie de jueves — fechas según anuncio"],
    ["Around the festival, plus monthly", "En torno al festival, más mensual"],
    ["Concerts; open jams when posted", "Conciertos; jams abiertos cuando se anuncian"],
    ["Monthly, Thursday — check the band", "Mensual, jueves — consultar el grupo"],
    ["Monthly Sunday — check Facebook", "Domingo mensual — consultar Facebook"],
    ["Regular — check Kozlov Club", "Regular — consultar Kozlov Club"],
    ["When posted — not weekly", "Cuando se anuncia — no semanal"],
    ["2nd Friday of even months", "2.º viernes de meses pares"],
    ["1st and 3rd Tuesdays", "1.er y 3.er martes"],
    ["2nd and 4th Sundays", "2.º y 4.º domingo"],
    ["2nd and 4th Thursday", "2.º y 4.º jueves"],
    ["Every other Tuesday", "Un martes sí y otro no"],
    ["Tuesdays when posted", "Martes cuando se anuncia"],
    ["Thursday when posted", "Jueves cuando se anuncia"],
    ["Session nights (posted)", "Noches de sesión (anunciadas)"],
    ["Monthly (date posted)", "Mensual (fecha anunciada)"],
    ["Posted per date", "Anunciado por fecha"],
    ["Selected Fridays", "Viernes concretos"],
    ["Festival week, late June", "Semana del festival, finales de junio"],
    ["Festival week", "Semana del festival"],
    ["Spring camp", "Campamento de primavera"],
    ["Camp weeks", "Semanas de campamento"],
    ["Every Thursday", "Todos los jueves"],
    ["Every Sunday", "Todos los domingos"],
    ["Every Tuesday", "Todos los martes"],
    ["Every Wednesday", "Todos los miércoles"],
    ["Every Monday", "Todos los lunes"],
    ["First Tuesday", "Primer martes"],
    ["First Sunday", "Primer domingo"],
    ["Last Tuesday", "Último martes"],
    ["4th Wednesday", "4.º miércoles"],
    ["2nd Wednesday", "2.º miércoles"],
    ["3rd Saturday", "3.er sábado"],
    ["3rd Sunday", "3.er domingo"],
    ["1st Sunday", "1.er domingo"],
    ["Most Mondays", "La mayoría de los lunes"],
    ["Weekly, Wednesday", "Semanal, miércoles"],
    ["Weekly, Monday", "Semanal, lunes"],
    ["Wednesday–Saturday", "Miércoles–sábado"],
    ["When posted", "Cuando se anuncia"],
    ["Weekends", "Fines de semana"],
    ["Weekly", "Semanal"],
    ["Monthly", "Mensual"],
    ["Mondays", "Los lunes"],
    ["Thursday", "Jueves"],
    ["Sunday", "Domingo"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sáb. y dom."],
    ["from ", "desde "],
  ],
  pt: [
    ["No regular Gypsy Jazz jam posted", "Não há jam regular de gypsy jazz anunciada"],
    ["No regular open jam posted", "Não há jam aberta regular anunciada"],
    ["No regular jam posted", "Não há jam regular anunciada"],
    ["First Saturday of the month", "Primeiro sábado do mês"],
    ["First Tuesday of the month", "Primeira terça-feira do mês"],
    ["Third Saturday of the month", "Terceiro sábado do mês"],
    ["Second Wednesday of the month", "Segunda quarta-feira do mês"],
    ["Last Wednesday of the month", "Última quarta-feira do mês"],
    ["Last Sunday of the month", "Último domingo do mês"],
    ["Thursday series — dates as posted", "Série de quintas — datas conforme anúncio"],
    ["Around the festival, plus monthly", "Em torno do festival, mais mensal"],
    ["Concerts; open jams when posted", "Concertos; jams abertas quando anunciadas"],
    ["Monthly, Thursday — check the band", "Mensal, quinta — ver a banda"],
    ["Monthly Sunday — check Facebook", "Domingo mensal — ver Facebook"],
    ["Regular — check Kozlov Club", "Regular — ver Kozlov Club"],
    ["When posted — not weekly", "Quando anunciado — não semanal"],
    ["2nd Friday of even months", "2.ª sexta dos meses pares"],
    ["1st and 3rd Tuesdays", "1.ª e 3.ª terças"],
    ["2nd and 4th Sundays", "2.º e 4.º domingo"],
    ["2nd and 4th Thursday", "2.ª e 4.ª quinta"],
    ["Every other Tuesday", "Uma terça sim, outra não"],
    ["Tuesdays when posted", "Terças quando anunciado"],
    ["Thursday when posted", "Quinta quando anunciado"],
    ["Session nights (posted)", "Noites de sessão (anunciadas)"],
    ["Monthly (date posted)", "Mensal (data anunciada)"],
    ["Posted per date", "Anunciado por data"],
    ["Selected Fridays", "Sextas escolhidas"],
    ["Festival week, late June", "Semana do festival, fim de junho"],
    ["Festival week", "Semana do festival"],
    ["Spring camp", "Campo de primavera"],
    ["Camp weeks", "Semanas de campo"],
    ["Every Thursday", "Todas as quintas"],
    ["Every Sunday", "Todos os domingos"],
    ["Every Tuesday", "Todas as terças"],
    ["Every Wednesday", "Todas as quartas"],
    ["Every Monday", "Todas as segundas"],
    ["First Tuesday", "Primeira terça"],
    ["First Sunday", "Primeiro domingo"],
    ["Last Tuesday", "Última terça"],
    ["4th Wednesday", "4.ª quarta"],
    ["2nd Wednesday", "2.ª quarta"],
    ["3rd Saturday", "3.º sábado"],
    ["3rd Sunday", "3.º domingo"],
    ["1st Sunday", "1.º domingo"],
    ["Most Mondays", "A maior parte das segundas"],
    ["Weekly, Wednesday", "Semanal, quarta"],
    ["Weekly, Monday", "Semanal, segunda"],
    ["Wednesday–Saturday", "Quarta–sábado"],
    ["When posted", "Quando anunciado"],
    ["Weekends", "Fins de semana"],
    ["Weekly", "Semanal"],
    ["Monthly", "Mensal"],
    ["Mondays", "As segundas"],
    ["Thursday", "Quinta"],
    ["Sunday", "Domingo"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sáb. e dom."],
    ["from ", "a partir de "],
  ],
  it: [
    ["No regular Gypsy Jazz jam posted", "Nessun jam gypsy jazz fisso indicato"],
    ["No regular open jam posted", "Nessun jam aperto fisso indicato"],
    ["No regular jam posted", "Nessun jam fisso indicato"],
    ["First Saturday of the month", "Primo sabato del mese"],
    ["First Tuesday of the month", "Primo martedì del mese"],
    ["Third Saturday of the month", "Terzo sabato del mese"],
    ["Second Wednesday of the month", "Secondo mercoledì del mese"],
    ["Last Wednesday of the month", "Ultimo mercoledì del mese"],
    ["Last Sunday of the month", "Ultima domenica del mese"],
    ["Thursday series — dates as posted", "Serie del giovedì — date come indicate"],
    ["Around the festival, plus monthly", "Intorno al festival, più mensile"],
    ["Concerts; open jams when posted", "Concerti; jam aperti quando indicati"],
    ["Monthly, Thursday — check the band", "Mensile, giovedì — vedi il gruppo"],
    ["Monthly Sunday — check Facebook", "Domenica mensile — vedi Facebook"],
    ["Regular — check Kozlov Club", "Fisso — vedi Kozlov Club"],
    ["When posted — not weekly", "Quando indicato — non settimanale"],
    ["2nd Friday of even months", "2° venerdì dei mesi pari"],
    ["1st and 3rd Tuesdays", "1° e 3° martedì"],
    ["2nd and 4th Sundays", "2° e 4° domenica"],
    ["2nd and 4th Thursday", "2° e 4° giovedì"],
    ["Every other Tuesday", "Un martedì sì e uno no"],
    ["Tuesdays when posted", "Martedì quando indicato"],
    ["Thursday when posted", "Giovedì quando indicato"],
    ["Session nights (posted)", "Sere di sessione (indicate)"],
    ["Monthly (date posted)", "Mensile (data indicata)"],
    ["Posted per date", "Indicato per data"],
    ["Selected Fridays", "Venerdì scelti"],
    ["Festival week, late June", "Settimana del festival, fine giugno"],
    ["Festival week", "Settimana del festival"],
    ["Spring camp", "Campo di primavera"],
    ["Camp weeks", "Settimane di campo"],
    ["Every Thursday", "Ogni giovedì"],
    ["Every Sunday", "Ogni domenica"],
    ["Every Tuesday", "Ogni martedì"],
    ["Every Wednesday", "Ogni mercoledì"],
    ["Every Monday", "Ogni lunedì"],
    ["First Tuesday", "Primo martedì"],
    ["First Sunday", "Prima domenica"],
    ["Last Tuesday", "Ultimo martedì"],
    ["4th Wednesday", "4° mercoledì"],
    ["2nd Wednesday", "2° mercoledì"],
    ["3rd Saturday", "3° sabato"],
    ["3rd Sunday", "3° domenica"],
    ["1st Sunday", "1° domenica"],
    ["Most Mondays", "La maggior parte dei lunedì"],
    ["Weekly, Wednesday", "Settimanale, mercoledì"],
    ["Weekly, Monday", "Settimanale, lunedì"],
    ["Wednesday–Saturday", "Mercoledì–sabato"],
    ["When posted", "Quando indicato"],
    ["Weekends", "Fine settimana"],
    ["Weekly", "Settimanale"],
    ["Monthly", "Mensile"],
    ["Mondays", "I lunedì"],
    ["Thursday", "Giovedì"],
    ["Sunday", "Domenica"],
    ["Meetup", "Meetup"],
    ["Sat & Sun", "Sab. e dom."],
    ["from ", "dalle "],
  ],
};

for (const rows of Object.values(PHRASES)) rows.sort((a, b) => b[0].length - a[0].length);

const GENERIC_DAYS: Record<string, Record<string, string>> = {
  ru: { Thursday: "четверг", Sunday: "воскресенье", Tuesday: "вторник", Wednesday: "среда", Monday: "понедельник", Friday: "пятница", Saturday: "суббота", Weekends: "выходные" },
  ja: { Thursday: "木曜日", Sunday: "日曜日", Tuesday: "火曜日", Wednesday: "水曜日", Monday: "月曜日", Friday: "金曜日", Saturday: "土曜日", Weekends: "週末" },
  ko: { Thursday: "목요일", Sunday: "일요일", Tuesday: "화요일", Wednesday: "수요일", Monday: "월요일", Friday: "금요일", Saturday: "토요일", Weekends: "주말" },
  zh: { Thursday: "周四", Sunday: "周日", Tuesday: "周二", Wednesday: "周三", Monday: "周一", Friday: "周五", Saturday: "周六", Weekends: "周末" },
  "zh-tw": { Thursday: "週四", Sunday: "週日", Tuesday: "週二", Wednesday: "週三", Monday: "週一", Friday: "週五", Saturday: "週六", Weekends: "週末" },
  hu: { Thursday: "csütörtök", Sunday: "vasárnap", Tuesday: "kedd", Wednesday: "szerda", Monday: "hétfő", Friday: "péntek", Saturday: "szombat", Weekends: "hétvégék" },
  pl: { Thursday: "czwartek", Sunday: "niedziela", Tuesday: "wtorek", Wednesday: "środa", Monday: "poniedziałek", Friday: "piątek", Saturday: "sobota", Weekends: "weekendy" },
  cs: { Thursday: "čtvrtek", Sunday: "neděle", Tuesday: "úterý", Wednesday: "středa", Monday: "pondělí", Friday: "pátek", Saturday: "sobota", Weekends: "víkendy" },
  hr: { Thursday: "četvrtak", Sunday: "nedjelja", Tuesday: "utorak", Wednesday: "srijeda", Monday: "ponedjeljak", Friday: "petak", Saturday: "subota", Weekends: "vikendi" },
  sr: { Thursday: "четвртак", Sunday: "недеља", Tuesday: "уторак", Wednesday: "среда", Monday: "понедељак", Friday: "петак", Saturday: "субота", Weekends: "викенди" },
  ro: { Thursday: "joi", Sunday: "duminică", Tuesday: "marți", Wednesday: "miercuri", Monday: "luni", Friday: "vineri", Saturday: "sâmbătă", Weekends: "weekenduri" },
  id: { Thursday: "Kamis", Sunday: "Minggu", Tuesday: "Selasa", Wednesday: "Rabu", Monday: "Senin", Friday: "Jumat", Saturday: "Sabtu", Weekends: "akhir pekan" },
  th: { Thursday: "พฤหัส", Sunday: "อาทิตย์", Tuesday: "อังคาร", Wednesday: "พุธ", Monday: "จันทร์", Friday: "ศุกร์", Saturday: "เสาร์", Weekends: "สุดสัปดาห์" },
};

const GENERIC_BITS: Record<string, [string, string][]> = {
  ru: [["Last Sunday of the month", "Последнее воскресенье месяца"], ["First Tuesday of the month", "Первый вторник месяца"], ["Third Saturday of the month", "Третья суббота месяца"], ["Every ", "Каждый "], ["Weekly", "Еженедельно"], ["Monthly", "Ежемесячно"], ["When posted", "Когда объявлено"], ["Festival week", "Неделя фестиваля"], ["from ", "с "], ["Sat & Sun", "сб и вс"]],
  ja: [["Last Sunday of the month", "毎月最終日曜日"], ["First Tuesday of the month", "毎月第一火曜日"], ["Third Saturday of the month", "毎月第3土曜日"], ["Every ", "毎週"], ["Weekly", "毎週"], ["Monthly", "毎月"], ["When posted", "告知時"], ["Festival week", "フェスティバル週"], ["from ", ""], ["Sat & Sun", "土・日"]],
  ko: [["Last Sunday of the month", "매월 마지막 일요일"], ["First Tuesday of the month", "매월 첫째 화요일"], ["Third Saturday of the month", "매월 셋째 토요일"], ["Every ", "매주 "], ["Weekly", "매주"], ["Monthly", "매월"], ["When posted", "공지 시"], ["Festival week", "페스티벌 주"], ["from ", ""], ["Sat & Sun", "토·일"]],
  zh: [["Last Sunday of the month", "每月最后一个星期日"], ["First Tuesday of the month", "每月第一个星期二"], ["Third Saturday of the month", "每月第三个星期六"], ["Every ", "每周"], ["Weekly", "每周"], ["Monthly", "每月"], ["When posted", "公布时"], ["Festival week", "音乐节周"], ["from ", ""], ["Sat & Sun", "周六周日"]],
  "zh-tw": [["Last Sunday of the month", "每月最後一個星期日"], ["First Tuesday of the month", "每月第一個星期二"], ["Third Saturday of the month", "每月第三個星期六"], ["Every ", "每週"], ["Weekly", "每週"], ["Monthly", "每月"], ["When posted", "公布時"], ["Festival week", "音樂節週"], ["from ", ""], ["Sat & Sun", "週六週日"]],
  hu: [["Last Sunday of the month", "A hónap utolsó vasárnapja"], ["First Tuesday of the month", "A hónap első keddje"], ["Third Saturday of the month", "A hónap harmadik szombatja"], ["Every ", "Minden "], ["Weekly", "Hetente"], ["Monthly", "Havonta"], ["When posted", "Ha kiírják"], ["Festival week", "Fesztiválhét"], ["from ", ""], ["Sat & Sun", "szo és v"]],
  pl: [["Last Sunday of the month", "Ostatnia niedziela miesiąca"], ["First Tuesday of the month", "Pierwszy wtorek miesiąca"], ["Third Saturday of the month", "Trzecia sobota miesiąca"], ["Every ", "Każdy "], ["Weekly", "Co tydzień"], ["Monthly", "Co miesiąc"], ["When posted", "Gdy podane"], ["Festival week", "Tydzień festiwalu"], ["from ", "od "], ["Sat & Sun", "sob. i nd."]],
  cs: [["Last Sunday of the month", "Poslední neděle v měsíci"], ["First Tuesday of the month", "První úterý v měsíci"], ["Third Saturday of the month", "Třetí sobota v měsíci"], ["Every ", "Každý "], ["Weekly", "Týdně"], ["Monthly", "Měsíčně"], ["When posted", "Když je vypsáno"], ["Festival week", "Týden festivalu"], ["from ", "od "], ["Sat & Sun", "so a ne"]],
  hr: [["Last Sunday of the month", "Posljednja nedjelja u mjesecu"], ["First Tuesday of the month", "Prvi utorak u mjesecu"], ["Third Saturday of the month", "Treća subota u mjesecu"], ["Every ", "Svaki "], ["Weekly", "Tjedno"], ["Monthly", "Mjesečno"], ["When posted", "Kad je objavljeno"], ["Festival week", "Tjedan festivala"], ["from ", "od "], ["Sat & Sun", "sub i ned"]],
  sr: [["Last Sunday of the month", "Последња недеља у месецу"], ["First Tuesday of the month", "Први уторак у месецу"], ["Third Saturday of the month", "Трећа субота у месецу"], ["Every ", "Сваки "], ["Weekly", "Недељно"], ["Monthly", "Месечно"], ["When posted", "Кад је објављено"], ["Festival week", "Недеља фестивала"], ["from ", "од "], ["Sat & Sun", "суб и нед"]],
  ro: [["Last Sunday of the month", "Ultima duminică a lunii"], ["First Tuesday of the month", "Prima marți a lunii"], ["Third Saturday of the month", "A treia sâmbătă a lunii"], ["Every ", "Fiecare "], ["Weekly", "Săptămânal"], ["Monthly", "Lunar"], ["When posted", "Când e anunțat"], ["Festival week", "Săptămâna festivalului"], ["from ", "de la "], ["Sat & Sun", "sâm. și dum."]],
  id: [["Last Sunday of the month", "Minggu terakhir setiap bulan"], ["First Tuesday of the month", "Selasa pertama setiap bulan"], ["Third Saturday of the month", "Sabtu ketiga setiap bulan"], ["Every ", "Setiap "], ["Weekly", "Mingguan"], ["Monthly", "Bulanan"], ["When posted", "Saat diumumkan"], ["Festival week", "Minggu festival"], ["from ", "dari "], ["Sat & Sun", "Sab & Min"]],
  th: [["Last Sunday of the month", "วันอาทิตย์สุดท้ายของเดือน"], ["First Tuesday of the month", "วันอังคารแรกของเดือน"], ["Third Saturday of the month", "วันเสาร์ที่สามของเดือน"], ["Every ", "ทุก"], ["Weekly", "รายสัปดาห์"], ["Monthly", "รายเดือน"], ["When posted", "เมื่อประกาศ"], ["Festival week", "สัปดาห์เทศกาล"], ["from ", "ตั้งแต่ "], ["Sat & Sun", "ส. และ อา."]],
};

export function jamWhen(when: string, locale: string) {
  if (!when || locale === "en" || locale === "he") return when;
  const rows = PHRASES[locale];
  let out = when;
  if (rows) {
    for (const [en, tr] of rows) out = out.replaceAll(en, tr);
  } else {
    const days = GENERIC_DAYS[locale];
    if (days) {
      for (const [en, tr] of Object.entries(days).sort((a, b) => b[0].length - a[0].length)) {
        out = out.replaceAll(en, tr);
      }
    }
    const bits = GENERIC_BITS[locale];
    if (bits) for (const [en, tr] of bits) out = out.replaceAll(en, tr);
  }
  return festivalWhen(out, locale);
}

export function jamHoursLabel(hours: string, locale: string) {
  if (!hours || locale === "en" || locale === "he") return hours;
  return jamWhen(hours, locale);
}

export const JAM_UI: Record<string, Record<string, string>> = {
  en: {
    "jam.edit": "Edit",
    "jam.editLead": "Fix the address, hours, next date or the description. The jam keeps the correction.",
    "jam.editVenue": "Venue",
    "jam.editAddress": "Street address",
    "jam.editCity": "City",
    "jam.editHours": "From – until",
    "jam.editWhen": "When",
    "jam.editNext": "Next date",
    "jam.editBio": "About",
    "jam.editSave": "Save correction",
    "jam.editSaving": "Saving…",
    "jam.editSaved": "Saved. This jam now uses the new address, times and description.",
    "jam.editPending": "Thanks — first posts wait for a look.",
    "jam.editFail": "Could not save.",
    "jam.editCancel": "Cancel",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Session leader",
    "jam.leaderHint": "Optional. Who runs this jam.",
    "jam.leaderContact": "Contact",
    "jam.leaderContactHint": "Email or phone — shown on the jam page.",
    "jam.byInvite": "By invitation only: {email}",
    "jam.fromDjangoBooks": "From DjangoBooks",
    "jam.save": "Save jam",
    "jam.notify": "Notify me",
    "jam.follow": "Follow / join",
    "jam.whatsapp": "WhatsApp community — updates and sessions",
    "jam.djangobooksThread": "DjangoBooks thread",
    "jam.nextDates": "Next two nights",
    "jam.night1": "Next",
    "jam.night2": "The one after",
    "jam.noteTitle": "Notes on this jam",
    "jam.noteLead": "Leave a note for the room — a special guest, a one-off date, or who is sitting in.",
    "jam.noteName": "Your name",
    "jam.noteNameHint": "The name others will see",
    "jam.noteNight": "Night (optional)",
    "jam.noteNightHint": "The date this note is about. Leave empty if it is just a message.",
    "jam.noteBody": "Note",
    "jam.notePlaceholder": "Special guest this Friday: …",
    "jam.notePost": "Post note",
    "jam.notePosting": "Posting…",
    "jam.noteEmpty": "No notes yet. First one can announce a guest night.",
    "jam.noteSignin": "Sign in to leave a note on this jam.",
  },
  fr: {
    "jam.edit": "Modifier",
    "jam.editLead": "Corrigez l’adresse, les horaires ou la prochaine date. Le jam garde la correction.",
    "jam.editVenue": "Salle",
    "jam.editAddress": "Adresse",
    "jam.editCity": "Ville",
    "jam.editHours": "De – à",
    "jam.editWhen": "Quand",
    "jam.editNext": "Prochaine date",
    "jam.editBio": "Présentation",
    "jam.editSave": "Enregistrer",
    "jam.editSaving": "Enregistrement…",
    "jam.editSaved": "Enregistré. Ce jam utilise maintenant la nouvelle adresse et les horaires.",
    "jam.editPending": "Merci — les premiers ajouts attendent un regard.",
    "jam.editFail": "Impossible d’enregistrer.",
    "jam.editCancel": "Annuler",
    "concert.editLead": "Une correction ici passe sur la page du pays et en une si cette soirée y figure.",
    "concert.editSaved": "Enregistré. Les pages pays et la une utilisent maintenant cette soirée.",
    "jam.leader": "Session leader",
    "jam.leaderHint": "Facultatif. Qui mène ce jam.",
    "jam.leaderContact": "Contact",
    "jam.leaderContactHint": "E-mail ou téléphone — affiché sur la page du jam.",
    "jam.byInvite": "Sur invitation uniquement : {email}",
    "jam.fromDjangoBooks": "Depuis DjangoBooks",
    "jam.save": "Enregistrer le jam",
    "jam.notify": "Me prévenir",
    "jam.follow": "Suivre / rejoindre",
    "jam.whatsapp": "Communauté WhatsApp — dates et sessions",
    "jam.djangobooksThread": "Fil DjangoBooks",
    "jam.nextDates": "Deux prochaines soirées",
    "jam.night1": "Prochaine",
    "jam.night2": "Celle d’après",
    "jam.noteTitle": "Notes sur ce jam",
    "jam.noteLead": "Laisse une note pour la salle — un invité, une date, ou qui s’assoit.",
    "jam.noteName": "Ton nom",
    "jam.noteNameHint": "Le nom que les autres verront",
    "jam.noteNight": "Soirée (facultatif)",
    "jam.noteNightHint": "La date dont parle cette note. Vide si c’est juste un message.",
    "jam.noteBody": "Note",
    "jam.notePlaceholder": "Invité ce vendredi : …",
    "jam.notePost": "Publier la note",
    "jam.notePosting": "Publication…",
    "jam.noteEmpty": "Pas encore de note. La première peut annoncer un invité.",
    "jam.noteSignin": "Connecte-toi pour laisser une note sur ce jam.",
  },
  de: {
    "jam.edit": "Bearbeiten",
    "jam.editLead": "Adresse, Zeiten oder das nächste Datum korrigieren. Der Jam behält die Korrektur.",
    "jam.editVenue": "Ort",
    "jam.editAddress": "Adresse",
    "jam.editCity": "Stadt",
    "jam.editHours": "Von – bis",
    "jam.editWhen": "Wann",
    "jam.editNext": "Nächstes Datum",
    "jam.editBio": "Beschreibung",
    "jam.editSave": "Korrektur speichern",
    "jam.editSaving": "Speichern…",
    "jam.editSaved": "Gespeichert. Dieser Jam nutzt jetzt die neue Adresse und Zeiten.",
    "jam.editPending": "Danke — erste Beiträge warten auf einen Blick.",
    "jam.editFail": "Speichern fehlgeschlagen.",
    "jam.editCancel": "Abbrechen",
    "concert.editLead": "Eine Korrektur hier erscheint auf der Länderseite und vorn, wenn der Abend dort steht.",
    "concert.editSaved": "Gespeichert. Länderseiten und die Startseite nutzen jetzt diesen Abend.",
    "jam.leader": "Session-Leiter",
    "jam.leaderHint": "Optional. Wer leitet diesen Jam.",
    "jam.leaderContact": "Kontakt",
    "jam.leaderContactHint": "E-Mail oder Telefon — steht auf der Jam-Seite.",
    "jam.byInvite": "Nur auf Einladung: {email}",
    "jam.fromDjangoBooks": "Von DjangoBooks",
    "jam.save": "Jam speichern",
    "jam.notify": "Benachrichtige mich",
    "jam.follow": "Folgen / beitreten",
    "jam.whatsapp": "WhatsApp-Community — Termine und Sessions",
    "jam.djangobooksThread": "DjangoBooks-Thread",
    "jam.nextDates": "Nächste zwei Abende",
    "jam.night1": "Nächster",
    "jam.night2": "Der danach",
    "jam.noteTitle": "Notizen zu diesem Jam",
    "jam.noteLead": "Eine Notiz für den Raum — Gast, einzelnes Datum, oder wer sitzt ein.",
    "jam.noteName": "Dein Name",
    "jam.noteNameHint": "Der Name, den andere sehen",
    "jam.noteNight": "Abend (optional)",
    "jam.noteNightHint": "Das Datum zu dieser Notiz. Leer lassen für eine allgemeine Nachricht.",
    "jam.noteBody": "Notiz",
    "jam.notePlaceholder": "Gast diesen Freitag: …",
    "jam.notePost": "Notiz posten",
    "jam.notePosting": "Posten…",
    "jam.noteEmpty": "Noch keine Notiz. Die erste kann einen Gastabend ankündigen.",
    "jam.noteSignin": "Melde dich an, um eine Notiz zu hinterlassen.",
  },
  nl: {
    "jam.edit": "Bewerken",
    "jam.editLead": "Corrigeer adres, tijden, de volgende datum of de omschrijving. De jam onthoudt de correctie.",
    "jam.editVenue": "Podium",
    "jam.editAddress": "Adres",
    "jam.editCity": "Stad",
    "jam.editHours": "Van – tot",
    "jam.editWhen": "Wanneer",
    "jam.editNext": "Volgende datum",
    "jam.editBio": "Omschrijving",
    "jam.editSave": "Correctie bewaren",
    "jam.editSaving": "Bewaren…",
    "jam.editSaved": "Bewaard. Deze jam gebruikt nu het nieuwe adres, de tijden en de omschrijving.",
    "jam.editPending": "Bedankt — eerste posts wachten op een blik.",
    "jam.editFail": "Bewaren lukte niet.",
    "jam.editCancel": "Annuleren",
    "concert.editLead": "Een correctie hier gaat meteen naar de landpagina en de voorpagina als deze avond daar staat.",
    "concert.editSaved": "Bewaard. Landpagina’s en de voorpagina gebruiken nu deze avond.",
    "jam.leader": "Session leader",
    "jam.leaderHint": "Optioneel. Wie leidt deze jam.",
    "jam.leaderContact": "Contact",
    "jam.leaderContactHint": "E-mail of telefoon — zichtbaar op de jam-pagina.",
    "jam.byInvite": "Alleen op uitnodiging: {email}",
    "jam.fromDjangoBooks": "Van DjangoBooks",
    "jam.save": "Jam bewaren",
    "jam.notify": "Houd me op de hoogte",
    "jam.follow": "Volgen / meedoen",
    "jam.whatsapp": "WhatsApp-groep — updates en sessies",
    "jam.djangobooksThread": "DjangoBooks-draad",
    "jam.nextDates": "Volgende twee avonden",
    "jam.night1": "Volgende",
    "jam.night2": "Die daarna",
    "jam.noteTitle": "Notities bij deze jam",
    "jam.noteLead": "Laat een notitie voor de zaal — een gast, een extra datum, of wie meespeelt.",
    "jam.noteName": "Jouw naam",
    "jam.noteNameHint": "De naam die anderen zien",
    "jam.noteNight": "Avond (optioneel)",
    "jam.noteNightHint": "De datum van deze notitie. Leeg laten als het alleen een bericht is.",
    "jam.noteBody": "Notitie",
    "jam.notePlaceholder": "Speciale gast deze vrijdag: …",
    "jam.notePost": "Notitie plaatsen",
    "jam.notePosting": "Plaatsen…",
    "jam.noteEmpty": "Nog geen notities. De eerste kan een gastavond aankondigen.",
    "jam.noteSignin": "Log in om een notitie bij deze jam te laten.",
  },
  es: {
    "jam.edit": "Editar",
    "jam.editLead": "Corrige la dirección, el horario o la próxima fecha. El jam guarda la corrección.",
    "jam.editVenue": "Sala",
    "jam.editAddress": "Dirección",
    "jam.editCity": "Ciudad",
    "jam.editHours": "De – a",
    "jam.editWhen": "Cuándo",
    "jam.editNext": "Próxima fecha",
    "jam.editBio": "Descripción",
    "jam.editSave": "Guardar corrección",
    "jam.editSaving": "Guardando…",
    "jam.editSaved": "Guardado. Este jam usa ya la nueva dirección y horas.",
    "jam.editPending": "Gracias — los primeros envíos esperan una mirada.",
    "jam.editFail": "No se pudo guardar.",
    "jam.editCancel": "Cancelar",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Líder de sesión",
    "jam.leaderHint": "Opcional. Quién dirige este jam.",
    "jam.leaderContact": "Contacto",
    "jam.leaderContactHint": "Email o teléfono — visible en la página del jam.",
    "jam.byInvite": "Solo con invitación: {email}",
    "jam.fromDjangoBooks": "De DjangoBooks",
    "jam.save": "Guardar jam",
    "jam.notify": "Avísame",
    "jam.follow": "Seguir / unirse",
    "jam.whatsapp": "Comunidad WhatsApp — fechas y sesiones",
    "jam.djangobooksThread": "Hilo de DjangoBooks",
  },
  pt: {
    "jam.edit": "Editar",
    "jam.editLead": "Corrige a morada, o horário ou a próxima data. O jam guarda a correção.",
    "jam.editVenue": "Sala",
    "jam.editAddress": "Morada",
    "jam.editCity": "Cidade",
    "jam.editHours": "Das – às",
    "jam.editWhen": "Quando",
    "jam.editNext": "Próxima data",
    "jam.editBio": "Descrição",
    "jam.editSave": "Guardar correção",
    "jam.editSaving": "A guardar…",
    "jam.editSaved": "Guardado. Este jam usa agora a nova morada e horários.",
    "jam.editPending": "Obrigado — as primeiras publicações esperam uma olhada.",
    "jam.editFail": "Não foi possível guardar.",
    "jam.editCancel": "Cancelar",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Líder da sessão",
    "jam.leaderHint": "Opcional. Quem conduz este jam.",
    "jam.leaderContact": "Contacto",
    "jam.leaderContactHint": "Email ou telefone — visível na página do jam.",
    "jam.byInvite": "Só por convite: {email}",
    "jam.fromDjangoBooks": "Do DjangoBooks",
    "jam.save": "Guardar jam",
    "jam.notify": "Avisar-me",
    "jam.follow": "Seguir / juntar-me",
    "jam.whatsapp": "Comunidade WhatsApp — datas e sessões",
    "jam.djangobooksThread": "Tópico DjangoBooks",
  },
  it: {
    "jam.edit": "Modifica",
    "jam.editLead": "Correggi indirizzo, orari o la prossima data. Il jam tiene la correzione.",
    "jam.editVenue": "Locale",
    "jam.editAddress": "Indirizzo",
    "jam.editCity": "Città",
    "jam.editHours": "Dalle – alle",
    "jam.editWhen": "Quando",
    "jam.editNext": "Prossima data",
    "jam.editBio": "Descrizione",
    "jam.editSave": "Salva correzione",
    "jam.editSaving": "Salvataggio…",
    "jam.editSaved": "Salvato. Questo jam usa ora il nuovo indirizzo e gli orari.",
    "jam.editPending": "Grazie — i primi post aspettano uno sguardo.",
    "jam.editFail": "Salvataggio non riuscito.",
    "jam.editCancel": "Annulla",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Session leader",
    "jam.leaderHint": "Facoltativo. Chi conduce questo jam.",
    "jam.leaderContact": "Contatto",
    "jam.leaderContactHint": "Email o telefono — visibile sulla pagina del jam.",
    "jam.byInvite": "Solo su invito: {email}",
    "jam.fromDjangoBooks": "Da DjangoBooks",
    "jam.save": "Salva jam",
    "jam.notify": "Avvisami",
    "jam.follow": "Segui / unisciti",
    "jam.whatsapp": "Community WhatsApp — date e sessioni",
    "jam.djangobooksThread": "Thread DjangoBooks",
  },
  ru: {
    "jam.edit": "Править",
    "jam.editLead": "Исправьте адрес, время или ближайшую дату. Джем сохранит правку.",
    "jam.editVenue": "Площадка",
    "jam.editAddress": "Адрес",
    "jam.editCity": "Город",
    "jam.editHours": "С – до",
    "jam.editWhen": "Когда",
    "jam.editNext": "Ближайшая дата",
    "jam.editBio": "Описание",
    "jam.editSave": "Сохранить",
    "jam.editSaving": "Сохранение…",
    "jam.editSaved": "Сохранено. Этот джем теперь с новым адресом и временем.",
    "jam.editPending": "Спасибо — первые записи ждут просмотра.",
    "jam.editFail": "Не удалось сохранить.",
    "jam.editCancel": "Отмена",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Лидер сессии",
    "jam.leaderHint": "Необязательно. Кто ведёт этот джем.",
    "jam.leaderContact": "Контакт",
    "jam.leaderContactHint": "Почта или телефон — на странице джема.",
    "jam.byInvite": "Только по приглашению: {email}",
    "jam.fromDjangoBooks": "С DjangoBooks",
    "jam.save": "Сохранить джем",
    "jam.notify": "Напомнить",
    "jam.follow": "Следить / присоединиться",
    "jam.whatsapp": "Сообщество WhatsApp — даты и сессии",
    "jam.djangobooksThread": "Тема DjangoBooks",
  },
  ja: {
    "jam.edit": "編集",
    "jam.editLead": "住所・時間・次回を直すと、このジャムに残ります。",
    "jam.editVenue": "会場",
    "jam.editAddress": "住所",
    "jam.editCity": "都市",
    "jam.editHours": "開始–終了",
    "jam.editWhen": "いつ",
    "jam.editNext": "次回",
    "jam.editBio": "説明",
    "jam.editSave": "保存",
    "jam.editSaving": "保存中…",
    "jam.editSaved": "保存しました。新しい住所と時間が使われます。",
    "jam.editPending": "ありがとうございます。最初の投稿は確認待ちです。",
    "jam.editFail": "保存できませんでした。",
    "jam.editCancel": "キャンセル",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "セッションリーダー",
    "jam.leaderHint": "任意。このジャムの進行役。",
    "jam.leaderContact": "連絡先",
    "jam.leaderContactHint": "メールまたは電話 — ジャムのページに表示。",
    "jam.byInvite": "招待制：{email}",
    "jam.fromDjangoBooks": "DjangoBooks より",
    "jam.save": "ジャムを保存",
    "jam.notify": "通知する",
    "jam.follow": "フォロー / 参加",
    "jam.whatsapp": "WhatsAppコミュニティ — 日程とセッション",
    "jam.djangobooksThread": "DjangoBooksスレッド",
  },
  ko: {
    "jam.edit": "수정",
    "jam.editLead": "주소, 시간, 다음 날짜를 고치면 이 잼에 남습니다.",
    "jam.editVenue": "장소",
    "jam.editAddress": "주소",
    "jam.editCity": "도시",
    "jam.editHours": "시작–끝",
    "jam.editWhen": "언제",
    "jam.editNext": "다음 날짜",
    "jam.editBio": "설명",
    "jam.editSave": "저장",
    "jam.editSaving": "저장 중…",
    "jam.editSaved": "저장됨. 이 잼이 새 주소와 시간을 씁니다.",
    "jam.editPending": "감사합니다. 첫 글은 확인을 기다립니다.",
    "jam.editFail": "저장하지 못했습니다.",
    "jam.editCancel": "취소",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "세션 리더",
    "jam.leaderHint": "선택. 이 잼을 이끄는 사람.",
    "jam.leaderContact": "연락처",
    "jam.leaderContactHint": "이메일 또는 전화 — 잼 페이지에 표시.",
    "jam.byInvite": "초대만: {email}",
    "jam.fromDjangoBooks": "DjangoBooks에서",
    "jam.save": "잼 저장",
    "jam.notify": "알림 받기",
    "jam.follow": "팔로우 / 참여",
    "jam.whatsapp": "WhatsApp 커뮤니티 — 일정과 세션",
    "jam.djangobooksThread": "DjangoBooks 스레드",
  },
  zh: {
    "jam.edit": "编辑",
    "jam.editLead": "改正地址、时间或下一场日期，此即兴会保留更正。",
    "jam.editVenue": "场地",
    "jam.editAddress": "地址",
    "jam.editCity": "城市",
    "jam.editHours": "起–止",
    "jam.editWhen": "何时",
    "jam.editNext": "下一场",
    "jam.editBio": "简介",
    "jam.editSave": "保存更正",
    "jam.editSaving": "保存中…",
    "jam.editSaved": "已保存。此即兴会现用新地址和时间。",
    "jam.editPending": "谢谢——首次发布需审核。",
    "jam.editFail": "无法保存。",
    "jam.editCancel": "取消",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "场次主持",
    "jam.leaderHint": "选填。谁主持这场即兴。",
    "jam.leaderContact": "联系方式",
    "jam.leaderContactHint": "邮箱或电话 — 显示在即兴页面。",
    "jam.byInvite": "仅凭邀请：{email}",
    "jam.fromDjangoBooks": "来自 DjangoBooks",
    "jam.save": "收藏即兴",
    "jam.notify": "提醒我",
    "jam.follow": "关注 / 加入",
    "jam.whatsapp": "WhatsApp 社群 — 日期与场次",
    "jam.djangobooksThread": "DjangoBooks 帖子",
  },
  "zh-tw": {
    "jam.edit": "編輯",
    "jam.editLead": "改正地址、時間或下一場日期，此即興會保留更正。",
    "jam.editVenue": "場地",
    "jam.editAddress": "地址",
    "jam.editCity": "城市",
    "jam.editHours": "起–迄",
    "jam.editWhen": "何時",
    "jam.editNext": "下一場",
    "jam.editBio": "簡介",
    "jam.editSave": "儲存更正",
    "jam.editSaving": "儲存中…",
    "jam.editSaved": "已儲存。此即興會現用新地址和時間。",
    "jam.editPending": "謝謝——首次發布需審核。",
    "jam.editFail": "無法儲存。",
    "jam.editCancel": "取消",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "場次主持",
    "jam.leaderHint": "選填。誰主持這場即興。",
    "jam.leaderContact": "聯絡方式",
    "jam.leaderContactHint": "信箱或電話 — 顯示在即興頁面。",
    "jam.byInvite": "僅憑邀請：{email}",
    "jam.fromDjangoBooks": "來自 DjangoBooks",
    "jam.save": "收藏即興",
    "jam.notify": "通知我",
    "jam.follow": "追蹤 / 加入",
    "jam.whatsapp": "WhatsApp 社群 — 日期與場次",
    "jam.djangobooksThread": "DjangoBooks 討論串",
  },
  id: {
    "jam.edit": "Sunting",
    "jam.editLead": "Perbaiki alamat, jam, atau tanggal berikutnya. Jam ini menyimpan koreksi.",
    "jam.editVenue": "Tempat",
    "jam.editAddress": "Alamat",
    "jam.editCity": "Kota",
    "jam.editHours": "Dari – sampai",
    "jam.editWhen": "Kapan",
    "jam.editNext": "Tanggal berikutnya",
    "jam.editBio": "Deskripsi",
    "jam.editSave": "Simpan koreksi",
    "jam.editSaving": "Menyimpan…",
    "jam.editSaved": "Tersimpan. Jam ini memakai alamat dan jam baru.",
    "jam.editPending": "Terima kasih — kiriman pertama menunggu tinjauan.",
    "jam.editFail": "Tidak bisa menyimpan.",
    "jam.editCancel": "Batal",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Pemimpin sesi",
    "jam.leaderHint": "Opsional. Siapa yang memimpin jam ini.",
    "jam.leaderContact": "Kontak",
    "jam.leaderContactHint": "Email atau telepon — tampil di halaman jam.",
    "jam.byInvite": "Hanya dengan undangan: {email}",
    "jam.fromDjangoBooks": "Dari DjangoBooks",
    "jam.save": "Simpan jam",
    "jam.notify": "Kabari saya",
    "jam.follow": "Ikuti / gabung",
    "jam.whatsapp": "Komunitas WhatsApp — jadwal dan sesi",
    "jam.djangobooksThread": "Utas DjangoBooks",
  },
  th: {
    "jam.edit": "แก้ไข",
    "jam.editLead": "แก้ที่อยู่ เวลา หรือวันถัดไป แจมนี้จะจำการแก้",
    "jam.editVenue": "สถานที่",
    "jam.editAddress": "ที่อยู่",
    "jam.editCity": "เมือง",
    "jam.editHours": "จาก – ถึง",
    "jam.editWhen": "เมื่อ",
    "jam.editNext": "วันถัดไป",
    "jam.editBio": "คำอธิบาย",
    "jam.editSave": "บันทึกการแก้",
    "jam.editSaving": "กำลังบันทึก…",
    "jam.editSaved": "บันทึกแล้ว แจมนี้ใช้ที่อยู่และเวลาใหม่",
    "jam.editPending": "ขอบคุณ — โพสต์แรกรอตรวจ",
    "jam.editFail": "บันทึกไม่ได้",
    "jam.editCancel": "ยกเลิก",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "ผู้นำเซสชัน",
    "jam.leaderHint": "ไม่บังคับ ใครดูแลแจมนี้",
    "jam.leaderContact": "ติดต่อ",
    "jam.leaderContactHint": "อีเมลหรือโทรศัพท์ — แสดงบนหน้าแจม",
    "jam.byInvite": "เฉพาะผู้ได้รับเชิญ: {email}",
    "jam.fromDjangoBooks": "จาก DjangoBooks",
    "jam.save": "บันทึกแจม",
    "jam.notify": "แจ้งเตือนฉัน",
    "jam.follow": "ติดตาม / เข้าร่วม",
    "jam.whatsapp": "ชุมชน WhatsApp — วันและเซสชัน",
    "jam.djangobooksThread": "กระทู้ DjangoBooks",
  },
  hu: {
    "jam.edit": "Szerkesztés",
    "jam.editLead": "Javítsd a címet, az időt vagy a következő dátumot. A jam megjegyzi.",
    "jam.editVenue": "Helyszín",
    "jam.editAddress": "Cím",
    "jam.editCity": "Város",
    "jam.editHours": "Tól – ig",
    "jam.editWhen": "Mikor",
    "jam.editNext": "Következő dátum",
    "jam.editBio": "Leírás",
    "jam.editSave": "Javítás mentése",
    "jam.editSaving": "Mentés…",
    "jam.editSaved": "Mentve. A jam most az új címet és időket használja.",
    "jam.editPending": "Köszi — az első posztok várnak egy ránézésre.",
    "jam.editFail": "Nem sikerült menteni.",
    "jam.editCancel": "Mégse",
    "concert.editLead": "A javítás azonnal az országoldalon és a címlapon jelenik meg, ha ez az este ott szerepel.",
    "concert.editSaved": "Mentve. Az országoldalak és a címlap most ezt az estét használja.",
    "jam.leader": "Session leader",
    "jam.leaderHint": "Opcionális. Ki vezeti ezt a jamet.",
    "jam.leaderContact": "Kapcsolat",
    "jam.leaderContactHint": "Email vagy telefon — a jam oldalán látszik.",
    "jam.byInvite": "Csak meghívásra: {email}",
    "jam.fromDjangoBooks": "DjangoBooks-ról",
    "jam.save": "Jam mentése",
    "jam.notify": "Értesíts",
    "jam.follow": "Követés / csatlakozás",
    "jam.whatsapp": "WhatsApp-közösség — dátumok és sessionök",
    "jam.djangobooksThread": "DjangoBooks-szál",
  },
  pl: {
    "jam.edit": "Edytuj",
    "jam.editLead": "Popraw adres, godziny lub następną datę. Jam zapamięta poprawkę.",
    "jam.editVenue": "Miejsce",
    "jam.editAddress": "Adres",
    "jam.editCity": "Miasto",
    "jam.editHours": "Od – do",
    "jam.editWhen": "Kiedy",
    "jam.editNext": "Następna data",
    "jam.editBio": "Opis",
    "jam.editSave": "Zapisz poprawkę",
    "jam.editSaving": "Zapisywanie…",
    "jam.editSaved": "Zapisano. Ten jam używa teraz nowego adresu i godzin.",
    "jam.editPending": "Dzięki — pierwsze wpisy czekają na spojrzenie.",
    "jam.editFail": "Nie udało się zapisać.",
    "jam.editCancel": "Anuluj",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Lider sesji",
    "jam.leaderHint": "Opcjonalnie. Kto prowadzi ten jam.",
    "jam.leaderContact": "Kontakt",
    "jam.leaderContactHint": "Email lub telefon — na stronie jamu.",
    "jam.byInvite": "Tylko na zaproszenie: {email}",
    "jam.fromDjangoBooks": "Z DjangoBooks",
    "jam.save": "Zapisz jam",
    "jam.notify": "Powiadom mnie",
    "jam.follow": "Obserwuj / dołącz",
    "jam.whatsapp": "Społeczność WhatsApp — daty i sesje",
    "jam.djangobooksThread": "Wątek DjangoBooks",
  },
  cs: {
    "jam.edit": "Upravit",
    "jam.editLead": "Oprav adresu, časy nebo příští datum. Jam si opravu zapamatuje.",
    "jam.editVenue": "Místo",
    "jam.editAddress": "Adresa",
    "jam.editCity": "Město",
    "jam.editHours": "Od – do",
    "jam.editWhen": "Kdy",
    "jam.editNext": "Příští datum",
    "jam.editBio": "Popis",
    "jam.editSave": "Uložit opravu",
    "jam.editSaving": "Ukládání…",
    "jam.editSaved": "Uloženo. Tento jam teď používá novou adresu a časy.",
    "jam.editPending": "Díky — první příspěvky čekají na pohled.",
    "jam.editFail": "Uložení selhalo.",
    "jam.editCancel": "Zrušit",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Vedoucí session",
    "jam.leaderHint": "Volitelné. Kdo tento jam vede.",
    "jam.leaderContact": "Kontakt",
    "jam.leaderContactHint": "Email nebo telefon — na stránce jamu.",
    "jam.byInvite": "Pouze na pozvání: {email}",
    "jam.fromDjangoBooks": "Z DjangoBooks",
    "jam.save": "Uložit jam",
    "jam.notify": "Upozornit mě",
    "jam.follow": "Sledovat / připojit se",
    "jam.whatsapp": "WhatsApp komunita — termíny a session",
    "jam.djangobooksThread": "Vlákno DjangoBooks",
  },
  hr: {
    "jam.edit": "Uredi",
    "jam.editLead": "Ispravi adresu, sate ili sljedeći datum. Jam pamti ispravak.",
    "jam.editVenue": "Mjesto",
    "jam.editAddress": "Adresa",
    "jam.editCity": "Grad",
    "jam.editHours": "Od – do",
    "jam.editWhen": "Kada",
    "jam.editNext": "Sljedeći datum",
    "jam.editBio": "Opis",
    "jam.editSave": "Spremi ispravak",
    "jam.editSaving": "Spremanje…",
    "jam.editSaved": "Spremljeno. Ovaj jam sada koristi novu adresu i sate.",
    "jam.editPending": "Hvala — prvi unosi čekaju pogled.",
    "jam.editFail": "Spremanje nije uspjelo.",
    "jam.editCancel": "Odustani",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Voditelj sessiona",
    "jam.leaderHint": "Neobavezno. Tko vodi ovaj jam.",
    "jam.leaderContact": "Kontakt",
    "jam.leaderContactHint": "Email ili telefon — na stranici jama.",
    "jam.byInvite": "Samo na poziv: {email}",
    "jam.fromDjangoBooks": "S DjangoBooksa",
    "jam.save": "Spremi jam",
    "jam.notify": "Obavijesti me",
    "jam.follow": "Prati / pridruži se",
    "jam.whatsapp": "WhatsApp zajednica — datumi i sessioni",
    "jam.djangobooksThread": "DjangoBooks nit",
  },
  sr: {
    "jam.edit": "Уреди",
    "jam.editLead": "Исправи адресу, сате или следећи датум. Џем памти исправку.",
    "jam.editVenue": "Место",
    "jam.editAddress": "Адреса",
    "jam.editCity": "Град",
    "jam.editHours": "Од – до",
    "jam.editWhen": "Када",
    "jam.editNext": "Следећи датум",
    "jam.editBio": "Опис",
    "jam.editSave": "Сачувај исправку",
    "jam.editSaving": "Чување…",
    "jam.editSaved": "Сачувано. Овај џем сада користи нову адресу и сате.",
    "jam.editPending": "Хвала — први уноси чекају поглед.",
    "jam.editFail": "Чување није успело.",
    "jam.editCancel": "Одустани",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Водитељ сесије",
    "jam.leaderHint": "Опционо. Ко води овај џем.",
    "jam.leaderContact": "Контакт",
    "jam.leaderContactHint": "Имејл или телефон — на страници џема.",
    "jam.byInvite": "Само на позив: {email}",
    "jam.fromDjangoBooks": "Са DjangoBooks-а",
    "jam.save": "Сачувај џем",
    "jam.notify": "Обавивести ме",
    "jam.follow": "Прати / придружи се",
    "jam.whatsapp": "WhatsApp заједница — датуми и сесије",
    "jam.djangobooksThread": "DjangoBooks тема",
  },
  ro: {
    "jam.edit": "Editează",
    "jam.editLead": "Corectează adresa, orele sau următoarea dată. Jam-ul păstrează corecția.",
    "jam.editVenue": "Locație",
    "jam.editAddress": "Adresă",
    "jam.editCity": "Oraș",
    "jam.editHours": "De la – până",
    "jam.editWhen": "Când",
    "jam.editNext": "Următoarea dată",
    "jam.editBio": "Descriere",
    "jam.editSave": "Salvează corecția",
    "jam.editSaving": "Se salvează…",
    "jam.editSaved": "Salvat. Acest jam folosește acum noua adresă și orele.",
    "jam.editPending": "Mulțumim — primele postări așteaptă o privire.",
    "jam.editFail": "Nu s-a putut salva.",
    "jam.editCancel": "Anulează",
    "concert.editLead": "A correction here goes on the country page and the front of the hub if this night is listed there.",
    "concert.editSaved": "Saved. Country pages and the front of the hub now use this night.",
    "jam.leader": "Lider de sesiune",
    "jam.leaderHint": "Opțional. Cine conduce acest jam.",
    "jam.leaderContact": "Contact",
    "jam.leaderContactHint": "Email sau telefon — pe pagina jam-ului.",
    "jam.byInvite": "Doar pe invitație: {email}",
    "jam.fromDjangoBooks": "De pe DjangoBooks",
    "jam.save": "Salvează jam-ul",
    "jam.notify": "Anunță-mă",
    "jam.follow": "Urmărește / alătură-te",
    "jam.whatsapp": "Comunitate WhatsApp — date și sesiuni",
    "jam.djangobooksThread": "Fir DjangoBooks",
  },
};
