export type JamKind = "regular" | "meetup";
export type JamScene = "gypsy" | "jazz";

export type Jam = {
  slug: string;
  name: string;
  city: string;
  country: string;
  venue: string;
  address: string;
  hours: string;
  when: string;
  nextStartsAt: string;
  bio: string;
  relatedSlugs: string[];
  kind?: JamKind;
  scene?: JamScene;
  site?: string;
};

export function isStandingGypsyJam(jam: Jam) {
  if (jam.kind === "meetup") return false;
  return (jam.scene ?? "gypsy") === "gypsy";
}

/** No posted Hot Club jam, but rooms exist to write to. */
export function isThinGypsyScene(jams: Jam[], venueCount: number) {
  return !jams.some(isStandingGypsyJam) && venueCount > 0;
}

export function jamPlace(jam: Jam) {
  const bits = [jam.venue, jam.address, jam.city].filter(Boolean);
  const out: string[] = [];
  for (const bit of bits) {
    if (!out.some((row) => row.toLowerCase().includes(bit.toLowerCase()) || bit.toLowerCase().includes(row.toLowerCase()))) {
      out.push(bit);
    }
  }
  return out.join(", ");
}

export function jamHours(jam: Jam) {
  return jam.hours?.trim() || "";
}

export function jamMapsUrl(jam: Jam) {
  const q = [jam.venue, jam.address, jam.city, jam.country].filter(Boolean).join(", ");
  if (!q.trim()) return "";
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

const CITY_TZ: Record<string, string> = {
  melbourne: "Australia/Melbourne",
  sydney: "Australia/Sydney",
  perth: "Australia/Perth",
  brisbane: "Australia/Brisbane",
  auckland: "Pacific/Auckland",
  wellington: "Pacific/Auckland",
  "new york": "America/New_York",
  pittsburgh: "America/New_York",
  missoula: "America/Denver",
  lockport: "America/Chicago",
  arvada: "America/Denver",
  brooklyn: "America/New_York",
  boston: "America/New_York",
  washington: "America/New_York",
  "washington dc": "America/New_York",
  "takoma park": "America/New_York",
  bethesda: "America/New_York",
  chicago: "America/Chicago",
  austin: "America/Chicago",
  "san francisco": "America/Los_Angeles",
  oakland: "America/Los_Angeles",
  seattle: "America/Los_Angeles",
  "los angeles": "America/Los_Angeles",
  vancouver: "America/Vancouver",
  montreal: "America/Toronto",
  toronto: "America/Toronto",
  jakarta: "Asia/Jakarta",
  sanur: "Asia/Makassar",
  bali: "Asia/Makassar",
  tokyo: "Asia/Tokyo",
  osaka: "Asia/Tokyo",
  singapore: "Asia/Singapore",
  bangkok: "Asia/Bangkok",
  "ho chi minh city": "Asia/Ho_Chi_Minh",
  hanoi: "Asia/Ho_Chi_Minh",
  "phnom penh": "Asia/Phnom_Penh",
  manila: "Asia/Manila",
  "kuala lumpur": "Asia/Kuala_Lumpur",
  taipei: "Asia/Taipei",
  shanghai: "Asia/Shanghai",
  beijing: "Asia/Shanghai",
  mumbai: "Asia/Kolkata",
  delhi: "Asia/Kolkata",
  "new delhi": "Asia/Kolkata",
  "cape town": "Africa/Johannesburg",
  johannesburg: "Africa/Johannesburg",
  casablanca: "Africa/Casablanca",
  marrakech: "Africa/Casablanca",
  reykjavik: "Atlantic/Reykjavik",
  malmö: "Europe/Stockholm",
  malmo: "Europe/Stockholm",
  basel: "Europe/Zurich",
  copenhagen: "Europe/Copenhagen",
  "the hague": "Europe/Amsterdam",
  "den haag": "Europe/Amsterdam",
  ubbergen: "Europe/Amsterdam",
  nijmegen: "Europe/Amsterdam",
  "tel aviv": "Asia/Jerusalem",
  jerusalem: "Asia/Jerusalem",
};

const COUNTRY_TZ: Record<string, string> = {
  "United Kingdom": "Europe/London",
  Ireland: "Europe/Dublin",
  France: "Europe/Paris",
  Belgium: "Europe/Brussels",
  Netherlands: "Europe/Amsterdam",
  Germany: "Europe/Berlin",
  Spain: "Europe/Madrid",
  Italy: "Europe/Rome",
  Portugal: "Europe/Lisbon",
  Switzerland: "Europe/Zurich",
  Austria: "Europe/Vienna",
  Czechia: "Europe/Prague",
  Hungary: "Europe/Budapest",
  Poland: "Europe/Warsaw",
  Serbia: "Europe/Belgrade",
  Norway: "Europe/Oslo",
  Sweden: "Europe/Stockholm",
  Denmark: "Europe/Copenhagen",
  Iceland: "Atlantic/Reykjavik",
  Israel: "Asia/Jerusalem",
  Russia: "Europe/Moscow",
  Japan: "Asia/Tokyo",
  China: "Asia/Shanghai",
  Taiwan: "Asia/Taipei",
  Thailand: "Asia/Bangkok",
  Vietnam: "Asia/Ho_Chi_Minh",
  Cambodia: "Asia/Phnom_Penh",
  Philippines: "Asia/Manila",
  Malaysia: "Asia/Kuala_Lumpur",
  Singapore: "Asia/Singapore",
  Indonesia: "Asia/Jakarta",
  India: "Asia/Kolkata",
  Australia: "Australia/Sydney",
  "New Zealand": "Pacific/Auckland",
  Morocco: "Africa/Casablanca",
  "South Africa": "Africa/Johannesburg",
  Argentina: "America/Argentina/Buenos_Aires",
  Brazil: "America/Sao_Paulo",
  Canada: "America/Toronto",
  "United States of America": "America/New_York",
  "United States": "America/New_York",
};

export function jamTimeZone(jam: { country: string; city: string }) {
  const city = jam.city.trim().toLowerCase();
  if (city && CITY_TZ[city]) return CITY_TZ[city];
  return COUNTRY_TZ[jam.country] ?? "UTC";
}

function ymdInTimeZone(date: Date, timeZone: string) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

function addCalendarDays(ymd: string, days: number) {
  const [year, month, day] = ymd.split("-").map(Number);
  const next = new Date(Date.UTC(year, month - 1, day + days));
  return next.toISOString().slice(0, 10);
}

/** Split by the jam's own local calendar — not the visitor's clock. */
export function splitUpcomingJams(jams: Jam[], now = new Date()) {
  const today: Jam[] = [];
  const week: Jam[] = [];
  const later: Jam[] = [];
  for (const jam of jams) {
    const tz = jamTimeZone(jam);
    const jamDay = ymdInTimeZone(new Date(jam.nextStartsAt), tz);
    const todayDay = ymdInTimeZone(now, tz);
    if (Number.isNaN(new Date(jam.nextStartsAt).getTime())) continue;
    if (jamDay === todayDay) today.push(jam);
    else if (jamDay > todayDay && jamDay <= addCalendarDays(todayDay, 7)) week.push(jam);
    else later.push(jam);
  }
  return { today, week, later };
}

export function formatJamNext(jam: Jam) {
  const date = new Date(jam.nextStartsAt);
  if (Number.isNaN(date.getTime())) return jam.nextStartsAt;
  const parts = new Intl.DateTimeFormat("en-GB", {
    timeZone: jamTimeZone(jam),
    weekday: "short",
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).formatToParts(date);
  const get = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((part) => part.type === type)?.value ?? "";
  const hour = get("hour").padStart(2, "0");
  const minute = get("minute").padStart(2, "0");
  return `${get("weekday")} ${get("day")} ${get("month")} ${get("year")} · ${hour}:${minute}`;
}

export const JAMS: Jam[] = [
  {
    slug: "melbourne-hot-djams",
    name: "Melbourne Hot Djams",
    city: "Melbourne",
    country: "Australia",
    venue: "Caulfield Park Rotunda",
    address: "Caulfield Park, Melbourne",
    hours: "from 13:00",
    when: "First Sunday",
    nextStartsAt: "2026-09-06T03:00:00.000Z",
    bio: "First-Sunday Melbourne Hot Djams at the Caulfield Park rotunda — the long amateur jam. Facebook and the Melbourne Hot Club page keep the chairs filled.",
    relatedSlugs: [],
    site: "https://www.melbournehotclub.com/",
  },
  {
    slug: "chope-des-puces",
    name: "La Chope des Puces",
    city: "Saint-Ouen",
    country: "France",
    venue: "La Chope des Puces",
    address: "122 rue des Rosiers, 93400 Saint-Ouen",
    hours: "Sat & Sun 14:00–19:00",
    when: "Weekends",
    nextStartsAt: "2026-08-23T12:00:00.000Z",
    bio: "The flea-market room in Saint-Ouen where manouche guitar still happens in daylight. Saturday and Sunday afternoons. Steven Reinhardt is a regular chair; amateurs sit in, the regulars hold the pompe. Facebook @lachopedespuces.",
    relatedSlugs: ["steven-reinhardt", "angelo-debarre", "ninine-garcia"],
  },
  {
    slug: "paris-green-linnet",
    name: "The Green Linnet",
    city: "Paris",
    country: "France",
    venue: "The Green Linnet",
    address: "8 avenue Victoria, 75004 Paris",
    hours: "19:00–23:00",
    when: "Every Sunday",
    nextStartsAt: "2026-08-23T17:00:00.000Z",
    bio: "Sunday gypsy jazz jam in the 4th, full acoustic. Running about fifteen years — the second-oldest standing Paris manouche jam after La Chope des Puces. Michel Mercier holds the room. Facebook @TheGreenLinnet.",
    relatedSlugs: [],
    site: "https://www.facebook.com/TheGreenLinnet/",
  },
  {
    slug: "samois-berceau",
    name: "Île du Berceau campsite sessions",
    city: "Samois-sur-Seine",
    country: "France",
    venue: "Île du Berceau",
    address: "Île du Berceau, 77920 Samois-sur-Seine",
    hours: "from 18:00, late",
    when: "Festival week, late June",
    nextStartsAt: "2027-06-24T16:00:00.000Z",
    bio: "After the official stages, the island and the campsites are the real school. Open jams through Festival Django Reinhardt week.",
    relatedSlugs: ["daniel-gueli", "yorgui-loeffler", "benji-winterstein"],
  },
  {
    slug: "paris-manouche-jam",
    name: "Paris Manouche Jam",
    city: "Paris",
    country: "France",
    venue: "Caveau circuit",
    address: "Ask the organisers for this week’s caveau",
    hours: "from 21:30",
    when: "Weekly",
    nextStartsAt: "2026-08-26T19:30:00.000Z",
    bio: "A weekday open jam on the Paris caveau circuit. Bring a Selmer, sit behind the pompe, learn the language the way the city still teaches it.",
    relatedSlugs: ["adrien-moignard", "rocky-gresset"],
  },
  {
    slug: "amsterdam-circle-jam",
    name: "Amsterdam Circle Jam",
    city: "Amsterdam",
    country: "Netherlands",
    venue: "Café de Pels",
    address: "Huidenstraat 25, 1016 ER Amsterdam",
    hours: "from 19:00",
    when: "Monthly",
    nextStartsAt: "2026-09-03T17:00:00.000Z",
    bio: "Daniel Gueli's house jam. Channel players, Rosenberg-family chairs and whoever is in town — open to amateurs who can keep time.",
    relatedSlugs: ["daniel-gueli", "marcia-bamberg", "ronald-weel"],
  },
  {
    slug: "helmond-sinti-jam",
    name: "Helmond Sinti Jam",
    city: "Helmond",
    country: "Netherlands",
    venue: "Local hall / family rooms",
    address: "Helmond — room announced with the date",
    hours: "from 20:00",
    when: "Monthly",
    nextStartsAt: "2026-09-19T18:00:00.000Z",
    bio: "Dutch Sinti community jam around Helmond. The Rosenberg orbit's home ground — listen first, then sit in.",
    relatedSlugs: ["stochelo-rosenberg", "mozes-rosenberg", "nousche-rosenberg"],
  },
  {
    slug: "berlin-hot-club-jam",
    name: "Berlin Hot Club Jam",
    city: "Berlin",
    country: "Germany",
    venue: "A-Trane",
    address: "Pestalozzistraße 105, 10625 Berlin",
    hours: "from 22:00",
    when: "Weekly",
    nextStartsAt: "2026-08-25T20:00:00.000Z",
    bio: "Berlin's open gypsy jazz jam at A-Trane. German Hot Club players and visiting leads — Joscho Stephan's city is a regular stop. Kreuzberg’s unterRock night is a separate jam.",
    relatedSlugs: ["joscho-stephan", "gismo-graf"],
  },
  {
    slug: "london-gypsy-jazz-jam",
    name: "London Gypsy Jazz Jam",
    city: "London",
    country: "United Kingdom",
    venue: "Hot Club rooms",
    address: "London — room posted with each date",
    hours: "from 20:30",
    when: "Weekly",
    nextStartsAt: "2026-08-24T19:30:00.000Z",
    bio: "The capital's amateur night. British pompe, visiting Dutch and French chairs, and the players who fill London Gypsy Jazz Festival week.",
    relatedSlugs: ["dave-kelbie", "robin-nolan"],
  },
  {
    slug: "django-in-june-jams",
    name: "Django in June night jams",
    city: "Northampton",
    country: "United States of America",
    venue: "Smith College campus",
    address: "Smith College, Northampton, MA 01063",
    hours: "after classes, from 21:00",
    when: "Festival week, June",
    nextStartsAt: "2027-06-07T23:00:00.000Z",
    bio: "Workshops by day, jams by night. The American amateur week — open to every student on the grounds.",
    relatedSlugs: ["stephane-wrembel", "denis-chang", "dario-napoli"],
  },
  {
    slug: "nyc-hot-club-jam",
    name: "New York Hot Club Jam",
    city: "New York",
    country: "United States of America",
    venue: "Birdland / Brooklyn rooms",
    address: "315 W 44th St, New York, NY 10036 (Birdland)",
    hours: "from 21:30",
    when: "Weekly",
    nextStartsAt: "2026-08-27T23:30:00.000Z",
    bio: "The city's standing gypsy jazz jam. Thursday is Bistro So in Williamsburg (Alex Simon); Sunday family night is Retro in Greenpoint. Birdland still hosts festival week.",
    relatedSlugs: ["stephane-wrembel", "frank-vignola"],
  },
  {
    slug: "midwest-swing-jam",
    name: "Midwest Gypsy Swing Jam",
    city: "Madison",
    country: "United States of America",
    venue: "William G. Lunney Lake Farm County Park",
    address: "4330 Libby Road, Madison, WI 53711",
    hours: "after the concert — Super Djam 21:00, campfire from 21:15",
    when: "11–12 September 2026",
    nextStartsAt: "2026-09-12T02:00:00.000Z",
    bio: "Open jam at Midwest Django Fest. Friday and Saturday Super Djam on stage, then the campfire. Dario Napoli, Gonzalo Bergara, Alfonso Ponticelli, Harmonious Wail and whoever brought a guitar.",
    relatedSlugs: ["dario-napoli", "gonzalo-bergara", "alfonso-ponticelli"],
  },
  {
    slug: "django-a-gogo-jam",
    name: "Django à Gogo camp jam",
    city: "New York",
    country: "United States of America",
    venue: "Guitar camp",
    address: "Posted with the camp each year",
    hours: "after the concert night, late",
    when: "Spring camp",
    nextStartsAt: "2027-03-13T00:00:00.000Z",
    bio: "After Wrembel's concert night, the camp stays up. Students and billed players in one room.",
    relatedSlugs: ["stephane-wrembel"],
  },
  {
    slug: "abbiategrasso-immersion-jam",
    name: "Full Immersion jam",
    city: "Abbiategrasso",
    country: "Italy",
    venue: "Jazz & strings camp",
    address: "Abbiategrasso (MI) — camp site on the camp page",
    hours: "after classes, from 20:00",
    when: "Camp weeks",
    nextStartsAt: "2026-09-25T18:00:00.000Z",
    bio: "Dario Napoli and Benji Winterstein's camp jam. Students sit with the trio after the classes.",
    relatedSlugs: ["dario-napoli", "benji-winterstein", "tonino-de-sensi"],
  },
  {
    slug: "milan-manouche-jam",
    name: "Milan Manouche Jam",
    city: "Milan",
    country: "Italy",
    venue: "Local Hot Club",
    address: "Milan — room posted with each date",
    hours: "from 21:00",
    when: "Monthly",
    nextStartsAt: "2026-09-08T19:00:00.000Z",
    bio: "Northern Italy's amateur night. A room for the manouche players who feed the Full Immersion camps.",
    relatedSlugs: ["dario-napoli", "tommaso-papini"],
  },
  {
    slug: "montreal-hot-club-jam",
    name: "Montreal Hot Club Jam",
    city: "Montreal",
    country: "Canada",
    venue: "DC Music School circle",
    address: "Montreal, QC — school posts the room",
    hours: "from 19:00",
    when: "Monthly",
    nextStartsAt: "2026-09-10T23:00:00.000Z",
    bio: "Denis Chang's city jam. Students from DC Music School and whoever is passing through Quebec.",
    relatedSlugs: ["denis-chang"],
  },
  {
    slug: "brussels-manouche-jam",
    name: "Brussels Manouche Jam",
    city: "Brussels",
    country: "Belgium",
    venue: "Hot Club rooms",
    address: "Brussels — room posted with each date",
    hours: "from 20:30",
    when: "Monthly",
    nextStartsAt: "2026-09-11T18:30:00.000Z",
    bio: "Belgian amateur night between Liberchies and Djangofollies. Waso-family chairs and visiting Dutch players.",
    relatedSlugs: ["fapy-lafertin", "waso-de-cauter", "koen-de-cauter"],
  },
  {
    slug: "taipei-hot-club-jam",
    name: "Taipei Hot Club Jam",
    city: "Taipei",
    country: "Taiwan",
    venue: "Sappho Live / festival rooms",
    address: "Linsen N Rd, Zhongshan — room posted with each date on the Hot Club / festival page",
    hours: "from 21:00",
    when: "Around the festival, plus monthly",
    nextStartsAt: "2026-11-19T13:00:00.000Z",
    bio: "The Taipei Hot Club jam. Open chairs around Taipei Gypsy Jazz Festival — often Sappho Live — and a monthly night the rest of the year. Vincent Tsai holds the room; Larry Chen and visiting chairs sit in. LINE ＠xdn2807w and WhatsApp on the festival page.",
    relatedSlugs: ["vincent-tsai", "larry-chen", "paulus-schafer", "christiaan-van-hemert", "denis-chang"],
    site: "https://www.gypsyjazztaipei.com/",
  },
  {
    slug: "tokyo-django-jam",
    name: "Tokyo Django Jam",
    city: "Tokyo",
    country: "Japan",
    venue: "Hot Club Tokyo",
    address: "Tokyo — room posted with each date",
    hours: "from 20:00",
    when: "Monthly",
    nextStartsAt: "2026-09-15T11:00:00.000Z",
    bio: "Japan's city jam, sister to Hita Django Festival. European guests sit in when they tour. Alison Zhen and Hanaoka Toshio hold chairs when they are in town; Denis Chang sits in between Japan dates.",
    relatedSlugs: ["alison-zhen", "hanaoka-toshio", "denis-chang"],
  },
  {
    slug: "oslo-cosmopolite-jam",
    name: "Oslo Cosmopolite Jam",
    city: "Oslo",
    country: "Norway",
    venue: "Cosmopolite",
    address: "Vogts gate 64, 0477 Oslo",
    hours: "after the billed sets, from 23:00",
    when: "Festival week, January",
    nextStartsAt: "2027-01-22T22:00:00.000Z",
    bio: "Late jam at Djangofestivalen. Hot Club de Norvège's room stays open after the billed sets.",
    relatedSlugs: ["jon-larsen", "ola-erlien", "gustav-skaaret"],
  },
  {
    slug: "hot-club-de-tms",
    name: "Hot Club de TMS",
    city: "Utrecht",
    country: "Netherlands",
    venue: "The Music Space XL",
    address: "Australiëlaan 24, 3526 AB Utrecht",
    hours: "19:00–23:00",
    when: "First Saturday of the month",
    nextStartsAt: "2026-09-05T17:00:00.000Z",
    bio: "Jazz Manouche at The Music Space, Utrecht. First Saturday of the month, 19:00–23:00. Organised with muziekstudio The Music Space. First night 5 September 2026: Chris’ Collective opens — Django’s repertoire with saxophone, bass clarinet and harmonica (Django recorded with Larry Adler; those tunes are on the list). Come play, listen, or sit in. Everyone welcome.",
    relatedSlugs: [],
    site: "https://chat.whatsapp.com/HJqtyO0dszj5ePPdWsrRbn",
  },
  {
    slug: "hot-club-insulinde",
    name: "Hot Club Insulinde",
    city: "Amsterdam",
    country: "Netherlands",
    venue: "Café Insulinde",
    address: "Sumatrastraat 24, 1094 ND Amsterdam",
    hours: "from 19:00",
    when: "Second Wednesday of the month",
    nextStartsAt: "2026-10-14T17:00:00.000Z",
    bio: "Acoustic Hot Club Manouche jam in Amsterdam’s Indische Buurt. Café Insulinde, Sumatrastraat 24. Second Wednesday of the month from 19:00. 100% acoustic — no amps, no mics. Open to all. Cash drinks. Instagram @hotclubinsulinde.",
    relatedSlugs: [],
    site: "https://www.instagram.com/hotclubinsulinde/",
  },
  {
    slug: "hot-club-de-hong-kong",
    name: "Hot Club de Hong Kong",
    city: "Hong Kong",
    country: "China",
    venue: "Allure Music Salon",
    address: "3 School Street, Tai Hang, Hong Kong",
    hours: "evening — time on Instagram @hotclubdehk",
    when: "Weekly",
    nextStartsAt: "2026-08-29T12:00:00.000Z",
    bio: "Hong Kong’s gypsy jazz Hot Club. Simon Choi, Neil Lau, Bob Pang and the band — weekly session, plus nights at Allure Music Salon (3 School Street, Tai Hang) and The Fringe Club. The only active manouche band in town. Instagram @hotclubdehk.",
    relatedSlugs: ["simon-choi", "neil-lau", "bob-pang"],
    site: "https://www.instagram.com/hotclubdehk/",
  },
  {
    slug: "shanghai-cottons-gypsy-jam",
    name: "Shanghai Gypsy Jazz Jam",
    city: "Shanghai",
    country: "China",
    venue: "Cottons",
    address: "Shanghai — Cottons, posted with each date",
    hours: "evening",
    when: "Session nights (posted)",
    nextStartsAt: "2026-09-05T12:00:00.000Z",
    bio: "Gypsy jazz jam in Shanghai. Hot Club de Shaolin sit in at Cottons — Minor Swing on the East China scene. Room and date on the club page.",
    relatedSlugs: [],
  },
  {
    slug: "manuska-jam-club",
    name: "Manuska Jam Club",
    city: "Budapest",
    country: "Hungary",
    venue: "Pótkulcs (room posted)",
    address: "Csengery utca 65/b, Budapest — next room in Gypsy Jazz Jams Budapest",
    hours: "evening — room posted in Gypsy Jazz Jams Budapest",
    when: "Weekly",
    nextStartsAt: "2026-08-30T17:00:00.000Z",
    bio: "Budapest’s standing weekly Django/manouche jam — the city’s only fixed manouche circle. Manuska chairs, not a general jazz jam. Next room in Gypsy Jazz Jams Budapest; Jazz Manouche Hungary is the wider Hungarian group. Often Pótkulcs (Csengery utca 65/b). Bring a guitar, listen first, sit in when the pompe is open.",
    relatedSlugs: ["roby-lakatos", "robert-karpati"],
    site: "https://www.facebook.com/groups/628542240660254/",
  },
  {
    slug: "gypsy-jazz-club-belgrade",
    name: "Gypsy Jazz Club",
    city: "Belgrade",
    country: "Serbia",
    venue: "Gypsy Jazz Club",
    address: "Kičevska 21, Vračar, Belgrade",
    hours: "Wed–Sat from 22:00",
    when: "Wednesday–Saturday",
    nextStartsAt: "2026-08-26T20:00:00.000Z",
    bio: "Belgrade live club in Vračar, near St Sava. Open Wednesday–Saturday from 22:00. Instagram @gypsy_jazz_club, reserve 069 663 111. Balkan and gypsy-jazz nights — not a posted open Django jam; Hot Club of Belgrade is the city’s Django group. Ask the door who is on.",
    relatedSlugs: ["dejan-krsmanovic", "tomislav-vujnovic"],
    site: "https://www.instagram.com/gypsy_jazz_club/",
  },
  {
    slug: "prague-manouche-jam",
    name: "Jazz Manouche Prague",
    city: "Prague",
    country: "Czechia",
    venue: "Scarface Café / Pracovna / Alva",
    address: "Rooms posted in Jazz Manouche Czech Republic — Scarface Café (Legerova 36, Vinohrady), Pracovna Žižkov, Alva",
    hours: "evening — see the group",
    when: "Posted per date",
    nextStartsAt: "2026-09-07T18:30:00.000Z",
    bio: "Czech manouche is not a fixed weekly night. Dates go up in Jazz Manouche Czech Republic on Facebook. Recent rooms: Scarface Café (Legerova 36, Vinohrady), Pracovna in Žižkov, Alva. Django Always (Kája and Tschavolo Vlasák) hold the Prague chairs. Ask in the group before you pack a guitar.",
    relatedSlugs: ["kaja-vlasak", "tschavolo-vlasak"],
    site: "https://www.facebook.com/groups/467446336607200/",
  },
  {
    slug: "swing-medical-bar-de-fondo",
    name: "Swing Medical Gypsy Jazz Jam",
    city: "Buenos Aires",
    country: "Argentina",
    venue: "Bar de Fondo",
    address: "Julián Álvarez 1200, Palermo, CABA",
    hours: "evening — often 21:30 or 22:00",
    when: "Monthly (date posted)",
    nextStartsAt: "2026-09-05T01:00:00.000Z",
    bio: "Buenos Aires Django jam. Swing Medical (Lucas Reydó and Matías Pagani) host at Bar de Fondo. Not a fixed weekly night — they post each date on Instagram @swing.medical and swingmedicaljam.com. Reservations 11.3009.5795 / WhatsApp 15-6872-4804. Suggested hat. Sit in when the pompe is open.",
    relatedSlugs: ["lucas-reydo", "matias-pagani", "juan-pablo-robaldo", "tomas-bobrowicky", "maria-fernanda-yamil"],
    site: "https://swingmedicaljam.com/",
  },
  {
    slug: "barcelona-martes-manouche",
    name: "Martes Manouche",
    city: "Barcelona",
    country: "Spain",
    venue: "Soda Acústic",
    address: "Carrer de les Guilleries 6, Gràcia, Barcelona",
    hours: "from 21:30",
    when: "Every Tuesday",
    nextStartsAt: "2026-08-25T19:30:00.000Z",
    bio: "Barcelona’s only weekly gypsy-jazz and acoustic-swing night. Every Tuesday in Gràcia at Soda Acústic — a short concert, then the jam. Django’s language in a neighbourhood bar. Instagram @martesmanouche.",
    relatedSlugs: [],
    site: "https://www.instagram.com/martesmanouche/",
  },
  {
    slug: "chicago-la-tosca-jam",
    name: "La Tosca Jam",
    city: "Chicago",
    country: "United States of America",
    venue: "Cara Cara Club",
    address: "2545 South Kedzie Avenue, Chicago, IL 60623",
    hours: "16:00–19:00",
    when: "2nd and 4th Sundays",
    nextStartsAt: "2026-08-23T21:00:00.000Z",
    bio: "Chicago gypsy-jazz jam. La Tosca host at Cara Cara Club — listen or sit in. Second and fourth Sundays. Alfonso Ponticelli’s city; the Chicago Gypsy Jazz Fest sits the same week in September.",
    relatedSlugs: ["alfonso-ponticelli"],
    site: "https://www.gypsyjazz.us/new-events",
  },
  {
    slug: "djangofest-nw-jams",
    name: "DjangoFest Northwest night jams",
    city: "Langley",
    country: "United States of America",
    venue: "Whidbey Island Center for the Arts",
    address: "565 Camano Avenue, Langley, WA 98260",
    hours: "after the concert, late",
    when: "Festival week, 15–20 September",
    nextStartsAt: "2026-09-16T04:00:00.000Z",
    bio: "Late jams at DjangoFest NW. Gismo Graf, Gonzalo Bergara, Tim Kliphuis, John Jorgenson, Pearl Django and Jimmy Grant on the billed nights — then the island stays up. Bring a guitar.",
    relatedSlugs: ["gismo-graf", "gonzalo-bergara", "tim-kliphuis", "john-jorgenson", "jimmy-grant"],
    site: "https://www.djangofest.com/",
  },
  {
    slug: "django-in-london-jams",
    name: "Django In London sessions",
    city: "London",
    country: "United Kingdom",
    venue: "St Mary's Church",
    address: "Upper Street, Islington, London N1 2TX",
    hours: "after the billed sets",
    when: "17–19 September 2026",
    nextStartsAt: "2026-09-17T21:00:00.000Z",
    bio: "Three-day London gathering. Concerts at St Mary’s, then the circle. Harry Diplock, Hugo Guezbar, Angelo Debarre, Elias Prinz & Sunny Franz, Giacomo Smith, London Django Collective with Kourosh Kanani.",
    relatedSlugs: ["harry-diplock", "hugo-guezbar", "angelo-debarre", "elias-prinz", "kourosh-kanani", "giacomo-smith"],
    site: "https://www.eventbrite.com/e/django-in-london-tickets-1995698734638",
  },
  {
    slug: "sydney-rio-gypsy-swing",
    name: "Rio Gypsy Swing Sessions",
    city: "Sydney",
    country: "Australia",
    venue: "The Rio",
    address: "126 Smith Street, Summer Hill",
    hours: "Wed 18:30–21:30",
    when: "Weekly, Wednesday",
    nextStartsAt: "2026-08-26T08:30:00.000Z",
    bio: "Weekly gypsy swing gig and jam at The Rio, Summer Hill. Acoustic, sit-in. The room has hosted this Wednesday night for years; check that week’s guest on the venue page.",
    relatedSlugs: [],
    site: "https://www.theriosummerhill.com/",
  },
  {
    slug: "ozmanouche-jams",
    name: "OzManouche jams",
    city: "Brisbane",
    country: "Australia",
    venue: "Brisbane Jazz Club",
    address: "1 Casino Street, Brisbane",
    hours: "after the billed sets",
    when: "Festival week, 23–27 September",
    nextStartsAt: "2026-09-25T09:00:00.000Z",
    bio: "Australia’s jazz manouche festival. Tazzmania Jam with Charlie McCarthy on the river deck, Friday 25 September 2026. Bring a guitar.",
    relatedSlugs: ["john-jorgenson", "daniel-weltlinger", "charlie-mccarthy"],
    site: "https://www.ozmanouche.com/",
  },
  {
    slug: "ashfield-miss-celies-jam",
    name: "Miss Celie’s Gypsy Swing Jam",
    city: "Sydney",
    country: "Australia",
    venue: "Miss Celie's",
    address: "15–17 Hercules Street, Ashfield",
    hours: "19:00–22:00",
    when: "First Tuesday",
    nextStartsAt: "2026-09-01T09:00:00.000Z",
    bio: "Sydney gypsy swing jam at Miss Celie’s, Ashfield — near the station. First Tuesday 19:00–22:00, free. Extra nights get posted. Sit in.",
    relatedSlugs: [],
    site: "https://misscelies.com.au/",
  },
  {
    slug: "auckland-pineapple-jam",
    name: "Auckland gypsy jazz jams",
    city: "Auckland",
    country: "New Zealand",
    venue: "Pineapple on Parnell",
    address: "Parnell, Auckland",
    hours: "21:00–23:00 when posted",
    when: "Monthly, Thursday — check the band",
    nextStartsAt: "2026-09-03T09:00:00.000Z",
    kind: "meetup",
    bio: "Twistin' the Swing host Thursday nights at Pineapple on Parnell when they post. A WhatsApp circle jams besides the gig — not a standing weekly open jam. Confirm on the band page before you go.",
    relatedSlugs: [],
    site: "",
  },
  {
    slug: "moscow-manouche-jam",
    name: "Moscow manouche jams",
    city: "Moscow",
    country: "Russia",
    venue: "Alexey Kozlov Club",
    address: "ul. Maroseyka 9/2, Moscow",
    hours: "evening — date on kozlovclub.ru",
    when: "Regular — check Kozlov Club",
    nextStartsAt: "2026-08-30T16:00:00.000Z",
    kind: "meetup",
    bio: "Moscow jazz-manouche jams around Georgiy Yashagashvili (Django Friends) and Dmitry Kuptsov. Often the Alexey Kozlov Club, Maroseyka 9/2. Not a printed weekday — they post each night. Sit in when the pompe is open. kozlovclub.ru",
    relatedSlugs: ["georgiy-yashagashvili", "dmitry-kuptsov", "lu-golovina", "ilya-delizonas"],
    site: "https://kozlovclub.ru/",
  },
  {
    slug: "petersburg-jfc-jam",
    name: "Hot Club of Saint-Petersburg at JFC",
    city: "Saint Petersburg",
    country: "Russia",
    venue: "JFC Jazz Club",
    address: "ul. Shpalernaya 33, Saint Petersburg",
    hours: "evening — check the club",
    when: "Concerts; open jams when posted",
    nextStartsAt: "2026-09-05T16:00:00.000Z",
    kind: "meetup",
    bio: "Saint Petersburg gypsy jazz. Hot Club of Saint-Petersburg (Pavel Ravvich, Alexey Baev, Andrey Smirnov, Roman Tentler) at JFC Jazz Club. Regular concerts, occasional open jams and rehearsals. Confirm on jfc-club.spb.ru.",
    relatedSlugs: ["andrey-smirnov"],
    site: "https://jfc-club.spb.ru/hot_club_of_saint-petersburg/",
  },
  {
    slug: "exeter-gypsy-jazz-sessions",
    name: "Gypsy Jazz Sessions Exeter",
    city: "Exeter",
    country: "United Kingdom",
    venue: "Topsham Brewery",
    address: "Exeter quayside / Topsham, Exeter",
    hours: "from 20:00",
    when: "Last Wednesday of the month",
    nextStartsAt: "2026-08-26T19:00:00.000Z",
    bio: "Open gypsy jazz jam, last Wednesday of the month at Topsham Brewery, Exeter quayside. Django / Grappelli book. Guitar, violin, bass, clarinet, horn, cello. Facebook: Gypsy Jazz Sessions Exeter.",
    relatedSlugs: [],
    site: "https://www.facebook.com/groups/gypsyjazzexeter/",
  },
  {
    slug: "baltimore-django-jazz-jam",
    name: "Baltimore Django Jazz Jam",
    city: "Baltimore",
    country: "United States of America",
    venue: "Bluebird Green Room",
    address: "Hampden, Baltimore, Maryland",
    hours: "Mon 18:00–22:00",
    when: "Weekly, Monday",
    nextStartsAt: "2026-08-24T22:00:00.000Z",
    bio: "Monday Django jam in Hampden — Bluebird’s Green Room, 18:00–22:00. Sit in. Facebook: Baltimore Django Jazz Jam.",
    relatedSlugs: [],
    site: "https://www.facebook.com/groups/2022554631159901/",
  },
  {
    slug: "louisville-gypsy-jazz-jam",
    name: "Louisville Gypsy Jazz",
    city: "Louisville",
    country: "United States of America",
    venue: "Rose Hill Lagerhaus",
    address: "1753 Bardstown Rd, Louisville, KY",
    hours: "Sun 18:00–20:00",
    when: "Monthly Sunday — check Facebook",
    nextStartsAt: "2026-09-20T22:00:00.000Z",
    kind: "meetup",
    bio: "Louisville Gypsy Jazz — Django and Grappelli collective. Monthly open jam at Rose Hill Lagerhaus, 1753 Bardstown Rd. First set a small group (often Swing ’39), then sit-in. Acoustic. Dates on louisvillegypsyjazz.weebly.com and the Facebook group.",
    relatedSlugs: [],
    site: "https://louisvillegypsyjazz.weebly.com/",
  },
  {
    slug: "ventura-gypsy-jazz-jam",
    name: "Ventura County Gypsy Jazz Jam",
    city: "Ventura",
    country: "United States of America",
    venue: "Vaquero y Mar",
    address: "435 E Thompson Blvd, Ventura, CA 93001",
    hours: "19:00–21:00",
    when: "4th Wednesday",
    nextStartsAt: "2026-08-27T02:00:00.000Z",
    bio: "Open acoustic jam, every 4th Wednesday at Vaquero y Mar. Seth Andrey Oster guitar, Bill Arnold bass, Gordon Roberts / Charletta Erb / Deborah Murphy violin. Django and 1930s swing. Facebook: Ventura County Gypsy Jazz Jam.",
    relatedSlugs: [],
    site: "https://www.facebook.com/groups/176588178695302/",
  },
  {
    slug: "brooklyn-bistro-so-jam",
    name: "Gypsy Jazz Jam at Bistro So",
    city: "Brooklyn",
    country: "United States of America",
    venue: "Bistro So",
    address: "530 Driggs Ave, Brooklyn, NY 11211",
    hours: "20:00–23:00",
    when: "Every Thursday",
    nextStartsAt: "2026-08-28T00:00:00.000Z",
    bio: "Williamsburg Thursday. Alex Simon’s weekly jazz manouche jam at Bistro So — 20:00–23:00. Sit in. Monday is Kings County Swing at St. Mazie; Sunday family night is at Retro, Greenpoint.",
    relatedSlugs: [],
    site: "https://www.alexsimonmusic.com/show",
  },
  {
    slug: "brooklyn-retro-jam",
    name: "Sunday jam at Retro",
    city: "Brooklyn",
    country: "United States of America",
    venue: "Retro Polish Restaurant",
    address: "853 Manhattan Ave, Brooklyn, NY 11222",
    hours: "18:00–21:00",
    when: "Every Sunday",
    nextStartsAt: "2026-08-23T22:00:00.000Z",
    bio: "Greenpoint Sunday family night. Gypsy swing and hot jazz, 18:00–21:00 at Retro. Monday is Kings County Swing at St. Mazie; Thursday is Bistro So, Williamsburg.",
    relatedSlugs: [],
    site: "https://www.alexsimonmusic.com/show",
  },
  {
    slug: "dc-gypsy-jazz-monday",
    name: "Gypsy Jazz DC Area Meetup",
    city: "Takoma Park",
    country: "United States of America",
    venue: "VFW Takoma Park / Brookmont Church",
    address: "Takoma Park MD / Bethesda MD — room posted with the date",
    hours: "Monday evening",
    when: "Most Mondays",
    nextStartsAt: "2026-08-24T23:00:00.000Z",
    kind: "meetup",
    bio: "Weekly Monday gypsy and swing jam for the DC area. VFW Takoma Park or Brookmont Church, Bethesda — check Meetup for which room this week.",
    relatedSlugs: [],
    site: "https://www.meetup.com/gypsy-jazz-dc-area-meetup/",
  },
  {
    slug: "london-the-hum-stokey",
    name: "Gypsy Jazz Night at The Hum",
    city: "London",
    country: "United Kingdom",
    venue: "The Hum",
    address: "86 Stoke Newington High Street, London N16 7PA",
    hours: "from 20:00",
    when: "Every Tuesday",
    nextStartsAt: "2026-08-25T19:00:00.000Z",
    bio: "Stoke Newington Tuesday. Erhan Öztürk’s house band — two guitars and bass — then sit-in. Angelo Debarre and Amati Schmitt have used the room. 86 Stoke Newington High Street.",
    relatedSlugs: ["angelo-debarre", "amati-schmitt"],
    site: "https://www.eventbrite.co.uk/e/gypsy-jazz-night-midnight-in-paris-tickets-1438456424889",
  },
  {
    slug: "wurzburg-z87-jam",
    name: "Würzburger Gypsy Jazz Jam",
    city: "Würzburg",
    country: "Germany",
    venue: "Keller Z87",
    address: "Frankfurter Straße 87, 97082 Würzburg",
    hours: "from 19:00",
    when: "1st Sunday",
    nextStartsAt: "2026-09-06T17:00:00.000Z",
    bio: "First Sunday of the month in Keller Z87, Bürgerbräu-Areal. Inswingtief started the room — opener band, then open jam. gypsy-session-würzburg.de / z87.de.",
    relatedSlugs: [],
    site: "https://z87.de/",
  },
  {
    slug: "lisbon-ma-lingua-jam",
    name: "Má Lingua Manouche",
    city: "Lisbon",
    country: "Portugal",
    venue: "Má Lingua",
    address: "Lisbon — Má Lingua",
    hours: "21:30–23:00",
    when: "1st and 3rd Tuesdays",
    nextStartsAt: "2026-09-01T20:30:00.000Z",
    bio: "Lisbon gypsy jazz jam, first and third Tuesday, 21:30. Intimate room, no stage. €5. jamsessions.pt keeps the date.",
    relatedSlugs: ["nuno-marinho"],
    site: "https://jamsessions.pt/venue/ma-lingua/",
  },
  {
    slug: "valencia-turia-manouche",
    name: "Miércoles Manouche",
    city: "Valencia",
    country: "Spain",
    venue: "Turia Bistro Pub",
    address: "Carrer del Túria 44, Valencia",
    hours: "from 19:30",
    when: "Every Wednesday",
    nextStartsAt: "2026-08-26T17:30:00.000Z",
    bio: "Valencia’s weekly gypsy jazz. Wednesday at Turia Bistro Pub — short set then jam. Jimmy Grant, Eva Slongo and Sessions Manouches use the room.",
    relatedSlugs: ["jimmy-grant"],
    site: "https://www.instagram.com/turiabistropub/",
  },
  {
    slug: "osaka-jazz-bar-845",
    name: "Osaka Gypsy Session",
    city: "Osaka",
    country: "Japan",
    venue: "Jazz Bar 845",
    address: "Bigsalt 845, Namba, Osaka",
    hours: "afternoon session",
    when: "3rd Sunday",
    nextStartsAt: "2026-09-20T05:00:00.000Z",
    bio: "Third Sunday of the month at Jazz Bar 845, Namba — Osaka Gypsy Jazz day session. Check jazz845.jp for the bill and charge.",
    relatedSlugs: [],
    site: "https://jazz845.jp/schedule/",
  },
  {
    slug: "cologne-agnes-klause",
    name: "Agnes-Klause Jazz & Hot Swing",
    city: "Cologne",
    country: "Germany",
    venue: "Agnes-Klause",
    address: "Weißenburgstraße 8a, 50670 Köln",
    hours: "from 19:00",
    when: "When posted — next: Saturday 31 Oct 2026",
    nextStartsAt: "2026-10-31T18:00:00.000Z",
    kind: "meetup",
    bio: "Hagen Horn’s Cologne jam. Jazz, blues and hot-swing / gypsy chairs when posted — often Friday, sometimes a Saturday night. Next: Halloween Acoustic Swing Session, Saturday 31 October 2026, 19:00 at Agnes-Klause (Weißenburgstraße 8a). Open session, not a concert bill. In good weather also outdoors at Jazz Point Agnes. Dates on the Agnesviertel LIVE Facebook group.",
    relatedSlugs: ["hagen-horn"],
    site: "https://www.facebook.com/groups/1826268940989735/",
  },
  {
    slug: "belfast-sunflower-manouche",
    name: "Manouche at the Sunflower",
    city: "Belfast",
    country: "United Kingdom",
    venue: "Sunflower Public House",
    address: "65 Union Street, Belfast",
    hours: "from 17:30",
    when: "Every Thursday",
    nextStartsAt: "2026-08-27T16:30:00.000Z",
    bio: "Northern Ireland’s weekly gypsy swing. Thursday 17:30 at the Sunflower — Manouche’s 1920s Paris set, then the room. Historically a jam; bring a guitar. Facebook: Manouche Belfast.",
    relatedSlugs: [],
    site: "https://sunflowerbelfast.com/",
  },
  {
    slug: "dublin-tenters-walters",
    name: "The Tenters at Walters Bar",
    city: "Dún Laoghaire",
    country: "Ireland",
    venue: "Walters Bar",
    address: "68 George's Street Upper, Dún Laoghaire",
    hours: "20:00–22:00",
    when: "Every Thursday",
    nextStartsAt: "2026-08-27T19:00:00.000Z",
    bio: "Dublin’s weekly Tenters night — hot jazz and gypsy swing. Five-piece: viola, two guitars, banjo and bass. Jazz Ireland lists the residency from April 2026.",
    relatedSlugs: [],
    site: "https://www.jazzireland.ie/jazz-events/residency/hot-jazz-swing-with-the-tenters-gypsy-jazz-band-48.html",
  },
  {
    slug: "dublin-django-djam",
    name: "Dublin Django D’jam",
    city: "Dublin",
    country: "Ireland",
    venue: "Brendan the Navigator",
    address: "Dublin",
    hours: "from 20:00",
    when: "Thursday when posted",
    nextStartsAt: "2026-08-27T19:00:00.000Z",
    kind: "meetup",
    bio: "Open gypsy jazz jam — all levels, all instruments. Posted on Gypsy Jazz Ireland and at Brendan the Navigator. Check the Facebook group before you go; the Tenters also hold Thursday at Walters in Dún Laoghaire.",
    relatedSlugs: [],
    site: "https://www.facebook.com/groups/gypsyjazzireland/",
  },
  {
    slug: "south-wales-gypsy-jazzers",
    name: "Gypsy Jazzers of South Wales",
    city: "Cardiff",
    country: "United Kingdom",
    venue: "Rooms posted in the group",
    address: "Cardiff and Swansea — room posted with each date",
    hours: "when posted",
    when: "When posted",
    nextStartsAt: "2026-08-30T18:00:00.000Z",
    kind: "meetup",
    bio: "South Wales gypsy jazz circle. Jams and gigs in Cardiff and Swansea — dates on the Gypsy Jazzers Of South Wales Facebook group. No standing weekly room posted this week; the group is where the chairs meet.",
    relatedSlugs: [],
    site: "https://www.facebook.com/groups/1652019531681084/",
  },
  {
    slug: "berlin-unterrock-jam",
    name: "Jazz Manouche Jam unterRock",
    city: "Berlin",
    country: "Germany",
    venue: "unterRock",
    address: "Fürbringerstraße 20A, 10961 Berlin",
    hours: "from 20:00",
    when: "2nd and 4th Thursday",
    nextStartsAt: "2026-08-27T18:00:00.000Z",
    bio: "Kreuzberg. Jazz manouche jam at unterRock, Fürbringerstraße 20A — 2nd and 4th Thursday from 20:00. Sit-in. Not the A-Trane Hot Club night.",
    relatedSlugs: [],
  },
  {
    slug: "malmo-dame-ginette-jam",
    name: "Gypsy jazz and jam at Dame Ginette",
    city: "Malmö",
    country: "Sweden",
    venue: "Dame Ginette",
    address: "Östra Förstadsgatan 18, 211 31 Malmö",
    hours: "18:00–21:00",
    when: "Every Wednesday",
    nextStartsAt: "2026-08-26T16:00:00.000Z",
    bio: "Malmö’s weekly Hot Club night — the first posted gypsy jazz jam in Sweden on the hub. Hot Club Trio 18:00–20:00 at Dame Ginette, then open sit-in. Dancers welcome. French bistro, Östra Förstadsgatan 18.",
    relatedSlugs: [],
    site: "https://www.dameginette.se/",
  },
  {
    slug: "basel-blaupause-jam",
    name: "Swiss Jazz Manouche Open Jam",
    city: "Basel",
    country: "Switzerland",
    venue: "Blaupause",
    address: "Utengasse 28, 4058 Basel",
    hours: "19:30–22:00",
    when: "Tuesdays when posted",
    nextStartsAt: "2026-09-01T17:30:00.000Z",
    kind: "meetup",
    bio: "Basel open jam hosted by the Swiss Jazz Manouche Association at Blaupause cocktail bar, Utengasse 28. Tuesdays when posted, 19:30–22:00. First night 19 May 2026; next posted 1 Sep 2026.",
    relatedSlugs: [],
    site: "https://www.swissjazzmanouche.ch/",
  },
  {
    slug: "copenhagen-django-jam",
    name: "Django Jam",
    city: "Copenhagen",
    country: "Denmark",
    venue: "Christianshavns Beboerhus",
    address: "Dronningensgade 34, 1420 Copenhagen",
    hours: "from 20:00",
    when: "Last Tuesday",
    nextStartsAt: "2026-09-29T18:00:00.000Z",
    bio: "Copenhagen’s standing Django Reinhardt / jazz manouche jam. Last Tuesday of the month at Christianshavns Beboerhus, Dronningensgade 34. Free. Hosted by Jens Fuglsang.",
    relatedSlugs: [],
    site: "https://beboerhus.dk/",
  },
  {
    slug: "amsterdam-langereis-jam",
    name: "Café Langereis session",
    city: "Amsterdam",
    country: "Netherlands",
    venue: "Café Langereis",
    address: "Amstel 202, Amsterdam",
    hours: "20:00–23:00",
    when: "First Tuesday",
    nextStartsAt: "2026-09-01T18:00:00.000Z",
    bio: "First Tuesday, 20:00–23:00. Gypsy swing jam at Café Langereis, Amstel 202 — often an opening set, then sit-in. Led by Tessa Spaaij. Listed by Hot Club de France Nederland.",
    relatedSlugs: [],
    site: "https://hcdf.nl/2025/08/09/gypsy-jazz-jam-sessies/",
  },
  {
    slug: "amsterdam-de-pianist-jam",
    name: "De Pianist gypsy jazz",
    city: "Amsterdam",
    country: "Netherlands",
    venue: "Café De Pianist",
    address: "Groen van Prinstererstraat 41, 1051 EH Amsterdam",
    hours: "from 20:30",
    when: "2nd Friday of even months",
    nextStartsAt: "2026-10-09T18:30:00.000Z",
    bio: "Amsterdam Westerpark. Gypsy jazz at Café De Pianist, 2nd Friday of even months from 20:30. Led by Martin Wachters. Listed by Hot Club de France Nederland.",
    relatedSlugs: [],
    site: "https://www.cafedepianist.nl/agenda-live-muziek/",
  },
  {
    slug: "den-haag-manouche-jam",
    name: "Manouche Den Haag",
    city: "The Hague",
    country: "Netherlands",
    venue: "Gunst Wat ’n Kunst",
    address: "Raamweg 45, 2596 HN Den Haag",
    hours: "14:00–18:00",
    when: "3rd Saturday",
    nextStartsAt: "2026-09-19T12:00:00.000Z",
    bio: "Manouche Den Haag — 3rd Saturday afternoon, 14:00–18:00 at Gunst Wat ’n Kunst, Raamweg 45. Organised by Evelien Tollenaar. Ask before you sit in. Listed by Hot Club de France Nederland.",
    relatedSlugs: [],
    site: "https://hcdf.nl/2025/08/09/gypsy-jazz-jam-sessies/",
  },
  {
    slug: "ubbergen-refter-jam",
    name: "Nijmegen jam at Café van de Refter",
    city: "Ubbergen",
    country: "Netherlands",
    venue: "Café van de Refter",
    address: "Rijkstraatweg 37, Ubbergen",
    hours: "19:30–23:30",
    when: "Selected Fridays",
    nextStartsAt: "2026-08-28T17:30:00.000Z",
    kind: "meetup",
    bio: "Near Nijmegen. Gypsy jazz at Café van de Refter, Rijkstraatweg 37, Ubbergen — selected Fridays 19:30–23:30. Organised by Sigrid Booden. Confirm the Friday with Hot Club de France Nederland before you go.",
    relatedSlugs: [],
    site: "https://hcdf.nl/2025/08/09/gypsy-jazz-jam-sessies/",
  },
  {
    slug: "pittsburgh-conjure-jam",
    name: "Open Hot Club Jam at Conjure",
    city: "Pittsburgh",
    country: "United States of America",
    venue: "Conjure Bar & Stage",
    address: "753 East Warrington Avenue, Pittsburgh, PA 15210",
    hours: "from 19:30",
    when: "Every other Tuesday",
    nextStartsAt: "2026-08-25T23:30:00.000Z",
    bio: "Allentown, Pittsburgh. Swing Dynamique hosts a biweekly open Hot Club jam at Conjure Bar & Stage (Inspired by Spirits distillery) — enter through Dr. Tumblety’s. No cover. Bring an instrument or listen. 18+ at Conjure.",
    relatedSlugs: [],
    site: "https://inspiredbyspirits.com/",
  },
  {
    slug: "missoula-old-post-jam",
    name: "Elephant Gerald’s Gypsy Jazz Jam",
    city: "Missoula",
    country: "United States of America",
    venue: "The Old Post",
    address: "103 W Spruce St, Missoula, MT",
    hours: "19:00–21:00",
    when: "4th Wednesday",
    nextStartsAt: "2026-08-27T01:00:00.000Z",
    bio: "Missoula. Elephant Gerald’s gypsy jazz jam at The Old Post, 103 W Spruce — 4th Wednesday 19:00–21:00. Sit in.",
    relatedSlugs: [],
    site: "https://elephantgeraldmt.com/home",
  },
  {
    slug: "lockport-roxy-jam",
    name: "Jazz Manouche Jam at ROXY",
    city: "Lockport",
    country: "United States of America",
    venue: "ROXY Lockport",
    address: "1017 S State St, Lockport, IL 60441",
    hours: "20:00–23:00",
    when: "2nd Wednesday",
    nextStartsAt: "2026-09-10T01:00:00.000Z",
    bio: "Lockport, Illinois. Free jazz manouche jam at ROXY, 1017 S State St — 2nd Wednesday 20:00–23:00. Bring an instrument, dance, or listen.",
    relatedSlugs: [],
    site: "https://www.roxylockport.com/calendar/manouche-gypsy-jazz-jam-2/2026-09-09/",
  },
  {
    slug: "arvada-silver-vines-jam",
    name: "Gypsy Jazz Jam at Silver Vines",
    city: "Arvada",
    country: "United States of America",
    venue: "Silver Vines Winery",
    address: "7509 Grandview Ave, Arvada, CO 80002",
    hours: "19:30–21:30",
    when: "Every Monday",
    nextStartsAt: "2026-09-01T01:30:00.000Z",
    bio: "Arvada, Colorado. Weekly gypsy jazz jam at Silver Vines Winery, 7509 Grandview Ave — every Monday 19:30–21:30. No reservations.",
    relatedSlugs: [],
    site: "https://silvervineswinery.com/events/gypsy-jazz-jam-every-monday/",
  },
  {
    slug: "brooklyn-st-mazie-jam",
    name: "Kings County Swing at St. Mazie",
    city: "Brooklyn",
    country: "United States of America",
    venue: "St. Mazie Bar & Supper Club",
    address: "345 Grand St, Brooklyn, NY 11211",
    hours: "20:00–22:30",
    when: "Mondays",
    nextStartsAt: "2026-09-01T00:00:00.000Z",
    bio: "Williamsburg Monday. Kings County Swing gypsy jazz jam at St. Mazie, 345 Grand St — 20:00–22:30. Separate from Thursday at Bistro So and Sunday at Retro. Dates on the St. Mazie live-music page.",
    relatedSlugs: [],
    site: "https://www.stmazie.com/live-music/",
  },
  {
    slug: "south-africa-manouche",
    name: "South Africa — no standing Gypsy Jazz jam",
    city: "Johannesburg / Cape Town",
    country: "South Africa",
    venue: "Performance bands, not an open jam",
    address: "Johannesburg and Cape Town — dates with the bands",
    hours: "concert nights when posted",
    when: "No regular open jam posted",
    nextStartsAt: "2026-09-01T18:00:00.000Z",
    kind: "meetup",
    bio: "Dedicated Gypsy Jazz open jams are essentially nonexistent in Africa. In South Africa the chairs are performance bands — Hot Club d’Afrique, Hot Club of Cape Town, Tarabu, Manouche. The jazz clubs on the country page (The Crypt, Fat Harry’s, Openwine, The Blue Room, Six Cocktail Bar, Niki’s Oasis) are the rooms to start a Hot Club jam. Ask the house.",
    relatedSlugs: [],
    site: "https://www.africangypsyjazz.com/",
  },
  {
    slug: "morocco-manouche",
    name: "Morocco — occasional Django concerts",
    city: "Casablanca / Rabat",
    country: "Morocco",
    venue: "Concert halls when posted",
    address: "Casablanca and Rabat — dates with the promoters",
    hours: "when billed",
    when: "No regular jam posted",
    nextStartsAt: "2026-09-15T19:00:00.000Z",
    kind: "meetup",
    bio: "No regular Gypsy Jazz jam is documented in Morocco. Occasional Django homage concerts have been given (Jazz Band of the Royal Symphony Orchestra, Casablanca and Rabat, 2024). Jazz rooms on the country page — Rick’s Café, Blue Note Agadir, Weston Jazz Club — are the houses to start one. Ask the room.",
    relatedSlugs: [],
    site: "",
  },
  {
    slug: "iceland-manouche",
    name: "Iceland — no standing Gypsy Jazz jam",
    city: "Reykjavík",
    country: "Iceland",
    venue: "Jazz clubs, not an open Hot Club night",
    address: "Reykjavík — Múlinn at Harpa, KEX, Café Rosenberg, Iðnó",
    hours: "when the jazz houses post",
    when: "No regular Gypsy Jazz jam posted",
    nextStartsAt: "2026-09-02T20:00:00.000Z",
    kind: "meetup",
    bio: "No dedicated Gypsy Jazz jam is posted in Reykjavík. Jazz rooms — Múlinn Jazz Club at Harpa, KEX Hostel, Café Rosenberg, Iðnó — are the houses to start one. Ask the room.",
    relatedSlugs: [],
    site: "",
  },
  {
    slug: "indonesia-manouche",
    name: "Indonesia — no standing Gypsy Jazz jam",
    city: "Jakarta",
    country: "Indonesia",
    venue: "Jazz clubs and Java Jazz",
    address: "Jakarta — Penn Jakarta, Java Jazz Festival",
    hours: "when posted",
    when: "No regular Gypsy Jazz jam posted",
    nextStartsAt: "2026-09-05T12:00:00.000Z",
    kind: "meetup",
    bio: "No dedicated Gypsy Jazz jam is posted in Indonesia. Jakarta jazz sits at Penn Jakarta (Mostly Jazz nights) and at Java Jazz Festival. Ask those houses if you want to start a Hot Club jam.",
    relatedSlugs: [],
    site: "https://pennjakarta.com/",
  },
  {
    slug: "goro-goro-sanur-jam",
    name: "Goro Goro Thursday jazz jam",
    city: "Sanur",
    country: "Indonesia",
    venue: "Goro Goro Cafe & Kitchen",
    address: "Jl. Bypass Ngurah Rai No. 157, Sanur, Bali",
    hours: "from 19:00 WITA",
    when: "Thursday",
    nextStartsAt: "2026-08-27T11:00:00.000Z",
    scene: "jazz",
    bio: "Bali’s posted jazz jam — Thursday at Goro Goro, Sanur. Sit-in welcome when the house posts it. Straight-ahead, not Gypsy Jazz. Jakarta jazz sits at Penn Jakarta and Java Jazz Festival.",
    relatedSlugs: [],
    site: "https://www.facebook.com/gorogorocafekitchen/",
  },
  {
    slug: "piano-man-delhi-jam",
    name: "The Piano Man Sunday jam",
    city: "New Delhi",
    country: "India",
    venue: "The Piano Man Jazz Club",
    address: "Safdarjung, New Delhi",
    hours: "from 21:00",
    when: "Sunday",
    nextStartsAt: "2026-08-30T15:30:00.000Z",
    scene: "jazz",
    bio: "Delhi’s long-running Sunday jazz jam / musician mixer. Tickets on thepianoman.in. Straight-ahead, not Gypsy Jazz. Mumbai nights go through The Bombay Jazz Club (Bonobo and other rooms).",
    relatedSlugs: [],
    site: "https://www.thepianoman.in/",
  },
  {
    slug: "tel-aviv-ala-rampa-table",
    name: "Ala Rampa gypsy swing table",
    city: "Tel Aviv",
    country: "Israel",
    venue: "Ala Rampa",
    address: "Ha’Amal 21, Tel Aviv",
    hours: "from 21:00",
    when: "When posted — not weekly",
    nextStartsAt: "2026-08-12T18:00:00.000Z",
    kind: "meetup",
    bio: "Past table session, 12 August 2026, 21:00. Yaakov Hoter, Nissim Zaga and Aner Albuquerque. Second half open jam — bring an instrument. Free entry, book a table (לניגון / for the playing). Ha’Amal 21. Not a weekly listing. When they post the next night, it belongs here.",
    relatedSlugs: ["yaakov-hoter", "nissim-zaga", "aner-albuquerque"],
    site: "",
  }
];

export function getJam(slug: string) {
  return JAMS.find((jam) => jam.slug === slug);
}

function isPostedNotRecurring(when: string) {
  return /when posted|no regular|festival week|camp week|selected friday|check (the band|facebook|kozlov)/i.test(
    when,
  );
}

function isWeekly(when: string) {
  return /weekly|every (monday|tuesday|wednesday|thursday|friday|saturday|sunday)|weekends|mondays|tuesdays|wednesdays|thursdays|fridays|saturdays|sundays/i.test(
    when,
  ) && !/every other|biweekly|1st|2nd|3rd|4th|first |last /i.test(when);
}

function isBiweekly(when: string) {
  return /every other|biweekly|every other tuesday/i.test(when);
}

function isMonthlyish(when: string) {
  return /monthly|1st |2nd |3rd |4th |first |last /i.test(when);
}

/** Keep the original clock; only walk the calendar forward. Do not invent new rooms. */
export function rollJamNext(jam: Jam, now = Date.now()): string {
  const raw = jam.nextStartsAt;
  const date = new Date(raw);
  if (Number.isNaN(date.getTime()) || date.getTime() >= now) return raw;
  if (isPostedNotRecurring(jam.when)) return raw;
  const stepDays = isWeekly(jam.when) ? 7 : isBiweekly(jam.when) ? 14 : isMonthlyish(jam.when) ? 28 : 0;
  if (!stepDays) return raw;
  let guard = 0;
  while (date.getTime() < now && guard < 80) {
    date.setUTCDate(date.getUTCDate() + stepDays);
    guard += 1;
  }
  return date.toISOString();
}

export function upcomingJams(now = Date.now()) {
  return JAMS.map((jam) => ({ ...jam, nextStartsAt: rollJamNext(jam, now) }))
    .filter((jam) => new Date(jam.nextStartsAt).getTime() >= now)
    .sort((a, b) => new Date(a.nextStartsAt).getTime() - new Date(b.nextStartsAt).getTime());
}

export function jamsByCountry(extra: Jam[] = [], now = Date.now()) {
  const all = [...upcomingJams(now)];
  for (const jam of extra) {
    if (new Date(jam.nextStartsAt).getTime() < now) continue;
    if (!all.some((row) => row.slug === jam.slug)) all.push(jam);
  }
  const counts: Record<string, number> = {};
  for (const jam of all) counts[jam.country] = (counts[jam.country] ?? 0) + 1;
  const present = [...new Set(all.map((jam) => jam.country))];
  const ordered = present.sort(
    (a, b) => (counts[b] ?? 0) - (counts[a] ?? 0) || a.localeCompare(b),
  );
  return ordered.map((country) => ({
    country,
    jams: all
      .filter((jam) => jam.country === country)
      .sort((a, b) => {
        const meetup = Number((b.kind ?? "regular") === "meetup") - Number((a.kind ?? "regular") === "meetup");
        if (meetup) return meetup;
        return new Date(a.nextStartsAt).getTime() - new Date(b.nextStartsAt).getTime();
      }),
  }));
}

export function jamsInCountry(atlasName: string, now = Date.now()) {
  return upcomingJams(now).filter((jam) => jam.country === atlasName);
}
