export type LuthierCraft = "guitar" | "bass" | "violin";

export type Luthier = {
  slug: string;
  name: string;
  city: string;
  country: string;
  site: string;
  contact: string;
  bio: string;
  address: string;
  phone: string;
  email: string;
  hours: string;
  craft: LuthierCraft;
  note: string;
};

function guitar(row: Omit<Luthier, "craft" | "note"> & Partial<Pick<Luthier, "note">>): Luthier {
  return { ...row, note: row.note ?? "", craft: "guitar" };
}

function bass(
  row: Omit<Luthier, "craft" | "contact" | "address" | "phone" | "email" | "hours" | "site" | "note"> &
    Partial<Pick<Luthier, "contact" | "address" | "phone" | "email" | "hours" | "site" | "note">>,
): Luthier {
  return {
    ...row,
    contact: row.contact ?? "",
    address: row.address ?? "",
    phone: row.phone ?? "",
    email: row.email ?? "",
    hours: row.hours ?? "By appointment",
    site: row.site ?? "",
    note: row.note ?? "",
    craft: "bass",
  };
}

function violin(
  row: Omit<Luthier, "craft" | "contact" | "address" | "phone" | "email" | "hours" | "site" | "note"> &
    Partial<Pick<Luthier, "contact" | "address" | "phone" | "email" | "hours" | "site" | "note">>,
): Luthier {
  return {
    ...row,
    contact: row.contact ?? "",
    address: row.address ?? "",
    phone: row.phone ?? "",
    email: row.email ?? "",
    hours: row.hours ?? "By appointment",
    site: row.site ?? "",
    note: row.note ?? "",
    craft: "violin",
  };
}

export function parseLuthierCraft(raw: string | undefined | null): LuthierCraft {
  if (raw === "bass") return "bass";
  if (raw === "violin") return "violin";
  return "guitar";
}

const GUITAR_LUTHIERS: Luthier[] = [
  guitar({
    slug: "mauro-freschi",
    name: "Mauro Freschi",
    city: "Spresiano",
    country: "Italy",
    site: "https://www.maurofreschiguitars.com/",
    contact: "mailto:info@maurofreschiguitars.com",
    address: "Via XXIV Maggio 33, 31027 Spresiano, Italy",
    phone: "+39 348 042 4035",
    email: "info@maurofreschiguitars.com",
    hours: "By appointment",
    bio: "Spresiano, Italy. Building since 2003 — archtop and Selmer-Maccaferri manouche guitars, the bulk of the workshop. Gismo Graf has played Freschi instruments. Custom orders from the studio.",
  }),
  guitar({
    slug: "marco-la-manna",
    name: "Marco La Manna",
    city: "Dovera, Cremona",
    country: "Italy",
    site: "http://www.marcolamannaguitars.com/",
    contact: "mailto:info@marcolamannaguitars.com",
    address: "Via Folla 23, Dovera (Cremona), Italy",
    phone: "",
    email: "info@marcolamannaguitars.com",
    hours: "By appointment",
    bio: "Marco La Manna builds in Dovera, in the Cremona country. Jazz manouche, classical and acoustic guitars — a current Italian chair for the Selmer sound.",
  }),
  guitar({
    slug: "bruno-bagnarelli",
    name: "Bruno Bagnarelli / BB Guitars",
    city: "Milan",
    country: "Italy",
    site: "https://www.bbguitars.it/",
    contact: "mailto:bbluthier@gmail.com",
    address: "Via Dante Chiasserini 68, 20157 Milan, Italy",
    phone: "+39 331 879 9635",
    email: "bbluthier@gmail.com",
    hours: "By appointment",
    bio: "Milan workshop. Bruno Bagnarelli trained at the Civica Scuola di Liuteria and builds Selmer-Maccaferri models — maintenance and new guitars for the Italian scene.",
  }),
  guitar({
    slug: "michele-gattoni",
    name: "Michele Gattoni / Arte Manouche",
    city: "Viggiù",
    country: "Italy",
    site: "https://www.facebook.com/atelierartemanouche/",
    contact: "mailto:info@atelierartemanouche.it",
    address: "Vicolo San Rocco 4, 21059 Viggiù, Italy",
    phone: "+39 347 535 6866",
    email: "info@atelierartemanouche.it",
    hours: "By appointment",
    bio: "Atelier Arte Manouche. Michele Gattoni builds manouche guitars in northern Italy — including instruments played by Joscho Stephan.",
  }),
  guitar({
    slug: "maurice-dupont",
    name: "Maurice Dupont",
    city: "Cognac",
    country: "France",
    site: "https://www.dupont-guitars.com/",
    contact: "",
    address: "20 rue Port-Boutiers, 16100 Boutiers-Saint-Trojan, France",
    phone: "",
    email: "",
    hours: "By appointment",
    bio: "Cognac. Apprentice of Jacques Favino, Meilleur Ouvrier de France. Dupont guitars are the working French Selmer for a generation of professionals.",
  }),
  guitar({
    slug: "jean-barault",
    name: "Jean Barault",
    city: "Grasse",
    country: "France",
    site: "https://www.barault.com/",
    contact: "mailto:jeanbarault@gmail.com",
    address: "1 Avenue Thiers, 06130 Grasse, France",
    phone: "+33 6 09 55 15 30",
    email: "jeanbarault@gmail.com",
    hours: "By appointment",
    bio: "French luthier. Barault gypsy jazz guitars — Favino-family feel, built now. A first call beside Dupont and Favino.",
  }),
  guitar({
    slug: "castelluccia",
    name: "Castelluccia",
    city: "Paris",
    country: "France",
    site: "https://www.castelluccia.fr/en/",
    contact: "",
    address: "3 Rue de Constantinople, 75008 Paris, France",
    phone: "+33 1 43 87 39 50",
    email: "",
    hours: "Tue–Sat 14:30–18:30, by appointment",
    bio: "The oldest gypsy jazz shop still open in Paris. Jean-Baptiste Castelluccia carries the family line Jacques started — honest Selmer-style guitars from the 11th arrondissement.",
  }),
  guitar({
    slug: "ajl-guitars",
    name: "AJL Guitars",
    city: "Kokkola",
    country: "Finland",
    site: "https://www.ajl-guitars.com/",
    contact: "mailto:aj@ajl-guitars.com",
    address: "Kokkola, Finland",
    phone: "+358 40 507 1383",
    email: "aj@ajl-guitars.com",
    hours: "By appointment",
    bio: "Hand-built Selmers from Ari-Jukka Luomaranta. AJL is known for detail, playability and a modern take on the oval-hole and D-hole chairs.",
  }),
  guitar({
    slug: "jean-pierre-favino",
    name: "Jean-Pierre Favino",
    city: "Paris",
    country: "France",
    site: "https://www.favino.com/en/",
    contact: "",
    address: "",
    phone: "",
    email: "",
    hours: "Workshop permanently closed",
    bio: "Son of Jacques Favino. The Favino workshop is closed; the guitars remain the measure — Modele S and the family oval-hole that Dutch and French players still hunt.",
  }),
  guitar({
    slug: "stefan-hahl",
    name: "Stefan Hahl",
    city: "Mudershausen",
    country: "Germany",
    site: "https://hahl-guitars.de/",
    contact: "mailto:info@hahl-guitars.de",
    address: "Taunusblick 1, 65623 Mudershausen, Germany",
    phone: "+49 6430 6476",
    email: "info@hahl-guitars.de",
    hours: "By appointment",
    bio: "Master luthier, Taunusblick 1, Mudershausen. Hahl Selmer-Maccaferri guitars — German build, balance and projection. A top European chair.",
  }),
  guitar({
    slug: "nicolas-perez",
    name: "Nicolas Perez",
    city: "Berlin",
    country: "Germany",
    site: "",
    contact: "",
    address: "Berlin, Germany",
    phone: "",
    email: "",
    hours: "By appointment",
    bio: "French-born, Berlin workshop. High-end acoustic and gypsy jazz guitars — Paris craft in the German capital.",
  }),
  guitar({
    slug: "leo-eimers",
    name: "Leo Eimers",
    city: "Almere",
    country: "Netherlands",
    site: "https://www.eimersguitars.com/",
    contact: "mailto:info@eimersguitars.com",
    address: "Fioringrasstraat 13-15, 1313 LB Almere, Netherlands",
    phone: "+31 36 534 4808",
    email: "info@eimersguitars.com",
    hours: "By appointment",
    bio: "Dutch builder of Selmer/Maccaferri guitars for more than twenty-five years. Player and luthier — restorations of Favino, Busato, Di Mauro, and new Eimers instruments.",
  }),
  guitar({
    slug: "rino-van-hooydonk",
    name: "Rino van Hooydonk",
    city: "Netherlands",
    country: "Netherlands",
    site: "",
    contact: "",
    address: "",
    phone: "",
    email: "",
    hours: "By appointment",
    bio: "Dutch player-builder. Rino van Hooydonk (Hooijdonk) has spent nearly two decades on Selmer-style gypsy jazz guitars — loud bass, crunchy treble, old-school dry sound. Also on the musicians page.",
  }),
  guitar({
    slug: "shelley-park",
    name: "Shelley Park",
    city: "North Vancouver",
    country: "Canada",
    site: "https://www.parkguitars.com/",
    contact: "mailto:info@parkguitars.com",
    address: "North Vancouver, British Columbia, Canada",
    phone: "+1 604 988 4324",
    email: "info@parkguitars.com",
    hours: "By appointment",
    bio: "Canadian luthier. Park gypsy jazz guitars carry the Selmer look and a contemporary hand — a favourite on the North American circuit.",
  }),
  guitar({
    slug: "jerome-duffell",
    name: "Jerome Duffell",
    city: "Cardigan",
    country: "United Kingdom",
    site: "https://jeromeduffell.com/",
    contact: "mailto:info@jeromeduffell.com",
    address: "Cardigan, West Wales, United Kingdom",
    phone: "",
    email: "info@jeromeduffell.com",
    hours: "By appointment",
    bio: "Cardigan, West Wales. Hand-made Selmer-Maccaferri gypsy jazz guitars — also steel-string and classical. One-month Selmer guitar-making courses in the workshop (max four people).",
  }),
  guitar({
    slug: "john-le-voi",
    name: "John Le Voi",
    city: "Alford",
    country: "United Kingdom",
    site: "https://www.johnlevoiguitars.co.uk/",
    contact: "https://www.johnlevoiguitars.co.uk/",
    address: "10 Station Road, Alford, Lincolnshire LN13 9HY, United Kingdom",
    phone: "",
    email: "",
    hours: "By appointment",
    bio: "Alford, Lincolnshire. Building since 1970 — Selmer-Maccaferri gypsy jazz guitars, plus flat-tops, archtops and mandolin-family instruments. One of the first UK makers in the style. Shown at Django In The Bay.",
  }),
  guitar({
    slug: "killy-nonis",
    name: "Killy Nonis",
    city: "Canterbury",
    country: "United Kingdom",
    site: "https://www.facebook.com/killynonisguitars/",
    contact: "https://www.facebook.com/killynonisguitars/",
    address: "Canterbury / Barham, Kent, United Kingdom",
    phone: "+44 7951 399310",
    email: "",
    hours: "By appointment",
    bio: "Kent. Selmer and Busato-style gypsy jazz guitars — decades of copies and restorations. Regular in the Django In The Bay luthier tent.",
  }),
  guitar({
    slug: "alex-bishop",
    name: "Alex Bishop",
    city: "Bristol",
    country: "United Kingdom",
    site: "https://www.alexbishopguitars.com/",
    contact: "mailto:alex@alexbishopguitars.com",
    address: "Easton Road, Easton, Bristol, United Kingdom",
    phone: "",
    email: "alex@alexbishopguitars.com",
    hours: "By appointment",
    bio: "Bristol workshop. Handmade gypsy jazz and folk guitars, plus repair and a guitar-making school. Shown at Django In The Bay.",
  }),
  guitar({
    slug: "robert-ford",
    name: "Robert Ford",
    city: "London",
    country: "United Kingdom",
    site: "https://www.facebook.com/p/Robert-Ford-Guitars-100070177093252/",
    contact: "https://www.facebook.com/p/Robert-Ford-Guitars-100070177093252/",
    address: "London, United Kingdom",
    phone: "",
    email: "",
    hours: "By appointment",
    bio: "London. Selmer / Favino-style gypsy jazz guitars. Regular in the Django In The Bay luthier tent.",
  }),
  guitar({
    slug: "edward-polak",
    name: "Edward Polak / Polak Guitars",
    city: "",
    country: "Israel",
    site: "https://polakguitars.wixsite.com/polak-gypsy-guitars",
    contact: "mailto:sergei.erg@gmail.com",
    address: "",
    phone: "",
    email: "sergei.erg@gmail.com",
    hours: "",
    bio: "Polak Guitars (formerly ERG). Builds gypsy-jazz and archtop guitars in Israel. Yaakov Hoter signature model. Also listed at gypsyandjazz.com/guitars.",
  }),
];

const BASS_LUTHIERS: Luthier[] = [
  bass({
    slug: "kanzian-traunsteiner",
    name: "Kanzian & Traunsteiner",
    city: "Vienna",
    country: "Austria",
    site: "https://doublebassmaker.com",
    bio: "Vienna workshop. New double basses, repairs and sound work — Alex Kanzian and Fabian Traunsteiner.",
  }),
  bass({
    slug: "benedict-puglisi",
    name: "Benedict G. Puglisi / Atelier Puglisi",
    city: "Hawthorn, Victoria",
    country: "Australia",
    bio: "Atelier Puglisi in Hawthorn. Fine double basses, repairs and restorations.",
  }),
  bass({
    slug: "matthew-tucker",
    name: "Matthew Tucker",
    city: "Sydney",
    country: "Australia",
    bio: "Sydney-area double bass maker — new instruments, repairs and setup.",
  }),
  bass({
    slug: "bass-works-australia",
    name: "Bass Works Australia",
    city: "Belair",
    country: "Australia",
    site: "https://www.bassworks.com.au/",
    address: "30 Gloucester Avenue, Belair SA 5052, Australia",
    phone: "+61 8 8278 2016",
    email: "info@bassworks.com.au",
    contact: "mailto:info@bassworks.com.au",
    hours: "By appointment, 10:00–17:00",
    bio: "Belair, South Australia. Double basses, cellos, repairs and restorations since 1990.",
  }),
  bass({
    slug: "neville-whitehead",
    name: "Neville Whitehead",
    city: "Sydney",
    country: "Australia",
    bio: "Sydney. Double bass making, restoration and repair.",
  }),
  bass({
    slug: "jacky-walraet",
    name: "Atelier Jacky Walraet",
    city: "Ghent",
    country: "Belgium",
    bio: "Ghent workshop. Setup, repairs, extensions and construction for double bass.",
  }),
  bass({
    slug: "jean-franco-fiorini",
    name: "Jean-Franco Fiorini",
    city: "Belo Horizonte",
    country: "Brazil",
    bio: "Belo Horizonte. Double bass maker and restorer.",
  }),
  bass({
    slug: "andrea-spada",
    name: "Andrea Spada",
    city: "Rio de Janeiro",
    country: "Brazil",
    bio: "Rio de Janeiro. Double bass luthier.",
  }),
  bass({
    slug: "paulo-gomes",
    name: "Paulo Gomes",
    city: "",
    country: "Brazil",
    bio: "Brazilian workshop for double basses.",
  }),
  bass({
    slug: "kai-arvi",
    name: "Kai Arvi / Arvi Basses",
    city: "Prince Edward Island",
    country: "Canada",
    bio: "Prince Edward Island. Arvi Basses — contemporary handmade double basses.",
  }),
  bass({
    slug: "james-ham",
    name: "James Ham",
    city: "Victoria, BC",
    country: "Canada",
    bio: "Victoria, British Columbia. Maker and restorer of double basses.",
  }),
  bass({
    slug: "mario-lamarre",
    name: "Mario Lamarre",
    city: "Montreal",
    country: "Canada",
    bio: "Montreal. Contemporary stringed instruments, including double bass.",
  }),
  bass({
    slug: "masa-miki-inokuchi",
    name: "Masa & Miki Inokuchi",
    city: "Toronto",
    country: "Canada",
    bio: "Toronto. Double bass making and restoration.",
  }),
  bass({
    slug: "gerard-ivan-samija",
    name: "Gerard Ivan Samija",
    city: "Vancouver",
    country: "Canada",
    bio: "Vancouver. Double bass luthier.",
  }),
  bass({
    slug: "robert-tichy",
    name: "Robert Tichy",
    city: "",
    country: "Czechia",
    bio: "Czech double bass maker.",
  }),
  bass({
    slug: "jiri-kropik",
    name: "Jiri Kropik",
    city: "",
    country: "Czechia",
    bio: "Czech double bass maker.",
  }),
  bass({
    slug: "strunal-schonbach",
    name: "Strunal Schönbach",
    city: "Luby",
    country: "Czechia",
    bio: "Luby. Production of double basses and other string instruments.",
  }),
  bass({
    slug: "jean-auray",
    name: "Jean Auray",
    city: "Villefranche-sur-Saône",
    country: "France",
    site: "http://www.jauray.com/",
    address: "888 route de Riottier, 69400 Villefranche-sur-Saône, France",
    phone: "+33 4 74 60 00 73",
    email: "aurayjean.luthier@wanadoo.fr",
    contact: "mailto:aurayjean.luthier@wanadoo.fr",
    bio: "Villefranche-sur-Saône. Double bass specialist — travel basses with removable necks. Played by Charlie Haden, Renaud Garcia-Fons and others.",
  }),
  bass({
    slug: "christian-laborie",
    name: "Christian Laborie",
    city: "Varacieux",
    country: "France",
    bio: "Varacieux. Double bass maker.",
  }),
  bass({
    slug: "patrick-charton",
    name: "Patrick Charton",
    city: "Paris",
    country: "France",
    bio: "Paris area. Double bass luthier.",
  }),
  bass({
    slug: "fabrice-gougi",
    name: "Fabrice Gougi",
    city: "Penmarch",
    country: "France",
    bio: "Penmarch. Jazz setup specialist for double bass.",
  }),
  bass({
    slug: "em-pollmann",
    name: "EM Pöllmann",
    city: "Mittenwald",
    country: "Germany",
    site: "https://poellmann-contrabass.de/en/",
    address: "Elmauer Weg 17, 82481 Mittenwald, Germany",
    phone: "+49 8823 4548",
    email: "info@poellmann-contrabass.de",
    contact: "mailto:info@poellmann-contrabass.de",
    bio: "Mittenwald. Traditional contrabass makers — the Pöllmann line, now the Krahmer workshop.",
  }),
  bass({
    slug: "stefan-krattenmacher",
    name: "Stefan Johann Krattenmacher",
    city: "Münchweier",
    country: "Germany",
    bio: "Münchweier. Double bass maker.",
  }),
  bass({
    slug: "horst-grunert",
    name: "Horst Grünert",
    city: "Penzberg",
    country: "Germany",
    site: "https://gruenert.com/",
    address: "Postgasse 2, Penzberg, Germany",
    bio: "Penzberg. Grünert double basses and cellos — new instruments, repairs and the shop atelier.",
  }),
  bass({
    slug: "andreas-wilfer",
    name: "Andreas Wilfer",
    city: "Nauheim",
    country: "Germany",
    bio: "Nauheim. Cello and double bass specialist.",
  }),
  bass({
    slug: "bjorn-stoll",
    name: "Björn Stoll",
    city: "Erlbach",
    country: "Germany",
    bio: "Erlbach. Double bass maker.",
  }),
  bass({
    slug: "heiner-windelband",
    name: "Heiner Windelband",
    city: "Suennenblink",
    country: "Germany",
    bio: "Suennenblink Musikwerkstatt. Double bass making and repair.",
  }),
  bass({
    slug: "emanuel-wilfer",
    name: "Emanuel Wilfer",
    city: "Mittenwald",
    country: "Germany",
    bio: "Mittenwald / Bubenreuth tradition. Double bass maker.",
  }),
  bass({
    slug: "barnabas-racz",
    name: "Barnabas Racz",
    city: "",
    country: "Hungary",
    bio: "Hungarian double bass maker — also works in Germany.",
  }),
  bass({
    slug: "sergio-scaramelli",
    name: "Sergio Scaramelli",
    city: "Ferrara",
    country: "Italy",
    site: "https://www.italiandoublebasses.com/",
    bio: "Ferrara. Specialist double bass maker and restorer in the Emilian tradition.",
  }),
  bass({
    slug: "luciano-golia",
    name: "Luciano Golia",
    city: "",
    country: "Italy",
    bio: "Italian double bass maker.",
  }),
  bass({
    slug: "edgar-russ",
    name: "Edgar Russ",
    city: "Cremona",
    country: "Italy",
    bio: "Cremona. Double bass and stringed-instrument making.",
  }),
  bass({
    slug: "alessandro-ciciliati",
    name: "Alessandro Ciciliati",
    city: "Ferrara",
    country: "Italy",
    bio: "Ferrara. Double bass maker.",
  }),
  bass({
    slug: "rene-zaal",
    name: "René Zaal",
    city: "Bemmel",
    country: "Netherlands",
    site: "https://www.renezaal.nl/",
    bio: "Bemmel. Maker, restorer and dealer of double basses.",
  }),
  bass({
    slug: "harry-jansen",
    name: "Harry Jansen",
    city: "Amsterdam",
    country: "Netherlands",
    bio: "Amsterdam. Double bass maker and restorer.",
  }),
  bass({
    slug: "hendrik-van-den-broek",
    name: "Hendrik van den Broek",
    city: "",
    country: "Netherlands",
    bio: "Dutch double bass maker.",
  }),
  bass({
    slug: "lucas-suringar",
    name: "Lucas Suringar",
    city: "",
    country: "Netherlands",
    bio: "Dutch double bass maker.",
  }),
  bass({
    slug: "hora-reghin",
    name: "Hora",
    city: "Reghin",
    country: "Romania",
    site: "https://hora-instruments.com/",
    bio: "Reghin. Large Romanian workshop producing double basses and other string instruments.",
  }),
  bass({
    slug: "alexandru-ozon",
    name: "Alexandru Ozon",
    city: "Bucharest",
    country: "Romania",
    bio: "Bucharest. Double bass luthier.",
  }),
  bass({
    slug: "harsan-mihaila",
    name: "Harsan Mihaila",
    city: "",
    country: "Romania",
    bio: "Romanian double bass maker.",
  }),
  bass({
    slug: "peter-elias",
    name: "Peter Elias",
    city: "Ollon",
    country: "Switzerland",
    site: "https://eliasbasses.wordpress.com/",
    bio: "Ollon. Double basses and cellos. Canadian-born, working in Switzerland.",
  }),
  bass({
    slug: "thomas-george-martin",
    name: "Thomas & George Martin",
    city: "Banbury",
    country: "United Kingdom",
    bio: "Banbury, Oxfordshire. Double bass making.",
  }),
  bass({
    slug: "paul-n-bryant",
    name: "Paul N. Bryant / Bryant Basses",
    city: "Kidderminster",
    country: "United Kingdom",
    site: "https://bryantbasses.co.uk/",
    bio: "Kidderminster. Hand-made English double basses.",
  }),
  bass({
    slug: "neal-heppleston",
    name: "Neal Heppleston",
    city: "Mirfield",
    country: "United Kingdom",
    bio: "Mirfield, West Yorkshire. Double bass maker.",
  }),
  bass({
    slug: "martin-penning",
    name: "Martin Penning",
    city: "Frome",
    country: "United Kingdom",
    bio: "Frome, Somerset. Double bass maker.",
  }),
  bass({
    slug: "martyn-j-bailey",
    name: "Martyn J. Bailey",
    city: "North Essex",
    country: "United Kingdom",
    bio: "North Essex. Double bass maker.",
  }),
  bass({
    slug: "upton-bass",
    name: "Upton Bass",
    city: "Mystic, Connecticut",
    country: "United States",
    site: "https://uptonbass.com/",
    address: "159 Packer Rd, Mystic, CT 06355, United States",
    phone: "+1 860 535 9399",
    hours: "By appointment",
    bio: "Mystic, Connecticut. Handmade double basses, vintage instruments, repair and restoration.",
  }),
  bass({
    slug: "nick-lloyd",
    name: "Nick Lloyd",
    city: "Cincinnati, Ohio",
    country: "United States",
    bio: "Cincinnati. Double bass maker.",
  }),
  bass({
    slug: "robertson-and-sons",
    name: "Robertson & Sons",
    city: "Albuquerque, New Mexico",
    country: "United States",
    site: "https://www.robertsonviolins.com/",
    address: "3201 Carlisle Blvd NE, Albuquerque, NM 87110, United States",
    phone: "+1 505 889 2999",
    hours: "Tue–Sat — call the shop",
    bio: "Albuquerque. Major string shop with a strong double bass desk — sales, setup and restoration.",
  }),
  bass({
    slug: "kolstein-sons",
    name: "Kolstein & Sons",
    city: "Baldwin, New York",
    country: "United States",
    site: "https://kolstein.com/",
    address: "720 Sunrise Hwy, Baldwin, NY 11510, United States",
    phone: "+1 516 546 9300",
    email: "info@kolstein.com",
    contact: "mailto:info@kolstein.com",
    bio: "Baldwin, Long Island. Samuel Kolstein & Son — double basses, bows, restoration. A working American bass shop since 1943.",
  }),
  bass({
    slug: "thomas-andres-wolf",
    name: "Thomas Andres / Wolf Instruments",
    city: "The Plains, Virginia",
    country: "United States",
    site: "https://wolfinstruments.com/",
    bio: "The Plains, Virginia. Historic keyboard and double bass making.",
  }),
  bass({
    slug: "alberto-solari",
    name: "Alberto Solari",
    city: "Buenos Aires",
    country: "Argentina",
    bio: "Buenos Aires. Double bass luthier.",
  }),
  bass({
    slug: "auday-giormenti",
    name: "Auday-Giormenti",
    city: "Buenos Aires",
    country: "Argentina",
    bio: "Argentina. Double bass making.",
  }),
  bass({
    slug: "linear-kontrabass",
    name: "Linear Kontrabass",
    city: "",
    country: "South Korea",
    bio: "South Korea. Linear Kontrabass luthier workshop.",
  }),
];

const BASS_NOTES: Record<string, string> = {
  "kanzian-traunsteiner": "New instruments, repairs & sound work",
  "benedict-puglisi": "New instruments, repairs & restorations",
  "matthew-tucker": "Making, repairs & setup",
  "bass-works-australia": "Instruments, repairs & restorations",
  "neville-whitehead": "Making, restoration & repair",
  "jacky-walraet": "Setup, repairs, extensions & construction",
  "jean-franco-fiorini": "Belo Horizonte — making and restoration",
  "andrea-spada": "Rio de Janeiro workshop",
  "paulo-gomes": "Brazilian double bass workshop",
  "kai-arvi": "Handmade double basses",
  "james-ham": "Maker and restorer",
  "mario-lamarre": "Contemporary stringed instruments",
  "masa-miki-inokuchi": "Making and restoration",
  "gerard-ivan-samija": "Vancouver workshop",
  "robert-tichy": "Czech workshop — new instruments",
  "jiri-kropik": "Czech workshop — new instruments",
  "strunal-schonbach": "Production workshop",
  "jean-auray": "Travel basses & new instruments",
  "christian-laborie": "Varacieux — new instruments",
  "patrick-charton": "Double bass luthier",
  "fabrice-gougi": "Jazz setup specialist",
  "em-pollmann": "Traditional contrabass makers",
  "stefan-krattenmacher": "Münchweier — new instruments",
  "horst-grunert": "New instruments, repairs & the shop atelier",
  "andreas-wilfer": "Cello and double bass specialist",
  "bjorn-stoll": "Erlbach — new instruments",
  "heiner-windelband": "Making and repair",
  "emanuel-wilfer": "Mittenwald / Bubenreuth tradition",
  "barnabas-racz": "Hungarian workshop — new instruments",
  "sergio-scaramelli": "Making and restoration",
  "luciano-golia": "Ferrara — new instruments",
  "edgar-russ": "Double bass and stringed-instrument making",
  "alessandro-ciciliati": "Italian workshop — new instruments",
  "rene-zaal": "Maker, restorer & dealer",
  "harry-jansen": "Maker and restorer",
  "hendrik-van-den-broek": "Amsterdam — making and restoration",
  "lucas-suringar": "Amsterdam workshop",
  "hora-reghin": "Production workshop",
  "alexandru-ozon": "Double bass luthier",
  "harsan-mihaila": "Romanian workshop — new instruments",
  "peter-elias": "Double basses and cellos",
  "thomas-george-martin": "Double bass making",
  "paul-n-bryant": "Hand-made English double basses",
  "neal-heppleston": "Mirfield, West Yorkshire — new instruments",
  "martin-penning": "Frome, Somerset — new instruments",
  "martyn-j-bailey": "North Essex — new instruments",
  "upton-bass": "Handmade & vintage, repair & restoration",
  "nick-lloyd": "Cincinnati — new instruments",
  "robertson-and-sons": "Sales, setup & restoration",
  "kolstein-sons": "Basses, bows & restoration",
  "thomas-andres-wolf": "Historic keyboard and double bass making",
  "alberto-solari": "Double bass luthier",
  "auday-giormenti": "Double bass making",
  "linear-kontrabass": "Luthier workshop",
};

const VIOLIN_LUTHIERS: Luthier[] = [
  violin({
    slug: "grisales-lutherie",
    name: "Grisales Lutherie",
    city: "Cremona",
    country: "Italy",
    site: "https://www.grisales.it/",
    bio: "Cremona workshop founded by Giorgio Grisales. Violins, violas, cellos and double basses, plus restoration of antique instruments.",
    note: "New instruments and restoration",
  }),
  violin({
    slug: "stefano-conia",
    name: "Stefano Conia",
    city: "Cremona",
    country: "Italy",
    site: "http://www.stefanoconia.com/",
    bio: "Cremona. Hungarian-born contemporary maker of violins, violas and cellos after classical Cremonese models.",
    note: "Cremonese violins, violas and cellos",
  }),
  violin({
    slug: "stefano-conia-il-giovane",
    name: "Stefano Conia Il Giovane",
    city: "Cremona",
    country: "Italy",
    site: "https://www.stefanoconia.eu/",
    bio: "Cremona workshop of Stefano Conia “Il Giovane” — handmade violins, violas and cellos, and professional restoration.",
    note: "Making and restoration",
  }),
  violin({
    slug: "mauro-lucini",
    name: "Mauro Lucini",
    city: "Cremona",
    country: "Italy",
    site: "https://www.mauro-lucini.it/",
    bio: "Cremona. Contemporary violin-making workshop in the Cremonese tradition.",
    note: "Contemporary Cremonese making",
  }),
  violin({
    slug: "carlson-neumann",
    name: "Carlson & Neumann",
    city: "Cremona",
    country: "Italy",
    site: "https://www.ccnviolins.it/",
    bio: "Cremona. Bruce Carlson and Bernard Neumann — making, restoration and conservation of string instruments.",
    note: "Restoration and making",
  }),
  violin({
    slug: "vatelot-rampal",
    name: "Vatelot-Rampal",
    city: "Paris",
    country: "France",
    site: "http://www.vatelot-rampal.com/en/",
    address: "11 bis rue Portalis, 75008 Paris, France",
    email: "contact@vatelot-rampal.com",
    contact: "mailto:contact@vatelot-rampal.com",
    hours: "Tue–Fri — by appointment",
    bio: "Paris workshop on rue Portalis. Fine restoration, setup and everyday maintenance of string instruments, plus expertise and certificates.",
    note: "Restoration, setup and expertise",
  }),
  violin({
    slug: "pierre-jaffre",
    name: "Pierre Jaffré Luthier",
    city: "Paris",
    country: "France",
    site: "https://www.pierrejaffreluthier.com/",
    address: "65 rue de Rome, 75008 Paris, France",
    hours: "Mon–Sat 10:00–19:00",
    bio: "Paris, rue de Rome. Workshop and shop for the sale, setup and repair of violins, violas and cellos.",
    note: "Sales, setup and repair",
  }),
  violin({
    slug: "luthiers-mirecourt",
    name: "Cognier & Terrier / Luthiers Mirecourt",
    city: "Mirecourt",
    country: "France",
    site: "https://www.luthiers-mirecourt.com/",
    bio: "Mirecourt, the historic French violin-making town. Workshop of Jean-Philippe Cognier and Roland Terrier — making, maintenance and repair.",
    note: "Making, maintenance and repair",
  }),
  violin({
    slug: "maison-bernard",
    name: "Maison Bernard",
    city: "Brussels",
    country: "Belgium",
    site: "https://www.maison-bernard.com/",
    address: "Rue Ernest Allard 38, 1000 Brussels, Belgium",
    email: "info@maison-bernard.com",
    contact: "mailto:info@maison-bernard.com",
    bio: "Brussels. Jan Strick and Pierre Guillaume — fine violins, violas and cellos, restoration and expertise.",
    note: "Fine instruments, restoration and expertise",
  }),
  violin({
    slug: "thomas-meuwissen",
    name: "Thomas Meuwissen",
    city: "Brussels",
    country: "Belgium",
    site: "https://thomasmeuwissen.com/",
    bio: "Brussels. Master luthier — new and baroque violins, violas and cellos, restoration and certificates.",
    note: "Making, restoration and certificates",
  }),
  violin({
    slug: "meteny-pascal-gilis",
    name: "Pascal Gilis / Atelier Meteny",
    city: "Brussels",
    country: "Belgium",
    site: "http://www.meteny.be/",
    address: "Avenue de Broqueville 245/13, 1200 Brussels, Belgium",
    bio: "Brussels. Meteny workshop — restoration, sales, setup, rentals and new instruments.",
    note: "Making, restoration and setup",
  }),
  violin({
    slug: "heilbron-van-geldre",
    name: "Heilbron & van Geldre",
    city: "Amsterdam",
    country: "Netherlands",
    site: "https://www.heilbronvangeldre.com/",
    bio: "Amsterdam. Fine violins and bows — sales, and a workshop specialised in sound adjustment.",
    note: "Fine violins and sound adjustment",
  }),
  violin({
    slug: "camille-dolibeau",
    name: "Camille Dolibeau",
    city: "Amsterdam",
    country: "Netherlands",
    site: "https://www.camilledolibeau.com/",
    bio: "Amsterdam. Violin maker — new instruments and restoration.",
    note: "Making and restoration",
  }),
  violin({
    slug: "achttienribbe-vioolbouw",
    name: "Achttienribbe Vioolbouw",
    city: "Amsterdam",
    country: "Netherlands",
    site: "https://www.achttienribbe.com/",
    bio: "Amsterdam. Chaim Achttienribbe — making, restoration, repair and sales of violins, violas, cellos and bows.",
    note: "Making, restoration and sales",
  }),
  violin({
    slug: "matthieu-besseling",
    name: "Matthieu Besseling",
    city: "Amsterdam",
    country: "Netherlands",
    site: "http://www.violinsbesseling.com/",
    bio: "Amsterdam, Keizersgracht. Contemporary maker of violins and violas.",
    note: "New instruments",
  }),
  violin({
    slug: "martin-schleske",
    name: "Martin Schleske",
    city: "Munich",
    country: "Germany",
    site: "https://www.schleske.de/",
    email: "violins@schleske.de",
    contact: "mailto:violins@schleske.de",
    bio: "Munich area. Master studio and acoustics laboratory — new violins, not restoration.",
    note: "New instruments and acoustics research",
  }),
  violin({
    slug: "andrea-durr",
    name: "Andrea Dürr",
    city: "Berlin",
    country: "Germany",
    site: "https://www.geigenbauerin.berlin/",
    bio: "Berlin-Schöneberg. Repair and restoration of violins, violas and cellos, plus sales and rentals.",
    note: "Repair, restoration and sales",
  }),
  violin({
    slug: "matthias-von-wallbrunn",
    name: "Matthias N. von Wallbrunn",
    city: "Berlin",
    country: "Germany",
    site: "https://www.von-wallbrunn.de/",
    bio: "Berlin-Kreuzberg. Maker of fine violins, violas and cellos.",
    note: "New violins, violas and cellos",
  }),
  violin({
    slug: "j-and-a-beare",
    name: "J & A Beare",
    city: "London",
    country: "United Kingdom",
    site: "https://www.beares.com/",
    bio: "London. International violin dealer and restoration workshop — fine instruments, certificates and expertise.",
    note: "Fine instruments, restoration and expertise",
  }),
  violin({
    slug: "florian-leonhard",
    name: "Florian Leonhard Fine Violins",
    city: "London",
    country: "United Kingdom",
    site: "https://www.florianleonhard.com/",
    address: "3 Frognal Lane, London NW3 7DY, United Kingdom",
    email: "info@florianleonhard.com",
    contact: "mailto:info@florianleonhard.com",
    bio: "London. Fine violins, restoration, copies and consultancy.",
    note: "Fine instruments, restoration and copies",
  }),
  violin({
    slug: "gliga-reghin",
    name: "Gliga",
    city: "Reghin",
    country: "Romania",
    site: "https://www.gliga.com/",
    bio: "Reghin. Handmade violins, violas, cellos and double basses from the Romanian workshop of Vasile Gliga.",
    note: "Handmade workshop instruments",
  }),
  violin({
    slug: "gergely-ficsor",
    name: "Gergely Ficsor",
    city: "Budapest",
    country: "Hungary",
    site: "https://www.ficsorviolin.com/",
    address: "Wesselényi utca 21, 1077 Budapest, Hungary",
    bio: "Budapest. Making and repairing violins, violas, cellos and bows.",
    note: "Making and repair",
  }),
  violin({
    slug: "laszlo-ronai",
    name: "László Rónai",
    city: "Budapest",
    country: "Hungary",
    site: "https://www.ronaiviolin.hu/",
    bio: "Budapest. String-instrument making, repair and restoration of antique instruments.",
    note: "Making and restoration",
  }),
  violin({
    slug: "darius-music",
    name: "Darius Music",
    city: "Budapest",
    country: "Hungary",
    site: "https://dariusmusic.hu/",
    bio: "Budapest. Violin shop and workshop — sales, repair and instrument making.",
    note: "Shop and repair workshop",
  }),
  violin({
    slug: "ifshin-violins",
    name: "Ifshin Violins",
    city: "El Cerrito, California",
    country: "United States",
    site: "https://www.ifshinviolins.com/",
    address: "6420 Fairmount Ave, El Cerrito, CA 94530, United States",
    phone: "+1 510 843 5466",
    email: "info@ifshinviolins.com",
    contact: "mailto:info@ifshinviolins.com",
    hours: "Tue–Fri 10:30–17:00, Sat 10:30–16:00 (no repairs Sat)",
    bio: "El Cerrito, California. Full-service violin shop — sales, repairs, rentals and setup.",
    note: "Full-service violin shop",
  }),
  violin({
    slug: "reuning-and-son",
    name: "Reuning & Son Violins",
    city: "Boston, Massachusetts",
    country: "United States",
    site: "https://www.reuning.com/",
    email: "info@reuning.com",
    contact: "mailto:info@reuning.com",
    hours: "By appointment",
    bio: "Boston (and New York by appointment). Fine violins, violas and cellos — sales, certificates and expertise.",
    note: "Fine instruments and expertise",
  }),
  violin({
    slug: "luthier-vidal",
    name: "Luthier Vidal",
    city: "Barcelona",
    country: "Spain",
    site: "https://luthiervidal.com/",
    email: "info@luthiervidal.com",
    contact: "mailto:info@luthiervidal.com",
    bio: "Barcelona. Xavier Vidal — making, repair, rental and sale of violins, violas and cellos.",
    note: "Making, repair, rental and sales",
  }),
];

export const LUTHIERS: Luthier[] = [
  ...GUITAR_LUTHIERS,
  ...BASS_LUTHIERS.map((row) => ({
    ...row,
    note: BASS_NOTES[row.slug] ?? row.note,
  })),
  ...VIOLIN_LUTHIERS,
];

export function getLuthier(slug: string) {
  return LUTHIERS.find((row) => row.slug === slug);
}

export function splitLuthiers(rows: Luthier[]) {
  return {
    guitar: rows.filter((row) => row.craft === "guitar"),
    bass: rows.filter((row) => row.craft === "bass"),
    violin: rows.filter((row) => row.craft === "violin"),
  };
}

export function luthiersByCountry(extra: Luthier[] = []) {
  const all = [...LUTHIERS];
  for (const row of extra) {
    if (!all.some((item) => item.slug === row.slug)) all.push(row);
  }
  const counts: Record<string, number> = {};
  for (const row of all) counts[row.country] = (counts[row.country] ?? 0) + 1;
  const present = [...new Set(all.map((row) => row.country))];
  const lead = ["Italy", "France"].filter((name) => present.includes(name));
  const rest = present
    .filter((name) => !lead.includes(name))
    .sort((a, b) => (counts[b] ?? 0) - (counts[a] ?? 0) || a.localeCompare(b));
  return [...lead, ...rest].map((country) => ({
    country,
    luthiers: all
      .filter((row) => row.country === country)
      .sort((a, b) => a.name.localeCompare(b.name)),
  }));
}

export function luthiersByCountryForCraft(craft: LuthierCraft, extra: Luthier[] = []) {
  return luthiersByCountry(extra)
    .map((group) => ({
      ...group,
      luthiers: group.luthiers.filter((row) => row.craft === craft),
    }))
    .filter((group) => group.luthiers.length);
}

export function bassLuthiersByCountry(extra: Luthier[] = []) {
  return luthiersByCountryForCraft("bass", extra);
}

export function violinLuthiersByCountry(extra: Luthier[] = []) {
  return luthiersByCountryForCraft("violin", extra);
}

export function siteHost(url: string) {
  if (!url.trim()) return "";
  try {
    return new URL(url).host.replace(/^www\./, "");
  } catch {
    return url.replace(/^https?:\/\/(www\.)?/i, "").replace(/\/.*$/, "");
  }
}
