/** Short luthier / shop captions on country lists. Missing locale falls back to a craft line. */

const BIOS: Record<string, Record<string, string>> = {
  "mauro-freschi": {
    fr: "Spresiano. Archtop et guitares manouche Selmer-Maccaferri depuis 2003. Gismo Graf a joué ses instruments.",
    de: "Spresiano. Archtop- und Selmer-Maccaferri-Manouche-Gitarren seit 2003. Gismo Graf spielte seine Instrumente.",
    nl: "Spresiano. Archtop- en Selmer-Maccaferri-manouchegitaren sinds 2003.",
    it: "Spresiano. Archtop e chitarre manouche Selmer-Maccaferri dal 2003.",
    es: "Spresiano. Archtop y guitarras manouche Selmer-Maccaferri desde 2003.",
    pt: "Spresiano. Archtop e guitarras manouche Selmer-Maccaferri desde 2003.",
  },
  "emanuele-dalo": {
    fr: "Milan. Archtops faits main, joués dans la scène manouche. shankinstruments.com.",
    de: "Mailand. Handgebaute Archtops in der Manouche-Szene. shankinstruments.com.",
    nl: "Milaan. Handgemaakte archtops in de manouchescene.",
    it: "Milano. Archtop artigianali usate nella scena manouche. shankinstruments.com.",
    es: "Milán. Archtops artesanales en la escena manouche.",
    pt: "Milão. Archtops artesanais na cena manouche.",
  },
  "fulvio-cappelli": {
    fr: "Volterra. Modèles manouche et archtops. acousticliuteria.it.",
    de: "Volterra. Manouche-Modelle und Archtops. acousticliuteria.it.",
    nl: "Volterra. Manouchemodellen en archtops.",
    it: "Volterra. Modelli manouche e archtop. acousticliuteria.it.",
    es: "Volterra. Modelos manouche y archtops.",
    pt: "Volterra. Modelos manouche e archtops.",
  },
  "riccardo-mordeglia": {
    fr: "Ferrare. Spécialiste des guitares gypsy Maccaferri et Mozzani. Annonces sur DjangoBooks.",
    de: "Ferrara. Spezialist für Maccaferri- und Mozzani-Gypsy-Gitarren. Inserate auf DjangoBooks.",
    nl: "Ferrara. Specialist in Maccaferri- en Mozzani-gypsygitaren. DjangoBooks.",
    it: "Ferrara. Specialista di chitarre gypsy Maccaferri e Mozzani. Annunci su DjangoBooks.",
    es: "Ferrara. Especialista en guitarras gypsy Maccaferri y Mozzani. DjangoBooks.",
    pt: "Ferrara. Especialista em guitarras gypsy Maccaferri e Mozzani. DjangoBooks.",
  },
  "maurice-dupont": {
    fr: "Cognac. Élève de Jacques Favino, Meilleur Ouvrier de France. Les Dupont sont le Selmer français de travail d’une génération.",
    de: "Cognac. Schüler von Jacques Favino, Meilleur Ouvrier de France. Dupont-Gitarren sind der französische Selmer einer Generation.",
    nl: "Cognac. Leerling van Jacques Favino, Meilleur Ouvrier de France.",
    it: "Cognac. Allievo di Jacques Favino, Meilleur Ouvrier de France.",
    es: "Cognac. Aprendiz de Jacques Favino, Meilleur Ouvrier de France.",
    pt: "Cognac. Aprendiz de Jacques Favino, Meilleur Ouvrier de France.",
  },
  "jean-barault": {
    fr: "Luthier français. Guitares gypsy jazz Barault — le toucher Favino, construit maintenant.",
    de: "Französischer Gitarrenbauer. Barault Gypsy-Jazz-Gitarren — Favino-Gefühl, heute gebaut.",
    nl: "Franse gitaarbouwer. Barault gypsy-jazzgitaren — Favino-gevoel, nu gebouwd.",
    it: "Liutaio francese. Chitarre gypsy jazz Barault — feeling Favino, costruite ora.",
    es: "Luthier francés. Guitarras gypsy jazz Barault — el tacto Favino, construidas ahora.",
    pt: "Luthier francês. Guitarras gypsy jazz Barault — o toque Favino, construídas agora.",
  },
  "castelluccia": {
    fr: "Le plus ancien magasin gypsy jazz encore ouvert à Paris. Jean-Baptiste Castelluccia tient la ligne familiale de Jacques.",
    de: "Der älteste noch offene Gypsy-Jazz-Laden in Paris. Jean-Baptiste Castelluccia führt die Familienlinie von Jacques.",
    nl: "De oudste gypsy-jazzzaak die nog open is in Parijs. Jean-Baptiste Castelluccia draagt de familielijn van Jacques.",
    it: "Il negozio gypsy jazz più antico ancora aperto a Parigi. Jean-Baptiste Castelluccia porta la linea di famiglia di Jacques.",
    es: "La tienda gypsy jazz más antigua aún abierta en París. Jean-Baptiste Castelluccia sigue la línea familiar de Jacques.",
    pt: "A loja gypsy jazz mais antiga ainda aberta em Paris. Jean-Baptiste Castelluccia segue a linha familiar de Jacques.",
  },
  "jean-pierre-favino": {
    fr: "Fils de Jacques Favino. L’atelier Favino est fermé ; les guitares restent la mesure — Modèle S et les oval-hole de la famille.",
    de: "Sohn von Jacques Favino. Die Favino-Werkstatt ist geschlossen; die Gitarren bleiben der Maßstab.",
    nl: "Zoon van Jacques Favino. Het Favino-atelier is gesloten; de gitaren blijven de maat.",
    it: "Figlio di Jacques Favino. L’atelier Favino è chiuso; le chitarre restano la misura.",
    es: "Hijo de Jacques Favino. El taller Favino está cerrado; las guitarras siguen siendo la medida.",
    pt: "Filho de Jacques Favino. A oficina Favino está fechada; as guitarras continuam a medida.",
  },
  "leo-eimers": {
    fr: "Facteur néerlandais de guitares Selmer/Maccaferri depuis plus de vingt-cinq ans. Joueur et luthier — restaurations Favino, Busato, Di Mauro.",
    de: "Niederländischer Bauer von Selmer/Maccaferri-Gitarren seit mehr als 25 Jahren. Spieler und Gitarrenbauer.",
    nl: "Nederlandse bouwer van Selmer/Maccaferri-gitaren al meer dan vijfentwintig jaar. Speler en luthier.",
    it: "Costruttore olandese di chitarre Selmer/Maccaferri da più di venticinque anni.",
    es: "Constructor holandés de guitarras Selmer/Maccaferri desde hace más de veinticinco años.",
    pt: "Construtor holandês de guitarras Selmer/Maccaferri há mais de vinte e cinco anos.",
  },
  "rino-van-hooydonk": {
    fr: "Joueur-luthier néerlandais. Près de vingt ans sur les guitares gypsy jazz Selmer — grave fort, aigus croustillants.",
    de: "Niederländischer Spieler-Gitarrenbauer. Fast zwanzig Jahre Selmer-Gypsy-Jazz-Gitarren.",
    nl: "Nederlandse speler-bouwer. Bijna twintig jaar Selmer-stijl gypsy-jazzgitaren.",
    it: "Suonatore-liutaio olandese. Quasi vent’anni su chitarre gypsy jazz Selmer.",
    es: "Tocador-luthier holandés. Casi veinte años en guitarras gypsy jazz Selmer.",
    pt: "Tocador-luthier holandês. Quase vinte anos em guitarras gypsy jazz Selmer.",
  },
  "stefan-hahl": {
    fr: "Maître luthier à Mudershausen. Guitares Hahl Selmer-Maccaferri — construction allemande, équilibre et projection.",
    de: "Meistergitarrenbauer in Mudershausen. Hahl Selmer-Maccaferri — deutscher Bau, Balance und Projektion.",
    nl: "Meesterbouwer in Mudershausen. Hahl Selmer-Maccaferri — Duitse bouw, balans en projectie.",
    it: "Maestro liutaio a Mudershausen. Chitarre Hahl Selmer-Maccaferri.",
    es: "Maestro luthier en Mudershausen. Guitarras Hahl Selmer-Maccaferri.",
    pt: "Mestre luthier em Mudershausen. Guitarras Hahl Selmer-Maccaferri.",
  },
  "nicolas-perez": {
    fr: "Né en France, atelier à Berlin. Guitares acoustiques et gypsy jazz haut de gamme.",
    de: "In Frankreich geboren, Werkstatt in Berlin. High-End-Akustik- und Gypsy-Jazz-Gitarren.",
    nl: "In Frankrijk geboren, atelier in Berlijn. High-end akoestische en gypsy-jazzgitaren.",
    it: "Nato in Francia, bottega a Berlino. Chitarre acustiche e gypsy jazz di alto livello.",
    es: "Nacido en Francia, taller en Berlín. Guitarras acústicas y gypsy jazz de alto nivel.",
    pt: "Nascido em França, oficina em Berlim. Guitarras acústicas e gypsy jazz de alto nível.",
  },
  "ajl-guitars": {
    fr: "Selmer faits main par Ari-Jukka Luomaranta. Détail, jouabilité, oval-hole et D-hole modernes.",
    de: "Handgebaute Selmer von Ari-Jukka Luomaranta. Detail, Spielbarkeit, moderne Oval- und D-Löcher.",
    nl: "Handgebouwde Selmers van Ari-Jukka Luomaranta.",
    it: "Selmer fatte a mano da Ari-Jukka Luomaranta.",
    es: "Selmer hechas a mano por Ari-Jukka Luomaranta.",
    pt: "Selmer feitas à mão por Ari-Jukka Luomaranta.",
  },
  tfoa: {
    fr: "Grand spécialiste acoustique avec un rayon Gypsy Jazz et du stock Selmer régulier. Une des salles les plus connues d’Europe pour ça.",
    de: "Großer Akustik-Spezialist mit Gypsy-Jazz-Abteilung und regelmäßigem Selmer-Bestand.",
    nl: "Grote akoestische specialist met een Gypsy Jazz-afdeling en regelmatig Selmer-voorraad.",
    it: "Grande specialista acustico con reparto Gypsy Jazz e stock Selmer regolare.",
    es: "Gran especialista acústico con sección Gypsy Jazz y stock Selmer regular.",
    pt: "Grande especialista acústico com secção Gypsy Jazz e stock Selmer regular.",
  },
  "galerie-casanova": {
    fr: "Anciennement R & F Charle. Boutique légendaire à la Galerie Véro-Dodat — une des salles les plus importantes au monde pour le Selmer-Maccaferri.",
    de: "Früher R & F Charle. Legendärer Pariser Laden in der Galerie Véro-Dodat — einer der wichtigsten Räume der Welt für Selmer-Maccaferri.",
    nl: "Voorheen R & F Charle. Legendarische Parijse zaak in Galerie Véro-Dodat.",
    it: "Ex R & F Charle. Negozio leggendario a Parigi in Galerie Véro-Dodat.",
    es: "Antes R & F Charle. Tienda legendaria en Galerie Véro-Dodat, París.",
    pt: "Antes R & F Charle. Loja lendária na Galerie Véro-Dodat, Paris.",
  },
  "castelluccia-shop": {
    fr: "Atelier familial historique, spécialisé dans les guitares gypsy jazz Selmer. Sur rendez-vous à Paris ; l’atelier travaille aussi depuis Honfleur.",
    de: "Historische Familienwerkstatt für Selmer-Gypsy-Jazz-Gitarren. In Paris nach Termin; die Werkstatt arbeitet auch aus Honfleur.",
    nl: "Historisch familieatelier voor Selmer-stijl gypsy-jazzgitaren. Op afspraak in Parijs.",
    it: "Bottega familiare storica per chitarre gypsy jazz Selmer. Su appuntamento a Parigi.",
    es: "Taller familiar histórico de guitarras gypsy jazz Selmer. Con cita en París.",
    pt: "Oficina familiar histórica de guitarras gypsy jazz Selmer. Por marcação em Paris.",
  },
  "django-guitars": {
    fr: "Boutique gypsy jazz sur la côte californienne. Instruments européens neufs et vintage — Dupont, Favino, Busato.",
    de: "Gypsy-Jazz-Laden an der kalifornischen Küste. Neue und vintage europäische Instrumente — Dupont, Favino, Busato.",
    nl: "Gypsy-jazzzaak aan de Californische kust. Nieuwe en vintage Europese instrumenten.",
    it: "Negozio gypsy jazz sulla costa californiana. Strumenti europei nuovi e vintage.",
    es: "Tienda gypsy jazz en la costa de California. Instrumentos europeos nuevos y vintage.",
    pt: "Loja gypsy jazz na costa da Califórnia. Instrumentos europeus novos e vintage.",
  },
  gypsyguitar: {
    fr: "Boutique spécialisée de Norman Ort — stock ciblé, réglages et la ligne Selmer-Maccaferri.",
    de: "Norman Orts Fachladen — gezielter Bestand, Setups und die Selmer-Maccaferri-Linie.",
    nl: "Norman Orts specialistzaak — gerichte voorraad, setups en de Selmer-Maccaferri-lijn.",
    it: "Negozio specializzato di Norman Ort — stock mirato e la linea Selmer-Maccaferri.",
    es: "Tienda especializada de Norman Ort — stock concreto y la línea Selmer-Maccaferri.",
    pt: "Loja especializada de Norman Ort — stock focado e a linha Selmer-Maccaferri.",
  },
  "musik-heckmann": {
    fr: "Près de Munich. Stock régulier de Geronimo Mateos et d’autres modèles gypsy jazz.",
    de: "Bei München. Regelmäßig Geronimo Mateos und andere Gypsy-Jazz-Modelle.",
    nl: "Bij München. Regelmatig Geronimo Mateos en andere gypsy-jazzmodellen.",
    it: "Vicino a Monaco. Stock regolare di Geronimo Mateos e altri modelli gypsy jazz.",
    es: "Cerca de Múnich. Stock regular de Geronimo Mateos y otros modelos gypsy jazz.",
    pt: "Perto de Munique. Stock regular de Geronimo Mateos e outros modelos gypsy jazz.",
  },
  "london-guitar-studio": {
    fr: "Guitares gypsy jazz Selmer, dont Geronimo Mateos, au centre de Londres.",
    de: "Selmer-Gypsy-Jazz-Gitarren, darunter Geronimo Mateos, in der Londoner Innenstadt.",
    nl: "Selmer-stijl gypsy-jazzgitaren, waaronder Geronimo Mateos, in centraal Londen.",
    it: "Chitarre gypsy jazz Selmer, tra cui Geronimo Mateos, nel centro di Londra.",
    es: "Guitarras gypsy jazz Selmer, entre ellas Geronimo Mateos, en el centro de Londres.",
    pt: "Guitarras gypsy jazz Selmer, incluindo Geronimo Mateos, no centro de Londres.",
  },
  "the-guitar-bar": {
    fr: "Boutique anversoise connue pour les instruments et accessoires gypsy jazz.",
    de: "Antwerpener Laden, bekannt für Gypsy-Jazz-Instrumente und Zubehör.",
    nl: "Antwerpse zaak bekend om gypsy-jazz-instrumenten en toebehoren.",
    it: "Negozio di Anversa noto per strumenti e accessori gypsy jazz.",
    es: "Tienda de Amberes conocida por instrumentos y accesorios gypsy jazz.",
    pt: "Loja de Antuérpia conhecida por instrumentos e acessórios gypsy jazz.",
  },
};

export function makerBio(slug: string, locale: string) {
  if (!locale || locale === "en" || locale === "he") return "";
  return BIOS[slug]?.[locale] || "";
}
