import type { NewsItem } from "./music-core";

export type { NewsItem };
import { NEWS_MORE } from "./music-news-more";

export const NEWS: NewsItem[] = [
  {
    slug: "dario-immersion-abbiategrasso-2026",
    date: "2026-09-17",
    title: "Two spots left — Dario Napoli Full Immersion, 25–27 September",
    body: "Dario Napoli wrote from Chicago, after the Midwest Gypsy Swing Fest, before the Green Mill night at Chicago Gypsy Jazz Fest. 25–27 September in Abbiategrasso, near Milan: Gypsy Jazz Full Immersion Weekend with Benji Winterstein. Small group, three days of workshops and jams. Bed and meals in one price. Two places left. Email darionapoliguitar@gmail.com, call +39 339 641 3847, or book on his site.",
    kind: "scene",
    artistSlugs: ["dario-napoli", "benji-winterstein"],
    href: "/learn/full-immersion-camp",
    hrefLabel: "Camp page",
    image: "/artists/dario-napoli-guitar.jpg",
  },
  {
    slug: "django-donegal-october-2026",
    date: "2026-09-13",
    title: "Django Donegal returns to Letterkenny — 2–3 October",
    body: "The Django Sur Lennon festival is back at Letterkenny’s Regional Cultural Centre. Friday 2 October, 20:00: Giacomo Smith Trio with Hugo Guezbar. Saturday 3 October, 20:00: Angelo Debarre Trio with Alexandre Cavaliere. Belleville play Blake’s Bar after the Saturday concert, with a jam. Tickets from the RCC or on the door.",
    kind: "scene",
    artistSlugs: ["angelo-debarre", "giacomo-smith", "hugo-guezbar"],
    href: "/festivals/django-sur-lennon",
    hrefLabel: "news.openFestival",
  },
  {
    slug: "elias-prinz-autumn-2026",
    date: "2026-09-14",
    title: "Elias Prinz announces autumn dates",
    body: "The Munich guitarist posted his public concerts for autumn 2026. 18 September: Django In London with Sunny Franz. Then Germany — Kiel, Hanau, Worms, Munich (Unterfahrt, Silbersaal, Bazar Cuisine), Schloss Elmau (solo, 14–16 October), Ofterschwang and Ingolstadt. Dates on his page.",
    kind: "scene",
    artistSlugs: ["elias-prinz", "sunny-franz"],
    href: "/musicians/elias-prinz",
    hrefLabel: "Dates",
  },
  {
    slug: "django-in-london-2026",
    date: "2026-09-14",
    title: "Django In London — 17–19 September, this week",
    body: "Three days at St Mary's, Upper Street, Islington. Harry Diplock Trio, Hugo Guezbar Trio, Elias Prinz & Sunny Franz, Angelo Debarre Trio, Giacomo Smith matinee, London Django Collective with Kourosh Kanani, Debi Botos. Tickets on Eventbrite. All concerts on the festival page.",
    kind: "scene",
    artistSlugs: [
      "angelo-debarre",
      "hugo-guezbar",
      "harry-diplock",
      "elias-prinz",
      "kourosh-kanani",
      "debi-botos",
      "giacomo-smith",
    ],
    href: "/festivals/django-in-london",
    hrefLabel: "news.openFestival",
    image: "/news/django-in-london-2026.jpg",
  },
  {
    slug: "angelo-debarre-ulule",
    date: "2026-09-10",
    title: "Crowdfund for Angelo Debarre",
    body: "Denis Chang passed on a message from Angelo Debarre: he is having health difficulties and is in need of help. A crowdfunding page is open on Ulule — Soutien au guitariste Angelo Debarre. The link is on this page.",
    kind: "scene",
    artistSlugs: ["angelo-debarre", "denis-chang"],
    href: "https://fr.ulule.com/soutien-au-guitariste-angelo-debarre/",
    hrefLabel: "Ulule",
    image: "/news/angelo-debarre-ulule.jpg",
  },
  {
    slug: "la-pompe-live-app",
    date: "2026-09-10",
    title: "Christiaan van Hemert released La Pompe",
    body: "The Dutch violinist and teacher released La Pompe Live in August 2026 — charts, setlists and the pompe in your pocket. iPhone and Android. Beginner guide on YouTube from 10 August.",
    kind: "scene",
    artistSlugs: ["christiaan-van-hemert"],
    href: "/learn/apps",
    hrefLabel: "news.openApps",
    youtubeUrl: "https://www.youtube.com/watch?v=RYLanvfhm3I",
    image: "/artists/christiaan-van-hemert.jpg",
  },
  {
    slug: "moignard-miroirs-sunset",
    date: "2026-09-09",
    title: "Adrien Moignard Quartet + guests — Miroirs at Sunset, 11 September",
    body: "Friday 11 September 2026, 20:30, Sunset in Paris, for the album Miroirs (Label Ouest). Adrien Moignard Quartet + guests — Benji Winterstein and Julien Cattiaux on rhythm, Fabricio Nicolas-Garcia on bass. Tickets from Sunset-Sunside.",
    kind: "scene",
    artistSlugs: ["adrien-moignard", "benji-winterstein", "julien-cattiaux"],
    albumSlug: "adrien-moignard-miroirs",
    href: "https://billetterie.sunset-sunside.com/event/777395-adrien-moignard-quartet?eventDate=2964111",
    hrefLabel: "Tickets",
    image: "/guitar-wood.jpg",
  },
  {
    slug: "midwest-django-fest-2026",
    date: "2026-09-08",
    title: "Midwest Django Fest — Madison this weekend",
    body: "11–12 September at William G. Lunney Lake Farm County Park, Madison. Gonzalo Bergara Trio, Dario Napoli Trio, Alfonso Ponticelli, Hot Club of Baltimore, Harmonious Wail. Campfire djam both nights. Schedule: midwestdjangofestival.com.",
    kind: "scene",
    artistSlugs: ["gonzalo-bergara", "dario-napoli", "alfonso-ponticelli"],
    href: "https://midwestdjangofestival.com/schedule/",
    hrefLabel: "Schedule",
    image: "/samois-jam.jpg",
  },
  {
    slug: "shrewsbury-django-fest-2026",
    date: "2026-09-08",
    title: "Shrewsbury Django Fest 2026 line-up is up",
    body: "23–25 October in Shrewsbury. Friday: John Wheatcroft Trio featuring Olivia Frances Brown, then the Mozes Rosenberg Trio with Christiaan van Hemert. Saturday: Marion & Sobo Band, then Paulus Schäfer and Olli Soikkeli. Sunday: the Gypsy Jazz Retreat concert, Marion & Sobo again, and the all-star jam. Free daytime DJams Saturday and Sunday at Glou Glou, The Bull Inn and The Nags Head. Tickets from shrewsburydjangofest.co.uk.",
    kind: "scene",
    artistSlugs: [
      "mozes-rosenberg",
      "christiaan-van-hemert",
      "paulus-schafer",
      "olli-soikkeli",
      "john-wheatcroft",
      "chris-quinn",
    ],
    href: "https://www.shrewsburydjangofest.co.uk/django-fest-line-up",
    hrefLabel: "Line-up",
    image: "/festival-django.jpg",
  },
  {
    slug: "weekly-scan-2026-08-23",
    date: "2026-09-07",
    title: "This week on the globe — Paris, Madison, Chicago, Langley",
    body: "Tonight and Friday: Olli Soikkeli with the Finnish Air Force Big Band (Kuopio, Tampere). Friday in Paris: Adrien Moignard’s Miroirs at Sunset. Weekend: Midwest Django Fest in Madison (Bergara, Napoli, Ponticelli). Next week: DjangoFest Northwest (15–20 Sep, Whidbey Island — Gismo Graf, Gonzalo Bergara, Pearl Django), Chicago Gypsy Jazz Fest from 15 Sep (SPACE, Green Mill), Django In London 17–19 Sep. Rosenberg brothers in Viljandi, 9 October.",
    kind: "scene",
    artistSlugs: [
      "olli-soikkeli",
      "adrien-moignard",
      "hugo-guezbar",
      "angelo-debarre",
      "dario-napoli",
      "stephane-wrembel",
      "gismo-graf",
      "stochelo-rosenberg",
      "mozes-rosenberg",
      "alfonso-ponticelli",
    ],
    image: "/samois-jam.jpg",
  },
  {
    slug: "pgc-steven-reinhardt",
    date: "2026-09-06",
    title: "Paris Guitar Connection sits with Steven Reinhardt",
    body: "The Paris podcast — six guitarists, two sofas — put Saint-Ouen’s Steven Reinhardt on the couch. Gypsy Jazz with a Gypsy: family time, the pompe, Swing Lâg shop guitars, then Blues en mineur and What Is This Thing Called Love. PGC is not a weekly jam. The public jam is still La Chope des Puces, weekends on rue des Rosiers. The hosts are Aurélien Robert, Guillaume Muschalle, François Thouvenot, Ghali Hadefi, Nicolas Lestoquoy and Yoann Kempst. Ghali’s pompe shorts are the ones players send each other. Watch the episode on the channel.",
    kind: "scene",
    artistSlugs: ["steven-reinhardt"],
    href: "https://www.youtube.com/watch?v=4cK5mZdbNqM",
    hrefLabel: "news.watchPodcast",
    youtubeUrl: "https://www.youtube.com/watch?v=4cK5mZdbNqM",
    image: "/guitar-wood.jpg",
  },
  ...NEWS_MORE,
];
