import type { NewsItem } from "./music-core";

export const NEWS_MORE: NewsItem[] = [
  {
    slug: "djangofest-northwest-2026",
    date: "2026-09-03",
    title: "DjangoFest Northwest — Gismo Graf, Pearl Django, Bergara",
    body: "26th year at WICA, Langley, 15–20 September 2026. Six days: 3 Parts Bourbon, Pearl Django, Eric Vanderbilt-Mathews, John Jorgenson Trio, Gonzalo Bergara Quintet, Gismo Graf Quintet, then the Nick Lehr Memorial djam. Free second-stage sets. BroadwayWorld posted the bill 3 September.",
    kind: "scene",
    artistSlugs: ["gismo-graf", "gonzalo-bergara", "john-jorgenson"],
    href: "https://www.broadwayworld.com/seattle/article/Gismo-Graf-Quintet-Pearl-Django-More-Set-for-DjangoFest-Northwest-20260903",
    hrefLabel: "Line-up",
    image: "/festival-django.jpg",
  },
  {
    slug: "africa-manouche-2026",
    date: "2026-09-03",
    title: "Gypsy jazz is rare in Africa. South Africa is where most of it lives.",
    body: "Dedicated Gypsy Jazz open jams are essentially nonexistent across Africa. The style stays niche and European. South Africa has the only standing scene: Hot Club d’Afrique in Johannesburg (all-acoustic, founded 2008), Hot Club of Cape Town, Tarabu in the Winelands, and Manouche in Cape Town — performance groups for venues, festivals and hire, not open jams. Morocco has seen occasional Django homage concerts (Royal Symphony Orchestra Jazz Band, Casablanca and Rabat, 2024). Egypt, Senegal, Nigeria, Kenya, Ghana and Ethiopia have no posted Manouche jam. General jazz jams in Cape Town, Johannesburg, Cairo and Dakar are not Hot Club nights.",
    kind: "scene",
    artistSlugs: [],
    image: "/guitar-wood.jpg",
  },
  {
    slug: "latin-america-manouche-2026",
    date: "2026-09-04",
    title: "South & Central America — jams and festivals on the globe",
    body: "Buenos Aires: Swing Medical’s monthly jam at Bar de Fondo (Julián Álvarez 1200). Argentina Django Festival returns each May. Curitiba: Festival Manouche, 20–25 October 2026. Brasília Gypsy Jazz Club, Piracicaba, Hot Club Medellín, Hot Club de San Miguel, Festival Django CL in Santiago. Uruguay has no standing jam posted.",
    kind: "scene",
    artistSlugs: [
      "lucas-reydo",
      "roque-monsalve",
      "lucas-miranda",
      "ludovik-dorkis",
      "victor-angeleas",
      "carlos-caceres",
      "antonio-lozoya",
    ],
    image: "/guitar-wood.jpg",
  },
  {
    slug: "hot-club-de-tms",
    date: "2026-09-05",
    title: "Hot Club de TMS — first Saturday in Utrecht",
    body: "Jazz Manouche at The Music Space XL, Australiëlaan 24. First Saturday of the month, 19:00–23:00. First night 5 September 2026: Chris’ Collective opens. WhatsApp community on the jam page.",
    kind: "scene",
    artistSlugs: [],
    image: "/samois-jam.jpg",
  },
  {
    slug: "denis-chang-japan-tour",
    date: "2026-09-05",
    title: "Denis Chang — first leader mini-tour in Japan",
    body: "October 2026: Tokyo 8th (u-ma Kagurazaka), Osaka 9th (Piano Bar Kiyomi), then Setouchi Django Street in Yashima, Kagawa, 10–11. Reilly Farrell on violin, Alison Zhen on rhythm, Hanaoka Toshio on bass. Live and session both club nights, 19:30.",
    kind: "scene",
    artistSlugs: ["denis-chang", "reilly-farrell", "alison-zhen", "hanaoka-toshio"],
    image: "/artists/denis-chang.jpg",
  },
  {
    slug: "django-portugal-camp-2027",
    date: "2026-09-04",
    title: "Django Portugal Camp — Vila Viçosa, 28 April–2 May 2027",
    body: "Nuno Marinho and Marian Yanchyk’s gypsy jazz camp in the Alentejo. Rhythm in the morning, soloing after lunch, jams after dinner. Festival Django Portugal is the touring sister.",
    kind: "scene",
    artistSlugs: ["nuno-marinho", "marian-yanchyk"],
    image: "/festival-django.jpg",
  },
  {
    slug: "hot-club-insulinde",
    date: "2026-09-10",
    title: "Hot Club Insulinde — second Wednesday in Amsterdam",
    body: "Acoustic gypsy jazz jam at Café Insulinde, Sumatrastraat 24 (Insulindeweg). Second Wednesday of the month from 19:00. Open to all. Next: 14 October 2026.",
    kind: "scene",
    artistSlugs: [],
    image: "/guitar-wood.jpg",
  },
  {
    slug: "hub-opens",
    date: "2026-09-01",
    title: "Gypsy Jazz Hub is open",
    body: "A worldwide circle for the music: jams, concerts, groups, camps, luthiers, and the pages of the players. Join and put a date on the calendar.",
    kind: "scene",
    artistSlugs: ["daniel-gueli"],
    image: "/artists/daniel-gueli.jpg",
  },
  {
    slug: "gypsy-jazz-band-klebelsberg",
    date: "2026-08-30",
    title: "Gypsy Jazz Band — Klebelsberg Kultürkúria, 30 August",
    body: "Budapest, Sunday 30 August 2026, 19:30. Róbert Kárpáti’s Gypsy Jazz Band with Roby Lakatos, guests Charlie Horváth and Csondor Kata. Templom utca 2–10. For chairs to sit in, Manuska posts Django jams in Gypsy Jazz Jams Budapest — not a fixed weekly night.",
    kind: "scene",
    artistSlugs: ["robert-karpati", "roby-lakatos"],
    image: "/festival-django.jpg",
  },
  {
    slug: "fanou-vol-2-out",
    date: "2023-05-31",
    title: "Fanou Torracinta — Gipsy Guitar From Corsica Vol. 2",
    body: "The Corsican guitarist’s second album with Benji Winterstein, William Brunard and Bastien Brison. One of the main current French groups. Listen on Spotify and iTunes.",
    kind: "album",
    artistSlugs: ["fanou-torracinta", "benji-winterstein", "william-brunard", "bastien-brison"],
    albumSlug: "fanou-gipsy-guitar-vol-2",
  },
  {
    slug: "olli-soikkeli-comeback-out",
    date: "2026-07-07",
    title: "Olli Soikkeli’s Comeback is out",
    body: "The Finnish guitarist’s new record returns to gypsy jazz. Stochelo Rosenberg, Paulus Schäfer, Nous’che Rosenberg and Matheus Nicolaiewsky are on it. Listen on Spotify and iTunes.",
    kind: "album",
    artistSlugs: ["olli-soikkeli", "stochelo-rosenberg", "paulus-schafer", "matheus-nicolaiewsky"],
    albumSlug: "olli-soikkeli-comeback",
  },
  {
    slug: "dario-napoli-sicilian-blood",
    date: "2026-05-01",
    title: "Dario Napoli: Sicilian Blood",
    body: "Napoli’s seventh album. The title track came first; the full record is on the platforms now. Benji Winterstein holds rhythm.",
    kind: "album",
    artistSlugs: ["dario-napoli", "benji-winterstein"],
    albumSlug: "dario-napoli-sicilian-blood",
  },
  {
    slug: "stochelo-django-celebration",
    date: "2025-09-17",
    title: "Stochelo Rosenberg — Django Celebration #01",
    body: "A new Django book from Helmond. Stochelo’s Celebration series is on Spotify; the live Django Celebration nights keep touring.",
    kind: "album",
    artistSlugs: ["stochelo-rosenberg"],
    albumSlug: "stochelo-django-celebration-01",
  },
  {
    slug: "joscho-playlist",
    date: "2025-05-09",
    title: "Joscho Stephan Trio: Playlist",
    body: "The German trio’s YouTube book, on record. California Dreamin’ opens it. Highwire followed the same year.",
    kind: "album",
    artistSlugs: ["joscho-stephan"],
    albumSlug: "joscho-stephan-playlist",
  },
  {
    slug: "joscho-highwire",
    date: "2025-03-07",
    title: "Joscho Stephan: Highwire",
    body: "Joscho Stephan with Cornelius Claudio Kreusch — the 2025 guitar record. Listen on Spotify and iTunes.",
    kind: "album",
    artistSlugs: ["joscho-stephan"],
    albumSlug: "joscho-stephan-highwire",
  },
  {
    slug: "joscho-four-of-a-kind",
    date: "2023-02-01",
    title: "Joscho Stephan Trio: Four Of A Kind",
    body: "The German trio’s album with Costel Nitescu — thirteen pieces, recorded in a day and a half.",
    kind: "album",
    artistSlugs: ["joscho-stephan"],
    albumSlug: "joscho-stephan-four-of-a-kind",
  },
  {
    slug: "bireli-loulou-gaste",
    date: "2024-06-01",
    title: "Biréli Lagrène plays Loulou Gasté",
    body: "Lagrène reads the French songwriter who wrote Feelings. A guitar record that is still gypsy jazz in the left hand.",
    kind: "album",
    artistSlugs: ["bireli-lagrene"],
    albumSlug: "bireli-plays-loulou-gaste",
  },
  {
    slug: "angelo-adrien-viaggio",
    date: "2025-02-01",
    title: "Angelo Debarre and Adrien Moignard: New Viaggio",
    body: "Two French lead guitars on one date. Debarre’s sound, Moignard’s fire.",
    kind: "album",
    artistSlugs: ["angelo-debarre", "adrien-moignard"],
    albumSlug: "angelo-adrien-new-viaggio",
  },
];
