/** Gypsy jazz artists documented on Festival Django Reinhardt stages (Samois-sur-Seine / Fontainebleau) and the campsite circuit around it. */
export const SAMOIS_SLUGS = new Set([
  "bireli-lagrene",
  "stochelo-rosenberg",
  "angelo-debarre",
  "tchavolo-schmitt",
  "dorado-schmitt",
  "samson-schmitt",
  "adrien-moignard",
  "fapy-lafertin",
  "hono-winterstein",
  "ninine-garcia",
  "rocky-gresset",
  "mozes-rosenberg",
  "jimmy-rosenberg",
  "paulus-schafer",
  "romane",
  "costel-nitescu",
  "stephane-wrembel",
  "joscho-stephan",
  "wawau-adler",
  "lulo-reinhardt",
  "tim-kliphuis",
  "andreas-oberg",
  "babik-reinhardt",
  "yorgui-loeffler",
  "marcel-loeffler",
  "gigi-loeffler",
  "raphael-fays",
  "boulou-ferre",
  "elios-ferre",
  "patrick-saussois",
  "sebastien-giniaux",
  "noe-reinhardt",
  "david-reinhardt",
  "mandino-reinhardt",
  "simba-baumgartner",
  "gismo-graf",
  "django-rosenberg",
  "titi-bamberger",
  "lollo-meier",
  "ritary-gaguenetti",
  "moreno-winterstein",
  "doudou-cuillerier",
  "fanou-garcia",
  "richard-manetti",
  "pierre-manetti",
  "nousche-rosenberg",
  "nonnie-rosenberg",
  "diknu-schneeberger",
  "robin-nolan",
  "john-jorgenson",
  "frank-vignola",
  "olli-soikkeli",
  "antoine-boyer",
  "samy-daussat",
  "florin-niculescu",
  "tcha-limberger",
  "pierre-blanchard",
  "alexandre-cavaliere",
  "aurore-voilque",
  "ludovic-beier",
  "claudius-dupont",
  "diego-imbert",
  "sebastien-girardot",
  "dave-kelbie",
  "benji-winterstein",
  "christian-escoude",
  "mike-reinhardt",
  "kussi-weiss",
  "olivier-kikteff",
  "cyrille-aimee",
  "schnuckenack-reinhardt",
  "waso-de-cauter",
  "koen-de-cauter",
  "mathias-levy",
  "william-brunard",
  "fanou-torracinta",
  "bastien-brison",
  "rodolphe-raffalli",
  "christophe-lartilleux",
  "sandro-roy",
  "gonzalo-bergara",
  "marcia-bamberg",
  "john-ligthart",
  "ronald-weel",
  "christiaan-van-hemert",
  "hugo-guezbar",
  "justin-geisler",
  "giacomo-smith",
  "holzmano-lagrene",
]);

export const SAMOIS_ARTISTS = [
  {
    slug: "yorgui-loeffler",
    name: "Yorgui Loeffler",
    years: "b. 1979",
    origin: "Alsace, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Alsatian Sinti guitarist and a pillar of Festival Django Reinhardt. Loeffler's drive, tone, and unaccompanied introductions are a Samois signature — the sound of the current French manouche stage.",
    notable: "Festival Django Reinhardt regular; Alsatian Sinti school",
    youtube_url: "",
    sort_order: 31,
  },
  {
    slug: "marcel-loeffler",
    name: "Marcel Loeffler",
    years: "b. 1956",
    origin: "Alsace, France",
    instruments: "Accordion",
    era: "Samois",
    bio: "The accordion voice of the Loeffler family. Marcel has carried waltz, musette, and swing onto the Samois stages for decades, often beside Yorgui and the Alsatian clans.",
    notable: "Festival Django Reinhardt; Loeffler family",
    youtube_url: "",
    sort_order: 32,
  },
  {
    slug: "gigi-loeffler",
    name: "Gigi Loeffler",
    years: "Alsace",
    origin: "Alsace, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Rhythm and lead guitar from the Loeffler family, a familiar face on the Festival Django Reinhardt bill and in the Alsatian ensembles that define the Samois week.",
    notable: "Festival Django Reinhardt; Loeffler family",
    youtube_url: "",
    sort_order: 33,
  },
  {
    slug: "raphael-fays",
    name: "Raphaël Faÿs",
    years: "b. 1959",
    origin: "Paris, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "A prodigy who recorded as a teenager and later stretched gypsy jazz toward classical technique. Faÿs has been a recurring presence at Festival Django Reinhardt, with a sound that is both scholarly and swinging.",
    notable: "Festival Django Reinhardt; classical-manouche bridge",
    youtube_url: "",
    sort_order: 34,
  },
  {
    slug: "boulou-ferre",
    name: "Boulou Ferré",
    years: "b. 1951",
    origin: "Paris, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Son of Baro Ferret, Boulou was a child prodigy in Django's wake and later a Samois-stage veteran. With his brother Elios he kept the Ferret dynasty on the festival boards.",
    notable: "Festival Django Reinhardt; Ferret family",
    youtube_url: "",
    sort_order: 35,
  },
  {
    slug: "elios-ferre",
    name: "Elios Ferré",
    years: "b. 1956",
    origin: "Paris, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Boulou's brother and partner in the Ferré duo. Elios's time and chord work have been part of Festival Django Reinhardt lineups across many editions.",
    notable: "Festival Django Reinhardt; Ferré duo",
    youtube_url: "",
    sort_order: 36,
  },
  {
    slug: "patrick-saussois",
    name: "Patrick Saussois",
    years: "1954–1995",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "A fierce French guitarist of the 1980s–90s generation, remembered on the Samois stages and in the clubs that fed the festival. His recordings still circulate among players who learned the style in those years.",
    notable: "Festival Django Reinhardt; 1980s French scene",
    youtube_url: "",
    sort_order: 37,
  },
  {
    slug: "sebastien-giniaux",
    name: "Sébastien Giniaux",
    years: "b. 1983",
    origin: "France",
    instruments: "Guitar, cello",
    era: "Samois",
    bio: "Guitarist and cellist who came up as a Samois rising star. Giniaux moves between strict manouche and a more chamber sound, and remains a first-call name on the Festival Django Reinhardt circuit.",
    notable: "Festival Django Reinhardt; guitar and cello",
    youtube_url: "",
    sort_order: 38,
  },
  {
    slug: "noe-reinhardt",
    name: "Noé Reinhardt",
    years: "b. 1982",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "A Reinhardt of the present generation — lead guitar with a singing tone and original writing. Noé has been a Festival Django Reinhardt regular, often beside David Reinhardt and the French nouvelle vague.",
    notable: "Festival Django Reinhardt; Reinhardt family",
    youtube_url: "",
    sort_order: 39,
  },
  {
    slug: "david-reinhardt",
    name: "David Reinhardt",
    years: "b. 1986",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Babik's son, carrying the family name onto the Samois and Fontainebleau stages. David plays with a modern harmonic ear while keeping the pompe and the repertoire that the festival was built on.",
    notable: "Festival Django Reinhardt; Babik's son",
    youtube_url: "",
    sort_order: 40,
  },
  {
    slug: "mandino-reinhardt",
    name: "Mandino Reinhardt",
    years: "b. 1956",
    origin: "Alsace, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Alsatian guitarist and teacher, a long-time presence around Festival Django Reinhardt. Mandino has trained a generation of Sinti players and still takes the stage with family groups.",
    notable: "Festival Django Reinhardt; Alsatian teaching lineage",
    youtube_url: "",
    sort_order: 41,
  },
  {
    slug: "simba-baumgartner",
    name: "Simba Baumgartner",
    years: "b. 1990s",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Django's great-grandson. Simba has played the festival Sunday mass and the young-player slots that keep the Reinhardt name on the Île du Berceau and Fontainebleau bills.",
    notable: "Festival Django Reinhardt; Django's great-grandson",
    youtube_url: "",
    sort_order: 42,
  },
  {
    slug: "gismo-graf",
    name: "Gismo Graf",
    years: "b. 1992",
    origin: "Germany",
    instruments: "Guitar",
    era: "Samois",
    bio: "German Sinti guitarist of startling facility, son of Wedeli Graf. Gismo is a frequent Festival Django Reinhardt guest and a face of the younger European school.",
    notable: "Festival Django Reinhardt; German Sinti school",
    youtube_url: "",
    sort_order: 43,
  },
  {
    slug: "titi-bamberger",
    name: "Titi Bamberger",
    years: "France / Germany",
    origin: "Germany",
    instruments: "Guitar",
    era: "Samois",
    bio: "A swinging lead and rhythm player on the Samois circuit, often cited among the festival's working Sinti guitarists — the kind of name you hear both on the official stage and in the campsite sessions.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 44,
  },
  {
    slug: "lollo-meier",
    name: "Lollo Meier",
    years: "b. 1963",
    origin: "Limburg, Netherlands",
    instruments: "Guitar",
    era: "Samois",
    bio: "Dutch Sinti guitarist with a fat, vocal tone close to the golden-age language. Meier has been a Festival Django Reinhardt guest and a favourite of players who want Django's sound more than modern flash.",
    notable: "Festival Django Reinhardt; Dutch Sinti school",
    youtube_url: "",
    sort_order: 45,
  },
  {
    slug: "ritary-gaguenetti",
    name: "Ritary Gaguenetti",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "French manouche guitarist and a familiar Festival Django Reinhardt name, known for a singing lead and for groups that sit right in the dance-floor swing the festival still lives on.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 46,
  },
  {
    slug: "moreno-winterstein",
    name: "Moreno Winterstein",
    years: "b. 1963",
    origin: "Alsace, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Alsatian guitarist from the Winterstein family. Moreno's records and Samois appearances helped carry the raw Sinti lead style into the 1990s and 2000s festival years.",
    notable: "Festival Django Reinhardt; Winterstein family",
    youtube_url: "",
    sort_order: 47,
  },
  {
    slug: "doudou-cuillerier",
    name: "Doudou Cuillerier",
    years: "France",
    origin: "France",
    instruments: "Guitar, vocal",
    era: "Samois",
    bio: "Guitarist and singer, a Festival Django Reinhardt regular whose showmanship and swing have opened the music to crowds beyond the guitarists in the front row.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 48,
  },
  {
    slug: "fanou-garcia",
    name: "Fanou Garcia",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Son of Ninine Garcia, carrying the family band onto later Festival Django Reinhardt editions. Fanou is part of the working French circuit that still treats Samois as the summer meeting.",
    notable: "Festival Django Reinhardt; Garcia family",
    youtube_url: "",
    sort_order: 49,
  },
  {
    slug: "richard-manetti",
    name: "Richard Manetti",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "One of the Manetti brothers — a French guitar voice heard on official Samois stages and in the off-festival sessions that players still talk about. Tight time, modern language, deep swing.",
    notable: "Festival Django Reinhardt; Manetti brothers",
    youtube_url: "",
    sort_order: 50,
  },
  {
    slug: "pierre-manetti",
    name: "Pierre Manetti",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Richard's brother and partner on the Festival Django Reinhardt bills. The Manetti groups are a marker of the 2000s–2010s French generation at Samois.",
    notable: "Festival Django Reinhardt; Manetti brothers",
    youtube_url: "",
    sort_order: 51,
  },
  {
    slug: "nousche-rosenberg",
    name: "Nous'che Rosenberg",
    years: "b. 1965",
    origin: "Helmond, Netherlands",
    instruments: "Rhythm guitar",
    era: "Samois",
    bio: "Rhythm guitar of the Rosenberg Trio. Nous'che's pompe is the engine behind Stochelo on every Festival Django Reinhardt appearance the trio has made.",
    notable: "Festival Django Reinhardt; Rosenberg Trio",
    youtube_url: "",
    sort_order: 52,
  },
  {
    slug: "nonnie-rosenberg",
    name: "Nonnie Rosenberg",
    years: "b. 1970",
    origin: "Helmond, Netherlands",
    instruments: "Double bass",
    era: "Samois",
    bio: "Bass of the Rosenberg Trio. Nonnie has held down the Samois and Fontainebleau stages whenever the family band is on the festival poster.",
    notable: "Festival Django Reinhardt; Rosenberg Trio",
    youtube_url: "",
    sort_order: 53,
  },
  {
    slug: "diknu-schneeberger",
    name: "Diknu Schneeberger",
    years: "b. 1990",
    origin: "Vienna, Austria",
    instruments: "Guitar",
    era: "Samois",
    bio: "Austrian Sinti guitarist, son of Martin Spanyi's scene and a European festival regular. Diknu has brought the Viennese school to Festival Django Reinhardt.",
    notable: "Festival Django Reinhardt; Austrian Sinti school",
    youtube_url: "",
    sort_order: 54,
  },
  {
    slug: "robin-nolan",
    name: "Robin Nolan",
    years: "b. 1970",
    origin: "United Kingdom",
    instruments: "Guitar",
    era: "Samois",
    bio: "British-born, Amsterdam-based guitarist who helped take gypsy jazz to students worldwide. Nolan has been on Festival Django Reinhardt bills and is a link between the Dutch scene and English-speaking players.",
    notable: "Festival Django Reinhardt; pedagogy and touring",
    youtube_url: "",
    sort_order: 55,
  },
  {
    slug: "john-jorgenson",
    name: "John Jorgenson",
    years: "b. 1956",
    origin: "United States",
    instruments: "Guitar",
    era: "Samois",
    bio: "American guitarist who put Hot Club language on US country and jazz stages, then crossed to Festival Django Reinhardt. Jorgenson's Gypsy Jazz group was an early bridge for American crowds at Samois.",
    notable: "Festival Django Reinhardt; American Hot Club scene",
    youtube_url: "",
    sort_order: 56,
  },
  {
    slug: "frank-vignola",
    name: "Frank Vignola",
    years: "b. 1965",
    origin: "United States",
    instruments: "Guitar",
    era: "Samois",
    bio: "New York guitarist equally at home with Grappelli-language swing and American jazz. Vignola has been a Festival Django Reinhardt guest and a regular counterpart to European lead players.",
    notable: "Festival Django Reinhardt; New York swing guitar",
    youtube_url: "",
    sort_order: 57,
  },
  {
    slug: "olli-soikkeli",
    name: "Olli Soikkeli",
    years: "b. 1991",
    origin: "Finland",
    instruments: "Guitar",
    era: "Samois",
    bio: "Finnish guitarist of the new international school, now based in the US. Soikkeli has played the European festival circuit including Django Reinhardt gatherings, with a clean, ferocious lead style.",
    notable: "Festival Django Reinhardt circuit; Nordic school",
    youtube_url: "https://www.youtube.com/@danielgueli",
    sort_order: 58,
  },
  {
    slug: "antoine-boyer",
    name: "Antoine Boyer",
    years: "b. 1995",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "French prodigy who grew up on the festival circuit. Boyer has shared Festival Django Reinhardt stages with the generation above him and writes original music inside the manouche language.",
    notable: "Festival Django Reinhardt; French prodigy generation",
    youtube_url: "",
    sort_order: 59,
  },
  {
    slug: "samy-daussat",
    name: "Samy Daussat",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "French guitarist who met Babik Reinhardt at Festival Django Reinhardt in Samois as a young player, later worked with Raphaël Faÿs, and has returned to the festival stages as a lead voice of his own.",
    notable: "Festival Django Reinhardt; Faÿs and Reinhardt circles",
    youtube_url: "",
    sort_order: 60,
  },
  {
    slug: "florin-niculescu",
    name: "Florin Niculescu",
    years: "b. 1967",
    origin: "Romania",
    instruments: "Violin",
    era: "Samois",
    bio: "The great Romanian violinist of the current manouche world. Niculescu has been a Festival Django Reinhardt headliner, with a sound that sits between Grappelli, Eastern lyricism, and modern jazz.",
    notable: "Festival Django Reinhardt; violin chair",
    youtube_url: "",
    sort_order: 61,
  },
  {
    slug: "tcha-limberger",
    name: "Tcha Limberger",
    years: "b. 1977",
    origin: "Belgium",
    instruments: "Violin, guitar, vocal",
    era: "Samois",
    bio: "Belgian-born Sinti multi-instrumentalist from the Waso/Limberger family. Tcha has brought gypsy jazz, Hungarian folk, and Django repertoire to Festival Django Reinhardt and to rooms far beyond it.",
    notable: "Festival Django Reinhardt; Limberger / Waso family",
    youtube_url: "",
    sort_order: 62,
  },
  {
    slug: "pierre-blanchard",
    name: "Pierre Blanchard",
    years: "b. 1956",
    origin: "France",
    instruments: "Violin",
    era: "Samois",
    bio: "French violinist of the post-Grappelli school, a Festival Django Reinhardt regular often heard with Samson Schmitt, Ludovic Beier, and the swing groups that fill the late sets.",
    notable: "Festival Django Reinhardt; French violin school",
    youtube_url: "",
    sort_order: 63,
  },
  {
    slug: "alexandre-cavaliere",
    name: "Alexandre Cavaliere",
    years: "b. 1987",
    origin: "Belgium",
    instruments: "Violin",
    era: "Samois",
    bio: "Belgian violin prodigy who appeared at Festival Django Reinhardt while still a teenager. Cavaliere's tone and speed made him one of the festival's most talked-about young guests.",
    notable: "Festival Django Reinhardt; Belgian violin",
    youtube_url: "",
    sort_order: 64,
  },
  {
    slug: "aurore-voilque",
    name: "Aurore Voilqué",
    years: "France",
    origin: "France",
    instruments: "Violin",
    era: "Samois",
    bio: "French violinist on the Festival Django Reinhardt bills, equally convincing on Grappelli repertoire and original writing. A regular of the French manouche concert scene that feeds Samois.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 65,
  },
  {
    slug: "ludovic-beier",
    name: "Ludovic Beier",
    years: "b. 1978",
    origin: "France",
    instruments: "Accordion",
    era: "Samois",
    bio: "Accordionist of the modern French swing groups, a Festival Django Reinhardt fixture beside Samson Schmitt, Pierre Blanchard, and visiting guitarists. Beier is the musette-to-manouche link on those stages.",
    notable: "Festival Django Reinhardt; accordion",
    youtube_url: "",
    sort_order: 66,
  },
  {
    slug: "claudius-dupont",
    name: "Claudius Dupont",
    years: "France",
    origin: "France",
    instruments: "Bass",
    era: "Samois",
    bio: "Double bassist of the current French circuit and a Festival Django Reinhardt regular. Dupont is the bass chair behind many of the guitar headliners on the Samois and Fontainebleau nights.",
    notable: "Festival Django Reinhardt; bass chair",
    youtube_url: "",
    sort_order: 67,
  },
  {
    slug: "diego-imbert",
    name: "Diego Imbert",
    years: "b. 1975",
    origin: "France",
    instruments: "Bass",
    era: "Samois",
    bio: "French bassist who has anchored Festival Django Reinhardt sets for guitar stars and mixed jazz bills. A first-call name when the festival wants a swinging, modern bass chair.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 68,
  },
  {
    slug: "sebastien-girardot",
    name: "Sébastien Girardot",
    years: "France",
    origin: "United Kingdom",
    instruments: "Bass",
    era: "Samois",
    bio: "Bassist heard with the Rosenberg orbit, Dave Kelbie, and Festival Django Reinhardt groups. Girardot is part of the Anglo-French rhythm section that travels between Samois and the British scene.",
    notable: "Festival Django Reinhardt; Rosenberg / Kelbie groups",
    youtube_url: "",
    sort_order: 69,
  },
  {
    slug: "dave-kelbie",
    name: "Dave Kelbie",
    years: "b. 1967",
    origin: "United Kingdom",
    instruments: "Rhythm guitar",
    era: "Samois",
    bio: "British rhythm guitarist whose pompe has driven countless Festival Django Reinhardt sets and European tours. Kelbie is also a documentarian of the scene — always in the thick of the Samois week.",
    notable: "Festival Django Reinhardt; British pompe",
    youtube_url: "",
    sort_order: 70,
  },
  {
    slug: "benji-winterstein",
    name: "Benji Winterstein",
    years: "b. 1991",
    origin: "Forbach, France",
    instruments: "Rhythm guitar",
    era: "Samois",
    bio: "Alsatian Sinti rhythm guitar, one of the great pompe players of the present. Benji is the engine of Fanou Torracinta’s group and of the Dario Napoli Trio — Festival Django Reinhardt, the Paris clubs, the Full Immersion camps. Based in France.",
    notable: "Fanou Torracinta; Dario Napoli Trio; Winterstein family; Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 19,
  },
  {
    slug: "christian-escoude",
    name: "Christian Escoudé",
    years: "b. 1947",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "French guitarist of Romani origin who moved between manouche, bebop, and fusion. Escoudé has been a Festival Django Reinhardt guest across the decades when the bill still mixed lineage players with jazz stars.",
    notable: "Festival Django Reinhardt; French jazz guitar",
    youtube_url: "",
    sort_order: 72,
  },
  {
    slug: "mike-reinhardt",
    name: "Mike Reinhardt",
    years: "Alsace, France",
    origin: "Alsace, France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Alsatian guitarist of the Reinhardt name, heard beside Yorgui Loeffler and Samson Schmitt on festival stages including Festival Django Reinhardt.",
    notable: "Festival Django Reinhardt; Alsatian Reinhardts",
    youtube_url: "",
    sort_order: 73,
  },
  {
    slug: "kussi-weiss",
    name: "Kussi Weiss",
    years: "Germany",
    origin: "Germany",
    instruments: "Guitar",
    era: "Samois",
    bio: "German Sinti guitarist documented on the Samois official and off-festival circuit. Weiss represents the German family bands that travel to Festival Django Reinhardt each summer.",
    notable: "Festival Django Reinhardt; German Sinti",
    youtube_url: "",
    sort_order: 74,
  },
  {
    slug: "olivier-kikteff",
    name: "Olivier Kikteff",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "French guitarist of the 2000s Samois generation, heard in the festival week sessions and on the bills that mixed established names with the nouvelle vague.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 75,
  },
  {
    slug: "cyrille-aimee",
    name: "Cyrille Aimée",
    years: "b. 1984",
    origin: "Samois-sur-Seine, France",
    instruments: "Vocal, guitar",
    era: "Samois",
    bio: "Born in Samois-sur-Seine, Aimée grew up around Festival Django Reinhardt and has returned as a headliner. A jazz singer with manouche roots, she is the festival's hometown voice.",
    notable: "Festival Django Reinhardt; born in Samois",
    youtube_url: "",
    sort_order: 76,
  },
  {
    slug: "schnuckenack-reinhardt",
    name: "Schnuckenack Reinhardt",
    years: "1921–2006",
    origin: "Germany",
    instruments: "Violin",
    era: "Samois",
    bio: "The great German Sinti violinist of the postwar years. Schnuckenack brought a rawer, more rural swing than Grappelli and was among the lineage players welcomed at Festival Django Reinhardt in its earlier Samois decades.",
    notable: "Festival Django Reinhardt; German Sinti violin",
    youtube_url: "",
    sort_order: 77,
  },
  {
    slug: "waso-de-cauter",
    name: "Waso De Cauter",
    years: "Belgium",
    origin: "Ghent, Belgium",
    instruments: "Guitar",
    era: "Samois",
    bio: "Guitarist of the Belgian Waso Quartet with Fapy Lafertin — the group that carried a very Django sound onto European festivals, including Festival Django Reinhardt.",
    notable: "Festival Django Reinhardt; Waso Quartet",
    youtube_url: "",
    sort_order: 78,
  },
  {
    slug: "koen-de-cauter",
    name: "Koen De Cauter",
    years: "b. 1950",
    origin: "Belgium",
    instruments: "Guitar, saxophone, clarinet",
    era: "Samois",
    bio: "Patriarch of the Belgian Waso family, multi-instrumentalist, and a Festival Django Reinhardt guest. Koen is a bridge between Belgian gypsy jazz, jazz clarinet, and the Samois week.",
    notable: "Festival Django Reinhardt; Waso family",
    youtube_url: "",
    sort_order: 79,
  },
  {
    slug: "mathias-levy",
    name: "Mathias Lévy",
    years: "France",
    origin: "France",
    instruments: "Violin",
    era: "Samois",
    bio: "French violinist heard at Festival Django Reinhardt and in the off-festival Samois sessions, part of the generation that learned Grappelli language on those riverbank stages.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 80,
  },
  {
    slug: "william-brunard",
    name: "William Brunard",
    years: "France",
    origin: "France",
    instruments: "Double bass",
    era: "Samois",
    bio: "French double bass, a first-call chair of the current Paris and Samois circuit. Brunard is the bass of Fanou Torracinta’s group with Benji Winterstein, and he also holds the low end for Angelo Debarre and Adrien Moignard. Based in France.",
    notable: "Fanou Torracinta; Angelo Debarre; Adrien Moignard; Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 17,
  },
  {
    slug: "rodolphe-raffalli",
    name: "Rodolphe Raffalli",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "French guitarist of the traditional school, a Festival Django Reinhardt guest whose tone sits close to the Selmer-Maccaferri language the festival was founded to honour.",
    notable: "Festival Django Reinhardt",
    youtube_url: "",
    sort_order: 82,
  },
  {
    slug: "christophe-lartilleux",
    name: "Christophe Lartilleux",
    years: "France",
    origin: "France",
    instruments: "Guitar",
    era: "Samois",
    bio: "Leader of Swing De Gitanes and a Festival Django Reinhardt regular. Lartilleux's groups have been part of the French touring circuit that treats Samois as the summer home game.",
    notable: "Festival Django Reinhardt; Swing De Gitanes",
    youtube_url: "",
    sort_order: 83,
  },
  {
    slug: "sandro-roy",
    name: "Sandro Roy",
    years: "b. 1994",
    origin: "Germany",
    instruments: "Violin",
    era: "Samois",
    bio: "German violinist of the new festival generation, billed at Festival Django Reinhardt beside Rosenberg-family groups and other European headliners.",
    notable: "Festival Django Reinhardt; German violin",
    youtube_url: "",
    sort_order: 84,
  },
];
