import { CIRCLE_ARTISTS, CIRCLE_CONCERTS } from "@/lib/circle-artists";
import { applyArtistBio } from "@/lib/profile-bios";
import { SAMOIS_ARTISTS } from "@/lib/samois-artists";

export type LegendSeed = {
  slug: string;
  name: string;
  years: string;
  origin: string;
  instruments: string;
  era: string;
  bio: string;
  notable: string;
  youtube_url: string;
  sort_order: number;
  website_url?: string;
  instagram_url?: string;
  photo_url?: string;
  photo_credit?: string;
};

export type ConcertSeed = {
  legend_slug: string;
  title: string;
  venue: string;
  city: string;
  country: string;
  starts_at: string;
  is_historic: boolean;
  note: string;
};

const CORE_LEGENDS: LegendSeed[] = [
  {
    slug: "django-reinhardt",
    name: "Django Reinhardt",
    years: "1910–1953",
    origin: "Samois-sur-Seine, France",
    instruments: "Solo guitar",
    era: "Golden Age",
    bio: "The founder of gypsy jazz. After a caravan fire left him with two functioning fingers on his left hand, Reinhardt invented a new guitar language — ferocious swing, rubato melody, and a sound the Selmer-Maccaferri still carries. With Stéphane Grappelli he formed the Quintette du Hot Club de France and gave manouche music its public face.",
    notable: "Quintette du Hot Club de France; Nuages; Minor Swing",
    youtube_url: "",
    sort_order: 1,
  },
  {
    slug: "stephane-grappelli",
    name: "Stéphane Grappelli",
    years: "1908–1997",
    origin: "Paris, France",
    instruments: "Violin",
    era: "Golden Age",
    bio: "The other half of the original Hot Club. Grappelli's violin floated above Django's guitar with salon elegance and dance-floor swing. He kept the music on the world's stages for six decades after Django's death, playing with everyone from Yehudi Menuhin to younger manouche players.",
    notable: "Quintette du Hot Club de France; decades of postwar touring",
    youtube_url: "",
    sort_order: 2,
  },
  {
    slug: "joseph-reinhardt",
    name: "Joseph Reinhardt",
    years: "1912–1982",
    origin: "Paris, France",
    instruments: "Rhythm guitar",
    era: "Golden Age",
    bio: "Django's younger brother, known as Nin-Nin. His pompe — the driving two-and-four rhythm that is the engine of the style — is still the model for every rhythm guitarist in the circle.",
    notable: "Rhythm chair of the original Quintette",
    youtube_url: "",
    sort_order: 3,
  },
  {
    slug: "baro-ferret",
    name: "Baro Ferret",
    years: "1908–1976",
    origin: "Rouen, France",
    instruments: "Guitar",
    era: "Golden Age",
    bio: "Pierre 'Baro' Ferret was a contemporary of Django and a ferocious soloist in his own right. The Ferret family line — Matelot, Sarane, and later generations — remains one of the great French manouche dynasties.",
    notable: "Swing guitar of the 1930s Paris scene",
    youtube_url: "",
    sort_order: 4,
  },
  {
    slug: "tchan-tchou-vidal",
    name: "Tchan Tchou Vidal",
    years: "1923–1999",
    origin: "Aix-en-Provence, France",
    instruments: "Guitar",
    era: "Postwar",
    bio: "A southern French master whose tone and time feel sit close to Django without imitation. Tchan Tchou kept the music alive in the decades when it was still mostly a family tradition.",
    notable: "La Gitane; the Provençal school",
    youtube_url: "",
    sort_order: 5,
  },
  {
    slug: "babik-reinhardt",
    name: "Babik Reinhardt",
    years: "1944–2001",
    origin: "Paris, France",
    instruments: "Guitar",
    era: "Postwar",
    bio: "Django's son. Babik absorbed bebop and fusion without leaving the family sound, becoming a bridge between the golden-age repertoire and a more modern harmonic language.",
    notable: "Bebop-manouche hybrid; Django's lineage",
    youtube_url: "",
    sort_order: 6,
  },
  {
    slug: "fapy-lafertin",
    name: "Fapy Lafertin",
    years: "b. 1950",
    origin: "Kortrijk, Belgium",
    instruments: "Guitar",
    era: "Nouvelle Vague",
    bio: "Often called the player closest to Django's actual sound. Lafertin's tone, vibrato, and ballad playing are a reference for anyone studying the original language rather than the later virtuoso school.",
    notable: "Waso Quartet; the Belgian school",
    youtube_url: "",
    sort_order: 7,
  },
  {
    slug: "tchavolo-schmitt",
    name: "Tchavolo Schmitt",
    years: "b. 1954",
    origin: "Alsace, France",
    instruments: "Guitar",
    era: "Nouvelle Vague",
    bio: "Raw, singing, and completely himself. Tchavolo's playing is the sound of Alsatian Sinti swing — less conservatory, more campfire and dance floor — and a favorite of musicians who want feel over flash.",
    notable: "Alsatian Sinti school; film appearances",
    youtube_url: "",
    sort_order: 8,
  },
  {
    slug: "dorado-schmitt",
    name: "Dorado Schmitt",
    years: "b. 1957",
    origin: "Alsace, France",
    instruments: "Violin, guitar",
    era: "Nouvelle Vague",
    bio: "Patriarch of another Alsatian dynasty. Dorado moves between violin and guitar with the same singing phrasing, and his sons — including Samson — carry the family sound onto the current festival circuit.",
    notable: "Schmitt family; violin and guitar dual threat",
    youtube_url: "",
    sort_order: 9,
  },
  {
    slug: "angelo-debarre",
    name: "Angelo Debarre",
    years: "b. 1962",
    origin: "Saint-Denis, France",
    instruments: "Guitar",
    era: "Nouvelle Vague",
    bio: "A Paris-born virtuoso of Romani origin, Debarre combines blistering technique with deep swing. He is a fixture of the French club and festival circuit and a model for the modern lead guitar chair.",
    notable: "French club circuit; modern lead language",
    youtube_url: "https://www.youtube.com/@danielgueli",
    sort_order: 10,
  },
  {
    slug: "bireli-lagrene",
    name: "Biréli Lagrène",
    years: "b. 1966",
    origin: "Soufflenheim, Alsace, France",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "The prodigy who reopened the world's ears. Lagrène recorded as a teenager in Django's vocabulary, then absorbed fusion, bass, and whatever else he wanted — always returning to swing with an authority nobody else has.",
    notable: "Routes to Django; Gipsy Project; living master",
    youtube_url: "https://www.youtube.com/@danielgueli",
    sort_order: 11,
  },
  {
    slug: "stochelo-rosenberg",
    name: "Stochelo Rosenberg",
    years: "b. 1968",
    origin: "Helmond, Netherlands",
    instruments: "Solo guitar",
    era: "Contemporary",
    bio: "Leader of the Rosenberg Trio and the public face of the Dutch Sinti school. Stochelo's tone is immediately recognizable — fat, singing, and impossibly in time — and the family band remains one of the music's essential working units.",
    notable: "Rosenberg Trio; Dutch Sinti school",
    youtube_url: "https://www.youtube.com/@RosenbergAcademy",
    sort_order: 12,
  },
  {
    slug: "romane",
    name: "Romane",
    years: "b. 1959",
    origin: "Paris, France",
    instruments: "Guitar",
    era: "Nouvelle Vague",
    bio: "Patrick Leguidecoq, known as Romane, is a composer and pedagogue as much as a soloist. His original themes and teaching books have shaped how a generation learns the style.",
    notable: "Composition and pedagogy; French concert stage",
    youtube_url: "https://www.youtube.com/@danielgueli",
    sort_order: 13,
  },
  {
    slug: "jimmy-rosenberg",
    name: "Jimmy Rosenberg",
    years: "b. 1980",
    origin: "Helmond, Netherlands",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "A child prodigy of staggering facility, cousin to Stochelo. Jimmy's early recordings still stop guitarists in their tracks. His story is also a reminder that the music lives in families, with all the pressure that brings.",
    notable: "Prodigy recordings; Rosenberg family",
    youtube_url: "",
    sort_order: 14,
  },
  {
    slug: "mozes-rosenberg",
    name: "Mozes Rosenberg",
    years: "b. 1981",
    origin: "Helmond, Netherlands",
    instruments: "Solo guitar",
    era: "Contemporary",
    bio: "Stochelo's brother and a complete musician — lead and rhythm, tone and time. Mozes leads the Mozes Rosenberg Trio with Daniel Rosenberg on rhythm and Matheus Nicolaiewsky on bass, and plays in The Rosenbergs with Johnny Rosenberg and Sani van Mullem.",
    notable: "Mozes Rosenberg Trio; The Rosenbergs; Rosenberg family",
    youtube_url: "",
    sort_order: 15,
  },
  {
    slug: "samson-schmitt",
    name: "Samson Schmitt",
    years: "b. 1979",
    origin: "Alsace, France",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "Dorado's son, carrying the Alsatian sound with contemporary fire. Samson is a constant on the festival circuit and a link between the Schmitt family tradition and younger players.",
    notable: "Schmitt family; festival circuit",
    youtube_url: "",
    sort_order: 16,
  },
  {
    slug: "joscho-stephan",
    name: "Joscho Stephan",
    years: "b. 1979",
    origin: "Mönchengladbach, Germany",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "German guitarist of dazzling technique and a wide repertoire, from strict manouche to more concert-hall presentations. Stephan has done as much as anyone to put the music on German and international stages.",
    notable: "German concert circuit; modern virtuoso school",
    youtube_url: "https://www.youtube.com/@joschostephan",
    sort_order: 17,
  },
  {
    slug: "adrien-moignard",
    name: "Adrien Moignard",
    years: "b. 1985",
    origin: "France",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "One of the defining lead players of the current French scene. Moignard's time, vocabulary, and ferocity in the high register have made him a first-call soloist from Paris clubs to Samois.",
    notable: "French nouvelle generation; Samois regular",
    youtube_url: "",
    sort_order: 18,
  },
  {
    slug: "paulus-schafer",
    name: "Paulus Schäfer",
    years: "b. 1978",
    origin: "Netherlands",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "A leading voice of the Dutch school after the Rosenbergs. Schäfer's groups swing hard, and his teaching and touring have spread that feel well beyond the Sinti community.",
    notable: "Dutch school; touring ensembles",
    youtube_url: "https://www.youtube.com/@danielgueli",
    sort_order: 19,
  },
  {
    slug: "stephane-wrembel",
    name: "Stéphane Wrembel",
    years: "b. 1974",
    origin: "New York, United States",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "French-born, New York-based composer and guitarist. Wrembel brought Django's language into film (Midnight in Paris) and built Django in June, the American gathering that has become a pilgrimage for players on this side of the Atlantic.",
    notable: "Bistro Fada; Django in June; Django à Gogo",
    youtube_url: "https://www.youtube.com/@danielgueli",
    sort_order: 20,
  },
  {
    slug: "costel-nitescu",
    name: "Costel Nitescu",
    years: "b. 1970",
    origin: "Romania",
    instruments: "Violin",
    era: "Contemporary",
    bio: "The violin voice of the current circuit. Nitescu's sound is both rooted and modern — Eastern European lyricism inside Hot Club swing — and he is a fixture from Samois to New York.",
    notable: "Contemporary violin chair; festival circuit",
    youtube_url: "",
    sort_order: 21,
  },
  {
    slug: "tim-kliphuis",
    name: "Tim Kliphuis",
    years: "b. 1974",
    origin: "Netherlands",
    instruments: "Violin",
    era: "Contemporary",
    bio: "Dutch violinist who moves between Grappelli language, folk, and classical rooms. Kliphuis is also a dedicated educator, and his groups are a model for mixed-lineup gypsy jazz outside the traditional family bands. August 2026 he played Festival Jazz Manouche Piracicaba on the same night as Nuno Marinho. Separate from the May festival week: Tim Kliphuis Trio with Nuno Marinho at Fábrica Braço de Prata, Lisbon (30 Oct 2026) and Salão Brazil, Coimbra (31 Oct 2026). Málaga Manouche DjangoCamp, Frigiliana, 23–25 October 2026.",
    notable: "Grappelli lineage; education and crossover",
    youtube_url: "",
    sort_order: 22,
  },
  {
    slug: "gonzalo-bergara",
    name: "Gonzalo Bergara",
    years: "b. 1980",
    origin: "Buenos Aires, Argentina",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "Proof that the music is no longer only European. Bergara's Argentine fire and Los Angeles years helped build a serious American scene, with original writing that still swings in 4/4 pompe.",
    notable: "South American voice; US club circuit",
    youtube_url: "",
    sort_order: 23,
  },
  {
    slug: "rocky-gresset",
    name: "Rocky Gresset",
    years: "b. 1980",
    origin: "France",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "A French guitarist of rare touch and lyricism. Gresset is as convincing on a ballad as on an uptempo stomp, and a regular collaborator for the current generation of lead players.",
    notable: "French lyric school; collaborative circuit",
    youtube_url: "",
    sort_order: 24,
  },
  {
    slug: "lulo-reinhardt",
    name: "Lulo Reinhardt",
    years: "b. 1961",
    origin: "Koblenz, Germany",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "A grandnephew of Django who has spent decades taking the family name on the road with his own Latin-tinged and straight-ahead projects. A living reminder that Reinhardt is both a surname and a tradition.",
    notable: "Reinhardt family; German and world touring",
    youtube_url: "",
    sort_order: 25,
  },
  {
    slug: "wawau-adler",
    name: "Wawau Adler",
    years: "b. 1967",
    origin: "Karlsruhe, Germany",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "German Sinti guitarist with a hard swing and a singing lead tone. Adler is a pillar of the German scene and a regular at European festivals.",
    notable: "German Sinti school",
    youtube_url: "",
    sort_order: 26,
  },
  {
    slug: "andreas-oberg",
    name: "Andreas Öberg",
    years: "b. 1978",
    origin: "Stockholm, Sweden",
    instruments: "Guitar",
    era: "Contemporary",
    bio: "Swedish guitarist who treats gypsy jazz as one dialect among several, with the technique to sit in any of them. A frequent guest on the manouche circuit and a bridge to the wider jazz guitar world.",
    notable: "Nordic scene; crossover jazz guitar",
    youtube_url: "",
    sort_order: 27,
  },
  {
    slug: "hono-winterstein",
    name: "Hono Winterstein",
    years: "b. 1962",
    origin: "Forbach, France",
    instruments: "Rhythm guitar",
    era: "Nouvelle Vague",
    bio: "One of the great living rhythm guitarists. Winterstein's pompe is a masterclass in time, and he has driven groups for Biréli, Tchavolo, and countless festival lineups.",
    notable: "Rhythm chair of the modern circuit",
    youtube_url: "",
    sort_order: 28,
  },
  {
    slug: "ninine-garcia",
    name: "Ninine Garcia",
    years: "b. 1956",
    origin: "France",
    instruments: "Guitar",
    era: "Nouvelle Vague",
    bio: "A French guitarist steeped in the tradition, equally at home leading and accompanying. Garcia represents the working musician's Hot Club — clubs, dances, and festivals rather than virtuoso showcase alone.",
    notable: "French working circuit",
    youtube_url: "",
    sort_order: 29,
  },
  {
    slug: "daniel-gueli",
    name: "Daniel Gueli",
    years: "",
    origin: "Netherlands",
    instruments: "Double bass",
    era: "The Circle",
    bio: "Netherlands double bass. Gypsy jazz. Creator of Gypsy Jazz Hub. On stage he is the double bass of the Marcia Bamberg Swing Quartet, the Django Rosenberg Trio with Noekie Basily, and Gismo Graf.",
    notable: "Creator of Gypsy Jazz Hub; Marcia Bamberg Swing Quartet; Django Rosenberg Trio; Gismo Graf",
    youtube_url: "https://www.youtube.com/@danielgueli",
    sort_order: 30,
  },
  {
    slug: "matelo-ferret",
    name: "Matelo Ferret",
    years: "1918–1989",
    origin: "Rouen, France",
    instruments: "Guitar",
    era: "Golden Age",
    bio: "Jean 'Matelo' Ferret, youngest of the Ferret brothers. He played with Django, kept the Parisian musette-and-manouche guitar alive after the war, and fathered Boulou and Elios Ferré.",
    notable: "Ferret family; musette and manouche guitar; father of Boulou and Elios",
    youtube_url: "",
    sort_order: 31,
  },
  {
    slug: "sarane-ferret",
    name: "Sarane Ferret",
    years: "1912–1970",
    origin: "Rouen, France",
    instruments: "Guitar",
    era: "Golden Age",
    bio: "Guillaume 'Sarane' Ferret. Brother of Baro and Matelo. A swing guitarist of the 1930s–50s Paris scene, often beside Django and in the family Hot Club rooms.",
    notable: "Ferret brothers; 1930s Paris swing",
    youtube_url: "",
    sort_order: 32,
  },
  {
    slug: "louis-vola",
    name: "Louis Vola",
    years: "1902–1990",
    origin: "La Seyne-sur-Mer, France",
    instruments: "Double bass",
    era: "Golden Age",
    bio: "The bass of the original Quintette du Hot Club de France. Vola held Django and Grappelli to the floor on the records that still teach the music — two-and-four, walking when the soloist needs air.",
    notable: "Quintette du Hot Club de France",
    youtube_url: "",
    sort_order: 33,
  },
  {
    slug: "roger-chaput",
    name: "Roger Chaput",
    years: "1909–1995",
    origin: "France",
    instruments: "Rhythm guitar",
    era: "Golden Age",
    bio: "Rhythm guitar of the early Quintette du Hot Club de France, beside Joseph Reinhardt. Chaput’s pompe is on the first Hot Club sides — the chair every rhythm player still studies.",
    notable: "Quintette du Hot Club de France; early pompe",
    youtube_url: "",
    sort_order: 34,
  },
  {
    slug: "tata-mirando",
    name: "Tata Mirando (Joseph Weiss)",
    years: "1895–1967",
    origin: "Dieren, Netherlands",
    instruments: "Double bass, violin",
    era: "Golden Age",
    bio: "Joseph Weiss, Tata Mirando, was a Sinti musician, violin maker and leader of the family gypsy orchestra that took the name Mirando. Born in Opfikon, Switzerland, in 1895, he brought the family to the Netherlands in 1937. The orchestra played the Kurhaus, private houses and the Dutch royal household: Hungarian csárdás, Romanian song, and sometimes gypsy jazz. The sons kept the name on Dutch stages.",
    notable: "Tata Mirando orchestra; Weiss family; Dutch Sinti",
    youtube_url: "https://www.youtube.com/watch?v=1aPVACDHK-c",
    sort_order: 35,
  },
  {
    slug: "hansche-weiss",
    name: "Häns’che Weiss",
    years: "1951–2016",
    origin: "Berlin, Germany",
    instruments: "Guitar",
    era: "Golden Age",
    bio: "German Sinti guitarist of the postwar revival. His quintet carried the tradition on German stages; he took Titi Winterstein in at fifteen. The 1970s records with Schnuckenack and Titi are the German house document.",
    notable: "Häns’che Weiss Quintett; German Sinti guitar",
    youtube_url: "https://www.youtube.com/watch?v=gfdgNK1RXYs",
    sort_order: 36,
  },
  {
    slug: "titi-winterstein",
    name: "Titi Winterstein",
    years: "1956–2008",
    origin: "Germany",
    instruments: "Violin",
    era: "Golden Age",
    bio: "German Sinti violinist, 1956–2008. Father Tokeli survived the Nazi years when much of the family did not. First stage: Sinti pilgrimage, Illingen, 1965. Häns’che Weiss took him at fifteen. Own quintet from 1978, six records, Django Reinhardt prize 2003. Died in Offenburg.",
    notable: "Titi Winterstein Quintett; German Sinti violin",
    youtube_url: "https://www.youtube.com/watch?v=yG45rZeNtsM",
    sort_order: 37,
  },
  {
    slug: "sandor-jaroka",
    name: "Sándor Járóka",
    years: "1922–1984",
    origin: "Budapest, Hungary",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Hungarian Roma primas, born 16 February 1922 in Kisvárda, died 11 April 1984 in Budapest. Called the primas of kings. At his funeral the Roma musicians of Budapest gathered; from that serenade the Budapest Gypsy Symphony Orchestra (100 Tagú Cigányzenekar) was born.",
    notable: "Hungarian primas; Budapest Gypsy Symphony Orchestra",
    youtube_url: "",
    sort_order: 38,
  },
  {
    slug: "sandor-jaroka-jr",
    name: "Sándor Járóka Jr",
    years: "1954–2007",
    origin: "Budapest, Hungary",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Hungarian primas, son of Sándor Járóka. Born 30 September 1954 in Budapest, died 18 September 2007. He carried his father’s gypsy orchestra. Married to singer Bangó Margit.",
    notable: "Sándor Járóka Jr and His Gypsy Band",
    youtube_url: "",
    sort_order: 39,
  },
  {
    slug: "lajos-boross",
    name: "Lajos Boross",
    years: "1925–2014",
    origin: "Budapest, Hungary",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Hungarian gypsy violinist and conductor, born 7 January 1925 in Budapest, died 8 July 2014. Leader of Lajos Boross and His Gypsy Band — the restaurant and concert primas chair.",
    notable: "Lajos Boross and His Gypsy Band",
    youtube_url: "",
    sort_order: 40,
  },
  {
    slug: "toki-horvath",
    name: "Toki Horváth (Gyula)",
    years: "1920–1971",
    origin: "Kaposvár, Hungary",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Gyula “Toki” Horváth, Hungarian primas, born 17 September 1920 in Kaposvár, died 13 October 1971 in Munich. First violin of the Rajkó Orchestra from 1931. Records billed him King of the Gypsies.",
    notable: "Rajkó Orchestra; King of the Gypsies",
    youtube_url: "",
    sort_order: 41,
  },
  {
    slug: "veres-lajos",
    name: "Veres Lajos",
    years: "1912–1981",
    origin: "Hungary",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Hungarian Roma primas, 1912–1981. Veres Lajos et son orchestre recorded Gipsy Souvenirs (1953) — Hungarian, Romanian and Russian gypsy melodies — for the French labels that later sat in the BnF collection (World Europe). The same book the Mirando orchestra played in the Netherlands.",
    notable: "Veres Lajos et son orchestre; Gipsy Souvenirs",
    youtube_url: "https://www.youtube.com/watch?v=-RINm0oACWA",
    sort_order: 42,
  },
  {
    slug: "lajos-kiss",
    name: "Lajos Kiss",
    years: "1902–1951",
    origin: "Debrecen, Hungary",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Hungarian violinist, born Debrecen 1902, died Budapest 20 January 1951. Played in his father’s orchestra from the age of eight, then led his own band. One of the primas names the Mirando family still keep.",
    notable: "Hungarian primas",
    youtube_url: "",
    sort_order: 43,
  },
  {
    slug: "sandor-lakatos",
    name: "Sándor Lakatos",
    years: "1924–1994",
    origin: "Budapest, Hungary",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Hungarian Roma primas, born 17 December 1924 in Budapest, died 24 May 1994 in Budapest. Uncle of Roby Lakatos. Roby learned in Sándor’s band and in his father Antal’s. Sándor led the Hungarian state radio folk orchestra 1950–52 and took the café violin around the world — the family book Roby later walked into jazz.",
    notable: "Lakatos family; Roby Lakatos’s uncle",
    youtube_url: "",
    sort_order: 44,
  },
  {
    slug: "georges-boulanger",
    name: "Georges Boulanger",
    years: "1893–1958",
    origin: "Tulcea, Romania",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Gheorghe Pantazi, billed Georges Boulanger. Born 18 April 1893 in Tulcea, Romania; died 3 June 1958. Violinist, conductor and composer — gypsy colour with Viennese light music. The Great Gypsy Violinist records (1934–1939). A Romanian chair, not a Budapest primas, named by the Mirando family beside the Hungarian orchestras.",
    notable: "Georges Boulanger and His Orchestra",
    youtube_url: "",
    sort_order: 45,
  },
  {
    slug: "kokalo-mirando",
    name: "Kokalo Mirando (Adolf Weiss)",
    years: "1933–2025",
    origin: "Arnhem, Netherlands",
    instruments: "Piano",
    era: "Golden Age",
    bio: "Adolf Kokalo Weiss (1933–2025), son of Joseph Weiss, billed Kokalo Mirando. Piano in the Tata Mirando orchestra — the 2001 film Een zwaar hart lists him on that chair. He later carried the Tata Mirando name himself. Died in Arnhem after a short illness, October 2025.",
    notable: "Tata Mirando orchestra; piano; later Tata",
    youtube_url: "",
    sort_order: 46,
  },
  {
    slug: "lako-aladar",
    name: "Lako Aladar",
    years: "† by 2001",
    origin: "Romania",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Romanian violinist. The 2001 VPRO film Een zwaar hart (Tata Mirando family) bills him under Romania, marked deceased. Guest chair beside the Dutch orchestra, not a Hot Club quintet.",
    notable: "Een zwaar hart; Romanian violin",
    youtube_url: "",
    sort_order: 47,
  },
  {
    slug: "fodor-sandor-neti",
    name: "Fodor Sándor “Neti”",
    years: "1922–2004",
    origin: "Méra, Romania",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Transylvanian Roma primas, born 2 April 1922 in Gilău (Gyalu), Cluj County, died 20 October 2004. Leader of Mera Gypsy Band from the Kalotaszeg village Méra. The 2001 film Een zwaar hart bills the band beside the Tata Mirando orchestra.",
    notable: "Mera Gypsy Band; Kalotaszeg primas",
    youtube_url: "",
    sort_order: 48,
  },
  {
    slug: "erno-kallai-kiss",
    name: "Ernő Kállai Kiss",
    years: "1939–2023",
    origin: "Budapest, Hungary",
    instruments: "Clarinet",
    era: "Golden Age",
    bio: "Hungarian Roma clarinetist, born 17 August 1939 in Budapest, died 17 October 2023. Billed the gypsy king of clarinet. Records with his own zenekara and with Frido Diepeveen. The International Archive for Sinti & Gypsy Music keeps the Dutch and Hungarian nights.",
    notable: "Ernő Kállai Kiss és zenekara; clarinet",
    youtube_url: "https://www.youtube.com/watch?v=4jBlN7ylR4Q",
    sort_order: 49,
  },
  {
    slug: "rinaldo-olah",
    name: "Rinaldo Oláh",
    years: "1929–2006",
    origin: "Zvolenská Slatina, Slovakia",
    instruments: "Violin",
    era: "Golden Age",
    bio: "Slovak Roma primas, born 13 January 1929 in Zvolenská Slatina, died 1 June 2006 in Bratislava. Called the Slovak Paganini. Concertmaster of SĽUK for more than thirty years. The International Archive bills Oláh Rinaldo the primas and his violin.",
    notable: "SĽUK; Slovak primas",
    youtube_url: "https://www.youtube.com/watch?v=_0ocB5_cXTM",
    sort_order: 50,
  },
  {
    slug: "nicolae-neacsu",
    name: "Nicolae Neacșu",
    years: "1924–2002",
    origin: "Clejani, Romania",
    instruments: "Violin, vocal",
    era: "Golden Age",
    bio: "Romanian lăutar violin from Clejani, billed Culai. A core chair of Taraf de Haïdouks. Born 1924, died September 2002. The International Archive posted the Haidouks documentary for listeners of Romanian Roma music.",
    notable: "Taraf de Haïdouks; Clejani",
    youtube_url: "https://www.youtube.com/watch?v=fwKNU1mBhjQ",
    sort_order: 51,
  },
  {
    slug: "manitas-de-plata",
    name: "Manitas de Plata",
    years: "1921–2014",
    origin: "Sète, France",
    instruments: "Guitar",
    era: "Golden Age",
    bio: "Ricardo Baliardo, billed Manitas de Plata — little hands of silver. Catalan Gitano guitar, born 7 August 1921 in a caravan near Sète, died 5 November 2014 in Montpellier. Played with José Reyes. Uncle of the Reyes brothers; father of the Baliardo brothers who later formed the Gipsy Kings. Flamenco and rumba — family music, like Tata Mirando: not a Hot Club quintet, still this world.",
    notable: "Manitas de Plata; Gipsy Kings lineage",
    youtube_url: "",
    sort_order: 52,
  },
  {
    slug: "jose-reyes",
    name: "José Reyes",
    years: "d. 1979",
    origin: "Arles, France",
    instruments: "Vocal",
    era: "Golden Age",
    bio: "Catalan Gitano singer from Arles. Sang with Manitas de Plata. After they split he led José et Los Reyes with his sons Nicolas, Canut, André, Patchaï and Pablo. Died 1979. The sons later joined the Baliardo cousins as the Gipsy Kings. Family rumba — the same overlap as Tata Mirando: not Django, still this music.",
    notable: "José et Los Reyes; father of the Reyes brothers",
    youtube_url: "",
    sort_order: 53,
  },
];

export const LEGENDS: LegendSeed[] = [
  ...CORE_LEGENDS,
  ...SAMOIS_ARTISTS,
  ...CIRCLE_ARTISTS,
].map(applyArtistBio);

const CORE_CONCERTS: ConcertSeed[] = [
  {
    legend_slug: "django-reinhardt",
    title: "Quintette du Hot Club de France — debut season",
    venue: "Hôtel Claridge",
    city: "Paris",
    country: "France",
    starts_at: "1934-12-02T20:00:00.000Z",
    is_historic: true,
    note: "The public beginning of the Quintette, with Grappelli and the Ferret/Reinhardt rhythm.",
  },
  {
    legend_slug: "django-reinhardt",
    title: "Django with Duke Ellington",
    venue: "Cleveland Public Auditorium",
    city: "Cleveland",
    country: "USA",
    starts_at: "1946-11-04T20:00:00.000Z",
    is_historic: true,
    note: "The American tour that put Django in front of a big-band audience.",
  },
  {
    legend_slug: "django-reinhardt",
    title: "Last studio session",
    venue: "Radio studio",
    city: "Rome",
    country: "Italy",
    starts_at: "1953-04-20T18:00:00.000Z",
    is_historic: true,
    note: "Late electric-guitar Django, weeks before his death in Fontainebleau.",
  },
  {
    legend_slug: "django-reinhardt",
    title: "Quintette du Hot Club de France — Spain",
    venue: "Cine Coliseum",
    city: "Barcelona",
    country: "Spain",
    starts_at: "1936-01-29T19:00:00.000Z",
    is_historic: true,
    note: "Django Reinhardt, Quintette du Hot Club de France and Stéphane Grappelli. Django’s only Spain concerts: 29 Jan Cine Coliseum, 31 Jan Palau de la Música, 2 Feb Teatre Olympia. Late jam under Pont de Marina.",
  },
  {
    legend_slug: "django-reinhardt",
    title: "Quintette du Hot Club de France — Spain",
    venue: "Palau de la Música Catalana",
    city: "Barcelona",
    country: "Spain",
    starts_at: "1936-01-31T19:00:00.000Z",
    is_historic: true,
    note: "With Stéphane Grappelli. One of Django’s three Barcelona nights, January–February 1936.",
  },
  {
    legend_slug: "django-reinhardt",
    title: "Quintette du Hot Club de France — Spain",
    venue: "Teatre Olympia",
    city: "Barcelona",
    country: "Spain",
    starts_at: "1936-02-02T19:00:00.000Z",
    is_historic: true,
    note: "With Stéphane Grappelli. Last of Django’s three Barcelona nights, 1936.",
  },
  {
    legend_slug: "stephane-grappelli",
    title: "Hot Club recordings",
    venue: "Gramophone / Ultraphone sessions",
    city: "Paris",
    country: "France",
    starts_at: "1935-03-14T14:00:00.000Z",
    is_historic: true,
    note: "The 78s that still teach the style.",
  },
  {
    legend_slug: "stephane-grappelli",
    title: "Menuhin & Grappelli",
    venue: "Festival Hall",
    city: "London",
    country: "UK",
    starts_at: "1973-06-18T19:30:00.000Z",
    is_historic: true,
    note: "The crossover concerts that introduced a new public to Hot Club violin.",
  },
  {
    legend_slug: "bireli-lagrene",
    title: "Routes to Django",
    venue: "Villingen sessions",
    city: "Villingen",
    country: "Germany",
    starts_at: "1980-06-01T18:00:00.000Z",
    is_historic: true,
    note: "The teenage recording that announced a new master.",
  },
  {
    legend_slug: "stochelo-rosenberg",
    title: "Rosenberg Trio — Serenata",
    venue: "European tour",
    city: "Amsterdam",
    country: "Netherlands",
    starts_at: "1990-05-12T20:00:00.000Z",
    is_historic: true,
    note: "The record that carried the Dutch school around the world.",
  },
];

export const LEGEND_CONCERTS: ConcertSeed[] = [
  ...CORE_CONCERTS,
  ...CIRCLE_CONCERTS,
];
