export type CatalogTeacher = {
  countrySlug: string;
  name: string;
  instruments: string;
  contact: string;
  region: string;
  city: string;
  note: string;
  artistSlug: string;
};

/** Seeded private teachers — not user-submitted. Upserted into hub_teachers. */
export const CATALOG_TEACHERS: CatalogTeacher[] = [
  {
    countrySlug: "netherlands",
    name: "Marcia Bamberg",
    instruments: "Vocal",
    contact: "https://marciabamberg.nl/marcia-bamberg-vocal-coach",
    region: "Noord-Holland",
    city: "Obdam",
    artistSlug: "marcia-bamberg",
    note: "Vocal coach. Private 60-minute lessons for beginners and experienced singers, any style — you bring the songs. Healthy voice, practical method, your pace. Workshop The Essence of the Voice: 4–8 people, every age, ±3.5 hours. Dutch, English, French. Book on her site or write mbamberg@kpnplanet.nl.",
  },
  {
    countrySlug: "germany",
    name: "Bertino Rodmann",
    instruments: "Guitar",
    contact: "https://www.bertino-guitarrist.com/en/",
    region: "Hessen",
    city: "Frankfurt",
    artistSlug: "bertino-rodmann",
    note: "Gypsy jazz guitar, Frankfurt. Weekend masterclass (Cassellapark, pompe, rest-stroke, arpeggios). Method books Gypsyjazz Guitar Vol. 1 & 2, and The REAL Gypsy-Jazz Book Edition 2026 (420 charts, PDF + iReal). Shop and info: bertino-guitarrist.com.",
  },
  {
    countrySlug: "netherlands",
    name: "Christiaan van Hemert",
    instruments: "Violin, guitar",
    contact: "https://christiaanvanhemert.com/workshops",
    region: "",
    city: "Rotterdam",
    artistSlug: "christiaan-van-hemert",
    note: "Van Hemert System — guitar and violin, improvisation, workshops online and on the road. Teaches at Codarts Rotterdam. A first-call guest with the Rosenberg Trio. La Pompe Live is his app.",
  },
  {
    countrySlug: "japan",
    name: "Denis Chang",
    instruments: "Guitar",
    contact: "https://www.dc-musicschool.com/",
    region: "",
    city: "Tokyo",
    artistSlug: "denis-chang",
    note: "Musician and teacher. Lives in Japan. DC Music School is online worldwide — lessons, transcriptions and the YouTube library. Personal channel @DenisChangMusic; school channel @DCMusicSchool.",
  },
  {
    countrySlug: "germany",
    name: "Joscho Stephan",
    instruments: "Guitar",
    contact: "https://gypsyguitaracademy.com/",
    region: "Nordrhein-Westfalen",
    city: "Mönchengladbach",
    artistSlug: "joscho-stephan",
    note: "Joscho Stephan Gypsy Guitar Academy — technique, repertoire and the German concert-school take on Django’s guitar. Online worldwide.",
  },
  {
    countrySlug: "netherlands",
    name: "Stochelo Rosenberg",
    instruments: "Guitar",
    contact: "https://rosenbergacademy.com/",
    region: "Noord-Brabant",
    city: "Helmond",
    artistSlug: "stochelo-rosenberg",
    note: "Rosenberg Academy — the Rosenberg family’s school. Stochelo and the Dutch Sinti chair, taught so amateurs anywhere can work the pompe and the lead language.",
  },
  {
    countrySlug: "portugal",
    name: "Nuno Marinho",
    instruments: "Guitar",
    contact: "https://www.nunomarinho.com/gypsy-jazz-workshops/",
    region: "",
    city: "Lisbon",
    artistSlug: "nuno-marinho",
    note: "Saturday Gypsy Jazz Workshops on Zoom, 15:00 UTC. Ninety minutes. Also teaches at Django in June and the Grappelli-Django Camp. nunomarinho.com.",
  },
  {
    countrySlug: "netherlands",
    name: "Tim Kliphuis",
    instruments: "Violin, guitar, bass",
    contact: "https://gypsyjazzviolinlessons.com/",
    region: "",
    city: "Amsterdam",
    artistSlug: "tim-kliphuis",
    note: "Tim Kliphuis Studio — violin, guitar and bass. Monthly songs, crash courses, play-alongs. Grappelli-Django camp. Professor of Improvisation at the Amsterdam Conservatoire. Studio: gypsyjazzviolinlessons.com.",
  },
  {
    countrySlug: "netherlands",
    name: "John Ligthart",
    instruments: "Guitar",
    contact: "https://gitaarschoolheiloo.nl/docent-bij-gitaarschool-heiloo-johnny-ligthart/",
    region: "Noord-Holland",
    city: "Heiloo",
    artistSlug: "john-ligthart",
    note: "Gitaarschool Heiloo. Private lessons — gypsy jazz and the rest of the guitar.",
  },
  {
    countrySlug: "germany",
    name: "Sven Jungbeck",
    instruments: "Guitar",
    contact: "https://www.youtube.com/@SvenJungbeck",
    region: "Nordrhein-Westfalen",
    city: "Bergheim",
    artistSlug: "sven-jungbeck",
    note: "Rhythm guitar of the Joscho Stephan Trio. Teaches from Bergheim — Proper Chords and online lessons.",
  },
  {
    countrySlug: "taiwan",
    name: "Vincent Tsai",
    instruments: "Accordion",
    contact: "https://www.vincentaccordion.net/",
    region: "",
    city: "Taipei",
    artistSlug: "vincent-tsai",
    note: "Vincent’s Accordion Studio — accordion teaching and repair in Taipei, with rooms in Taichung and Kaohsiung. Classroom of Taipei Gypsy Jazz Festival workshops. vincent.tsai.arts@gmail.com.",
  },
  {
    countrySlug: "kuwait",
    name: "Patil Zakarian",
    instruments: "Piano",
    contact: "https://about.me/patilzakarian",
    region: "",
    city: "Kuwait City",
    artistSlug: "patil-zakarian",
    note: "Piano manouche. Arranges Django, Tchan-Tchou and Angelo Debarre for solo piano. Channel Pat_Pianooo. Sheet via music.pzakarian@yahoo.com. Also teaches in Belgium.",
  },
  {
    countrySlug: "taiwan",
    name: "Yen-Hua Wang",
    instruments: "Harmonica",
    contact: "https://laelapsharmonica.com/en/laelaps-club/yen-hua-wang/",
    region: "",
    city: "Taipei",
    artistSlug: "yen-hua-wang",
    note: "Chromatic harmonica — full-time teaching and performance. Taipei Gypsy Jazz Festival, Piracicaba and Curitiba. Channel 王衍華Yen-Hua Wang.",
  },
  {
    countrySlug: "israel",
    name: "Yaakov Hoter",
    instruments: "Guitar",
    contact: "https://www.gypsyandjazz.com/",
    region: "",
    city: "Tel Aviv",
    artistSlug: "yaakov-hoter",
    note: "Gypsy & Jazz Academy — online and in person. Founder of Swing de Gitanes. gypsyandjazz.com.",
  },
  {
    countrySlug: "belgium",
    name: "Renaud Dardenne",
    instruments: "Guitar",
    contact: "https://muziekpublique.be/lessons/guitare-manouche-ensemble-swing-manouche/",
    region: "Brussels",
    city: "Brussels",
    artistSlug: "renaud-dardenne",
    note: "Ensemble swing manouche at Muziekpublique, Brussels. Guitar — the Belgian manouche room next to Tcha Limberger and Fapy Lafertin.",
  },
  {
    countrySlug: "belgium",
    name: "Patil Zakarian",
    instruments: "Piano",
    contact: "https://about.me/patilzakarian",
    region: "",
    city: "",
    artistSlug: "patil-zakarian",
    note: "Piano manouche. Arranges Django, Tchan-Tchou and Angelo Debarre for solo piano. Channel Pat_Pianooo. Sheet via music.pzakarian@yahoo.com. Also teaches in Kuwait.",
  },
];
