export const MAIL_LOCALES = [
  "en",
  "nl",
  "fr",
  "de",
  "es",
  "it",
  "pt",
  "ru",
  "hu",
  "ro",
  "pl",
  "cs",
  "sr",
  "hr",
  "ja",
  "ko",
  "zh",
  "zh-tw",
  "id",
  "th",
  "he",
] as const;

export type MailLocale = (typeof MAIL_LOCALES)[number];

type MailCopy = { subject: string; lines: string[] };

const LOGIN = "https://www.gypsyjazzhub.com/login";

const COPY: Record<MailLocale, MailCopy> = {
  en: {
    subject: "Welcome to Gypsy Jazz Hub",
    lines: [
      "Welcome — and thank you for joining Gypsy Jazz Hub.",
      "",
      "Open this link to confirm your email:",
      "{link}",
      "",
      "After that, login is simple: the same email and the password you chose.",
      LOGIN,
      "",
      "If you did not join, you can ignore this mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  nl: {
    subject: "Welkom bij Gypsy Jazz Hub",
    lines: [
      "Welkom — en dank je wel dat je lid wordt van Gypsy Jazz Hub.",
      "",
      "Open deze link om je e-mail te bevestigen:",
      "{link}",
      "",
      "Daarna is inloggen simpel: hetzelfde e-mailadres en het wachtwoord dat je koos.",
      LOGIN,
      "",
      "Als jij dit niet was, kun je deze mail negeren.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  fr: {
    subject: "Bienvenue sur Gypsy Jazz Hub",
    lines: [
      "Bienvenue — et merci de rejoindre Gypsy Jazz Hub.",
      "",
      "Ouvre ce lien pour confirmer ton e-mail :",
      "{link}",
      "",
      "Ensuite, la connexion est simple : le même e-mail et le mot de passe que tu as choisi.",
      LOGIN,
      "",
      "Si tu n’as pas créé de compte, ignore ce mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  de: {
    subject: "Willkommen bei Gypsy Jazz Hub",
    lines: [
      "Willkommen — und danke, dass du bei Gypsy Jazz Hub mitmachst.",
      "",
      "Öffne diesen Link, um deine E-Mail zu bestätigen:",
      "{link}",
      "",
      "Danach ist der Login einfach: dieselbe E-Mail und das Passwort, das du gewählt hast.",
      LOGIN,
      "",
      "Wenn du dich nicht angemeldet hast, kannst du diese Mail ignorieren.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  es: {
    subject: "Bienvenido a Gypsy Jazz Hub",
    lines: [
      "Bienvenido — y gracias por unirte a Gypsy Jazz Hub.",
      "",
      "Abre este enlace para confirmar tu correo:",
      "{link}",
      "",
      "Después, entrar es simple: el mismo correo y la contraseña que elegiste.",
      LOGIN,
      "",
      "Si no te inscribiste, puedes ignorar este correo.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  it: {
    subject: "Benvenuto su Gypsy Jazz Hub",
    lines: [
      "Benvenuto — e grazie per essere entrato in Gypsy Jazz Hub.",
      "",
      "Apri questo link per confermare la tua email:",
      "{link}",
      "",
      "Poi l’accesso è semplice: la stessa email e la password che hai scelto.",
      LOGIN,
      "",
      "Se non ti sei iscritto, ignora questa mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  pt: {
    subject: "Bem-vindo ao Gypsy Jazz Hub",
    lines: [
      "Bem-vindo — e obrigado por te juntares ao Gypsy Jazz Hub.",
      "",
      "Abre este link para confirmar o teu email:",
      "{link}",
      "",
      "Depois, entrar é simples: o mesmo email e a palavra-passe que escolheste.",
      LOGIN,
      "",
      "Se não foste tu, podes ignorar este mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ru: {
    subject: "Добро пожаловать в Gypsy Jazz Hub",
    lines: [
      "Добро пожаловать — и спасибо, что присоединились к Gypsy Jazz Hub.",
      "",
      "Откройте эту ссылку, чтобы подтвердить почту:",
      "{link}",
      "",
      "Потом вход простой: та же почта и пароль, который вы выбрали.",
      LOGIN,
      "",
      "Если это были не вы, просто проигнорируйте письмо.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  hu: {
    subject: "Üdv a Gypsy Jazz Hubon",
    lines: [
      "Üdv — és köszönjük, hogy csatlakozol a Gypsy Jazz Hubhoz.",
      "",
      "Nyisd meg ezt a linket az e-mail megerősítéséhez:",
      "{link}",
      "",
      "Utána a belépés egyszerű: ugyanaz az e-mail és a jelszó, amit választottál.",
      LOGIN,
      "",
      "Ha nem te jelentkeztél, hagyd figyelmen kívül ezt a levelet.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ro: {
    subject: "Bun venit pe Gypsy Jazz Hub",
    lines: [
      "Bun venit — și mulțumim că te-ai alăturat Gypsy Jazz Hub.",
      "",
      "Deschide acest link ca să confirmi e-mailul:",
      "{link}",
      "",
      "Apoi autentificarea e simplă: același e-mail și parola pe care ai ales-o.",
      LOGIN,
      "",
      "Dacă nu tu te-ai înscris, ignoră acest mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  pl: {
    subject: "Witamy w Gypsy Jazz Hub",
    lines: [
      "Witamy — i dziękujemy, że dołączasz do Gypsy Jazz Hub.",
      "",
      "Otwórz ten link, żeby potwierdzić e-mail:",
      "{link}",
      "",
      "Potem logowanie jest proste: ten sam e-mail i hasło, które wybrałeś.",
      LOGIN,
      "",
      "Jeśli to nie ty, zignoruj tę wiadomość.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  cs: {
    subject: "Vítejte na Gypsy Jazz Hub",
    lines: [
      "Vítejte — a díky, že se přidáváte k Gypsy Jazz Hub.",
      "",
      "Otevřete tento odkaz a potvrďte e-mail:",
      "{link}",
      "",
      "Pak je přihlášení jednoduché: stejný e-mail a heslo, které jste zvolili.",
      LOGIN,
      "",
      "Pokud jste se neregistrovali, e-mail ignorujte.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  sr: {
    subject: "Dobrodošli na Gypsy Jazz Hub",
    lines: [
      "Dobrodošli — i hvala što se pridružujete Gypsy Jazz Hubu.",
      "",
      "Otvorite ovaj link da potvrdite mejl:",
      "{link}",
      "",
      "Posle toga je prijava jednostavna: isti mejl i lozinka koju ste izabrali.",
      LOGIN,
      "",
      "Ako se niste vi prijavili, ignorišite ovaj mejl.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  hr: {
    subject: "Dobrodošli na Gypsy Jazz Hub",
    lines: [
      "Dobrodošli — i hvala što se pridružujete Gypsy Jazz Hubu.",
      "",
      "Otvorite ovaj link da potvrdite e-mail:",
      "{link}",
      "",
      "Nakon toga je prijava jednostavna: isti e-mail i lozinka koju ste odabrali.",
      LOGIN,
      "",
      "Ako se niste vi prijavili, zanemarite ovaj mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ja: {
    subject: "Gypsy Jazz Hub へようこそ",
    lines: [
      "ようこそ。Gypsy Jazz Hub に参加してくれてありがとうございます。",
      "",
      "このリンクを開いてメールを確認してください:",
      "{link}",
      "",
      "あとは簡単です。同じメールと、いま選んだパスワードでログインできます。",
      LOGIN,
      "",
      "この登録に覚えがなければ、このメールは無視してください。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ko: {
    subject: "Gypsy Jazz Hub에 오신 것을 환영합니다",
    lines: [
      "환영합니다. Gypsy Jazz Hub에 가입해 주셔서 감사합니다.",
      "",
      "이 링크를 열어 이메일을 확인해 주세요:",
      "{link}",
      "",
      "그다음 로그인은 간단합니다. 같은 이메일과 방금 고른 비밀번호면 됩니다.",
      LOGIN,
      "",
      "가입한 적이 없다면 이 메일은 무시하세요.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  zh: {
    subject: "欢迎来到 Gypsy Jazz Hub",
    lines: [
      "欢迎 — 谢谢你加入 Gypsy Jazz Hub。",
      "",
      "打开这个链接确认邮箱：",
      "{link}",
      "",
      "之后登录很简单：同一个邮箱，加上你刚设的密码。",
      LOGIN,
      "",
      "如果不是你注册的，请忽略这封邮件。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  "zh-tw": {
    subject: "歡迎來到 Gypsy Jazz Hub",
    lines: [
      "歡迎 — 謝謝你加入 Gypsy Jazz Hub。",
      "",
      "打開這個連結確認電子郵件：",
      "{link}",
      "",
      "之後登入很簡單：同一個信箱，加上你剛設的密碼。",
      LOGIN,
      "",
      "如果不是你註冊的，請忽略這封信。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  id: {
    subject: "Selamat datang di Gypsy Jazz Hub",
    lines: [
      "Selamat datang — terima kasih sudah bergabung di Gypsy Jazz Hub.",
      "",
      "Buka tautan ini untuk mengonfirmasi email:",
      "{link}",
      "",
      "Sesudah itu masuknya sederhana: email yang sama dan kata sandi yang baru kamu pilih.",
      LOGIN,
      "",
      "Kalau bukan kamu yang daftar, abaikan saja email ini.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  th: {
    subject: "ยินดีต้อนรับสู่ Gypsy Jazz Hub",
    lines: [
      "ยินดีต้อนรับ — ขอบคุณที่เข้าร่วม Gypsy Jazz Hub",
      "",
      "เปิดลิงก์นี้เพื่อยืนยันอีเมล:",
      "{link}",
      "",
      "จากนั้นเข้าสู่ระบบง่าย ๆ: อีเมลเดิมกับรหัสผ่านที่เพิ่งตั้ง",
      LOGIN,
      "",
      "ถ้าไม่ได้สมัครเอง ละเว้นเมลนี้ได้",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  he: {
    subject: "ברוכים הבאים ל-Gypsy Jazz Hub",
    lines: [
      "ברוכים הבאים — ותודה שהצטרפתם ל-Gypsy Jazz Hub.",
      "",
      "פתחו את הקישור הזה כדי לאשר את האימייל:",
      "{link}",
      "",
      "אחר כך הכניסה פשוטה: אותו אימייל והסיסמה שבחרתם.",
      LOGIN,
      "",
      "אם לא נרשמתם, אפשר להתעלם מהמייל.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
};

export function isMailLocale(raw: string | null | undefined): raw is MailLocale {
  return Boolean(raw && MAIL_LOCALES.includes(raw as MailLocale));
}

export function parseMailLocale(raw: string | null | undefined): MailLocale {
  const value = (raw ?? "").trim().toLowerCase();
  if (isMailLocale(value)) return value;
  const short = value.split(",")[0]?.split(";")[0]?.trim() ?? "";
  if (short.startsWith("zh-tw") || short.startsWith("zh-hant")) return "zh-tw";
  if (short.startsWith("zh")) return "zh";
  const base = short.split("-")[0] ?? "";
  if (isMailLocale(base)) return base;
  return "en";
}

export function welcomeMail(locale: MailLocale, link: string) {
  const copy = COPY[locale] ?? COPY.en;
  return {
    subject: copy.subject,
    body: copy.lines.map((line) => (line === "{link}" ? link : line)).join("\n"),
  };
}
