export const MAIL_LOCALES = [
  "en",
  "nl",
  "fr",
  "de",
  "es",
  "it",
  "pt",
  "ru",
  "hu",
  "ro",
  "pl",
  "cs",
  "sr",
  "hr",
  "ja",
  "ko",
  "zh",
  "zh-tw",
  "id",
  "th",
  "he",
] as const;

export type MailLocale = (typeof MAIL_LOCALES)[number];

type MailCopy = { subject: string; lines: string[] };

const LOGIN = "https://www.gypsyjazzhub.com/login";

const COPY: Record<MailLocale, MailCopy> = {
  en: {
    subject: "Welcome to Gypsy Jazz Hub",
    lines: [
      "Welcome — and thank you for joining Gypsy Jazz Hub.",
      "",
      "Open this link to confirm your email:",
      "{link}",
      "",
      "After that, login is simple: the same email and the password you chose.",
      LOGIN,
      "",
      "If you did not join, you can ignore this mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  nl: {
    subject: "Welkom bij Gypsy Jazz Hub",
    lines: [
      "Welkom — en dank je wel dat je lid wordt van Gypsy Jazz Hub.",
      "",
      "Open deze link om je e-mail te bevestigen:",
      "{link}",
      "",
      "Daarna is inloggen simpel: hetzelfde e-mailadres en het wachtwoord dat je koos.",
      LOGIN,
      "",
      "Als jij dit niet was, kun je deze mail negeren.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  fr: {
    subject: "Bienvenue sur Gypsy Jazz Hub",
    lines: [
      "Bienvenue — et merci de rejoindre Gypsy Jazz Hub.",
      "",
      "Ouvre ce lien pour confirmer ton e-mail :",
      "{link}",
      "",
      "Ensuite, la connexion est simple : le même e-mail et le mot de passe que tu as choisi.",
      LOGIN,
      "",
      "Si tu n’as pas créé de compte, ignore ce mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  de: {
    subject: "Willkommen bei Gypsy Jazz Hub",
    lines: [
      "Willkommen — und danke, dass du bei Gypsy Jazz Hub mitmachst.",
      "",
      "Öffne diesen Link, um deine E-Mail zu bestätigen:",
      "{link}",
      "",
      "Danach ist der Login einfach: dieselbe E-Mail und das Passwort, das du gewählt hast.",
      LOGIN,
      "",
      "Wenn du dich nicht angemeldet hast, kannst du diese Mail ignorieren.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  es: {
    subject: "Bienvenido a Gypsy Jazz Hub",
    lines: [
      "Bienvenido — y gracias por unirte a Gypsy Jazz Hub.",
      "",
      "Abre este enlace para confirmar tu correo:",
      "{link}",
      "",
      "Después, entrar es simple: el mismo correo y la contraseña que elegiste.",
      LOGIN,
      "",
      "Si no te inscribiste, puedes ignorar este correo.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  it: {
    subject: "Benvenuto su Gypsy Jazz Hub",
    lines: [
      "Benvenuto — e grazie per essere entrato in Gypsy Jazz Hub.",
      "",
      "Apri questo link per confermare la tua email:",
      "{link}",
      "",
      "Poi l’accesso è semplice: la stessa email e la password che hai scelto.",
      LOGIN,
      "",
      "Se non ti sei iscritto, ignora questa mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  pt: {
    subject: "Bem-vindo ao Gypsy Jazz Hub",
    lines: [
      "Bem-vindo — e obrigado por te juntares ao Gypsy Jazz Hub.",
      "",
      "Abre este link para confirmar o teu email:",
      "{link}",
      "",
      "Depois, entrar é simples: o mesmo email e a palavra-passe que escolheste.",
      LOGIN,
      "",
      "Se não foste tu, podes ignorar este mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ru: {
    subject: "Добро пожаловать в Gypsy Jazz Hub",
    lines: [
      "Добро пожаловать — и спасибо, что присоединились к Gypsy Jazz Hub.",
      "",
      "Откройте эту ссылку, чтобы подтвердить почту:",
      "{link}",
      "",
      "Потом вход простой: та же почта и пароль, который вы выбрали.",
      LOGIN,
      "",
      "Если это были не вы, просто проигнорируйте письмо.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  hu: {
    subject: "Üdv a Gypsy Jazz Hubon",
    lines: [
      "Üdv — és köszönjük, hogy csatlakozol a Gypsy Jazz Hubhoz.",
      "",
      "Nyisd meg ezt a linket az e-mail megerősítéséhez:",
      "{link}",
      "",
      "Utána a belépés egyszerű: ugyanaz az e-mail és a jelszó, amit választottál.",
      LOGIN,
      "",
      "Ha nem te jelentkeztél, hagyd figyelmen kívül ezt a levelet.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ro: {
    subject: "Bun venit pe Gypsy Jazz Hub",
    lines: [
      "Bun venit — și mulțumim că te-ai alăturat Gypsy Jazz Hub.",
      "",
      "Deschide acest link ca să confirmi e-mailul:",
      "{link}",
      "",
      "Apoi autentificarea e simplă: același e-mail și parola pe care ai ales-o.",
      LOGIN,
      "",
      "Dacă nu tu te-ai înscris, ignoră acest mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  pl: {
    subject: "Witamy w Gypsy Jazz Hub",
    lines: [
      "Witamy — i dziękujemy, że dołączasz do Gypsy Jazz Hub.",
      "",
      "Otwórz ten link, żeby potwierdzić e-mail:",
      "{link}",
      "",
      "Potem logowanie jest proste: ten sam e-mail i hasło, które wybrałeś.",
      LOGIN,
      "",
      "Jeśli to nie ty, zignoruj tę wiadomość.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  cs: {
    subject: "Vítejte na Gypsy Jazz Hub",
    lines: [
      "Vítejte — a díky, že se přidáváte k Gypsy Jazz Hub.",
      "",
      "Otevřete tento odkaz a potvrďte e-mail:",
      "{link}",
      "",
      "Pak je přihlášení jednoduché: stejný e-mail a heslo, které jste zvolili.",
      LOGIN,
      "",
      "Pokud jste se neregistrovali, e-mail ignorujte.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  sr: {
    subject: "Dobrodošli na Gypsy Jazz Hub",
    lines: [
      "Dobrodošli — i hvala što se pridružujete Gypsy Jazz Hubu.",
      "",
      "Otvorite ovaj link da potvrdite mejl:",
      "{link}",
      "",
      "Posle toga je prijava jednostavna: isti mejl i lozinka koju ste izabrali.",
      LOGIN,
      "",
      "Ako se niste vi prijavili, ignorišite ovaj mejl.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  hr: {
    subject: "Dobrodošli na Gypsy Jazz Hub",
    lines: [
      "Dobrodošli — i hvala što se pridružujete Gypsy Jazz Hubu.",
      "",
      "Otvorite ovaj link da potvrdite e-mail:",
      "{link}",
      "",
      "Nakon toga je prijava jednostavna: isti e-mail i lozinka koju ste odabrali.",
      LOGIN,
      "",
      "Ako se niste vi prijavili, zanemarite ovaj mail.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ja: {
    subject: "Gypsy Jazz Hub へようこそ",
    lines: [
      "ようこそ。Gypsy Jazz Hub に参加してくれてありがとうございます。",
      "",
      "このリンクを開いてメールを確認してください:",
      "{link}",
      "",
      "あとは簡単です。同じメールと、いま選んだパスワードでログインできます。",
      LOGIN,
      "",
      "この登録に覚えがなければ、このメールは無視してください。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ko: {
    subject: "Gypsy Jazz Hub에 오신 것을 환영합니다",
    lines: [
      "환영합니다. Gypsy Jazz Hub에 가입해 주셔서 감사합니다.",
      "",
      "이 링크를 열어 이메일을 확인해 주세요:",
      "{link}",
      "",
      "그다음 로그인은 간단합니다. 같은 이메일과 방금 고른 비밀번호면 됩니다.",
      LOGIN,
      "",
      "가입한 적이 없다면 이 메일은 무시하세요.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  zh: {
    subject: "欢迎来到 Gypsy Jazz Hub",
    lines: [
      "欢迎 — 谢谢你加入 Gypsy Jazz Hub。",
      "",
      "打开这个链接确认邮箱：",
      "{link}",
      "",
      "之后登录很简单：同一个邮箱，加上你刚设的密码。",
      LOGIN,
      "",
      "如果不是你注册的，请忽略这封邮件。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  "zh-tw": {
    subject: "歡迎來到 Gypsy Jazz Hub",
    lines: [
      "歡迎 — 謝謝你加入 Gypsy Jazz Hub。",
      "",
      "打開這個連結確認電子郵件：",
      "{link}",
      "",
      "之後登入很簡單：同一個信箱，加上你剛設的密碼。",
      LOGIN,
      "",
      "如果不是你註冊的，請忽略這封信。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  id: {
    subject: "Selamat datang di Gypsy Jazz Hub",
    lines: [
      "Selamat datang — terima kasih sudah bergabung di Gypsy Jazz Hub.",
      "",
      "Buka tautan ini untuk mengonfirmasi email:",
      "{link}",
      "",
      "Sesudah itu masuknya sederhana: email yang sama dan kata sandi yang baru kamu pilih.",
      LOGIN,
      "",
      "Kalau bukan kamu yang daftar, abaikan saja email ini.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  th: {
    subject: "ยินดีต้อนรับสู่ Gypsy Jazz Hub",
    lines: [
      "ยินดีต้อนรับ — ขอบคุณที่เข้าร่วม Gypsy Jazz Hub",
      "",
      "เปิดลิงก์นี้เพื่อยืนยันอีเมล:",
      "{link}",
      "",
      "จากนั้นเข้าสู่ระบบง่าย ๆ: อีเมลเดิมกับรหัสผ่านที่เพิ่งตั้ง",
      LOGIN,
      "",
      "ถ้าไม่ได้สมัครเอง ละเว้นเมลนี้ได้",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  he: {
    subject: "ברוכים הבאים ל-Gypsy Jazz Hub",
    lines: [
      "ברוכים הבאים — ותודה שהצטרפתם ל-Gypsy Jazz Hub.",
      "",
      "פתחו את הקישור הזה כדי לאשר את האימייל:",
      "{link}",
      "",
      "אחר כך הכניסה פשוטה: אותו אימייל והסיסמה שבחרתם.",
      LOGIN,
      "",
      "אם לא נרשמתם, אפשר להתעלם מהמייל.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
};

export function isMailLocale(raw: string | null | undefined): raw is MailLocale {
  return Boolean(raw && MAIL_LOCALES.includes(raw as MailLocale));
}

export function parseMailLocale(raw: string | null | undefined): MailLocale {
  const value = (raw ?? "").trim().toLowerCase();
  if (isMailLocale(value)) return value;
  const short = value.split(",")[0]?.split(";")[0]?.trim() ?? "";
  if (short.startsWith("zh-tw") || short.startsWith("zh-hant")) return "zh-tw";
  if (short.startsWith("zh")) return "zh";
  const base = short.split("-")[0] ?? "";
  if (isMailLocale(base)) return base;
  return "en";
}

function fill(lines: string[], vars: Record<string, string>) {
  return lines
    .map((line) => {
      let out = line;
      for (const [key, value] of Object.entries(vars)) {
        out = out.split(`{${key}}`).join(value);
      }
      return out;
    })
    .filter((line) => line !== "{omit}")
    .join("\n");
}

export function welcomeMail(locale: MailLocale, link: string) {
  const copy = COPY[locale] ?? COPY.en;
  return {
    subject: copy.subject,
    body: fill(copy.lines, { link }),
  };
}

const RESET: Record<MailLocale, MailCopy> = {
  en: {
    subject: "Set your Gypsy Jazz Hub password",
    lines: [
      "Hi{name},",
      "",
      "Login on Gypsy Jazz Hub is only an email and a password. This mail is how you set that password.",
      "",
      "1. Open this link (it works for one hour):",
      "{link}",
      "2. Choose a password — at least 8 characters.",
      "3. We send a confirmation mail when it is saved.",
      "4. After that, sign in here with the same email and that password:",
      LOGIN,
      "",
      "If you did not ask for this, ignore the mail. Your login stays the same.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  nl: {
    subject: "Zet je wachtwoord voor Gypsy Jazz Hub",
    lines: [
      "Hoi{name},",
      "",
      "Inloggen op Gypsy Jazz Hub is alleen een e-mailadres en een wachtwoord. Deze mail is hoe je dat wachtwoord zet.",
      "",
      "1. Open deze link (één uur geldig):",
      "{link}",
      "2. Kies een wachtwoord — minstens 8 tekens.",
      "3. Daarna sturen we een bevestigingsmail als het is opgeslagen.",
      "4. Vervolgens inloggen met hetzelfde e-mailadres en dat wachtwoord:",
      LOGIN,
      "",
      "Als jij dit niet vroeg, negeer de mail. Je inlog blijft hetzelfde.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  fr: {
    subject: "Choisis ton mot de passe Gypsy Jazz Hub",
    lines: [
      "Salut{name},",
      "",
      "Sur Gypsy Jazz Hub, la connexion c’est seulement un e-mail et un mot de passe. Ce mail sert à choisir ce mot de passe.",
      "",
      "1. Ouvre ce lien (valable une heure) :",
      "{link}",
      "2. Choisis un mot de passe — au moins 8 caractères.",
      "3. Nous envoyons un mail de confirmation quand c’est enregistré.",
      "4. Ensuite, connecte-toi avec le même e-mail et ce mot de passe :",
      LOGIN,
      "",
      "Si tu n’as pas demandé ça, ignore le mail. Ton compte ne change pas.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  de: {
    subject: "Passwort für Gypsy Jazz Hub setzen",
    lines: [
      "Hallo{name},",
      "",
      "Der Login auf Gypsy Jazz Hub ist nur E-Mail und Passwort. Diese Mail erklärt, wie du das Passwort setzt.",
      "",
      "1. Öffne diesen Link (eine Stunde gültig):",
      "{link}",
      "2. Wähle ein Passwort — mindestens 8 Zeichen.",
      "3. Danach schicken wir eine Bestätigungsmail, wenn es gespeichert ist.",
      "4. Danach einloggen mit derselben E-Mail und diesem Passwort:",
      LOGIN,
      "",
      "Wenn du das nicht angefordert hast, ignoriere die Mail. Dein Login bleibt gleich.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  es: {
    subject: "Elige tu contraseña de Gypsy Jazz Hub",
    lines: [
      "Hola{name},",
      "",
      "En Gypsy Jazz Hub entrar es solo un correo y una contraseña. Este mail es para poner esa contraseña.",
      "",
      "1. Abre este enlace (vale una hora):",
      "{link}",
      "2. Elige una contraseña — al menos 8 caracteres.",
      "3. Luego enviamos un correo de confirmación cuando esté guardada.",
      "4. Después entra con el mismo correo y esa contraseña:",
      LOGIN,
      "",
      "Si no lo pediste, ignora el correo. Tu acceso no cambia.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  it: {
    subject: "Scegli la password di Gypsy Jazz Hub",
    lines: [
      "Ciao{name},",
      "",
      "Su Gypsy Jazz Hub l’accesso è solo email e password. Questa mail serve a impostare quella password.",
      "",
      "1. Apri questo link (vale un’ora):",
      "{link}",
      "2. Scegli una password — almeno 8 caratteri.",
      "3. Poi mandiamo una mail di conferma quando è salvata.",
      "4. Dopo accedi con la stessa email e quella password:",
      LOGIN,
      "",
      "Se non l’hai chiesto tu, ignora la mail. L’accesso resta uguale.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  pt: {
    subject: "Define a tua palavra-passe do Gypsy Jazz Hub",
    lines: [
      "Olá{name},",
      "",
      "No Gypsy Jazz Hub o login é só um email e uma palavra-passe. Este mail explica como a defines.",
      "",
      "1. Abre este link (válido uma hora):",
      "{link}",
      "2. Escolhe uma palavra-passe — pelo menos 8 caracteres.",
      "3. Depois enviamos um mail de confirmação quando estiver gravada.",
      "4. A seguir entra com o mesmo email e essa palavra-passe:",
      LOGIN,
      "",
      "Se não pediste isto, ignora o mail. O teu acesso fica igual.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ru: {
    subject: "Задайте пароль для Gypsy Jazz Hub",
    lines: [
      "Здравствуйте{name},",
      "",
      "Вход на Gypsy Jazz Hub — только почта и пароль. Это письмо — как задать пароль.",
      "",
      "1. Откройте ссылку (действует час):",
      "{link}",
      "2. Выберите пароль — не меньше 8 символов.",
      "3. Затем мы пришлём письмо-подтверждение, когда пароль сохранится.",
      "4. Потом войдите с той же почтой и этим паролем:",
      LOGIN,
      "",
      "Если вы этого не просили, просто проигнорируйте письмо. Вход не изменится.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  hu: {
    subject: "Állítsd be a Gypsy Jazz Hub jelszavad",
    lines: [
      "Szia{name},",
      "",
      "A Gypsy Jazz Hubon a belépés csak e-mail és jelszó. Ez a levél arról szól, hogyan állítod be a jelszót.",
      "",
      "1. Nyisd meg ezt a linket (egy óráig él):",
      "{link}",
      "2. Válassz jelszót — legalább 8 karakter.",
      "3. Utána küldünk egy megerősítő e-mailt, ha elmentődött.",
      "4. Aztán lépj be ugyanazzal az e-maillel és ezzel a jelszóval:",
      LOGIN,
      "",
      "Ha nem te kérted, hagyd figyelmen kívül. A belépésed nem változik.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ro: {
    subject: "Setează parola pentru Gypsy Jazz Hub",
    lines: [
      "Salut{name},",
      "",
      "Pe Gypsy Jazz Hub autentificarea e doar e-mail și parolă. Acest mail explică cum setezi parola.",
      "",
      "1. Deschide acest link (valabil o oră):",
      "{link}",
      "2. Alege o parolă — cel puțin 8 caractere.",
      "3. Apoi trimitem un mail de confirmare când e salvată.",
      "4. După aceea intră cu același e-mail și parola aceea:",
      LOGIN,
      "",
      "Dacă nu ai cerut asta, ignoră mailul. Contul rămâne la fel.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  pl: {
    subject: "Ustaw hasło do Gypsy Jazz Hub",
    lines: [
      "Cześć{name},",
      "",
      "Na Gypsy Jazz Hub logowanie to tylko e-mail i hasło. Ten mail wyjaśnia, jak to hasło ustawić.",
      "",
      "1. Otwórz ten link (ważny godzinę):",
      "{link}",
      "2. Wybierz hasło — co najmniej 8 znaków.",
      "3. Potem wyślemy mail potwierdzający, gdy będzie zapisane.",
      "4. Potem zaloguj się tym samym e-mailem i tym hasłem:",
      LOGIN,
      "",
      "Jeśli tego nie prosiłeś, zignoruj wiadomość. Login zostaje bez zmian.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  cs: {
    subject: "Nastavte heslo pro Gypsy Jazz Hub",
    lines: [
      "Ahoj{name},",
      "",
      "Na Gypsy Jazz Hub je přihlášení jen e-mail a heslo. Tento mail vysvětluje, jak heslo nastavit.",
      "",
      "1. Otevřete tento odkaz (platí hodinu):",
      "{link}",
      "2. Zvolte heslo — nejméně 8 znaků.",
      "3. Pak pošleme potvrzovací e-mail, až bude uložené.",
      "4. Pak se přihlaste stejným e-mailem a tím heslem:",
      LOGIN,
      "",
      "Pokud jste o to nežádali, e-mail ignorujte. Přihlášení se nemění.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  sr: {
    subject: "Postavi lozinku za Gypsy Jazz Hub",
    lines: [
      "Zdravo{name},",
      "",
      "Na Gypsy Jazz Hubu prijava je samo mejl i lozinka. Ovaj mejl objašnjava kako da postaviš lozinku.",
      "",
      "1. Otvori ovaj link (važi sat vremena):",
      "{link}",
      "2. Izaberi lozinku — najmanje 8 karaktera.",
      "3. Posle šaljemo mejl potvrde kad je sačuvana.",
      "4. Zatim se prijavi istim mejlom i tom lozinkom:",
      LOGIN,
      "",
      "Ako ovo nisi tražio, ignoriši mejl. Prijava ostaje ista.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  hr: {
    subject: "Postavi lozinku za Gypsy Jazz Hub",
    lines: [
      "Bok{name},",
      "",
      "Na Gypsy Jazz Hubu prijava je samo e-mail i lozinka. Ovaj mail objašnjava kako postaviti lozinku.",
      "",
      "1. Otvori ovaj link (vrijedi sat vremena):",
      "{link}",
      "2. Odaberi lozinku — najmanje 8 znakova.",
      "3. Zatim šaljemo mail potvrde kad je spremljena.",
      "4. Nakon toga se prijavi istim e-mailom i tom lozinkom:",
      LOGIN,
      "",
      "Ako ovo nisi tražio, zanemari mail. Prijava ostaje ista.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ja: {
    subject: "Gypsy Jazz Hub のパスワードを設定",
    lines: [
      "{name}さん",
      "",
      "Gypsy Jazz Hub のログインはメールとパスワードだけです。このメールでパスワードの作り方を説明します。",
      "",
      "1. このリンクを開く（1時間有効）:",
      "{link}",
      "2. パスワードを決める — 8文字以上。",
      "3. 保存できたら確認メールを送ります。",
      "4. あとは同じメールと、そのパスワードでログイン:",
      LOGIN,
      "",
      "この操作に覚えがなければ、メールは無視してください。ログインは変わりません。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  ko: {
    subject: "Gypsy Jazz Hub 비밀번호 설정",
    lines: [
      "안녕하세요{name},",
      "",
      "Gypsy Jazz Hub 로그인은 이메일과 비밀번호뿐입니다. 이 메일이 그 비밀번호를 만드는 방법입니다.",
      "",
      "1. 이 링크를 여세요 (1시간 유효):",
      "{link}",
      "2. 비밀번호를 정하세요 — 8자 이상.",
      "3. 저장되면 확인 메일을 보냅니다.",
      "4. 그다음 같은 이메일과 그 비밀번호로 로그인:",
      LOGIN,
      "",
      "요청한 적이 없다면 이 메일은 무시하세요. 로그인은 그대로입니다.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  zh: {
    subject: "设置你的 Gypsy Jazz Hub 密码",
    lines: [
      "你好{name}，",
      "",
      "Gypsy Jazz Hub 的登录只有邮箱和密码。这封邮件说明怎么设置密码。",
      "",
      "1. 打开这个链接（一小时内有效）：",
      "{link}",
      "2. 选一个密码 — 至少 8 个字符。",
      "3. 保存成功后我们会再发一封确认邮件。",
      "4. 之后用同一个邮箱和这个密码登录：",
      LOGIN,
      "",
      "如果不是你要的，请忽略这封邮件。登录不会变。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  "zh-tw": {
    subject: "設定你的 Gypsy Jazz Hub 密碼",
    lines: [
      "你好{name}，",
      "",
      "Gypsy Jazz Hub 的登入只有信箱和密碼。這封信說明怎麼設定密碼。",
      "",
      "1. 打開這個連結（一小時內有效）：",
      "{link}",
      "2. 選一個密碼 — 至少 8 個字。",
      "3. 儲存成功後我們會再寄一封確認信。",
      "4. 之後用同一個信箱和這個密碼登入：",
      LOGIN,
      "",
      "如果不是你要的，請忽略這封信。登入不會變。",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  id: {
    subject: "Atur kata sandi Gypsy Jazz Hub",
    lines: [
      "Hai{name},",
      "",
      "Masuk ke Gypsy Jazz Hub hanya dengan email dan kata sandi. Email ini menjelaskan cara mengatur kata sandi itu.",
      "",
      "1. Buka tautan ini (berlaku satu jam):",
      "{link}",
      "2. Pilih kata sandi — minimal 8 karakter.",
      "3. Kami kirim email konfirmasi setelah tersimpan.",
      "4. Lalu masuk dengan email yang sama dan kata sandi itu:",
      LOGIN,
      "",
      "Kalau bukan kamu yang minta, abaikan email ini. Login tidak berubah.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  th: {
    subject: "ตั้งรหัสผ่าน Gypsy Jazz Hub",
    lines: [
      "สวัสดี{name}",
      "",
      "การเข้าสู่ระบบ Gypsy Jazz Hub มีแค่อีเมลกับรหัสผ่าน จดหมายนี้บอกวิธีตั้งรหัสผ่าน",
      "",
      "1. เปิดลิงก์นี้ (ใช้ได้ 1 ชั่วโมง):",
      "{link}",
      "2. เลือกรหัสผ่าน — อย่างน้อย 8 ตัวอักษร",
      "3. เราจะส่งเมลยืนยันเมื่อบันทึกแล้ว",
      "4. จากนั้นเข้าสู่ระบบด้วยอีเมลเดิมกับรหัสผ่านนั้น:",
      LOGIN,
      "",
      "ถ้าไม่ได้ขอเอง ละเว้นเมลนี้ได้ การเข้าสู่ระบบไม่เปลี่ยน",
      "",
      "Gypsy Jazz Hub",
    ],
  },
  he: {
    subject: "קבעו סיסמה ל-Gypsy Jazz Hub",
    lines: [
      "שלום{name},",
      "",
      "הכניסה ל-Gypsy Jazz Hub היא רק אימייל וסיסמה. המייל הזה מסביר איך לקבוע את הסיסמה.",
      "",
      "1. פתחו את הקישור (שעה אחת):",
      "{link}",
      "2. בחרו סיסמה — לפחות 8 תווים.",
      "3. אחר כך נשלח מייל אישור כשהיא נשמרת.",
      "4. ואז נכנסים עם אותו אימייל והסיסמה הזאת:",
      LOGIN,
      "",
      "אם לא ביקשתם את זה, התעלמו מהמייל. הכניסה לא משתנה.",
      "",
      "Gypsy Jazz Hub",
    ],
  },
};

export function passwordMail(locale: MailLocale, name: string, link: string) {
  const copy = RESET[locale] ?? RESET.en;
  const who = name.trim() ? ` ${name.trim()}` : "";
  return {
    subject: copy.subject,
    body: fill(copy.lines, { link, name: who }),
  };
}

