/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as BoardRouteImport } from './routes/board'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as DenisChangRouteImport } from './routes/denis-chang'
import { Route as DjangoRouteImport } from './routes/django'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GrappelliRouteImport } from './routes/grappelli'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SceneRouteImport } from './routes/scene'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TataMirandoRouteImport } from './routes/tata-mirando'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiDigestRouteImport } from './routes/api/digest'
import { Route as ApiDjangobooksImportRouteImport } from './routes/api/djangobooks-import'
import { Route as ApiFacebookImportRouteImport } from './routes/api/facebook-import'
import { Route as ApiRomaniMusicRouteImport } from './routes/api/romani-music'
import { Route as ArchiveIndexRouteImport } from './routes/archive/index'
import { Route as ArchiveSlugRouteImport } from './routes/archive/$slug'
import { Route as ConcertsIndexRouteImport } from './routes/concerts/index'
import { Route as ConcertsIdRouteImport } from './routes/concerts/$id'
import { Route as FamiliesSlugRouteImport } from './routes/families/$slug'
import { Route as FansIndexRouteImport } from './routes/fans/index'
import { Route as FansSlugRouteImport } from './routes/fans/$slug'
import { Route as FestivalsIndexRouteImport } from './routes/festivals/index'
import { Route as FestivalsSlugRouteImport } from './routes/festivals/$slug'
import { Route as FestivalsYoutubeRouteImport } from './routes/festivals/youtube'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsSlugRouteImport } from './routes/groups/$slug'
import { Route as InstrumentsIndexRouteImport } from './routes/instruments/index'
import { Route as InstrumentsDoubleBassRouteImport } from './routes/instruments/double-bass'
import { Route as InstrumentsGuitarsRouteImport } from './routes/instruments/guitars'
import { Route as InstrumentsOtherRouteImport } from './routes/instruments/other'
import { Route as InstrumentsViolinsRouteImport } from './routes/instruments/violins'
import { Route as JamsIndexRouteImport } from './routes/jams/index'
import { Route as JamsSlugRouteImport } from './routes/jams/$slug'
import { Route as JamsMeetupRouteImport } from './routes/jams/meetup'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as LearnAmplificationRouteImport } from './routes/learn/amplification'
import { Route as LearnAppsRouteImport } from './routes/learn/apps'
import { Route as LearnChartsRouteImport } from './routes/learn/charts'
import { Route as LearnStartJamRouteImport } from './routes/learn/start-jam'
import { Route as LearnTeachersRouteImport } from './routes/learn/teachers'
import { Route as LegendsIndexRouteImport } from './routes/legends/index'
import { Route as LegendsSlugRouteImport } from './routes/legends/$slug'
import { Route as LuthiersIndexRouteImport } from './routes/luthiers/index'
import { Route as LuthiersSlugRouteImport } from './routes/luthiers/$slug'
import { Route as LuthiersBassRouteImport } from './routes/luthiers/bass'
import { Route as LuthiersViolinRouteImport } from './routes/luthiers/violin'
import { Route as MusiciansIndexRouteImport } from './routes/musicians/index'
import { Route as MusiciansSlugRouteImport } from './routes/musicians/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as RomaniMusicIndexRouteImport } from './routes/romani-music/index'
import { Route as RomaniMusicSlugRouteImport } from './routes/romani-music/$slug'
import { Route as RomaniMusicOriginsRouteImport } from './routes/romani-music/origins'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as ShopsSlugRouteImport } from './routes/shops/$slug'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioOwnerRouteImport } from './routes/studio/owner'
import { Route as VenuesIndexRouteImport } from './routes/venues/index'
import { Route as VenuesSlugRouteImport } from './routes/venues/$slug'
import { Route as WorldIndexRouteImport } from './routes/world/index'
import { Route as WorldSlugRouteImport } from './routes/world/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiConcertMediaIdRouteImport } from './routes/api/concert-media/$id'
import { Route as InstrumentsLuthiersIndexRouteImport } from './routes/instruments/luthiers/index'
import { Route as InstrumentsLuthiersCountryRouteImport } from './routes/instruments/luthiers/$country'
import { Route as JamsInSlugRouteImport } from './routes/jams/in/$slug'
import { Route as LearnForumIndexRouteImport } from './routes/learn/forum/index'
import { Route as LearnForumSlugRouteImport } from './routes/learn/forum/$slug'
import { Route as LearnInstrumentsIndexRouteImport } from './routes/learn/instruments/index'
import { Route as LearnInstrumentsSlugRouteImport } from './routes/learn/instruments/$slug'
import { Route as VenuesInSlugRouteImport } from './routes/venues/in/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const DenisChangRoute = DenisChangRouteImport.update({
  id: '/denis-chang',
  path: '/denis-chang',
  getParentRoute: () => rootRouteImport,
} as any)
const DjangoRoute = DjangoRouteImport.update({
  id: '/django',
  path: '/django',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GrappelliRoute = GrappelliRouteImport.update({
  id: '/grappelli',
  path: '/grappelli',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneRoute = SceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TataMirandoRoute = TataMirandoRouteImport.update({
  id: '/tata-mirando',
  path: '/tata-mirando',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestRoute = ApiDigestRouteImport.update({
  id: '/api/digest',
  path: '/api/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDjangobooksImportRoute = ApiDjangobooksImportRouteImport.update({
  id: '/api/djangobooks-import',
  path: '/api/djangobooks-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookImportRoute = ApiFacebookImportRouteImport.update({
  id: '/api/facebook-import',
  path: '/api/facebook-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRomaniMusicRoute = ApiRomaniMusicRouteImport.update({
  id: '/api/romani-music',
  path: '/api/romani-music',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugRoute = ArchiveSlugRouteImport.update({
  id: '/archive/$slug',
  path: '/archive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsIndexRoute = ConcertsIndexRouteImport.update({
  id: '/concerts/',
  path: '/concerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsIdRoute = ConcertsIdRouteImport.update({
  id: '/concerts/$id',
  path: '/concerts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesSlugRoute = FamiliesSlugRouteImport.update({
  id: '/families/$slug',
  path: '/families/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FansIndexRoute = FansIndexRouteImport.update({
  id: '/fans/',
  path: '/fans/',
  getParentRoute: () => rootRouteImport,
} as any)
const FansSlugRoute = FansSlugRouteImport.update({
  id: '/fans/$slug',
  path: '/fans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsIndexRoute = FestivalsIndexRouteImport.update({
  id: '/festivals/',
  path: '/festivals/',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsSlugRoute = FestivalsSlugRouteImport.update({
  id: '/festivals/$slug',
  path: '/festivals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsYoutubeRoute = FestivalsYoutubeRouteImport.update({
  id: '/festivals/youtube',
  path: '/festivals/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsIndexRoute = InstrumentsIndexRouteImport.update({
  id: '/instruments/',
  path: '/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsDoubleBassRoute = InstrumentsDoubleBassRouteImport.update({
  id: '/instruments/double-bass',
  path: '/instruments/double-bass',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsGuitarsRoute = InstrumentsGuitarsRouteImport.update({
  id: '/instruments/guitars',
  path: '/instruments/guitars',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsOtherRoute = InstrumentsOtherRouteImport.update({
  id: '/instruments/other',
  path: '/instruments/other',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsViolinsRoute = InstrumentsViolinsRouteImport.update({
  id: '/instruments/violins',
  path: '/instruments/violins',
  getParentRoute: () => rootRouteImport,
} as any)
const JamsIndexRoute = JamsIndexRouteImport.update({
  id: '/jams/',
  path: '/jams/',
  getParentRoute: () => rootRouteImport,
} as any)
const JamsSlugRoute = JamsSlugRouteImport.update({
  id: '/jams/$slug',
  path: '/jams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JamsMeetupRoute = JamsMeetupRouteImport.update({
  id: '/jams/meetup',
  path: '/jams/meetup',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAmplificationRoute = LearnAmplificationRouteImport.update({
  id: '/learn/amplification',
  path: '/learn/amplification',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAppsRoute = LearnAppsRouteImport.update({
  id: '/learn/apps',
  path: '/learn/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnChartsRoute = LearnChartsRouteImport.update({
  id: '/learn/charts',
  path: '/learn/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnStartJamRoute = LearnStartJamRouteImport.update({
  id: '/learn/start-jam',
  path: '/learn/start-jam',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTeachersRoute = LearnTeachersRouteImport.update({
  id: '/learn/teachers',
  path: '/learn/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendsIndexRoute = LegendsIndexRouteImport.update({
  id: '/legends/',
  path: '/legends/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendsSlugRoute = LegendsSlugRouteImport.update({
  id: '/legends/$slug',
  path: '/legends/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LuthiersIndexRoute = LuthiersIndexRouteImport.update({
  id: '/luthiers/',
  path: '/luthiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const LuthiersSlugRoute = LuthiersSlugRouteImport.update({
  id: '/luthiers/$slug',
  path: '/luthiers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LuthiersBassRoute = LuthiersBassRouteImport.update({
  id: '/luthiers/bass',
  path: '/luthiers/bass',
  getParentRoute: () => rootRouteImport,
} as any)
const LuthiersViolinRoute = LuthiersViolinRouteImport.update({
  id: '/luthiers/violin',
  path: '/luthiers/violin',
  getParentRoute: () => rootRouteImport,
} as any)
const MusiciansIndexRoute = MusiciansIndexRouteImport.update({
  id: '/musicians/',
  path: '/musicians/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusiciansSlugRoute = MusiciansSlugRouteImport.update({
  id: '/musicians/$slug',
  path: '/musicians/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RomaniMusicIndexRoute = RomaniMusicIndexRouteImport.update({
  id: '/romani-music/',
  path: '/romani-music/',
  getParentRoute: () => rootRouteImport,
} as any)
const RomaniMusicSlugRoute = RomaniMusicSlugRouteImport.update({
  id: '/romani-music/$slug',
  path: '/romani-music/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RomaniMusicOriginsRoute = RomaniMusicOriginsRouteImport.update({
  id: '/romani-music/origins',
  path: '/romani-music/origins',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioOwnerRoute = StudioOwnerRouteImport.update({
  id: '/studio/owner',
  path: '/studio/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldIndexRoute = WorldIndexRouteImport.update({
  id: '/world/',
  path: '/world/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldSlugRoute = WorldSlugRouteImport.update({
  id: '/world/$slug',
  path: '/world/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConcertMediaIdRoute = ApiConcertMediaIdRouteImport.update({
  id: '/api/concert-media/$id',
  path: '/api/concert-media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsLuthiersIndexRoute =
  InstrumentsLuthiersIndexRouteImport.update({
    id: '/instruments/luthiers/',
    path: '/instruments/luthiers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstrumentsLuthiersCountryRoute =
  InstrumentsLuthiersCountryRouteImport.update({
    id: '/instruments/luthiers/$country',
    path: '/instruments/luthiers/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const JamsInSlugRoute = JamsInSlugRouteImport.update({
  id: '/jams/in/$slug',
  path: '/jams/in/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnForumIndexRoute = LearnForumIndexRouteImport.update({
  id: '/learn/forum/',
  path: '/learn/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnForumSlugRoute = LearnForumSlugRouteImport.update({
  id: '/learn/forum/$slug',
  path: '/learn/forum/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInstrumentsIndexRoute = LearnInstrumentsIndexRouteImport.update({
  id: '/learn/instruments/',
  path: '/learn/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInstrumentsSlugRoute = LearnInstrumentsSlugRouteImport.update({
  id: '/learn/instruments/$slug',
  path: '/learn/instruments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesInSlugRoute = VenuesInSlugRouteImport.update({
  id: '/venues/in/$slug',
  path: '/venues/in/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/agenda': typeof AgendaRoute
  '/board': typeof BoardRoute
  '/camps': typeof CampsRoute
  '/denis-chang': typeof DenisChangRoute
  '/django': typeof DjangoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grappelli': typeof GrappelliRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/tata-mirando': typeof TataMirandoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/youtube': typeof YoutubeRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/digest': typeof ApiDigestRoute
  '/api/djangobooks-import': typeof ApiDjangobooksImportRoute
  '/api/facebook-import': typeof ApiFacebookImportRoute
  '/api/romani-music': typeof ApiRomaniMusicRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/concerts/$id': typeof ConcertsIdRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/fans/$slug': typeof FansSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/festivals/youtube': typeof FestivalsYoutubeRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/instruments/double-bass': typeof InstrumentsDoubleBassRoute
  '/instruments/guitars': typeof InstrumentsGuitarsRoute
  '/instruments/other': typeof InstrumentsOtherRoute
  '/instruments/violins': typeof InstrumentsViolinsRoute
  '/jams/$slug': typeof JamsSlugRoute
  '/jams/meetup': typeof JamsMeetupRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/amplification': typeof LearnAmplificationRoute
  '/learn/apps': typeof LearnAppsRoute
  '/learn/charts': typeof LearnChartsRoute
  '/learn/start-jam': typeof LearnStartJamRoute
  '/learn/teachers': typeof LearnTeachersRoute
  '/legends/$slug': typeof LegendsSlugRoute
  '/luthiers/$slug': typeof LuthiersSlugRoute
  '/luthiers/bass': typeof LuthiersBassRoute
  '/luthiers/violin': typeof LuthiersViolinRoute
  '/musicians/$slug': typeof MusiciansSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/romani-music/$slug': typeof RomaniMusicSlugRoute
  '/romani-music/origins': typeof RomaniMusicOriginsRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/studio/owner': typeof StudioOwnerRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/world/$slug': typeof WorldSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/concerts/': typeof ConcertsIndexRoute
  '/fans/': typeof FansIndexRoute
  '/festivals/': typeof FestivalsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/jams/': typeof JamsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/legends/': typeof LegendsIndexRoute
  '/luthiers/': typeof LuthiersIndexRoute
  '/musicians/': typeof MusiciansIndexRoute
  '/news/': typeof NewsIndexRoute
  '/romani-music/': typeof RomaniMusicIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/world/': typeof WorldIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/concert-media/$id': typeof ApiConcertMediaIdRoute
  '/instruments/luthiers/$country': typeof InstrumentsLuthiersCountryRoute
  '/jams/in/$slug': typeof JamsInSlugRoute
  '/learn/forum/$slug': typeof LearnForumSlugRoute
  '/learn/instruments/$slug': typeof LearnInstrumentsSlugRoute
  '/venues/in/$slug': typeof VenuesInSlugRoute
  '/instruments/luthiers/': typeof InstrumentsLuthiersIndexRoute
  '/learn/forum/': typeof LearnForumIndexRoute
  '/learn/instruments/': typeof LearnInstrumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/agenda': typeof AgendaRoute
  '/board': typeof BoardRoute
  '/camps': typeof CampsRoute
  '/denis-chang': typeof DenisChangRoute
  '/django': typeof DjangoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grappelli': typeof GrappelliRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/tata-mirando': typeof TataMirandoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/youtube': typeof YoutubeRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/digest': typeof ApiDigestRoute
  '/api/djangobooks-import': typeof ApiDjangobooksImportRoute
  '/api/facebook-import': typeof ApiFacebookImportRoute
  '/api/romani-music': typeof ApiRomaniMusicRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/concerts/$id': typeof ConcertsIdRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/fans/$slug': typeof FansSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/festivals/youtube': typeof FestivalsYoutubeRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/instruments/double-bass': typeof InstrumentsDoubleBassRoute
  '/instruments/guitars': typeof InstrumentsGuitarsRoute
  '/instruments/other': typeof InstrumentsOtherRoute
  '/instruments/violins': typeof InstrumentsViolinsRoute
  '/jams/$slug': typeof JamsSlugRoute
  '/jams/meetup': typeof JamsMeetupRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/amplification': typeof LearnAmplificationRoute
  '/learn/apps': typeof LearnAppsRoute
  '/learn/charts': typeof LearnChartsRoute
  '/learn/start-jam': typeof LearnStartJamRoute
  '/learn/teachers': typeof LearnTeachersRoute
  '/legends/$slug': typeof LegendsSlugRoute
  '/luthiers/$slug': typeof LuthiersSlugRoute
  '/luthiers/bass': typeof LuthiersBassRoute
  '/luthiers/violin': typeof LuthiersViolinRoute
  '/musicians/$slug': typeof MusiciansSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/romani-music/$slug': typeof RomaniMusicSlugRoute
  '/romani-music/origins': typeof RomaniMusicOriginsRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/studio/owner': typeof StudioOwnerRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/world/$slug': typeof WorldSlugRoute
  '/archive': typeof ArchiveIndexRoute
  '/concerts': typeof ConcertsIndexRoute
  '/fans': typeof FansIndexRoute
  '/festivals': typeof FestivalsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/instruments': typeof InstrumentsIndexRoute
  '/jams': typeof JamsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/legends': typeof LegendsIndexRoute
  '/luthiers': typeof LuthiersIndexRoute
  '/musicians': typeof MusiciansIndexRoute
  '/news': typeof NewsIndexRoute
  '/romani-music': typeof RomaniMusicIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/venues': typeof VenuesIndexRoute
  '/world': typeof WorldIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/concert-media/$id': typeof ApiConcertMediaIdRoute
  '/instruments/luthiers/$country': typeof InstrumentsLuthiersCountryRoute
  '/jams/in/$slug': typeof JamsInSlugRoute
  '/learn/forum/$slug': typeof LearnForumSlugRoute
  '/learn/instruments/$slug': typeof LearnInstrumentsSlugRoute
  '/venues/in/$slug': typeof VenuesInSlugRoute
  '/instruments/luthiers': typeof InstrumentsLuthiersIndexRoute
  '/learn/forum': typeof LearnForumIndexRoute
  '/learn/instruments': typeof LearnInstrumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/agenda': typeof AgendaRoute
  '/board': typeof BoardRoute
  '/camps': typeof CampsRoute
  '/denis-chang': typeof DenisChangRoute
  '/django': typeof DjangoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grappelli': typeof GrappelliRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/tata-mirando': typeof TataMirandoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/youtube': typeof YoutubeRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/digest': typeof ApiDigestRoute
  '/api/djangobooks-import': typeof ApiDjangobooksImportRoute
  '/api/facebook-import': typeof ApiFacebookImportRoute
  '/api/romani-music': typeof ApiRomaniMusicRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/concerts/$id': typeof ConcertsIdRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/fans/$slug': typeof FansSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/festivals/youtube': typeof FestivalsYoutubeRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/instruments/double-bass': typeof InstrumentsDoubleBassRoute
  '/instruments/guitars': typeof InstrumentsGuitarsRoute
  '/instruments/other': typeof InstrumentsOtherRoute
  '/instruments/violins': typeof InstrumentsViolinsRoute
  '/jams/$slug': typeof JamsSlugRoute
  '/jams/meetup': typeof JamsMeetupRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/amplification': typeof LearnAmplificationRoute
  '/learn/apps': typeof LearnAppsRoute
  '/learn/charts': typeof LearnChartsRoute
  '/learn/start-jam': typeof LearnStartJamRoute
  '/learn/teachers': typeof LearnTeachersRoute
  '/legends/$slug': typeof LegendsSlugRoute
  '/luthiers/$slug': typeof LuthiersSlugRoute
  '/luthiers/bass': typeof LuthiersBassRoute
  '/luthiers/violin': typeof LuthiersViolinRoute
  '/musicians/$slug': typeof MusiciansSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/romani-music/$slug': typeof RomaniMusicSlugRoute
  '/romani-music/origins': typeof RomaniMusicOriginsRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/studio/owner': typeof StudioOwnerRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/world/$slug': typeof WorldSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/concerts/': typeof ConcertsIndexRoute
  '/fans/': typeof FansIndexRoute
  '/festivals/': typeof FestivalsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/jams/': typeof JamsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/legends/': typeof LegendsIndexRoute
  '/luthiers/': typeof LuthiersIndexRoute
  '/musicians/': typeof MusiciansIndexRoute
  '/news/': typeof NewsIndexRoute
  '/romani-music/': typeof RomaniMusicIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/world/': typeof WorldIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/concert-media/$id': typeof ApiConcertMediaIdRoute
  '/instruments/luthiers/$country': typeof InstrumentsLuthiersCountryRoute
  '/jams/in/$slug': typeof JamsInSlugRoute
  '/learn/forum/$slug': typeof LearnForumSlugRoute
  '/learn/instruments/$slug': typeof LearnInstrumentsSlugRoute
  '/venues/in/$slug': typeof VenuesInSlugRoute
  '/instruments/luthiers/': typeof InstrumentsLuthiersIndexRoute
  '/learn/forum/': typeof LearnForumIndexRoute
  '/learn/instruments/': typeof LearnInstrumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/agenda'
    | '/board'
    | '/camps'
    | '/denis-chang'
    | '/django'
    | '/forgot-password'
    | '/grappelli'
    | '/history'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/scene'
    | '/search'
    | '/tata-mirando'
    | '/verify-email'
    | '/welcome'
    | '/youtube'
    | '/api/alerts'
    | '/api/digest'
    | '/api/djangobooks-import'
    | '/api/facebook-import'
    | '/api/romani-music'
    | '/archive/$slug'
    | '/concerts/$id'
    | '/families/$slug'
    | '/fans/$slug'
    | '/festivals/$slug'
    | '/festivals/youtube'
    | '/groups/$slug'
    | '/instruments/double-bass'
    | '/instruments/guitars'
    | '/instruments/other'
    | '/instruments/violins'
    | '/jams/$slug'
    | '/jams/meetup'
    | '/learn/$slug'
    | '/learn/amplification'
    | '/learn/apps'
    | '/learn/charts'
    | '/learn/start-jam'
    | '/learn/teachers'
    | '/legends/$slug'
    | '/luthiers/$slug'
    | '/luthiers/bass'
    | '/luthiers/violin'
    | '/musicians/$slug'
    | '/news/$slug'
    | '/romani-music/$slug'
    | '/romani-music/origins'
    | '/shops/$slug'
    | '/studio/owner'
    | '/venues/$slug'
    | '/world/$slug'
    | '/archive/'
    | '/concerts/'
    | '/fans/'
    | '/festivals/'
    | '/groups/'
    | '/instruments/'
    | '/jams/'
    | '/learn/'
    | '/legends/'
    | '/luthiers/'
    | '/musicians/'
    | '/news/'
    | '/romani-music/'
    | '/shops/'
    | '/studio/'
    | '/venues/'
    | '/world/'
    | '/api/auth/$'
    | '/api/concert-media/$id'
    | '/instruments/luthiers/$country'
    | '/jams/in/$slug'
    | '/learn/forum/$slug'
    | '/learn/instruments/$slug'
    | '/venues/in/$slug'
    | '/instruments/luthiers/'
    | '/learn/forum/'
    | '/learn/instruments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/agenda'
    | '/board'
    | '/camps'
    | '/denis-chang'
    | '/django'
    | '/forgot-password'
    | '/grappelli'
    | '/history'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/scene'
    | '/search'
    | '/tata-mirando'
    | '/verify-email'
    | '/welcome'
    | '/youtube'
    | '/api/alerts'
    | '/api/digest'
    | '/api/djangobooks-import'
    | '/api/facebook-import'
    | '/api/romani-music'
    | '/archive/$slug'
    | '/concerts/$id'
    | '/families/$slug'
    | '/fans/$slug'
    | '/festivals/$slug'
    | '/festivals/youtube'
    | '/groups/$slug'
    | '/instruments/double-bass'
    | '/instruments/guitars'
    | '/instruments/other'
    | '/instruments/violins'
    | '/jams/$slug'
    | '/jams/meetup'
    | '/learn/$slug'
    | '/learn/amplification'
    | '/learn/apps'
    | '/learn/charts'
    | '/learn/start-jam'
    | '/learn/teachers'
    | '/legends/$slug'
    | '/luthiers/$slug'
    | '/luthiers/bass'
    | '/luthiers/violin'
    | '/musicians/$slug'
    | '/news/$slug'
    | '/romani-music/$slug'
    | '/romani-music/origins'
    | '/shops/$slug'
    | '/studio/owner'
    | '/venues/$slug'
    | '/world/$slug'
    | '/archive'
    | '/concerts'
    | '/fans'
    | '/festivals'
    | '/groups'
    | '/instruments'
    | '/jams'
    | '/learn'
    | '/legends'
    | '/luthiers'
    | '/musicians'
    | '/news'
    | '/romani-music'
    | '/shops'
    | '/studio'
    | '/venues'
    | '/world'
    | '/api/auth/$'
    | '/api/concert-media/$id'
    | '/instruments/luthiers/$country'
    | '/jams/in/$slug'
    | '/learn/forum/$slug'
    | '/learn/instruments/$slug'
    | '/venues/in/$slug'
    | '/instruments/luthiers'
    | '/learn/forum'
    | '/learn/instruments'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/agenda'
    | '/board'
    | '/camps'
    | '/denis-chang'
    | '/django'
    | '/forgot-password'
    | '/grappelli'
    | '/history'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/scene'
    | '/search'
    | '/tata-mirando'
    | '/verify-email'
    | '/welcome'
    | '/youtube'
    | '/api/alerts'
    | '/api/digest'
    | '/api/djangobooks-import'
    | '/api/facebook-import'
    | '/api/romani-music'
    | '/archive/$slug'
    | '/concerts/$id'
    | '/families/$slug'
    | '/fans/$slug'
    | '/festivals/$slug'
    | '/festivals/youtube'
    | '/groups/$slug'
    | '/instruments/double-bass'
    | '/instruments/guitars'
    | '/instruments/other'
    | '/instruments/violins'
    | '/jams/$slug'
    | '/jams/meetup'
    | '/learn/$slug'
    | '/learn/amplification'
    | '/learn/apps'
    | '/learn/charts'
    | '/learn/start-jam'
    | '/learn/teachers'
    | '/legends/$slug'
    | '/luthiers/$slug'
    | '/luthiers/bass'
    | '/luthiers/violin'
    | '/musicians/$slug'
    | '/news/$slug'
    | '/romani-music/$slug'
    | '/romani-music/origins'
    | '/shops/$slug'
    | '/studio/owner'
    | '/venues/$slug'
    | '/world/$slug'
    | '/archive/'
    | '/concerts/'
    | '/fans/'
    | '/festivals/'
    | '/groups/'
    | '/instruments/'
    | '/jams/'
    | '/learn/'
    | '/legends/'
    | '/luthiers/'
    | '/musicians/'
    | '/news/'
    | '/romani-music/'
    | '/shops/'
    | '/studio/'
    | '/venues/'
    | '/world/'
    | '/api/auth/$'
    | '/api/concert-media/$id'
    | '/instruments/luthiers/$country'
    | '/jams/in/$slug'
    | '/learn/forum/$slug'
    | '/learn/instruments/$slug'
    | '/venues/in/$slug'
    | '/instruments/luthiers/'
    | '/learn/forum/'
    | '/learn/instruments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AgendaRoute: typeof AgendaRoute
  BoardRoute: typeof BoardRoute
  CampsRoute: typeof CampsRoute
  DenisChangRoute: typeof DenisChangRoute
  DjangoRoute: typeof DjangoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GrappelliRoute: typeof GrappelliRoute
  HistoryRoute: typeof HistoryRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SceneRoute: typeof SceneRoute
  SearchRoute: typeof SearchRoute
  TataMirandoRoute: typeof TataMirandoRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiDigestRoute: typeof ApiDigestRoute
  ApiDjangobooksImportRoute: typeof ApiDjangobooksImportRoute
  ApiFacebookImportRoute: typeof ApiFacebookImportRoute
  ApiRomaniMusicRoute: typeof ApiRomaniMusicRoute
  ArchiveSlugRoute: typeof ArchiveSlugRoute
  ConcertsIdRoute: typeof ConcertsIdRoute
  FamiliesSlugRoute: typeof FamiliesSlugRoute
  FansSlugRoute: typeof FansSlugRoute
  FestivalsSlugRoute: typeof FestivalsSlugRoute
  FestivalsYoutubeRoute: typeof FestivalsYoutubeRoute
  GroupsSlugRoute: typeof GroupsSlugRoute
  InstrumentsDoubleBassRoute: typeof InstrumentsDoubleBassRoute
  InstrumentsGuitarsRoute: typeof InstrumentsGuitarsRoute
  InstrumentsOtherRoute: typeof InstrumentsOtherRoute
  InstrumentsViolinsRoute: typeof InstrumentsViolinsRoute
  JamsSlugRoute: typeof JamsSlugRoute
  JamsMeetupRoute: typeof JamsMeetupRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LearnAmplificationRoute: typeof LearnAmplificationRoute
  LearnAppsRoute: typeof LearnAppsRoute
  LearnChartsRoute: typeof LearnChartsRoute
  LearnStartJamRoute: typeof LearnStartJamRoute
  LearnTeachersRoute: typeof LearnTeachersRoute
  LegendsSlugRoute: typeof LegendsSlugRoute
  LuthiersSlugRoute: typeof LuthiersSlugRoute
  LuthiersBassRoute: typeof LuthiersBassRoute
  LuthiersViolinRoute: typeof LuthiersViolinRoute
  MusiciansSlugRoute: typeof MusiciansSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  RomaniMusicSlugRoute: typeof RomaniMusicSlugRoute
  RomaniMusicOriginsRoute: typeof RomaniMusicOriginsRoute
  ShopsSlugRoute: typeof ShopsSlugRoute
  StudioOwnerRoute: typeof StudioOwnerRoute
  VenuesSlugRoute: typeof VenuesSlugRoute
  WorldSlugRoute: typeof WorldSlugRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ConcertsIndexRoute: typeof ConcertsIndexRoute
  FansIndexRoute: typeof FansIndexRoute
  FestivalsIndexRoute: typeof FestivalsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  InstrumentsIndexRoute: typeof InstrumentsIndexRoute
  JamsIndexRoute: typeof JamsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LegendsIndexRoute: typeof LegendsIndexRoute
  LuthiersIndexRoute: typeof LuthiersIndexRoute
  MusiciansIndexRoute: typeof MusiciansIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  RomaniMusicIndexRoute: typeof RomaniMusicIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  WorldIndexRoute: typeof WorldIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConcertMediaIdRoute: typeof ApiConcertMediaIdRoute
  InstrumentsLuthiersCountryRoute: typeof InstrumentsLuthiersCountryRoute
  JamsInSlugRoute: typeof JamsInSlugRoute
  LearnForumSlugRoute: typeof LearnForumSlugRoute
  LearnInstrumentsSlugRoute: typeof LearnInstrumentsSlugRoute
  VenuesInSlugRoute: typeof VenuesInSlugRoute
  InstrumentsLuthiersIndexRoute: typeof InstrumentsLuthiersIndexRoute
  LearnForumIndexRoute: typeof LearnForumIndexRoute
  LearnInstrumentsIndexRoute: typeof LearnInstrumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denis-chang': {
      id: '/denis-chang'
      path: '/denis-chang'
      fullPath: '/denis-chang'
      preLoaderRoute: typeof DenisChangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/django': {
      id: '/django'
      path: '/django'
      fullPath: '/django'
      preLoaderRoute: typeof DjangoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grappelli': {
      id: '/grappelli'
      path: '/grappelli'
      fullPath: '/grappelli'
      preLoaderRoute: typeof GrappelliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tata-mirando': {
      id: '/tata-mirando'
      path: '/tata-mirando'
      fullPath: '/tata-mirando'
      preLoaderRoute: typeof TataMirandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest': {
      id: '/api/digest'
      path: '/api/digest'
      fullPath: '/api/digest'
      preLoaderRoute: typeof ApiDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/djangobooks-import': {
      id: '/api/djangobooks-import'
      path: '/api/djangobooks-import'
      fullPath: '/api/djangobooks-import'
      preLoaderRoute: typeof ApiDjangobooksImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook-import': {
      id: '/api/facebook-import'
      path: '/api/facebook-import'
      fullPath: '/api/facebook-import'
      preLoaderRoute: typeof ApiFacebookImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/romani-music': {
      id: '/api/romani-music'
      path: '/api/romani-music'
      fullPath: '/api/romani-music'
      preLoaderRoute: typeof ApiRomaniMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$slug': {
      id: '/archive/$slug'
      path: '/archive/$slug'
      fullPath: '/archive/$slug'
      preLoaderRoute: typeof ArchiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts/': {
      id: '/concerts/'
      path: '/concerts'
      fullPath: '/concerts/'
      preLoaderRoute: typeof ConcertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts/$id': {
      id: '/concerts/$id'
      path: '/concerts/$id'
      fullPath: '/concerts/$id'
      preLoaderRoute: typeof ConcertsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$slug': {
      id: '/families/$slug'
      path: '/families/$slug'
      fullPath: '/families/$slug'
      preLoaderRoute: typeof FamiliesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans/': {
      id: '/fans/'
      path: '/fans'
      fullPath: '/fans/'
      preLoaderRoute: typeof FansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans/$slug': {
      id: '/fans/$slug'
      path: '/fans/$slug'
      fullPath: '/fans/$slug'
      preLoaderRoute: typeof FansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/': {
      id: '/festivals/'
      path: '/festivals'
      fullPath: '/festivals/'
      preLoaderRoute: typeof FestivalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/$slug': {
      id: '/festivals/$slug'
      path: '/festivals/$slug'
      fullPath: '/festivals/$slug'
      preLoaderRoute: typeof FestivalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/youtube': {
      id: '/festivals/youtube'
      path: '/festivals/youtube'
      fullPath: '/festivals/youtube'
      preLoaderRoute: typeof FestivalsYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/': {
      id: '/instruments/'
      path: '/instruments'
      fullPath: '/instruments/'
      preLoaderRoute: typeof InstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/double-bass': {
      id: '/instruments/double-bass'
      path: '/instruments/double-bass'
      fullPath: '/instruments/double-bass'
      preLoaderRoute: typeof InstrumentsDoubleBassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/guitars': {
      id: '/instruments/guitars'
      path: '/instruments/guitars'
      fullPath: '/instruments/guitars'
      preLoaderRoute: typeof InstrumentsGuitarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/other': {
      id: '/instruments/other'
      path: '/instruments/other'
      fullPath: '/instruments/other'
      preLoaderRoute: typeof InstrumentsOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/violins': {
      id: '/instruments/violins'
      path: '/instruments/violins'
      fullPath: '/instruments/violins'
      preLoaderRoute: typeof InstrumentsViolinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jams/': {
      id: '/jams/'
      path: '/jams'
      fullPath: '/jams/'
      preLoaderRoute: typeof JamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jams/$slug': {
      id: '/jams/$slug'
      path: '/jams/$slug'
      fullPath: '/jams/$slug'
      preLoaderRoute: typeof JamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jams/meetup': {
      id: '/jams/meetup'
      path: '/jams/meetup'
      fullPath: '/jams/meetup'
      preLoaderRoute: typeof JamsMeetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/amplification': {
      id: '/learn/amplification'
      path: '/learn/amplification'
      fullPath: '/learn/amplification'
      preLoaderRoute: typeof LearnAmplificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/apps': {
      id: '/learn/apps'
      path: '/learn/apps'
      fullPath: '/learn/apps'
      preLoaderRoute: typeof LearnAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/charts': {
      id: '/learn/charts'
      path: '/learn/charts'
      fullPath: '/learn/charts'
      preLoaderRoute: typeof LearnChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/start-jam': {
      id: '/learn/start-jam'
      path: '/learn/start-jam'
      fullPath: '/learn/start-jam'
      preLoaderRoute: typeof LearnStartJamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/teachers': {
      id: '/learn/teachers'
      path: '/learn/teachers'
      fullPath: '/learn/teachers'
      preLoaderRoute: typeof LearnTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legends/': {
      id: '/legends/'
      path: '/legends'
      fullPath: '/legends/'
      preLoaderRoute: typeof LegendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legends/$slug': {
      id: '/legends/$slug'
      path: '/legends/$slug'
      fullPath: '/legends/$slug'
      preLoaderRoute: typeof LegendsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luthiers/': {
      id: '/luthiers/'
      path: '/luthiers'
      fullPath: '/luthiers/'
      preLoaderRoute: typeof LuthiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luthiers/$slug': {
      id: '/luthiers/$slug'
      path: '/luthiers/$slug'
      fullPath: '/luthiers/$slug'
      preLoaderRoute: typeof LuthiersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luthiers/bass': {
      id: '/luthiers/bass'
      path: '/luthiers/bass'
      fullPath: '/luthiers/bass'
      preLoaderRoute: typeof LuthiersBassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luthiers/violin': {
      id: '/luthiers/violin'
      path: '/luthiers/violin'
      fullPath: '/luthiers/violin'
      preLoaderRoute: typeof LuthiersViolinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicians/': {
      id: '/musicians/'
      path: '/musicians'
      fullPath: '/musicians/'
      preLoaderRoute: typeof MusiciansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicians/$slug': {
      id: '/musicians/$slug'
      path: '/musicians/$slug'
      fullPath: '/musicians/$slug'
      preLoaderRoute: typeof MusiciansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romani-music/': {
      id: '/romani-music/'
      path: '/romani-music'
      fullPath: '/romani-music/'
      preLoaderRoute: typeof RomaniMusicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romani-music/$slug': {
      id: '/romani-music/$slug'
      path: '/romani-music/$slug'
      fullPath: '/romani-music/$slug'
      preLoaderRoute: typeof RomaniMusicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romani-music/origins': {
      id: '/romani-music/origins'
      path: '/romani-music/origins'
      fullPath: '/romani-music/origins'
      preLoaderRoute: typeof RomaniMusicOriginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/owner': {
      id: '/studio/owner'
      path: '/studio/owner'
      fullPath: '/studio/owner'
      preLoaderRoute: typeof StudioOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/': {
      id: '/world/'
      path: '/world'
      fullPath: '/world/'
      preLoaderRoute: typeof WorldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$slug': {
      id: '/world/$slug'
      path: '/world/$slug'
      fullPath: '/world/$slug'
      preLoaderRoute: typeof WorldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concert-media/$id': {
      id: '/api/concert-media/$id'
      path: '/api/concert-media/$id'
      fullPath: '/api/concert-media/$id'
      preLoaderRoute: typeof ApiConcertMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/luthiers/': {
      id: '/instruments/luthiers/'
      path: '/instruments/luthiers'
      fullPath: '/instruments/luthiers/'
      preLoaderRoute: typeof InstrumentsLuthiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/luthiers/$country': {
      id: '/instruments/luthiers/$country'
      path: '/instruments/luthiers/$country'
      fullPath: '/instruments/luthiers/$country'
      preLoaderRoute: typeof InstrumentsLuthiersCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jams/in/$slug': {
      id: '/jams/in/$slug'
      path: '/jams/in/$slug'
      fullPath: '/jams/in/$slug'
      preLoaderRoute: typeof JamsInSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/forum/': {
      id: '/learn/forum/'
      path: '/learn/forum'
      fullPath: '/learn/forum/'
      preLoaderRoute: typeof LearnForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/forum/$slug': {
      id: '/learn/forum/$slug'
      path: '/learn/forum/$slug'
      fullPath: '/learn/forum/$slug'
      preLoaderRoute: typeof LearnForumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/instruments/': {
      id: '/learn/instruments/'
      path: '/learn/instruments'
      fullPath: '/learn/instruments/'
      preLoaderRoute: typeof LearnInstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/instruments/$slug': {
      id: '/learn/instruments/$slug'
      path: '/learn/instruments/$slug'
      fullPath: '/learn/instruments/$slug'
      preLoaderRoute: typeof LearnInstrumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/in/$slug': {
      id: '/venues/in/$slug'
      path: '/venues/in/$slug'
      fullPath: '/venues/in/$slug'
      preLoaderRoute: typeof VenuesInSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AgendaRoute: AgendaRoute,
  BoardRoute: BoardRoute,
  CampsRoute: CampsRoute,
  DenisChangRoute: DenisChangRoute,
  DjangoRoute: DjangoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GrappelliRoute: GrappelliRoute,
  HistoryRoute: HistoryRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SceneRoute: SceneRoute,
  SearchRoute: SearchRoute,
  TataMirandoRoute: TataMirandoRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  YoutubeRoute: YoutubeRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiDigestRoute: ApiDigestRoute,
  ApiDjangobooksImportRoute: ApiDjangobooksImportRoute,
  ApiFacebookImportRoute: ApiFacebookImportRoute,
  ApiRomaniMusicRoute: ApiRomaniMusicRoute,
  ArchiveSlugRoute: ArchiveSlugRoute,
  ConcertsIdRoute: ConcertsIdRoute,
  FamiliesSlugRoute: FamiliesSlugRoute,
  FansSlugRoute: FansSlugRoute,
  FestivalsSlugRoute: FestivalsSlugRoute,
  FestivalsYoutubeRoute: FestivalsYoutubeRoute,
  GroupsSlugRoute: GroupsSlugRoute,
  InstrumentsDoubleBassRoute: InstrumentsDoubleBassRoute,
  InstrumentsGuitarsRoute: InstrumentsGuitarsRoute,
  InstrumentsOtherRoute: InstrumentsOtherRoute,
  InstrumentsViolinsRoute: InstrumentsViolinsRoute,
  JamsSlugRoute: JamsSlugRoute,
  JamsMeetupRoute: JamsMeetupRoute,
  LearnSlugRoute: LearnSlugRoute,
  LearnAmplificationRoute: LearnAmplificationRoute,
  LearnAppsRoute: LearnAppsRoute,
  LearnChartsRoute: LearnChartsRoute,
  LearnStartJamRoute: LearnStartJamRoute,
  LearnTeachersRoute: LearnTeachersRoute,
  LegendsSlugRoute: LegendsSlugRoute,
  LuthiersSlugRoute: LuthiersSlugRoute,
  LuthiersBassRoute: LuthiersBassRoute,
  LuthiersViolinRoute: LuthiersViolinRoute,
  MusiciansSlugRoute: MusiciansSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  RomaniMusicSlugRoute: RomaniMusicSlugRoute,
  RomaniMusicOriginsRoute: RomaniMusicOriginsRoute,
  ShopsSlugRoute: ShopsSlugRoute,
  StudioOwnerRoute: StudioOwnerRoute,
  VenuesSlugRoute: VenuesSlugRoute,
  WorldSlugRoute: WorldSlugRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ConcertsIndexRoute: ConcertsIndexRoute,
  FansIndexRoute: FansIndexRoute,
  FestivalsIndexRoute: FestivalsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  InstrumentsIndexRoute: InstrumentsIndexRoute,
  JamsIndexRoute: JamsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LegendsIndexRoute: LegendsIndexRoute,
  LuthiersIndexRoute: LuthiersIndexRoute,
  MusiciansIndexRoute: MusiciansIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  RomaniMusicIndexRoute: RomaniMusicIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  WorldIndexRoute: WorldIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConcertMediaIdRoute: ApiConcertMediaIdRoute,
  InstrumentsLuthiersCountryRoute: InstrumentsLuthiersCountryRoute,
  JamsInSlugRoute: JamsInSlugRoute,
  LearnForumSlugRoute: LearnForumSlugRoute,
  LearnInstrumentsSlugRoute: LearnInstrumentsSlugRoute,
  VenuesInSlugRoute: VenuesInSlugRoute,
  InstrumentsLuthiersIndexRoute: InstrumentsLuthiersIndexRoute,
  LearnForumIndexRoute: LearnForumIndexRoute,
  LearnInstrumentsIndexRoute: LearnInstrumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
